$axure.loadCurrentPage({
  "url":"мой_профиль.html",
  "generationDate":new Date(1493889319387.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba1cda0212154936aaba72b9272c114d",
    "type":"Axure:Page",
    "name":"Мой профиль",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"586e7ead74684629b536ec7c6d0ad757",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":155},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f5776fc8e29469db3ce7fd13a2ae5cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":155},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da57547b630b4adda5dbf005ab10f533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":155},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb9a09887601418cbeed7cf3c089ff33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":155},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7342b50e38440b0ba7cc562c8258b7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":158},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"4e11f917623246f497709f985061b33b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":250,
              "y":266},
            "size":{
              "width":498,
              "height":330},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2337f5021c3f4a909efd466675e543d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":250,
                  "y":266},
                "size":{
                  "width":498,
                  "height":330},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/мой_профиль/u5.png"}},
{
          "id":"43965705e7bc442c80c93476d412ab0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":308,
              "y":306},
            "size":{
              "width":83,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83b3788a74e34ec2a89d0db5a2064d7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":308,
                  "y":306},
                "size":{
                  "width":83,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5d8f775488e46a78eb430d855517518",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":478,
              "y":306},
            "size":{
              "width":215,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1b766aaac0242c29861410473dbc00f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":478,
                  "y":306},
                "size":{
                  "width":215,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"107bca695b0146ea80b2eb626b2d97d7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":521},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"67772faa63ae4ce1a07085d7b86ada51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":-3,
              "y":653},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3143a2346c74c5fafd82dd3fe20ad5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":-3,
                  "y":653},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u33.png"}},
{
          "id":"b8ee9b671173404290869598a33a4e2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc52b0a20733453fb6250c78acd7fc80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":0},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"11e7352a031047f8a63be95857c8470c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"aa6b9860e3604adb8484dbf87d5cf748",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8424bd59f014dc08b5e1db84f80a6e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2316b2900584f6ca3e5bb5d47e8bb85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea432337731e4164b22df54e7813de9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"871fd9b2537040b8bdbda70487317bcd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"137ea80e0c2f4c268fe24fc3d715b103",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"2f808aef492b47adbfe829a3172e45a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":252,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"032cb6821cc041d4a7fac2ed0c4fcfd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":252,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a8e1d931ae64bc8af98c95f1a48389d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9043c2b9504149ba8812c401672865c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8edc919ce1c64934ab5cd880a773bb77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":641,
              "y":34},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f4671b551f43a58774c51fe5e309d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":641,
                  "y":34},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6301b92bcea94cf0a7b01294108c6c59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":4},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90aefa7881814af3a5a03b25e4f64e56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":4},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7531211301774a978e06f121a887d766",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5426e64f4fd8417f897b54376066d726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":916,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u17.png"}},
{
          "id":"f4b9c047614147d5939ee85cfb15682d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7153fcf660794c1096f6563731f4dcc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u19.png"}},
{
          "id":"7f11e03476794ff897f57085eedf5320",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"750021b4c71b445d9cb89ef64645855b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u21.png"}},
{
          "id":"f9766e6ea80544829dcc9251759e5ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":642,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dd5b8cbb56340239a79af26bdb397b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":642,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"225d150edc6842fc9e2e6847cfa8056c",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":66},
            "size":{
              "width":500,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab53e998fe6f4df78bc0adeb7d0aebb9",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32ae66382ce6414eb8328c49786704ec",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5338e6c1b464f299eabad08f62312e0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"90d5b66776db464e8279cd8f3a152459",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa76427f1129435699d0700c8f059651",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"172906e9a52141828d39917d75a503ab",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ed47559f4fc48d29dade54116b762e6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u104.png"}},
{
                  "id":"3c76fc8bd5af4fc397a98c4852add725",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e75fba1d72b4fb6a7ad7b0390fc8a54",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"1ff9e70cab3f48feb276025fae26da14",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5704e53867614a88b1f7477728fd5b66",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}}]},
{
              "id":"03c4361c506843899e9ebf52c1c2cca8",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d93facc2c904802b9704e135c7be98a",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ecad28ff01b84333b3ab3cc2f9516985",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e49bbe0df8b047a1b4cb82079f30ed5a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"b213ea61992b4903a7be491da5147c3c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"71971f140e374753acc44d4340f35472",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"d9333624afa5408bb6e78f7c6fcb2138",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"06881df4046343f0ad5821d8b32531ae",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"0da37d465a834ad98f6eddbe36f6a44d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d1b23842d26f4a899c671aed46487129",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u126.png"}},
{
                      "id":"1a0ca42c0e6b43be80d17ef50f3b5d13",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d29e7e7ed9ed4ddf87af2fa1dbb5fddd",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"6ab94326041a423fb56cd535faa4e0ae",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"111fb769a9ff42819368c06220ab1e79",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"47b603f7bb2547e7a2817254df00aebb",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f2c775316a064b588f9274b84530a5d4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"0dc7da4691584dddbd57df60829f7dc8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9ebc104102c64098a7b03960badc686c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"5b286fb09a684d939914b6a18878217c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3f067fe151e848c4a4979959806cccbe",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"6fd374d22e5a44478a9a8de71bf025df",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"20e93440aa734572a8460935fac3244b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}}]}],
              "parentCellId":"90d5b66776db464e8279cd8f3a152459"}]}]}},
  "masters":{
},
  "objectPaths":{
    "586e7ead74684629b536ec7c6d0ad757":{
      "scriptId":"u0"},
    "8f5776fc8e29469db3ce7fd13a2ae5cc":{
      "scriptId":"u1"},
    "da57547b630b4adda5dbf005ab10f533":{
      "scriptId":"u2"},
    "fb9a09887601418cbeed7cf3c089ff33":{
      "scriptId":"u3"},
    "b7342b50e38440b0ba7cc562c8258b7e":{
      "scriptId":"u4"},
    "4e11f917623246f497709f985061b33b":{
      "scriptId":"u5"},
    "2337f5021c3f4a909efd466675e543d9":{
      "scriptId":"u6"},
    "43965705e7bc442c80c93476d412ab0c":{
      "scriptId":"u7"},
    "83b3788a74e34ec2a89d0db5a2064d7a":{
      "scriptId":"u8"},
    "a5d8f775488e46a78eb430d855517518":{
      "scriptId":"u9"},
    "f1b766aaac0242c29861410473dbc00f":{
      "scriptId":"u10"},
    "107bca695b0146ea80b2eb626b2d97d7":{
      "scriptId":"u11"},
    "67772faa63ae4ce1a07085d7b86ada51":{
      "scriptId":"u12"},
    "b3143a2346c74c5fafd82dd3fe20ad5c":{
      "scriptId":"u13"},
    "b8ee9b671173404290869598a33a4e2f":{
      "scriptId":"u14"},
    "fc52b0a20733453fb6250c78acd7fc80":{
      "scriptId":"u15"},
    "11e7352a031047f8a63be95857c8470c":{
      "scriptId":"u16"},
    "aa6b9860e3604adb8484dbf87d5cf748":{
      "scriptId":"u17"},
    "f8424bd59f014dc08b5e1db84f80a6e1":{
      "scriptId":"u18"},
    "e2316b2900584f6ca3e5bb5d47e8bb85":{
      "scriptId":"u19"},
    "ea432337731e4164b22df54e7813de9b":{
      "scriptId":"u20"},
    "871fd9b2537040b8bdbda70487317bcd":{
      "scriptId":"u21"},
    "137ea80e0c2f4c268fe24fc3d715b103":{
      "scriptId":"u22"},
    "2f808aef492b47adbfe829a3172e45a3":{
      "scriptId":"u23"},
    "032cb6821cc041d4a7fac2ed0c4fcfd5":{
      "scriptId":"u24"},
    "0a8e1d931ae64bc8af98c95f1a48389d":{
      "scriptId":"u25"},
    "9043c2b9504149ba8812c401672865c4":{
      "scriptId":"u26"},
    "8edc919ce1c64934ab5cd880a773bb77":{
      "scriptId":"u27"},
    "d5f4671b551f43a58774c51fe5e309d2":{
      "scriptId":"u28"},
    "6301b92bcea94cf0a7b01294108c6c59":{
      "scriptId":"u29"},
    "90aefa7881814af3a5a03b25e4f64e56":{
      "scriptId":"u30"},
    "7531211301774a978e06f121a887d766":{
      "scriptId":"u31"},
    "5426e64f4fd8417f897b54376066d726":{
      "scriptId":"u32"},
    "f4b9c047614147d5939ee85cfb15682d":{
      "scriptId":"u33"},
    "7153fcf660794c1096f6563731f4dcc3":{
      "scriptId":"u34"},
    "7f11e03476794ff897f57085eedf5320":{
      "scriptId":"u35"},
    "750021b4c71b445d9cb89ef64645855b":{
      "scriptId":"u36"},
    "f9766e6ea80544829dcc9251759e5ace":{
      "scriptId":"u37"},
    "4dd5b8cbb56340239a79af26bdb397b7":{
      "scriptId":"u38"},
    "225d150edc6842fc9e2e6847cfa8056c":{
      "scriptId":"u39"},
    "ab53e998fe6f4df78bc0adeb7d0aebb9":{
      "scriptId":"u40"},
    "32ae66382ce6414eb8328c49786704ec":{
      "scriptId":"u41"},
    "d5338e6c1b464f299eabad08f62312e0":{
      "scriptId":"u42"},
    "90d5b66776db464e8279cd8f3a152459":{
      "scriptId":"u43"},
    "aa76427f1129435699d0700c8f059651":{
      "scriptId":"u44"},
    "1ff9e70cab3f48feb276025fae26da14":{
      "scriptId":"u45"},
    "5704e53867614a88b1f7477728fd5b66":{
      "scriptId":"u46"},
    "3c76fc8bd5af4fc397a98c4852add725":{
      "scriptId":"u47"},
    "9e75fba1d72b4fb6a7ad7b0390fc8a54":{
      "scriptId":"u48"},
    "172906e9a52141828d39917d75a503ab":{
      "scriptId":"u49"},
    "4ed47559f4fc48d29dade54116b762e6":{
      "scriptId":"u50"},
    "03c4361c506843899e9ebf52c1c2cca8":{
      "scriptId":"u51"},
    "7d93facc2c904802b9704e135c7be98a":{
      "scriptId":"u52"},
    "ecad28ff01b84333b3ab3cc2f9516985":{
      "scriptId":"u53"},
    "e49bbe0df8b047a1b4cb82079f30ed5a":{
      "scriptId":"u54"},
    "b213ea61992b4903a7be491da5147c3c":{
      "scriptId":"u55"},
    "71971f140e374753acc44d4340f35472":{
      "scriptId":"u56"},
    "d9333624afa5408bb6e78f7c6fcb2138":{
      "scriptId":"u57"},
    "06881df4046343f0ad5821d8b32531ae":{
      "scriptId":"u58"},
    "47b603f7bb2547e7a2817254df00aebb":{
      "scriptId":"u59"},
    "f2c775316a064b588f9274b84530a5d4":{
      "scriptId":"u60"},
    "6ab94326041a423fb56cd535faa4e0ae":{
      "scriptId":"u61"},
    "111fb769a9ff42819368c06220ab1e79":{
      "scriptId":"u62"},
    "1a0ca42c0e6b43be80d17ef50f3b5d13":{
      "scriptId":"u63"},
    "d29e7e7ed9ed4ddf87af2fa1dbb5fddd":{
      "scriptId":"u64"},
    "6fd374d22e5a44478a9a8de71bf025df":{
      "scriptId":"u65"},
    "20e93440aa734572a8460935fac3244b":{
      "scriptId":"u66"},
    "5b286fb09a684d939914b6a18878217c":{
      "scriptId":"u67"},
    "3f067fe151e848c4a4979959806cccbe":{
      "scriptId":"u68"},
    "0dc7da4691584dddbd57df60829f7dc8":{
      "scriptId":"u69"},
    "9ebc104102c64098a7b03960badc686c":{
      "scriptId":"u70"},
    "0da37d465a834ad98f6eddbe36f6a44d":{
      "scriptId":"u71"},
    "d1b23842d26f4a899c671aed46487129":{
      "scriptId":"u72"}}});