$axure.loadCurrentPage({
  "url":"о_нас.html",
  "generationDate":new Date(1493365930670.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2838f35a7d804b9dbd5d0afd32de1493",
    "type":"Axure:Page",
    "name":"О нас",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cd2642e75ddd4578926d28580dd1b88e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":340,
              "y":204},
            "size":{
              "width":72,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d777d336ac046b8b3c719674cc0352d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":340,
                  "y":204},
                "size":{
                  "width":72,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c2a454c2ae640ae9b1e49ccb44c5cc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":247},
            "size":{
              "width":300,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"771a72ed1b76431a84d438356f470d2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":247},
                "size":{
                  "width":300,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u2.png"}},
{
          "id":"7fc6d9be3f484cb5bc0419595e77386b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":155},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dd12866cab94b1ba9a43acb9228cb76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":155},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"690fa696400a41e5bfc80c5a5b317c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":155},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15fe13ef53a949f3abc227b11c3eea96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":155},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4f3664bda8f4e3cae355a5f764e3c38",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":158},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"479b2c5223ae49aabc89fee921f4dc25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":340,
              "y":247},
            "size":{
              "width":661,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceff7cde20e3402eafca42f15673e416",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":340,
                  "y":247},
                "size":{
                  "width":661,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa5658bc755a458ca169703c779b4dba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":391,
              "y":494},
            "size":{
              "width":213,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36afa2a9c9aa4f26bc64afa671dad83c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":391,
                  "y":494},
                "size":{
                  "width":213,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3e72f4100604a98bacccbef3e7a7265",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":24,
              "y":540},
            "size":{
              "width":978,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"428871954b36498fa6ad618e82d0fffc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":24,
                  "y":540},
                "size":{
                  "width":978,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89f34fcb3afb4c1da2512fe9826d270d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":398,
              "y":821},
            "size":{
              "width":205,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d61bf2dd3f463fac62a796dd119f17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":398,
                  "y":821},
                "size":{
                  "width":205,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80fdb5e9077f45bb9fd2f76a86a578b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":877},
            "size":{
              "width":991,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24424459af344f7b8eb0eeb11ae64a3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":877},
                "size":{
                  "width":991,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u17.png"}},
{
          "id":"6edd77017ec54ded9aa24ff2c691ff80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":991},
            "size":{
              "width":40,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1a4d0276e4e494f94143b40e447379c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":991},
                "size":{
                  "width":40,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u19.jpg"}},
{
          "id":"65cdf63a4d27426dba64c9e6645938cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":991},
            "size":{
              "width":40,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2adfb1ec2dcf4cabbaf999502f637e8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":950,
                  "y":991},
                "size":{
                  "width":40,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u21.jpg"}},
{
          "id":"301aea5f6cf043108ef9a3a019714c41",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":947},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c76a22ecf4c2468bb59f0a8b1df40d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":947},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u23.png"}},
{
          "id":"fe6732a2cd14422694a5982ab757deae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":947},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2622e6b2277b4df1a221ed8fcb60a693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":802,
                  "y":947},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u25.png"}},
{
          "id":"57aa26ab27e6470ea621408b5de0e57f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":947},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc6f42b17ec4dffa60b242dd456e6c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":947},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u27.png"}},
{
          "id":"4439d759d1b1456a847c0e0b69ab5861",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":947},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ab267de2934eee8f2249e460a3aab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":947},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u29.png"}},
{
          "id":"81c01f757ef54920b22813244e355436",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":633,
              "y":947},
            "size":{
              "width":128,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e621e4f4d1cd41638a340fde7cdefda5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":633,
                  "y":947},
                "size":{
                  "width":128,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u23.png"}},
{
          "id":"1ab756bd6f5742fb970bfd92d28eb1eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":-3,
              "y":1434},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc34cb762c74b749bdafa61454b196b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":-3,
                  "y":1434},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u33.png"}},
{
          "id":"2d38055c87564c1db41b378f05bf7f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":1211},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf718990c4e74642a1f0619928fe4477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":1211},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bae40619d4d4242b74d57160a774645",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":1195},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/о_нас/u37_line.png"}},
{
          "id":"0d15ba4714ba4c1c97637e8d1e9ef876",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af1f5cb8b0124139ba8d70b17f31ee0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":0},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"23b0e08ccd1c4f7eae5180e640bf0e4d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"ff5a119db91044008bf611a58575df82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd86990775b34bc7a72c0e6596ecce1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a42dec9fec4a4f93be93d7b7f83b3ee6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95cb02c8613b401089f4ee38000f981c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"bcab2bc4b80d4846b29061c59e553507",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c1de6b5e359b4ef484ee972b2851a305",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle Konsult",
                      "objectsToFades":[{
                          "objectPath":["1fced72b203a4e45b99adf7c69e86bb5"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"673c3631a1684202862a2714e7fb6539",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":252,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1070ea83dd714b41ada7960680e2fecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":252,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e602abbb7be24a27b3ffdb5735137721",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ad24bcd7f6a410d83682a6e871ead9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c337bec3c6234ed59835b6e3836083ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":641,
              "y":34},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa1f0b50745e44d5b111f3e24177f3f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":641,
                  "y":34},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4be0600799943fbaa990cf611b08f6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":4},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"593c66e63359412ba3fa860aa8cede30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":4},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18cbbf78f59f447c98eece91a3bfa017",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a274dcdd7f894a5dae42ae288f67e1e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":916,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"38dc94289472482a9cd6d2ffb944e813",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2e4fa8947248fc9eb939cfbb10e3f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"f0005dfda7ef47c49b41efa990cd8339",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d718322d854d27b1038caa0058ff40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u21.png"}},
{
          "id":"060acb88a85e401aa9c9a373caa984d5",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":66},
            "size":{
              "width":500,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34d66d848c154c2fbe2e5926c0fba28f",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1d61d9ac37747c4a47daab3ca15139a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c2edb9b67574fa5b2c536049541c609",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}},
{
                  "id":"4a842b09c94344368163ce069e129aaf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d7ff825d4f24c1aa418c36bd6246cb7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}},
{
                  "id":"e126923dbd7f4a49beb5cc363a00d292",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"248f8361caba4b74a8476ec5903fb67c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u104.png"}},
{
                  "id":"4826ca3e1c854e57aefa889ee3b375d1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43db7686ca6c4dad948a89dec52bd8a6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}},
{
                  "id":"ac3f9aa7d8bd42cabb463c884acf4cae",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7deb6aa5d9ee4fbd9453db903b098ec5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}}]},
{
              "id":"597359153e3141d9becf7f80955079d3",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c7580dfa0df40d385fc67c1f0fddb0a",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bc0a05d56404a3aba86d8ae2a724564",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"428ec7fdf1f144e0843b6e362c88284f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"3b33921a0a224ae5b04431337e46c14f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"efef9499e4fd41b1a9a3db0a9235526e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u110.png"}},
{
                      "id":"4dead7c868954acaa44f31c6b14e1162",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3a7cbc9704dc472eaf4c0cadd1fb0a83",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"809855d090554609aa2f9afbc7979694",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f84f372e423e4e46bab9741ac4160325",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u126.png"}},
{
                      "id":"c93ded0570d5408b931f31f0e44779dc",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b61f9a5d5a684f968d335e838abec75c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u116.png"}},
{
                      "id":"ddc2f43f3aea4ea59cfa2e31fbd493f9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b7a40719c9bd429c8942ee971964e2f9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u116.png"}},
{
                      "id":"565f37d3a9d94dd2bebe69a77d82b896",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fcf40d3bd87344bf850aa8e4669a887f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"5deeeb6b4064403d9cb3ab8ea2e712d7",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f300d909be9847208eb622ddbcb8b3da",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"556be65374564c9297a4aa3dbaf7aa5b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3c85ae40b32545918a5b1e9ff8539db8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u110.png"}},
{
                      "id":"3df9247bda384cf4845d1921cf9c802f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"873680ad3afe42c89c615f617a784cc0",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u110.png"}}]}],
              "parentCellId":"4a842b09c94344368163ce069e129aaf"}]},
{
          "id":"1fced72b203a4e45b99adf7c69e86bb5",
          "label":"Konsult",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":235,
              "y":122},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a5fa6fa3828147998d6dea27d2bc1320",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9cb7625d5cd042f4bb29b7b18ab81d98",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":358}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02d503917d304ecd8c73767aefa2cb39",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":100,
                          "y":50},
                        "size":{
                          "width":300,
                          "height":358}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u129.png"}},
{
                  "id":"3abf58564e8a40828f88809f24f5b2d9",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":88},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"089587cd731641acb6c0c76c339d4d19",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":72},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"042b8a3018a44086b7cb92e232be4001",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":72},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a4dd9cef633406aa0c1fcfcb2e321d2",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":138},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"2111916d392f44fa98ca1a5fa3684ef3",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":122},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"95cc17a01c2245c68bcd068b260bf651",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":122},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"be5b009e43b6425b8648b30b637d4980",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":188},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"e6d825c6842b447e81edddd1fe0b49de",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":172},
                    "size":{
                      "width":49,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ec62b0ffa48488a8a95e96a943ef424",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":172},
                        "size":{
                          "width":49,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"de64851907d144f7ba4bfa3c02cb3c2c",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":238},
                    "size":{
                      "width":260,
                      "height":91}},
                  "adaptiveStyles":{
}},
{
                  "id":"e6d76feec7b3463d99e320186e126085",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":222},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1ac9212350748cb949cf1114c80ae03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":222},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"18f0fb9ce88845ef98fa10ff02aedaa8",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":348},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show banner",
                              "objectsToFades":[{
                                  "objectPath":["6f08c516dde64fb4be0ef472981636d5"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"b55552dfdc3a417e99d40f66b7b86510",
                  "label":"",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":288,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"214dae1af358440e8a55fe8b90204eb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":106,
                          "y":0},
                        "size":{
                          "width":288,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6f08c516dde64fb4be0ef472981636d5",
                  "label":"banner",
                  "parentDynamicPanel":"1fced72b203a4e45b99adf7c69e86bb5",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"4e7ec3aba8f44b2f8cca35ba0bbe9860",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"3484a4c236da41f0b81ce338a67f0d47",
                          "label":"",
                          "parentDynamicPanel":"6f08c516dde64fb4be0ef472981636d5",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "size":{
                              "width":530,
                              "height":130}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"85f2fd4b738448a88403b8f281a500e3",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"6f08c516dde64fb4be0ef472981636d5",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "size":{
                                  "width":530,
                                  "height":130}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/u147.png"}},
{
                          "id":"fa603e669ae74d9ea4c8f8d6f2daa1dd",
                          "label":"",
                          "parentDynamicPanel":"6f08c516dde64fb4be0ef472981636d5",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":500,
                              "y":10},
                            "size":{
                              "width":20,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"32bcf4efdab345839a6bef5be8681765",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"6f08c516dde64fb4be0ef472981636d5",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":500,
                                  "y":10},
                                "size":{
                                  "width":20,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Hide banner",
                                      "objectsToFades":[{
                                          "objectPath":["6f08c516dde64fb4be0ef472981636d5"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/home/u149.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "cd2642e75ddd4578926d28580dd1b88e":{
      "scriptId":"u0"},
    "5d777d336ac046b8b3c719674cc0352d":{
      "scriptId":"u1"},
    "5c2a454c2ae640ae9b1e49ccb44c5cc9":{
      "scriptId":"u2"},
    "771a72ed1b76431a84d438356f470d2b":{
      "scriptId":"u3"},
    "7fc6d9be3f484cb5bc0419595e77386b":{
      "scriptId":"u4"},
    "4dd12866cab94b1ba9a43acb9228cb76":{
      "scriptId":"u5"},
    "690fa696400a41e5bfc80c5a5b317c24":{
      "scriptId":"u6"},
    "15fe13ef53a949f3abc227b11c3eea96":{
      "scriptId":"u7"},
    "b4f3664bda8f4e3cae355a5f764e3c38":{
      "scriptId":"u8"},
    "479b2c5223ae49aabc89fee921f4dc25":{
      "scriptId":"u9"},
    "ceff7cde20e3402eafca42f15673e416":{
      "scriptId":"u10"},
    "fa5658bc755a458ca169703c779b4dba":{
      "scriptId":"u11"},
    "36afa2a9c9aa4f26bc64afa671dad83c":{
      "scriptId":"u12"},
    "e3e72f4100604a98bacccbef3e7a7265":{
      "scriptId":"u13"},
    "428871954b36498fa6ad618e82d0fffc":{
      "scriptId":"u14"},
    "89f34fcb3afb4c1da2512fe9826d270d":{
      "scriptId":"u15"},
    "41d61bf2dd3f463fac62a796dd119f17":{
      "scriptId":"u16"},
    "80fdb5e9077f45bb9fd2f76a86a578b1":{
      "scriptId":"u17"},
    "24424459af344f7b8eb0eeb11ae64a3b":{
      "scriptId":"u18"},
    "6edd77017ec54ded9aa24ff2c691ff80":{
      "scriptId":"u19"},
    "d1a4d0276e4e494f94143b40e447379c":{
      "scriptId":"u20"},
    "65cdf63a4d27426dba64c9e6645938cf":{
      "scriptId":"u21"},
    "2adfb1ec2dcf4cabbaf999502f637e8f":{
      "scriptId":"u22"},
    "301aea5f6cf043108ef9a3a019714c41":{
      "scriptId":"u23"},
    "c76a22ecf4c2468bb59f0a8b1df40d92":{
      "scriptId":"u24"},
    "fe6732a2cd14422694a5982ab757deae":{
      "scriptId":"u25"},
    "2622e6b2277b4df1a221ed8fcb60a693":{
      "scriptId":"u26"},
    "57aa26ab27e6470ea621408b5de0e57f":{
      "scriptId":"u27"},
    "3cc6f42b17ec4dffa60b242dd456e6c9":{
      "scriptId":"u28"},
    "4439d759d1b1456a847c0e0b69ab5861":{
      "scriptId":"u29"},
    "33ab267de2934eee8f2249e460a3aab2":{
      "scriptId":"u30"},
    "81c01f757ef54920b22813244e355436":{
      "scriptId":"u31"},
    "e621e4f4d1cd41638a340fde7cdefda5":{
      "scriptId":"u32"},
    "1ab756bd6f5742fb970bfd92d28eb1eb":{
      "scriptId":"u33"},
    "0fc34cb762c74b749bdafa61454b196b":{
      "scriptId":"u34"},
    "2d38055c87564c1db41b378f05bf7f47":{
      "scriptId":"u35"},
    "bf718990c4e74642a1f0619928fe4477":{
      "scriptId":"u36"},
    "1bae40619d4d4242b74d57160a774645":{
      "scriptId":"u37"},
    "0d15ba4714ba4c1c97637e8d1e9ef876":{
      "scriptId":"u38"},
    "af1f5cb8b0124139ba8d70b17f31ee0a":{
      "scriptId":"u39"},
    "23b0e08ccd1c4f7eae5180e640bf0e4d":{
      "scriptId":"u40"},
    "ff5a119db91044008bf611a58575df82":{
      "scriptId":"u41"},
    "fd86990775b34bc7a72c0e6596ecce1b":{
      "scriptId":"u42"},
    "a42dec9fec4a4f93be93d7b7f83b3ee6":{
      "scriptId":"u43"},
    "95cb02c8613b401089f4ee38000f981c":{
      "scriptId":"u44"},
    "bcab2bc4b80d4846b29061c59e553507":{
      "scriptId":"u45"},
    "c1de6b5e359b4ef484ee972b2851a305":{
      "scriptId":"u46"},
    "673c3631a1684202862a2714e7fb6539":{
      "scriptId":"u47"},
    "1070ea83dd714b41ada7960680e2fecf":{
      "scriptId":"u48"},
    "e602abbb7be24a27b3ffdb5735137721":{
      "scriptId":"u49"},
    "7ad24bcd7f6a410d83682a6e871ead9d":{
      "scriptId":"u50"},
    "c337bec3c6234ed59835b6e3836083ee":{
      "scriptId":"u51"},
    "fa1f0b50745e44d5b111f3e24177f3f2":{
      "scriptId":"u52"},
    "c4be0600799943fbaa990cf611b08f6d":{
      "scriptId":"u53"},
    "593c66e63359412ba3fa860aa8cede30":{
      "scriptId":"u54"},
    "18cbbf78f59f447c98eece91a3bfa017":{
      "scriptId":"u55"},
    "a274dcdd7f894a5dae42ae288f67e1e3":{
      "scriptId":"u56"},
    "38dc94289472482a9cd6d2ffb944e813":{
      "scriptId":"u57"},
    "0a2e4fa8947248fc9eb939cfbb10e3f8":{
      "scriptId":"u58"},
    "f0005dfda7ef47c49b41efa990cd8339":{
      "scriptId":"u59"},
    "14d718322d854d27b1038caa0058ff40":{
      "scriptId":"u60"},
    "060acb88a85e401aa9c9a373caa984d5":{
      "scriptId":"u61"},
    "34d66d848c154c2fbe2e5926c0fba28f":{
      "scriptId":"u62"},
    "b1d61d9ac37747c4a47daab3ca15139a":{
      "scriptId":"u63"},
    "5c2edb9b67574fa5b2c536049541c609":{
      "scriptId":"u64"},
    "4a842b09c94344368163ce069e129aaf":{
      "scriptId":"u65"},
    "1d7ff825d4f24c1aa418c36bd6246cb7":{
      "scriptId":"u66"},
    "ac3f9aa7d8bd42cabb463c884acf4cae":{
      "scriptId":"u67"},
    "7deb6aa5d9ee4fbd9453db903b098ec5":{
      "scriptId":"u68"},
    "4826ca3e1c854e57aefa889ee3b375d1":{
      "scriptId":"u69"},
    "43db7686ca6c4dad948a89dec52bd8a6":{
      "scriptId":"u70"},
    "e126923dbd7f4a49beb5cc363a00d292":{
      "scriptId":"u71"},
    "248f8361caba4b74a8476ec5903fb67c":{
      "scriptId":"u72"},
    "597359153e3141d9becf7f80955079d3":{
      "scriptId":"u73"},
    "3c7580dfa0df40d385fc67c1f0fddb0a":{
      "scriptId":"u74"},
    "0bc0a05d56404a3aba86d8ae2a724564":{
      "scriptId":"u75"},
    "428ec7fdf1f144e0843b6e362c88284f":{
      "scriptId":"u76"},
    "3b33921a0a224ae5b04431337e46c14f":{
      "scriptId":"u77"},
    "efef9499e4fd41b1a9a3db0a9235526e":{
      "scriptId":"u78"},
    "4dead7c868954acaa44f31c6b14e1162":{
      "scriptId":"u79"},
    "3a7cbc9704dc472eaf4c0cadd1fb0a83":{
      "scriptId":"u80"},
    "565f37d3a9d94dd2bebe69a77d82b896":{
      "scriptId":"u81"},
    "fcf40d3bd87344bf850aa8e4669a887f":{
      "scriptId":"u82"},
    "ddc2f43f3aea4ea59cfa2e31fbd493f9":{
      "scriptId":"u83"},
    "b7a40719c9bd429c8942ee971964e2f9":{
      "scriptId":"u84"},
    "c93ded0570d5408b931f31f0e44779dc":{
      "scriptId":"u85"},
    "b61f9a5d5a684f968d335e838abec75c":{
      "scriptId":"u86"},
    "3df9247bda384cf4845d1921cf9c802f":{
      "scriptId":"u87"},
    "873680ad3afe42c89c615f617a784cc0":{
      "scriptId":"u88"},
    "556be65374564c9297a4aa3dbaf7aa5b":{
      "scriptId":"u89"},
    "3c85ae40b32545918a5b1e9ff8539db8":{
      "scriptId":"u90"},
    "5deeeb6b4064403d9cb3ab8ea2e712d7":{
      "scriptId":"u91"},
    "f300d909be9847208eb622ddbcb8b3da":{
      "scriptId":"u92"},
    "809855d090554609aa2f9afbc7979694":{
      "scriptId":"u93"},
    "f84f372e423e4e46bab9741ac4160325":{
      "scriptId":"u94"},
    "1fced72b203a4e45b99adf7c69e86bb5":{
      "scriptId":"u95"},
    "9cb7625d5cd042f4bb29b7b18ab81d98":{
      "scriptId":"u96"},
    "02d503917d304ecd8c73767aefa2cb39":{
      "scriptId":"u97"},
    "3abf58564e8a40828f88809f24f5b2d9":{
      "scriptId":"u98"},
    "089587cd731641acb6c0c76c339d4d19":{
      "scriptId":"u99"},
    "042b8a3018a44086b7cb92e232be4001":{
      "scriptId":"u100"},
    "5a4dd9cef633406aa0c1fcfcb2e321d2":{
      "scriptId":"u101"},
    "2111916d392f44fa98ca1a5fa3684ef3":{
      "scriptId":"u102"},
    "95cc17a01c2245c68bcd068b260bf651":{
      "scriptId":"u103"},
    "be5b009e43b6425b8648b30b637d4980":{
      "scriptId":"u104"},
    "e6d825c6842b447e81edddd1fe0b49de":{
      "scriptId":"u105"},
    "3ec62b0ffa48488a8a95e96a943ef424":{
      "scriptId":"u106"},
    "de64851907d144f7ba4bfa3c02cb3c2c":{
      "scriptId":"u107"},
    "e6d76feec7b3463d99e320186e126085":{
      "scriptId":"u108"},
    "c1ac9212350748cb949cf1114c80ae03":{
      "scriptId":"u109"},
    "18f0fb9ce88845ef98fa10ff02aedaa8":{
      "scriptId":"u110"},
    "b55552dfdc3a417e99d40f66b7b86510":{
      "scriptId":"u111"},
    "214dae1af358440e8a55fe8b90204eb7":{
      "scriptId":"u112"},
    "6f08c516dde64fb4be0ef472981636d5":{
      "scriptId":"u113"},
    "3484a4c236da41f0b81ce338a67f0d47":{
      "scriptId":"u114"},
    "85f2fd4b738448a88403b8f281a500e3":{
      "scriptId":"u115"},
    "fa603e669ae74d9ea4c8f8d6f2daa1dd":{
      "scriptId":"u116"},
    "32bcf4efdab345839a6bef5be8681765":{
      "scriptId":"u117"}}});