$axure.loadCurrentPage({
  "url":"вход.html",
  "generationDate":new Date(1494499903696.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"cd3cf04ab6c249baa6e30a3825060c17",
    "type":"Axure:Page",
    "name":"Вход",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b22d3ec3b5794879854d99f5be8ada56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":214},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e493dcdaaefa463a947283c27f4e80dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":214},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"433ca0ed27d54db4ae262f74cc5edca8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":214},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37db9a77eaef412faea7e93200907ede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":214},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae8035941772456d9b36ae5687a63cca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":217},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"6e7e35b7a3374427a6defbaac821503b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEDEDED},
            "location":{
              "x":385,
              "y":248},
            "size":{
              "width":230,
              "height":220},
            "borderFill":{
              "fillType":"solid",
              "color":0xFEFEFE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e21f20b286a44fe89215cc0c1c5b00fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEDEDED},
                "location":{
                  "x":385,
                  "y":248},
                "size":{
                  "width":230,
                  "height":220},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFEFEFE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/вход/u5.png"}},
{
          "id":"0dde34fd477e48678c0d83f86bf821af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":476,
              "y":260},
            "size":{
              "width":51,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c87dd6aca1a04d28a7181ecd448e535c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":476,
                  "y":260},
                "size":{
                  "width":51,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddc5317bcf634e7d9975f599cc80e887",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":293},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"827114a22d8f4f889f9abd3a5ae7b039",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":329},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"27b46be824794c29ba0a896f23ac5ba2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":400,
              "y":411},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u14_image_sketch.png",
            "disabled~":"images/контакты/u14_disabled.png"}},
{
          "id":"9fd5794c03a845528e380ae5b8fc53fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":501,
              "y":364},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd269b2ee84d4b5795860d1bb72a8725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":501,
                  "y":364},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0e978e8468240ad89b7fa93b1897156",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3209ee683e674be7a4b9b966d4c8e562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"380fb1530b5f4c04a073d8cb713c0605",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b4b26f7597469ebe149c9a6a143027",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8df97dd47fb74f1aa413d53a16b79876",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"faa802079df8403e913860b4b3176ac9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"19b6974be30a44bfb76bac9aeeafbbd9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"83d06306e773485e9c0ca9c57dc027e4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"ffdeb84a016d431789fff4c1c4974474",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6bc544b6322c489283a6613ef599ba4b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"02a6ebf10e14481aa98f29f37d769284",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56f04b398ee2406aa680f6b606b20feb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"0fe49b4eb6ea403ab2b0bbfea7382909",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0e87675b1cc466abc6e49ed6795a427",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"fc96a89a2a914b2aa7e3ae4133eee916",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed843dd5d7a747f6b40ead9f1c855f68",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc81c6f4839b40258dd49748b580826e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e1bcd1338eaf4dddaa16bf6e84589fda",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"49588c2deee2483a8b7bd33069996505",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"328ddb9eb12845fc94bc13f560901f17",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"539ccaa09c9d48f7b1169f35078b840c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3e8f8b03e0ee4c2cbbdab45ebefe124b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"d6e35c461bc640658d9450fbb41a788a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1fa1a5a35a8c4b19ba06dce01e55a243",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"0dbad4fbb0b64d739152b652502cfbac",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"50f7293992cf4a31862b8da6a2d70902",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"19b6974be30a44bfb76bac9aeeafbbd9"}]},
{
          "id":"b2dfd55b79904a399dfb69fef404ec10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"d091a23e54994129b3ed07796781b885",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"1d846849f3ae460894d99c622bf52f2d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"b64edfe9792a49cfa03a277abc71fb13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"485db3f5f4224a10a58b6e56378564de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7639931bed644fdd9787b6081e32d7d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ca4947873f645eaad862e6e8f760d8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bee45b935cb42958b5a635e12249638",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"078a53942aaa42289f5773c4408c6b6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"41a5ae12fe8a4da1ac1ae011c2397e39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"847af37e08f94dd18419294717151cd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"2cc9e751e6cf40d484fcb2f5c6641a5b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"09e0a159228f47d0a69eb1bc163926d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbe1affd2f704e8788b74e663656b7b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19278e297a23476cbb3c205a398ab176",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-3,
              "y":560},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65225d7021794b508eb5582089c8cc7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-3,
                  "y":560},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b22d3ec3b5794879854d99f5be8ada56":{
      "scriptId":"u0"},
    "e493dcdaaefa463a947283c27f4e80dc":{
      "scriptId":"u1"},
    "433ca0ed27d54db4ae262f74cc5edca8":{
      "scriptId":"u2"},
    "37db9a77eaef412faea7e93200907ede":{
      "scriptId":"u3"},
    "ae8035941772456d9b36ae5687a63cca":{
      "scriptId":"u4"},
    "6e7e35b7a3374427a6defbaac821503b":{
      "scriptId":"u5"},
    "e21f20b286a44fe89215cc0c1c5b00fe":{
      "scriptId":"u6"},
    "0dde34fd477e48678c0d83f86bf821af":{
      "scriptId":"u7"},
    "c87dd6aca1a04d28a7181ecd448e535c":{
      "scriptId":"u8"},
    "ddc5317bcf634e7d9975f599cc80e887":{
      "scriptId":"u9"},
    "827114a22d8f4f889f9abd3a5ae7b039":{
      "scriptId":"u10"},
    "27b46be824794c29ba0a896f23ac5ba2":{
      "scriptId":"u11"},
    "9fd5794c03a845528e380ae5b8fc53fa":{
      "scriptId":"u12"},
    "bd269b2ee84d4b5795860d1bb72a8725":{
      "scriptId":"u13"},
    "c0e978e8468240ad89b7fa93b1897156":{
      "scriptId":"u14"},
    "3209ee683e674be7a4b9b966d4c8e562":{
      "scriptId":"u15"},
    "380fb1530b5f4c04a073d8cb713c0605":{
      "scriptId":"u16"},
    "b8b4b26f7597469ebe149c9a6a143027":{
      "scriptId":"u17"},
    "8df97dd47fb74f1aa413d53a16b79876":{
      "scriptId":"u18"},
    "faa802079df8403e913860b4b3176ac9":{
      "scriptId":"u19"},
    "19b6974be30a44bfb76bac9aeeafbbd9":{
      "scriptId":"u20"},
    "83d06306e773485e9c0ca9c57dc027e4":{
      "scriptId":"u21"},
    "02a6ebf10e14481aa98f29f37d769284":{
      "scriptId":"u22"},
    "56f04b398ee2406aa680f6b606b20feb":{
      "scriptId":"u23"},
    "0fe49b4eb6ea403ab2b0bbfea7382909":{
      "scriptId":"u24"},
    "e0e87675b1cc466abc6e49ed6795a427":{
      "scriptId":"u25"},
    "ffdeb84a016d431789fff4c1c4974474":{
      "scriptId":"u26"},
    "6bc544b6322c489283a6613ef599ba4b":{
      "scriptId":"u27"},
    "fc96a89a2a914b2aa7e3ae4133eee916":{
      "scriptId":"u28"},
    "ed843dd5d7a747f6b40ead9f1c855f68":{
      "scriptId":"u29"},
    "bc81c6f4839b40258dd49748b580826e":{
      "scriptId":"u30"},
    "e1bcd1338eaf4dddaa16bf6e84589fda":{
      "scriptId":"u31"},
    "539ccaa09c9d48f7b1169f35078b840c":{
      "scriptId":"u32"},
    "3e8f8b03e0ee4c2cbbdab45ebefe124b":{
      "scriptId":"u33"},
    "d6e35c461bc640658d9450fbb41a788a":{
      "scriptId":"u34"},
    "1fa1a5a35a8c4b19ba06dce01e55a243":{
      "scriptId":"u35"},
    "49588c2deee2483a8b7bd33069996505":{
      "scriptId":"u36"},
    "328ddb9eb12845fc94bc13f560901f17":{
      "scriptId":"u37"},
    "0dbad4fbb0b64d739152b652502cfbac":{
      "scriptId":"u38"},
    "50f7293992cf4a31862b8da6a2d70902":{
      "scriptId":"u39"},
    "b2dfd55b79904a399dfb69fef404ec10":{
      "scriptId":"u40"},
    "d091a23e54994129b3ed07796781b885":{
      "scriptId":"u41"},
    "1d846849f3ae460894d99c622bf52f2d":{
      "scriptId":"u42"},
    "b64edfe9792a49cfa03a277abc71fb13":{
      "scriptId":"u43"},
    "485db3f5f4224a10a58b6e56378564de":{
      "scriptId":"u44"},
    "7639931bed644fdd9787b6081e32d7d1":{
      "scriptId":"u45"},
    "9ca4947873f645eaad862e6e8f760d8f":{
      "scriptId":"u46"},
    "8bee45b935cb42958b5a635e12249638":{
      "scriptId":"u47"},
    "078a53942aaa42289f5773c4408c6b6a":{
      "scriptId":"u48"},
    "41a5ae12fe8a4da1ac1ae011c2397e39":{
      "scriptId":"u49"},
    "847af37e08f94dd18419294717151cd8":{
      "scriptId":"u50"},
    "2cc9e751e6cf40d484fcb2f5c6641a5b":{
      "scriptId":"u51"},
    "09e0a159228f47d0a69eb1bc163926d3":{
      "scriptId":"u52"},
    "dbe1affd2f704e8788b74e663656b7b0":{
      "scriptId":"u53"},
    "19278e297a23476cbb3c205a398ab176":{
      "scriptId":"u54"},
    "65225d7021794b508eb5582089c8cc7c":{
      "scriptId":"u55"}}});