$axure.loadCurrentPage({
  "url":"доставка.html",
  "generationDate":new Date(1493281620660.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"9b2d01159ae94c85ac9d585f22ea6f0f",
    "type":"Axure:Page",
    "name":"Доставка",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"435421fe1fa5407e8ad867341795c563",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04b63d56b9f04758895a8338d97bf0e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"12bce73362414b92a9e9f37411f0a4fa",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":146},
            "size":{
              "width":700,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4682e020376548b9a83ad79a88388427",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":700,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c0ed3bc5e164a02a20956d5fee40f8f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34a38b485c97430ca7c340ae9f4d8663",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"621569ea83e44668b33c8bae8ddda1fe",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f9c27a33efd44bdb17f15c930c18d79",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"67f778e7ff0c410bbff7dab6062e251c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":614,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a04ca9d5351949209f870899719edfe0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":614,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u47.png"}},
{
                  "id":"bdfaa725bc6f427b87c93507084831b7",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79cbc809118b4049838d613eb560579a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"48ba3186988d414b9c89434f43de08f0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":514,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85aa923fa9054585933f02968d59595b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":514,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"04da8e0b40744e5a87f45348e69930ff",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45c9bc386b0041d1b6f8898faf7097d2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"0a3f672909824e69902d8b0c50673c26",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"416e8723c83d4f7aa14aabc3562af739",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"4ca6462b976242a7a4c01a36a594453e",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03ed4982ccf94ad6a9f9fbba5a068957",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e5e30209058428991575aa8351768ef",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"be2939247eb54b9a85263b4196b38a7d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"c61e19f3d53c4fdf8a88fed248c04ab5",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f88f2ec9251b4cf9aa485fb49d4e5091",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"217608d5b82d438ba98a610c538daa52",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"364ecf905569495b8a5dd58d4d0c2c9c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"3daed86f807c44db8680de453ce55b31",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c36b154bae2f4ce9903471bb450e951e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}},
{
                      "id":"55f8edca66cd4dba9a1d97561729743a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8eb7a434c41541c2bd3115c7aa12f135",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u59.png"}}]}],
              "parentCellId":"621569ea83e44668b33c8bae8ddda1fe"}]},
{
          "id":"3b655994f6b24c6e839a06ed48192f6f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":18},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u61_image_sketch.png",
            "disabled~":"images/главная/u61_disabled.png"}},
{
          "id":"769a97ad6f0a41fb9660fc9752b432e6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":56},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u62_image_sketch.png",
            "disabled~":"images/главная/u62_disabled.png"}},
{
          "id":"dbe8410378c84672993f0ff53cb1d33a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":141},
            "size":{
              "width":150,
              "height":44}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u73_image_sketch.png",
            "disabled~":"images/главная/u73_disabled.png"}},
{
          "id":"fc8278632437437dab56d9ce673251bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":862,
              "y":192},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1586008d10d24219a5c7882b671252ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":862,
                  "y":192},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c11ed18244e4255ae2c9cbf8c25fca9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":18},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u76_image_sketch.png",
            "disabled~":"images/главная/u76_disabled.png"}},
{
          "id":"76a8d48f3b9243c1aae2f07d421ae019",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":16},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fecf6fc391047809b124e21b4142572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":16},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbf339c291d442d1929439fd60008578",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":45},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a476c737b9a4ad285a0a79c2588acc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":45},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b54a82df55444a6e8dd78c17ea99545d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d7a4a781d24f5499141c20a0f58336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u81.png"}},
{
          "id":"b9b1ba8c544f47638fcad64a7dce2935",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b53fecef3b3246f19a606db0f8ff3c25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u83.png"}},
{
          "id":"e407c68e6dcd4606bb04f9ca6b0d8cfe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c663dd60182448d9c4f78a378cb5727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u85.png"}},
{
          "id":"226b175b74b6439e91520ba9a6b543da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":5,
              "y":239},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"490613f2ba3e4543ab61437c4dc3f1b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":5,
                  "y":239},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e12ae0f0206441aa33133ec2272082b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":242},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/доставка/u48_end.png",
            "line~":"images/доставка/u48_line.png"}},
{
          "id":"52e78cf3646b4120bc1b80096f5b700e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":75,
              "y":239},
            "size":{
              "width":132,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22dd5c5f905245dab9562ed88a769ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":75,
                  "y":239},
                "size":{
                  "width":132,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"924e622e61414ee698dd2e2d6328ce56",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":380},
            "size":{
              "width":150,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab74d9b4113476e9b1cb8cca0f8bdff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":380},
                "size":{
                  "width":150,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db8d48a75e9b4726a5b36e6fe9f0efba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":18,
              "y":414},
            "size":{
              "width":451,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63f0aac6510544c598d3538306e1324f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":18,
                  "y":414},
                "size":{
                  "width":451,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bf479fe38be4e9fb4a2d2ba1b76fc30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":380},
            "size":{
              "width":93,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"041ec5521c584474954ed6d254819f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":380},
                "size":{
                  "width":93,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0431541d691a47829546fc3b9517873f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":501,
              "y":414},
            "size":{
              "width":490,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64cc4e9b55444708adad2cbe9e85aafe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":501,
                  "y":414},
                "size":{
                  "width":490,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be511142e5f74e4cbaab50c5c26ed12b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":318},
            "size":{
              "width":110,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7322d454458477f92e65964f2b4ad19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":318},
                "size":{
                  "width":110,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95a4f034cbe640a5a22962e75c368c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":535},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6838b3ba71a4ccdab7708bf87d197f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":535},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"565150347b094d7882c9dc09bb0668c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":19,
              "y":569},
            "size":{
              "width":451,
              "height":136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17477cf2d4e1415daf793e8f6da1fe91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":19,
                  "y":569},
                "size":{
                  "width":451,
                  "height":136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"909a0f744b8a472796631f57305a0477",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":502,
              "y":535},
            "size":{
              "width":93,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be466b33c7ef443abddfdec7c3b969f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":502,
                  "y":535},
                "size":{
                  "width":93,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8805311c1b244e4ba825077748b7745",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":502,
              "y":569},
            "size":{
              "width":490,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85761a570eb7472aa2aa6ad2d082cea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":502,
                  "y":569},
                "size":{
                  "width":490,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c55fea76e1f54ff485e81f287a75a35b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":494},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u89_line.png"}},
{
          "id":"a183b8d8fd404c169a91bba53be2e834",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":702},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u89_line.png"}},
{
          "id":"a6cfcab892ce49f8bafbea759435efe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":744},
            "size":{
              "width":149,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6330e587c144f349151a8075206de62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":744},
                "size":{
                  "width":149,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea1856caee614623b63c435c504712c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":778},
            "size":{
              "width":451,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afb2de1b645f46d38ce1694956583a84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":20,
                  "y":778},
                "size":{
                  "width":451,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25f9b70e6263419089ab1861476c89f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":503,
              "y":744},
            "size":{
              "width":93,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee1de1cca5924855849489e8ae559508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":503,
                  "y":744},
                "size":{
                  "width":93,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22e1d5645052443b96efa1383fdf08ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":503,
              "y":778},
            "size":{
              "width":490,
              "height":123}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52747baa3258429daa47fc3ee2d2fc49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":503,
                  "y":778},
                "size":{
                  "width":490,
                  "height":123}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bda141618a14519a77bfdac29e9beb1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":911},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u89_line.png"}},
{
          "id":"f639f6e964bc494b92a26327ed73ba38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":0,
              "y":965},
            "size":{
              "width":1000,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f5bec4e90ce4eaba16fd8a73fd374a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":0,
                  "y":965},
                "size":{
                  "width":1000,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/доставка/u80.png"}},
{
          "id":"de187ff632bc4aa78f746273e13a47de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":965},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f0e43e496a41f193d614664d197cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":965},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/доставка/u82.png"}},
{
          "id":"12628539407b4e3f8bcee4076af75b1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":965},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89661b46b817414887ae375996959e23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":965},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/доставка/u84.png"}},
{
          "id":"a36ccec656d948858cb4bdefa2c1395d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":965},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65c39c9505934574b73366e0c036b9b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":965},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/доставка/u86.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "435421fe1fa5407e8ad867341795c563":{
      "scriptId":"u0"},
    "04b63d56b9f04758895a8338d97bf0e2":{
      "scriptId":"u1"},
    "12bce73362414b92a9e9f37411f0a4fa":{
      "scriptId":"u2"},
    "4682e020376548b9a83ad79a88388427":{
      "scriptId":"u3"},
    "1c0ed3bc5e164a02a20956d5fee40f8f":{
      "scriptId":"u4"},
    "34a38b485c97430ca7c340ae9f4d8663":{
      "scriptId":"u5"},
    "04da8e0b40744e5a87f45348e69930ff":{
      "scriptId":"u6"},
    "45c9bc386b0041d1b6f8898faf7097d2":{
      "scriptId":"u7"},
    "621569ea83e44668b33c8bae8ddda1fe":{
      "scriptId":"u8"},
    "7f9c27a33efd44bdb17f15c930c18d79":{
      "scriptId":"u9"},
    "0a3f672909824e69902d8b0c50673c26":{
      "scriptId":"u10"},
    "416e8723c83d4f7aa14aabc3562af739":{
      "scriptId":"u11"},
    "bdfaa725bc6f427b87c93507084831b7":{
      "scriptId":"u12"},
    "79cbc809118b4049838d613eb560579a":{
      "scriptId":"u13"},
    "48ba3186988d414b9c89434f43de08f0":{
      "scriptId":"u14"},
    "85aa923fa9054585933f02968d59595b":{
      "scriptId":"u15"},
    "67f778e7ff0c410bbff7dab6062e251c":{
      "scriptId":"u16"},
    "a04ca9d5351949209f870899719edfe0":{
      "scriptId":"u17"},
    "4ca6462b976242a7a4c01a36a594453e":{
      "scriptId":"u18"},
    "03ed4982ccf94ad6a9f9fbba5a068957":{
      "scriptId":"u19"},
    "8e5e30209058428991575aa8351768ef":{
      "scriptId":"u20"},
    "be2939247eb54b9a85263b4196b38a7d":{
      "scriptId":"u21"},
    "217608d5b82d438ba98a610c538daa52":{
      "scriptId":"u22"},
    "364ecf905569495b8a5dd58d4d0c2c9c":{
      "scriptId":"u23"},
    "3daed86f807c44db8680de453ce55b31":{
      "scriptId":"u24"},
    "c36b154bae2f4ce9903471bb450e951e":{
      "scriptId":"u25"},
    "c61e19f3d53c4fdf8a88fed248c04ab5":{
      "scriptId":"u26"},
    "f88f2ec9251b4cf9aa485fb49d4e5091":{
      "scriptId":"u27"},
    "55f8edca66cd4dba9a1d97561729743a":{
      "scriptId":"u28"},
    "8eb7a434c41541c2bd3115c7aa12f135":{
      "scriptId":"u29"},
    "3b655994f6b24c6e839a06ed48192f6f":{
      "scriptId":"u30"},
    "769a97ad6f0a41fb9660fc9752b432e6":{
      "scriptId":"u31"},
    "dbe8410378c84672993f0ff53cb1d33a":{
      "scriptId":"u32"},
    "fc8278632437437dab56d9ce673251bc":{
      "scriptId":"u33"},
    "1586008d10d24219a5c7882b671252ed":{
      "scriptId":"u34"},
    "7c11ed18244e4255ae2c9cbf8c25fca9":{
      "scriptId":"u35"},
    "76a8d48f3b9243c1aae2f07d421ae019":{
      "scriptId":"u36"},
    "4fecf6fc391047809b124e21b4142572":{
      "scriptId":"u37"},
    "fbf339c291d442d1929439fd60008578":{
      "scriptId":"u38"},
    "1a476c737b9a4ad285a0a79c2588acc2":{
      "scriptId":"u39"},
    "b54a82df55444a6e8dd78c17ea99545d":{
      "scriptId":"u40"},
    "75d7a4a781d24f5499141c20a0f58336":{
      "scriptId":"u41"},
    "b9b1ba8c544f47638fcad64a7dce2935":{
      "scriptId":"u42"},
    "b53fecef3b3246f19a606db0f8ff3c25":{
      "scriptId":"u43"},
    "e407c68e6dcd4606bb04f9ca6b0d8cfe":{
      "scriptId":"u44"},
    "9c663dd60182448d9c4f78a378cb5727":{
      "scriptId":"u45"},
    "226b175b74b6439e91520ba9a6b543da":{
      "scriptId":"u46"},
    "490613f2ba3e4543ab61437c4dc3f1b6":{
      "scriptId":"u47"},
    "2e12ae0f0206441aa33133ec2272082b":{
      "scriptId":"u48"},
    "52e78cf3646b4120bc1b80096f5b700e":{
      "scriptId":"u49"},
    "22dd5c5f905245dab9562ed88a769ddc":{
      "scriptId":"u50"},
    "924e622e61414ee698dd2e2d6328ce56":{
      "scriptId":"u51"},
    "dab74d9b4113476e9b1cb8cca0f8bdff":{
      "scriptId":"u52"},
    "db8d48a75e9b4726a5b36e6fe9f0efba":{
      "scriptId":"u53"},
    "63f0aac6510544c598d3538306e1324f":{
      "scriptId":"u54"},
    "9bf479fe38be4e9fb4a2d2ba1b76fc30":{
      "scriptId":"u55"},
    "041ec5521c584474954ed6d254819f8c":{
      "scriptId":"u56"},
    "0431541d691a47829546fc3b9517873f":{
      "scriptId":"u57"},
    "64cc4e9b55444708adad2cbe9e85aafe":{
      "scriptId":"u58"},
    "be511142e5f74e4cbaab50c5c26ed12b":{
      "scriptId":"u59"},
    "f7322d454458477f92e65964f2b4ad19":{
      "scriptId":"u60"},
    "95a4f034cbe640a5a22962e75c368c73":{
      "scriptId":"u61"},
    "d6838b3ba71a4ccdab7708bf87d197f4":{
      "scriptId":"u62"},
    "565150347b094d7882c9dc09bb0668c2":{
      "scriptId":"u63"},
    "17477cf2d4e1415daf793e8f6da1fe91":{
      "scriptId":"u64"},
    "909a0f744b8a472796631f57305a0477":{
      "scriptId":"u65"},
    "be466b33c7ef443abddfdec7c3b969f9":{
      "scriptId":"u66"},
    "b8805311c1b244e4ba825077748b7745":{
      "scriptId":"u67"},
    "85761a570eb7472aa2aa6ad2d082cea5":{
      "scriptId":"u68"},
    "c55fea76e1f54ff485e81f287a75a35b":{
      "scriptId":"u69"},
    "a183b8d8fd404c169a91bba53be2e834":{
      "scriptId":"u70"},
    "a6cfcab892ce49f8bafbea759435efe0":{
      "scriptId":"u71"},
    "d6330e587c144f349151a8075206de62":{
      "scriptId":"u72"},
    "ea1856caee614623b63c435c504712c8":{
      "scriptId":"u73"},
    "afb2de1b645f46d38ce1694956583a84":{
      "scriptId":"u74"},
    "25f9b70e6263419089ab1861476c89f4":{
      "scriptId":"u75"},
    "ee1de1cca5924855849489e8ae559508":{
      "scriptId":"u76"},
    "22e1d5645052443b96efa1383fdf08ca":{
      "scriptId":"u77"},
    "52747baa3258429daa47fc3ee2d2fc49":{
      "scriptId":"u78"},
    "5bda141618a14519a77bfdac29e9beb1":{
      "scriptId":"u79"},
    "f639f6e964bc494b92a26327ed73ba38":{
      "scriptId":"u80"},
    "4f5bec4e90ce4eaba16fd8a73fd374a6":{
      "scriptId":"u81"},
    "de187ff632bc4aa78f746273e13a47de":{
      "scriptId":"u82"},
    "e4f0e43e496a41f193d614664d197cc5":{
      "scriptId":"u83"},
    "12628539407b4e3f8bcee4076af75b1a":{
      "scriptId":"u84"},
    "89661b46b817414887ae375996959e23":{
      "scriptId":"u85"},
    "a36ccec656d948858cb4bdefa2c1395d":{
      "scriptId":"u86"},
    "65c39c9505934574b73366e0c036b9b8":{
      "scriptId":"u87"}}});