$axure.loadCurrentPage({
  "url":"контакты.html",
  "generationDate":new Date(1493889317967.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bbddb3f07dbb4ddb9d87da75266c1f9e",
    "type":"Axure:Page",
    "name":"Контакты",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91fd0536228e413688a866d170ef89e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":256},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50b84a298d6040f9af396594bcf8b5e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":256},
                "size":{
                  "width":300,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8738d7c634ff431f90aff775938b2196",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":262},
            "size":{
              "width":470,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df91ca1c921c4ba8b5a4d445c5a90880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":262},
                "size":{
                  "width":470,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u2.png"}},
{
          "id":"eadb8f47785646d384c8bad0496304cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":362},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35b073a5a5554d4eb91be4eb6193053e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":362},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u4.png"}},
{
          "id":"da6a754d7ada403d874eb8433876e1c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":760,
              "y":262},
            "size":{
              "width":230,
              "height":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3a5060f920144fba36907e46e3b4a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":760,
                  "y":262},
                "size":{
                  "width":230,
                  "height":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u6.png"}},
{
          "id":"b962b1da49304f9cbe89b77410271014",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":776,
              "y":274},
            "size":{
              "width":177,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c40505d84bf949f28e61db6358add47b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":776,
                  "y":274},
                "size":{
                  "width":177,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c5f91ea8eb4040945abed8d5d15471",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":307},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4c814b3dad63424d949c9398fb89935b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":342},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ce97af5985a84357bc4db64e110c34d7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":377},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ff0e6af3fb3442318ef5ac8a71b9f34f",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":412},
            "size":{
              "width":200,
              "height":94}},
          "adaptiveStyles":{
}},
{
          "id":"68e373bff2a64da8915ac8974bc8828b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":776,
              "y":531},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"89b101792c51416ebb29422a28f7c010",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":201},
            "size":{
              "width":114,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9d2fc8cda8445abb61ff3e0323010e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":444,
                  "y":201},
                "size":{
                  "width":114,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"869b41c9581645a1a3a51189d1b8caf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":-3,
              "y":622},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0996f23bd1e402b946c35ae27efdf98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":-3,
                  "y":622},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u33.png"}},
{
          "id":"1d9ae33cbef544aebd678d39c9197997",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":147},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5355a9e9553d4d96af472c7a545762cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":147},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3b468a9ab8040678842f396a7a635f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":148},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65766b09047845b9bc38c83d8e976efe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":148},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a94fe32727434c768d81c047878e752f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":150},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"9d7793df507f4a959698370e74db7083",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c511d17c91ea465e8a65099fa76dfd32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":0},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"889aac6fb86d4ec78668986234848337",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"7bd94b91516a4dea94b0610b373fcfda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521b09392c5e41429aa10826805812a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e01f5ea0f7f4dd593a1342ef7693504",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6049f72b8ec420fb677d555b9bcbb8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"5dabf6fcce894e228c6b62f1f0dbea3b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"744af0fe0fc04093ab00803298b7905b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle Konsult",
                      "objectsToFades":[{
                          "objectPath":["2a47ac1c02a143c6bfea350631304a54"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"2f588ab2930a431d9524c918a8bbc99d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":252,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cee4877569ea467aa5d926017dd6aea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":252,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93e76f7fec71416a83fd9278abff3e0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f007dfc6f21449689d4b2b369cd802c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e3b61baeb074f908a7ea97220d07ecd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":641,
              "y":34},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b966257bf0444d73b5c5cd4a60340304",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":641,
                  "y":34},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddc4695adca24a1397e6f6ddfe313e0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":4},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76efb6a4f26142ebb7b98fc51811eafb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":4},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03ba674f734f4b978cbd2153e5bc5daa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480b4d24d4004436a0e23eb8617e8272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":916,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u17.png"}},
{
          "id":"f0bec9ed0320400d832bf8862eee1f86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c098b017b9db49a492bace48dcf640fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u19.png"}},
{
          "id":"e6f488031b064d5c9aefee2f0a6a2ff1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b110ee9a23c48279a52e29564de9b4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u21.png"}},
{
          "id":"755531bbc4e44d7ca3ac49e331a51b65",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":66},
            "size":{
              "width":500,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1828b7cfbc6e4014909ed4f36ff73e4a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"edd5f027d5a8470d87f72329b3b1d071",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c5bde444baf4ded97239c6484f83cd5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"68b69101cfc9488c9f40770b73522384",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b5299e202cc4a4ebd69c9bb88396267",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"dd1948ea89fb47a5bd080959e9d6c865",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8177ab6b114545b88b18a97ea0a75768",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u104.png"}},
{
                  "id":"5f3b8b42d4ed4c5397fb507d39208076",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8bc7950933342ceafcb5e3c648d5c4d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"72ae0d3696934992a45bb0432cbf1364",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"004b92ea017b463284b2fc7d5c8208c9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}}]},
{
              "id":"00ce912ee79e435c8b093e2a0a47d71c",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d40182455d1f4d999ab0ef63c3502f08",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b765708056843c4ae2155568066512f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3400e1004df14690834f966af02a6061",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"d0a60e1c36134125942422be1c20bf12",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7443c48000054bf180e98f5a2d166cf2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"4cc9729e97174fafaad26517b4fe304b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d132d91294554b1e977bee0a5948b325",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"fee5682630524592aa6ba4c14ae20f0a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f73db7c0b1054ff8adf9cdfcf37fcdee",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u126.png"}},
{
                      "id":"053f12d0d7d3410abf889820d36cc695",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"21b4abaf53784f3c9adc4e77591ebd6b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"0a8c2fd5a87f47c4958fe609fbfe01e2",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7c2f641819d04da2987c3e27100cef31",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"cec70cb13a664c7e8e4ca65edf31647e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9af4c117f1c046ec9bc55985b561f337",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"8f9eb83c1ead477b9fd16ebc97e3de0a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9ccc9b0c6af541ea97a7b27f3b051c34",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"96b73f498ea945c7ad6901f739dd013a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e8798d42131844209f2f03d9caa2e6f4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"7fb1081e88194d54a71766d433fbe90b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2abd39d67bb643cb82ffab798225fc01",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}}]}],
              "parentCellId":"68b69101cfc9488c9f40770b73522384"}]},
{
          "id":"2a47ac1c02a143c6bfea350631304a54",
          "label":"Konsult",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":235,
              "y":122},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"16798e2bf85f4674bee1488a50ed0e81",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aeb560596ff542e99bbcafa3c7f0da1f",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":358}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34c2f7ca572a4f2e8df7a489455e8991",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":100,
                          "y":50},
                        "size":{
                          "width":300,
                          "height":358}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u129.png"}},
{
                  "id":"5957f203b2374380a27b3760d533f84e",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":88},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"f38a4d32a83d43b588abf3dd87364653",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":72},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18841c74b7ac4363a2cb6831cfcf6600",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":72},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"71c8ac427db347ad92e8ea52ab8239ad",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":138},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"dca5d27e22b24881bcc5656df4470b7b",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":122},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d55e3cc044754f1baaa45d7f31e205bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":122},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c75e7b09279e40edae3c36eb9a5b5f03",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":188},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"e77c0316ca1b4ec4b85c9e69d0016c38",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":172},
                    "size":{
                      "width":49,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"128a865fa2f5430881d159cb7e7e982f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":172},
                        "size":{
                          "width":49,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ef46dd87a2124910be517c73b94bcfb7",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":238},
                    "size":{
                      "width":260,
                      "height":91}},
                  "adaptiveStyles":{
}},
{
                  "id":"d06e2a15929a46948e6bb56ac47b0f40",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":222},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbd39b921b9a42d4a7d2797448945b47",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":222},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e8dc2301a0e14cdc9104e0afa14fb080",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":348},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show banner",
                              "objectsToFades":[{
                                  "objectPath":["7e2b1f06740b4feb95c59644358f2aaf"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"8ceb13bbb9a84816a8a774bc67f7d5c5",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":288,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4553dca83f7c46b2ad8240175b5d82eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":106,
                          "y":0},
                        "size":{
                          "width":288,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e2b1f06740b4feb95c59644358f2aaf",
                  "label":"banner",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a3914de4e07944a58ef5eb68c44c84db",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"d529038ca33642b895137d066ac1ab59",
                          "label":"",
                          "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "size":{
                              "width":530,
                              "height":130}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"77d2ec8187a443dc9dd8ccb262446aae",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "size":{
                                  "width":530,
                                  "height":130}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/главная/u147.png"}},
{
                          "id":"3ce00153cdf94f9ca4e93a98e865b2ec",
                          "label":"",
                          "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":500,
                              "y":10},
                            "size":{
                              "width":20,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f462f65fce0e4522946285e5432a1817",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":500,
                                  "y":10},
                                "size":{
                                  "width":20,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Hide banner",
                                      "objectsToFades":[{
                                          "objectPath":["7e2b1f06740b4feb95c59644358f2aaf"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/главная/u149.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"730b53ae5367429e98470b31baa1f5fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":642,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98d190812fc14d57bac97d8cedb03368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":642,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "91fd0536228e413688a866d170ef89e7":{
      "scriptId":"u0"},
    "50b84a298d6040f9af396594bcf8b5e1":{
      "scriptId":"u1"},
    "8738d7c634ff431f90aff775938b2196":{
      "scriptId":"u2"},
    "df91ca1c921c4ba8b5a4d445c5a90880":{
      "scriptId":"u3"},
    "eadb8f47785646d384c8bad0496304cd":{
      "scriptId":"u4"},
    "35b073a5a5554d4eb91be4eb6193053e":{
      "scriptId":"u5"},
    "da6a754d7ada403d874eb8433876e1c5":{
      "scriptId":"u6"},
    "b3a5060f920144fba36907e46e3b4a6e":{
      "scriptId":"u7"},
    "b962b1da49304f9cbe89b77410271014":{
      "scriptId":"u8"},
    "c40505d84bf949f28e61db6358add47b":{
      "scriptId":"u9"},
    "08c5f91ea8eb4040945abed8d5d15471":{
      "scriptId":"u10"},
    "4c814b3dad63424d949c9398fb89935b":{
      "scriptId":"u11"},
    "ce97af5985a84357bc4db64e110c34d7":{
      "scriptId":"u12"},
    "ff0e6af3fb3442318ef5ac8a71b9f34f":{
      "scriptId":"u13"},
    "68e373bff2a64da8915ac8974bc8828b":{
      "scriptId":"u14"},
    "89b101792c51416ebb29422a28f7c010":{
      "scriptId":"u15"},
    "e9d2fc8cda8445abb61ff3e0323010e8":{
      "scriptId":"u16"},
    "869b41c9581645a1a3a51189d1b8caf4":{
      "scriptId":"u17"},
    "d0996f23bd1e402b946c35ae27efdf98":{
      "scriptId":"u18"},
    "1d9ae33cbef544aebd678d39c9197997":{
      "scriptId":"u19"},
    "5355a9e9553d4d96af472c7a545762cd":{
      "scriptId":"u20"},
    "b3b468a9ab8040678842f396a7a635f7":{
      "scriptId":"u21"},
    "65766b09047845b9bc38c83d8e976efe":{
      "scriptId":"u22"},
    "a94fe32727434c768d81c047878e752f":{
      "scriptId":"u23"},
    "9d7793df507f4a959698370e74db7083":{
      "scriptId":"u24"},
    "c511d17c91ea465e8a65099fa76dfd32":{
      "scriptId":"u25"},
    "889aac6fb86d4ec78668986234848337":{
      "scriptId":"u26"},
    "7bd94b91516a4dea94b0610b373fcfda":{
      "scriptId":"u27"},
    "521b09392c5e41429aa10826805812a8":{
      "scriptId":"u28"},
    "5e01f5ea0f7f4dd593a1342ef7693504":{
      "scriptId":"u29"},
    "f6049f72b8ec420fb677d555b9bcbb8b":{
      "scriptId":"u30"},
    "5dabf6fcce894e228c6b62f1f0dbea3b":{
      "scriptId":"u31"},
    "744af0fe0fc04093ab00803298b7905b":{
      "scriptId":"u32"},
    "2f588ab2930a431d9524c918a8bbc99d":{
      "scriptId":"u33"},
    "cee4877569ea467aa5d926017dd6aea4":{
      "scriptId":"u34"},
    "93e76f7fec71416a83fd9278abff3e0a":{
      "scriptId":"u35"},
    "5f007dfc6f21449689d4b2b369cd802c":{
      "scriptId":"u36"},
    "5e3b61baeb074f908a7ea97220d07ecd":{
      "scriptId":"u37"},
    "b966257bf0444d73b5c5cd4a60340304":{
      "scriptId":"u38"},
    "ddc4695adca24a1397e6f6ddfe313e0d":{
      "scriptId":"u39"},
    "76efb6a4f26142ebb7b98fc51811eafb":{
      "scriptId":"u40"},
    "03ba674f734f4b978cbd2153e5bc5daa":{
      "scriptId":"u41"},
    "480b4d24d4004436a0e23eb8617e8272":{
      "scriptId":"u42"},
    "f0bec9ed0320400d832bf8862eee1f86":{
      "scriptId":"u43"},
    "c098b017b9db49a492bace48dcf640fd":{
      "scriptId":"u44"},
    "e6f488031b064d5c9aefee2f0a6a2ff1":{
      "scriptId":"u45"},
    "6b110ee9a23c48279a52e29564de9b4a":{
      "scriptId":"u46"},
    "755531bbc4e44d7ca3ac49e331a51b65":{
      "scriptId":"u47"},
    "1828b7cfbc6e4014909ed4f36ff73e4a":{
      "scriptId":"u48"},
    "edd5f027d5a8470d87f72329b3b1d071":{
      "scriptId":"u49"},
    "9c5bde444baf4ded97239c6484f83cd5":{
      "scriptId":"u50"},
    "68b69101cfc9488c9f40770b73522384":{
      "scriptId":"u51"},
    "2b5299e202cc4a4ebd69c9bb88396267":{
      "scriptId":"u52"},
    "72ae0d3696934992a45bb0432cbf1364":{
      "scriptId":"u53"},
    "004b92ea017b463284b2fc7d5c8208c9":{
      "scriptId":"u54"},
    "5f3b8b42d4ed4c5397fb507d39208076":{
      "scriptId":"u55"},
    "f8bc7950933342ceafcb5e3c648d5c4d":{
      "scriptId":"u56"},
    "dd1948ea89fb47a5bd080959e9d6c865":{
      "scriptId":"u57"},
    "8177ab6b114545b88b18a97ea0a75768":{
      "scriptId":"u58"},
    "00ce912ee79e435c8b093e2a0a47d71c":{
      "scriptId":"u59"},
    "d40182455d1f4d999ab0ef63c3502f08":{
      "scriptId":"u60"},
    "1b765708056843c4ae2155568066512f":{
      "scriptId":"u61"},
    "3400e1004df14690834f966af02a6061":{
      "scriptId":"u62"},
    "d0a60e1c36134125942422be1c20bf12":{
      "scriptId":"u63"},
    "7443c48000054bf180e98f5a2d166cf2":{
      "scriptId":"u64"},
    "4cc9729e97174fafaad26517b4fe304b":{
      "scriptId":"u65"},
    "d132d91294554b1e977bee0a5948b325":{
      "scriptId":"u66"},
    "cec70cb13a664c7e8e4ca65edf31647e":{
      "scriptId":"u67"},
    "9af4c117f1c046ec9bc55985b561f337":{
      "scriptId":"u68"},
    "0a8c2fd5a87f47c4958fe609fbfe01e2":{
      "scriptId":"u69"},
    "7c2f641819d04da2987c3e27100cef31":{
      "scriptId":"u70"},
    "053f12d0d7d3410abf889820d36cc695":{
      "scriptId":"u71"},
    "21b4abaf53784f3c9adc4e77591ebd6b":{
      "scriptId":"u72"},
    "7fb1081e88194d54a71766d433fbe90b":{
      "scriptId":"u73"},
    "2abd39d67bb643cb82ffab798225fc01":{
      "scriptId":"u74"},
    "96b73f498ea945c7ad6901f739dd013a":{
      "scriptId":"u75"},
    "e8798d42131844209f2f03d9caa2e6f4":{
      "scriptId":"u76"},
    "8f9eb83c1ead477b9fd16ebc97e3de0a":{
      "scriptId":"u77"},
    "9ccc9b0c6af541ea97a7b27f3b051c34":{
      "scriptId":"u78"},
    "fee5682630524592aa6ba4c14ae20f0a":{
      "scriptId":"u79"},
    "f73db7c0b1054ff8adf9cdfcf37fcdee":{
      "scriptId":"u80"},
    "2a47ac1c02a143c6bfea350631304a54":{
      "scriptId":"u81"},
    "aeb560596ff542e99bbcafa3c7f0da1f":{
      "scriptId":"u82"},
    "34c2f7ca572a4f2e8df7a489455e8991":{
      "scriptId":"u83"},
    "5957f203b2374380a27b3760d533f84e":{
      "scriptId":"u84"},
    "f38a4d32a83d43b588abf3dd87364653":{
      "scriptId":"u85"},
    "18841c74b7ac4363a2cb6831cfcf6600":{
      "scriptId":"u86"},
    "71c8ac427db347ad92e8ea52ab8239ad":{
      "scriptId":"u87"},
    "dca5d27e22b24881bcc5656df4470b7b":{
      "scriptId":"u88"},
    "d55e3cc044754f1baaa45d7f31e205bb":{
      "scriptId":"u89"},
    "c75e7b09279e40edae3c36eb9a5b5f03":{
      "scriptId":"u90"},
    "e77c0316ca1b4ec4b85c9e69d0016c38":{
      "scriptId":"u91"},
    "128a865fa2f5430881d159cb7e7e982f":{
      "scriptId":"u92"},
    "ef46dd87a2124910be517c73b94bcfb7":{
      "scriptId":"u93"},
    "d06e2a15929a46948e6bb56ac47b0f40":{
      "scriptId":"u94"},
    "dbd39b921b9a42d4a7d2797448945b47":{
      "scriptId":"u95"},
    "e8dc2301a0e14cdc9104e0afa14fb080":{
      "scriptId":"u96"},
    "8ceb13bbb9a84816a8a774bc67f7d5c5":{
      "scriptId":"u97"},
    "4553dca83f7c46b2ad8240175b5d82eb":{
      "scriptId":"u98"},
    "7e2b1f06740b4feb95c59644358f2aaf":{
      "scriptId":"u99"},
    "d529038ca33642b895137d066ac1ab59":{
      "scriptId":"u100"},
    "77d2ec8187a443dc9dd8ccb262446aae":{
      "scriptId":"u101"},
    "3ce00153cdf94f9ca4e93a98e865b2ec":{
      "scriptId":"u102"},
    "f462f65fce0e4522946285e5432a1817":{
      "scriptId":"u103"},
    "730b53ae5367429e98470b31baa1f5fb":{
      "scriptId":"u104"},
    "98d190812fc14d57bac97d8cedb03368":{
      "scriptId":"u105"}}});