$axure.loadCurrentPage({
  "url":"отзывы.html",
  "generationDate":new Date(1494499902191.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"15023fdf63974b9eafcd21511ae05f85",
    "type":"Axure:Page",
    "name":"Отзывы",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dceca9ffd0ad4abd8eeee3bfe1578292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":3,
              "y":233},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2deabb9bebdd4c23b7a9d00d2ea83035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":3,
                  "y":233},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44249af757fe4d66a5f261718aa56b68",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":236},
            "size":{
              "width":17,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/отзывы/u2_end.png",
            "line~":"images/отзывы/u2_line.png"}},
{
          "id":"3be5765aef5741978f58016d26e5d183",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":76,
              "y":233},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a62de04011048fe916dd2d92727d3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":76,
                  "y":233},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d9e74d921c54fa4bcea770d3f9a4a2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":78,
              "y":339},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9afdeac4d6634efc9d74ae3ea0df01d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":78,
                  "y":339},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e89c0c583e34b69a5a89ed9c4f628af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":80,
              "y":376},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87431022a8194eac9a77be772b8aa74c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":80,
                  "y":376},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0c0ae2ddf6141e7bf76811f376c2701",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":368},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2e479192c44285b9a386cedbe0569f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":368},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"de69721367a647178f0d04e78cf491c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":413},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0d722491e6460ebee8fa567c4067be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":413},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65431a13d2294461888961b5b9c2ac2a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":471},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"3c320eb58123452cbe19847a27fa414f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":256},
            "size":{
              "width":99,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe0332dfc0645308fc0c6f68616786d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":256},
                "size":{
                  "width":99,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a3e325c01f74064b5a299a4abbc7fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "location":{
              "x":413,
              "y":1125},
            "size":{
              "width":177,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c0c2922479c44a0a745a1d88f5f882e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "location":{
                  "x":413,
                  "y":1125},
                "size":{
                  "width":177,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f555cd977acc4a568c47b4f5139cb07b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":1078},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u102_image_sketch.png",
            "disabled~":"images/каталог/u102_disabled.png"}},
{
          "id":"883525f5fc664058be440497816e051e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":1181},
            "size":{
              "width":980,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"671e589bf7c44c558d9fc81e26fa0627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":1181},
                "size":{
                  "width":980,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db7d8c3ad18e4f1190d12bcef199244e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":80,
              "y":526},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e3787c19e8d473ca16037c3428d0b2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":80,
                  "y":526},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ce84369cc294b6c867ea4bcf1784a1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":82,
              "y":563},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c167271ee83454fa83fc590d7ea5428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":82,
                  "y":563},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f4102c4569f499b8700ebbdb72e23e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":555},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f29143f3b5b4483ea199ae12e13b1a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":555},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"e80e72f4919e41f0a6a81b62ed468a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":600},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7ba6e5fff0429191f3de71889726ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":600},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f904ce4dccc4774b236715d9c057a10",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":658},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"6a981290230b48e29409c558d6c6177c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":900},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb1a0c1efffd4d8c963a14223ce959b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":900},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5fc0a4908924dd1a137d7e76ec3a3e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":84,
              "y":937},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01e98b8e9eb45f0addd937ca39d7ed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":84,
                  "y":937},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f8522a20a464571ab72be4459445d93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":929},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52db0bb322b64601be66b743acb7b098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":929},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"353e09b7fdce4ccdb736b4f7adbf1069",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":974},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2516b02a1991439db010280184e5ff40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":974},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5db0805aa3bb40ce8775f322c9452bea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":1032},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"e4a5bf47e5dd4c7b819711476ffe04c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":90,
              "y":713},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c53b993d2a8d4d2e9465229f86ce4aa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":90,
                  "y":713},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa2ac76f54ea4facbbccda0cdb8f576a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":750},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e4a568bdf6747a6b3b8016609ea3574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":750},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce0b2e69634d4f1c94acf6243d8d2789",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":742},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6609200958b04af19a3d21470128f150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":742},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"cd8a8216d63f4d1291ebdcd9e7be0d5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":787},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a7193faf5e4156b216b396f6904fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":787},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db72f9033856439b84f94d4135ee6e48",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":845},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"72486addddc34b65befb7ce6d69bf126",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-4,
              "y":1450},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"904cb5ac5ef44df2bf6cbf95c17c0271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-4,
                  "y":1450},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"29acc76d57b94baeae4106ab8c100c22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa737041cec479b8d698048f5011488",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"e8cc45f13e594457b77d996fdcae8e46",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d023abb26be4c39a598160fc32d5b78",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4d29014ab7048e48f036dbf05474289",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ccbdaf6bd6ac4da58b49a1bbd2a4e0f0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"0958deae7db24588aa3333ceb0a19bb2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80ec6144206d47e4b257ffad083abf0d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"e71fe925e45e4cb0b84b00496599871c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cede9a64c023439a93df7cf51e30ccf0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"5291a13d7e9f41349f71ea1bfd31a7b0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f152121e04440f98d2f6a53a2c33521",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"18f3b1c730d0469cb8684136b4037731",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b828ff13f5a541fd90d5e3961f7b895f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"9cca211e15ee476b82b969e9aa1869bf",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3aa1e7080834b799153150eee7fcc52",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc946a7c2ba548dcb4a940b14f892e70",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"21219b100f834f748c622b7c09f0b836",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"83c0322dce8b4bc2a61823bf8ce8799b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5883c9eee0ea41729e3ea5e8ed03c7f4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"adf3a04c4b5c4eb589571345e785c35b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c13477ca4ff641e7b0e06ead511031db",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"7197c61211f545cb8a4df9163549cc8f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"eb81ffbbd3974efca47bd551de940e03",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"0a06ab73e3d34df2b9b6ef5fc52cf027",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8ceea98f57f643df887b2c62987856e2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"0958deae7db24588aa3333ceb0a19bb2"}]},
{
          "id":"56833eb9def744ea9d81378cd0b8077f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"f59fe87526b94f87acf4a031a7ea8b4c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"10d4069f8838437a806b64dad47492f8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"bbb60e2539df45d886817605db578178",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47a3903a71a1496f956588e62f21c6f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5974e2e0f70d437eab97ee3b7ec43cbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11dae9849181472b9fd16419d14c5846",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8369093fe664438b128b53fb3a5b20a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f3638ad71a44f8a84486b371be4279d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"32df0336cc2c4abca86e609f66eb6ed3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4433fcb37ea14915af09243bcd4b3e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"22dbb164940045489219b42c1736395b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"600a1c11ff184c07a683a162d0ae9f29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e282c56aba8f4d0e8a2fc4040961d459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dceca9ffd0ad4abd8eeee3bfe1578292":{
      "scriptId":"u0"},
    "2deabb9bebdd4c23b7a9d00d2ea83035":{
      "scriptId":"u1"},
    "44249af757fe4d66a5f261718aa56b68":{
      "scriptId":"u2"},
    "3be5765aef5741978f58016d26e5d183":{
      "scriptId":"u3"},
    "9a62de04011048fe916dd2d92727d3d5":{
      "scriptId":"u4"},
    "0d9e74d921c54fa4bcea770d3f9a4a2b":{
      "scriptId":"u5"},
    "9afdeac4d6634efc9d74ae3ea0df01d8":{
      "scriptId":"u6"},
    "0e89c0c583e34b69a5a89ed9c4f628af":{
      "scriptId":"u7"},
    "87431022a8194eac9a77be772b8aa74c":{
      "scriptId":"u8"},
    "b0c0ae2ddf6141e7bf76811f376c2701":{
      "scriptId":"u9"},
    "4e2e479192c44285b9a386cedbe0569f":{
      "scriptId":"u10"},
    "de69721367a647178f0d04e78cf491c7":{
      "scriptId":"u11"},
    "ff0d722491e6460ebee8fa567c4067be":{
      "scriptId":"u12"},
    "65431a13d2294461888961b5b9c2ac2a":{
      "scriptId":"u13"},
    "3c320eb58123452cbe19847a27fa414f":{
      "scriptId":"u14"},
    "6fe0332dfc0645308fc0c6f68616786d":{
      "scriptId":"u15"},
    "1a3e325c01f74064b5a299a4abbc7fb5":{
      "scriptId":"u16"},
    "9c0c2922479c44a0a745a1d88f5f882e":{
      "scriptId":"u17"},
    "f555cd977acc4a568c47b4f5139cb07b":{
      "scriptId":"u18"},
    "883525f5fc664058be440497816e051e":{
      "scriptId":"u19"},
    "671e589bf7c44c558d9fc81e26fa0627":{
      "scriptId":"u20"},
    "db7d8c3ad18e4f1190d12bcef199244e":{
      "scriptId":"u21"},
    "4e3787c19e8d473ca16037c3428d0b2f":{
      "scriptId":"u22"},
    "3ce84369cc294b6c867ea4bcf1784a1f":{
      "scriptId":"u23"},
    "7c167271ee83454fa83fc590d7ea5428":{
      "scriptId":"u24"},
    "1f4102c4569f499b8700ebbdb72e23e6":{
      "scriptId":"u25"},
    "f29143f3b5b4483ea199ae12e13b1a41":{
      "scriptId":"u26"},
    "e80e72f4919e41f0a6a81b62ed468a46":{
      "scriptId":"u27"},
    "de7ba6e5fff0429191f3de71889726ea":{
      "scriptId":"u28"},
    "4f904ce4dccc4774b236715d9c057a10":{
      "scriptId":"u29"},
    "6a981290230b48e29409c558d6c6177c":{
      "scriptId":"u30"},
    "eb1a0c1efffd4d8c963a14223ce959b0":{
      "scriptId":"u31"},
    "c5fc0a4908924dd1a137d7e76ec3a3e2":{
      "scriptId":"u32"},
    "c01e98b8e9eb45f0addd937ca39d7ed8":{
      "scriptId":"u33"},
    "5f8522a20a464571ab72be4459445d93":{
      "scriptId":"u34"},
    "52db0bb322b64601be66b743acb7b098":{
      "scriptId":"u35"},
    "353e09b7fdce4ccdb736b4f7adbf1069":{
      "scriptId":"u36"},
    "2516b02a1991439db010280184e5ff40":{
      "scriptId":"u37"},
    "5db0805aa3bb40ce8775f322c9452bea":{
      "scriptId":"u38"},
    "e4a5bf47e5dd4c7b819711476ffe04c7":{
      "scriptId":"u39"},
    "c53b993d2a8d4d2e9465229f86ce4aa2":{
      "scriptId":"u40"},
    "aa2ac76f54ea4facbbccda0cdb8f576a":{
      "scriptId":"u41"},
    "6e4a568bdf6747a6b3b8016609ea3574":{
      "scriptId":"u42"},
    "ce0b2e69634d4f1c94acf6243d8d2789":{
      "scriptId":"u43"},
    "6609200958b04af19a3d21470128f150":{
      "scriptId":"u44"},
    "cd8a8216d63f4d1291ebdcd9e7be0d5e":{
      "scriptId":"u45"},
    "38a7193faf5e4156b216b396f6904fbe":{
      "scriptId":"u46"},
    "db72f9033856439b84f94d4135ee6e48":{
      "scriptId":"u47"},
    "72486addddc34b65befb7ce6d69bf126":{
      "scriptId":"u48"},
    "904cb5ac5ef44df2bf6cbf95c17c0271":{
      "scriptId":"u49"},
    "29acc76d57b94baeae4106ab8c100c22":{
      "scriptId":"u50"},
    "baa737041cec479b8d698048f5011488":{
      "scriptId":"u51"},
    "e8cc45f13e594457b77d996fdcae8e46":{
      "scriptId":"u52"},
    "7d023abb26be4c39a598160fc32d5b78":{
      "scriptId":"u53"},
    "a4d29014ab7048e48f036dbf05474289":{
      "scriptId":"u54"},
    "ccbdaf6bd6ac4da58b49a1bbd2a4e0f0":{
      "scriptId":"u55"},
    "0958deae7db24588aa3333ceb0a19bb2":{
      "scriptId":"u56"},
    "80ec6144206d47e4b257ffad083abf0d":{
      "scriptId":"u57"},
    "5291a13d7e9f41349f71ea1bfd31a7b0":{
      "scriptId":"u58"},
    "0f152121e04440f98d2f6a53a2c33521":{
      "scriptId":"u59"},
    "18f3b1c730d0469cb8684136b4037731":{
      "scriptId":"u60"},
    "b828ff13f5a541fd90d5e3961f7b895f":{
      "scriptId":"u61"},
    "e71fe925e45e4cb0b84b00496599871c":{
      "scriptId":"u62"},
    "cede9a64c023439a93df7cf51e30ccf0":{
      "scriptId":"u63"},
    "9cca211e15ee476b82b969e9aa1869bf":{
      "scriptId":"u64"},
    "b3aa1e7080834b799153150eee7fcc52":{
      "scriptId":"u65"},
    "fc946a7c2ba548dcb4a940b14f892e70":{
      "scriptId":"u66"},
    "21219b100f834f748c622b7c09f0b836":{
      "scriptId":"u67"},
    "adf3a04c4b5c4eb589571345e785c35b":{
      "scriptId":"u68"},
    "c13477ca4ff641e7b0e06ead511031db":{
      "scriptId":"u69"},
    "7197c61211f545cb8a4df9163549cc8f":{
      "scriptId":"u70"},
    "eb81ffbbd3974efca47bd551de940e03":{
      "scriptId":"u71"},
    "83c0322dce8b4bc2a61823bf8ce8799b":{
      "scriptId":"u72"},
    "5883c9eee0ea41729e3ea5e8ed03c7f4":{
      "scriptId":"u73"},
    "0a06ab73e3d34df2b9b6ef5fc52cf027":{
      "scriptId":"u74"},
    "8ceea98f57f643df887b2c62987856e2":{
      "scriptId":"u75"},
    "56833eb9def744ea9d81378cd0b8077f":{
      "scriptId":"u76"},
    "f59fe87526b94f87acf4a031a7ea8b4c":{
      "scriptId":"u77"},
    "10d4069f8838437a806b64dad47492f8":{
      "scriptId":"u78"},
    "bbb60e2539df45d886817605db578178":{
      "scriptId":"u79"},
    "47a3903a71a1496f956588e62f21c6f8":{
      "scriptId":"u80"},
    "5974e2e0f70d437eab97ee3b7ec43cbd":{
      "scriptId":"u81"},
    "11dae9849181472b9fd16419d14c5846":{
      "scriptId":"u82"},
    "c8369093fe664438b128b53fb3a5b20a":{
      "scriptId":"u83"},
    "8f3638ad71a44f8a84486b371be4279d":{
      "scriptId":"u84"},
    "32df0336cc2c4abca86e609f66eb6ed3":{
      "scriptId":"u85"},
    "4433fcb37ea14915af09243bcd4b3e5f":{
      "scriptId":"u86"},
    "22dbb164940045489219b42c1736395b":{
      "scriptId":"u87"},
    "600a1c11ff184c07a683a162d0ae9f29":{
      "scriptId":"u88"},
    "e282c56aba8f4d0e8a2fc4040961d459":{
      "scriptId":"u89"}}});