$axure.loadCurrentPage({
  "url":"контакты.html",
  "generationDate":new Date(1494499902575.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"4ef15b743c06484784fd5e0075c7c9cf",
    "type":"Axure:Page",
    "name":"Контакты",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a1417c625dcd4a97aad9dfe851d15c5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":322},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ecad52d4b74e89b6b4442043b8b9c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":322},
                "size":{
                  "width":300,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc4fc11bb9f142b6a1ab20f52f905677",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":328},
            "size":{
              "width":470,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e4f4e899b54ec499e523de85702bf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":328},
                "size":{
                  "width":470,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u2.png"}},
{
          "id":"ab89171e91144707914ab923b926dc86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":428},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6700017f0b6846e09203be1dac534ed7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":428},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u4.png"}},
{
          "id":"1051a92c59ff41d4a9fa4a5573cf76ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEDEDED},
            "location":{
              "x":760,
              "y":328},
            "size":{
              "width":230,
              "height":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFEFEFE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa27633b88ce4b1599da2cac3e8f6da2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEDEDED},
                "location":{
                  "x":760,
                  "y":328},
                "size":{
                  "width":230,
                  "height":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFEFEFE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u6.png"}},
{
          "id":"a50d80ee16d74d088be31ec0aef1c3f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":776,
              "y":340},
            "size":{
              "width":177,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb52c7af54248b3a70387fa9d2ec683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":776,
                  "y":340},
                "size":{
                  "width":177,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86d389ee129045789e4f7ea7be8f4c3d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":373},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"f4a76a693ed448bd811ef81a2acdb4af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":408},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"2d9aff9396f747f88948ea77b65e4f10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":443},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"889c166b6d484ff7af740ed00039e2f2",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":478},
            "size":{
              "width":200,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u13_image_sketch.png",
            "disabled~":"images/контакты/u13_disabled.png"}},
{
          "id":"39629aae70de47629661bab63d09a22d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":776,
              "y":597},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u14_image_sketch.png",
            "disabled~":"images/контакты/u14_disabled.png"}},
{
          "id":"dd9ae83be44c41d0bd4149b3733b84c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":267},
            "size":{
              "width":114,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"767ce9066af04d1d896969733e7dd750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":444,
                  "y":267},
                "size":{
                  "width":114,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30cb5f2731e54378bdf8cffd8045c841",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-3,
              "y":688},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50babb2b763e4acdaea8d977d98d913b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-3,
                  "y":688},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"52acf44c6f2447599a00528cfd653ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":213},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aafc4c84ac01438dbb6b8b7cd800db81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":213},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48dcd52ce0d34138972e3c24291fac2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":214},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a6025d4e7a34aeabaca99b95d91ff1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":214},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e16094a41dfc4ce28ed2be00fcaa8698",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":216},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"bb68d737c22642edba78a7342d39a5af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be89c767cb68490e8fe50acb2c7b6bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"0e674b5f9f894863841d7c1242487b43",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca3edd605a844da9a9343417e9014c7",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7ab0f0675ad480b9be2d1acd61ca530",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42bd7201089e48c39dc94b7a195cd452",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"f2f8594dbcff482a88bc342d554bb7c2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4f2705d3945a486b9b378554fb130d1d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"b3bd241d694a42dea5ec4a99cfed0aa6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a179f1a5aaa47099fdfa0308a6a1022",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"0e996666c84d42199007ae511a66c9ab",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68ed7722e218463ca0874d2e2f44845f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"1cbb6e7812a445ea88c9bcf1c16697c8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f47f619a3392429b9509452213201c61",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"909c628a1bb74e5ebe92502a8255fec4",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ad730d7deff4ce3b4ed29bb15dba316",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2769abe71e1a4977a9bd72260261674f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"488d068c1e0948ac9d654e06eb3e0a4f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"0b027d695c204342a811b18d6399d642",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4ed428642d2e407c9f4b55c9ba4acdac",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"b3cc5fb33ee34780a82a8df044efc24b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"05512f8701a24ee18ebb207e5778b633",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"89f4f2d6bf3f4ae7b19d60cb23fcb2e6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ab0188c7501a42dcbceeb1e544447424",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"318a49af25084e3c83e3726affc2bfc8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"63462aa774534bef983bbbfdec9d632e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"f2f8594dbcff482a88bc342d554bb7c2"}]},
{
          "id":"fb195c775d9f4da69a083ccc6e5226ef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"1d9e1f7c9a2f449eb33d7e098eed9cdd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"616fdcc4bd3e4ac282c62b760ba34011",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"205ec709ef884c80b3515c0cb109f87c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bd3ec8c0db14eca97f8b9916d8ca750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c1b246c3b43417aa63f234b4e541f22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ffc25b64f07497cad2e69f3f4a9381e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bef8608417c4131a5b4418862a195a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a661ea9e0dd94c1590f5c59b7b6c9c93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"1d1c9964061643a2989198eea2045422",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b4bcae1d454b0ba95b1436936b5868",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"b8a53aa133314a1cbf30369c9d3edc3d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"8ba4efca89b140639e0a9c71783f10d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45eeef241665435b96a01beab1f794e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a1417c625dcd4a97aad9dfe851d15c5a":{
      "scriptId":"u0"},
    "23ecad52d4b74e89b6b4442043b8b9c1":{
      "scriptId":"u1"},
    "fc4fc11bb9f142b6a1ab20f52f905677":{
      "scriptId":"u2"},
    "c7e4f4e899b54ec499e523de85702bf0":{
      "scriptId":"u3"},
    "ab89171e91144707914ab923b926dc86":{
      "scriptId":"u4"},
    "6700017f0b6846e09203be1dac534ed7":{
      "scriptId":"u5"},
    "1051a92c59ff41d4a9fa4a5573cf76ce":{
      "scriptId":"u6"},
    "aa27633b88ce4b1599da2cac3e8f6da2":{
      "scriptId":"u7"},
    "a50d80ee16d74d088be31ec0aef1c3f6":{
      "scriptId":"u8"},
    "bdb52c7af54248b3a70387fa9d2ec683":{
      "scriptId":"u9"},
    "86d389ee129045789e4f7ea7be8f4c3d":{
      "scriptId":"u10"},
    "f4a76a693ed448bd811ef81a2acdb4af":{
      "scriptId":"u11"},
    "2d9aff9396f747f88948ea77b65e4f10":{
      "scriptId":"u12"},
    "889c166b6d484ff7af740ed00039e2f2":{
      "scriptId":"u13"},
    "39629aae70de47629661bab63d09a22d":{
      "scriptId":"u14"},
    "dd9ae83be44c41d0bd4149b3733b84c7":{
      "scriptId":"u15"},
    "767ce9066af04d1d896969733e7dd750":{
      "scriptId":"u16"},
    "30cb5f2731e54378bdf8cffd8045c841":{
      "scriptId":"u17"},
    "50babb2b763e4acdaea8d977d98d913b":{
      "scriptId":"u18"},
    "52acf44c6f2447599a00528cfd653ae9":{
      "scriptId":"u19"},
    "aafc4c84ac01438dbb6b8b7cd800db81":{
      "scriptId":"u20"},
    "48dcd52ce0d34138972e3c24291fac2a":{
      "scriptId":"u21"},
    "7a6025d4e7a34aeabaca99b95d91ff1f":{
      "scriptId":"u22"},
    "e16094a41dfc4ce28ed2be00fcaa8698":{
      "scriptId":"u23"},
    "bb68d737c22642edba78a7342d39a5af":{
      "scriptId":"u24"},
    "be89c767cb68490e8fe50acb2c7b6bcd":{
      "scriptId":"u25"},
    "0e674b5f9f894863841d7c1242487b43":{
      "scriptId":"u26"},
    "dca3edd605a844da9a9343417e9014c7":{
      "scriptId":"u27"},
    "c7ab0f0675ad480b9be2d1acd61ca530":{
      "scriptId":"u28"},
    "42bd7201089e48c39dc94b7a195cd452":{
      "scriptId":"u29"},
    "f2f8594dbcff482a88bc342d554bb7c2":{
      "scriptId":"u30"},
    "4f2705d3945a486b9b378554fb130d1d":{
      "scriptId":"u31"},
    "0e996666c84d42199007ae511a66c9ab":{
      "scriptId":"u32"},
    "68ed7722e218463ca0874d2e2f44845f":{
      "scriptId":"u33"},
    "1cbb6e7812a445ea88c9bcf1c16697c8":{
      "scriptId":"u34"},
    "f47f619a3392429b9509452213201c61":{
      "scriptId":"u35"},
    "b3bd241d694a42dea5ec4a99cfed0aa6":{
      "scriptId":"u36"},
    "5a179f1a5aaa47099fdfa0308a6a1022":{
      "scriptId":"u37"},
    "909c628a1bb74e5ebe92502a8255fec4":{
      "scriptId":"u38"},
    "4ad730d7deff4ce3b4ed29bb15dba316":{
      "scriptId":"u39"},
    "2769abe71e1a4977a9bd72260261674f":{
      "scriptId":"u40"},
    "488d068c1e0948ac9d654e06eb3e0a4f":{
      "scriptId":"u41"},
    "b3cc5fb33ee34780a82a8df044efc24b":{
      "scriptId":"u42"},
    "05512f8701a24ee18ebb207e5778b633":{
      "scriptId":"u43"},
    "89f4f2d6bf3f4ae7b19d60cb23fcb2e6":{
      "scriptId":"u44"},
    "ab0188c7501a42dcbceeb1e544447424":{
      "scriptId":"u45"},
    "0b027d695c204342a811b18d6399d642":{
      "scriptId":"u46"},
    "4ed428642d2e407c9f4b55c9ba4acdac":{
      "scriptId":"u47"},
    "318a49af25084e3c83e3726affc2bfc8":{
      "scriptId":"u48"},
    "63462aa774534bef983bbbfdec9d632e":{
      "scriptId":"u49"},
    "fb195c775d9f4da69a083ccc6e5226ef":{
      "scriptId":"u50"},
    "1d9e1f7c9a2f449eb33d7e098eed9cdd":{
      "scriptId":"u51"},
    "616fdcc4bd3e4ac282c62b760ba34011":{
      "scriptId":"u52"},
    "205ec709ef884c80b3515c0cb109f87c":{
      "scriptId":"u53"},
    "8bd3ec8c0db14eca97f8b9916d8ca750":{
      "scriptId":"u54"},
    "6c1b246c3b43417aa63f234b4e541f22":{
      "scriptId":"u55"},
    "5ffc25b64f07497cad2e69f3f4a9381e":{
      "scriptId":"u56"},
    "9bef8608417c4131a5b4418862a195a4":{
      "scriptId":"u57"},
    "a661ea9e0dd94c1590f5c59b7b6c9c93":{
      "scriptId":"u58"},
    "1d1c9964061643a2989198eea2045422":{
      "scriptId":"u59"},
    "99b4bcae1d454b0ba95b1436936b5868":{
      "scriptId":"u60"},
    "b8a53aa133314a1cbf30369c9d3edc3d":{
      "scriptId":"u61"},
    "8ba4efca89b140639e0a9c71783f10d6":{
      "scriptId":"u62"},
    "45eeef241665435b96a01beab1f794e6":{
      "scriptId":"u63"}}});