$axure.loadCurrentPage({
  "url":"мой_профиль.html",
  "generationDate":new Date(1494917362919.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba1cda0212154936aaba72b9272c114d",
    "type":"Axure:Page",
    "name":"Мой профиль",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"586e7ead74684629b536ec7c6d0ad757",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":155},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f5776fc8e29469db3ce7fd13a2ae5cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":155},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da57547b630b4adda5dbf005ab10f533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":155},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb9a09887601418cbeed7cf3c089ff33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":155},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7342b50e38440b0ba7cc562c8258b7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":158},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"4e11f917623246f497709f985061b33b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":250,
              "y":266},
            "size":{
              "width":498,
              "height":330},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2337f5021c3f4a909efd466675e543d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":250,
                  "y":266},
                "size":{
                  "width":498,
                  "height":330},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/мой_профиль/u5.png"}},
{
          "id":"43965705e7bc442c80c93476d412ab0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":308,
              "y":306},
            "size":{
              "width":83,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83b3788a74e34ec2a89d0db5a2064d7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":308,
                  "y":306},
                "size":{
                  "width":83,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5d8f775488e46a78eb430d855517518",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Обычный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":478,
              "y":306},
            "size":{
              "width":215,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1b766aaac0242c29861410473dbc00f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Обычный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":478,
                  "y":306},
                "size":{
                  "width":215,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"107bca695b0146ea80b2eb626b2d97d7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":521},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"62feae0349cb48f191cada0668659b9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "underline":true,
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1,
              "y":656},
            "size":{
              "width":1000,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a7f1cab9a354ff5b319331b18f32431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "underline":true,
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1,
                  "y":656},
                "size":{
                  "width":1000,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u105.png"}},
{
          "id":"bd6defcabe894c029796aaf27b3b1168",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":727},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef62b0b4161c492b9cecce2fae978070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":727},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u107.png"}},
{
          "id":"815dc632a7004813a73c4c95cf5eb958",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":727},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d7709c261c419dab27c90373d15cc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":97,
                  "y":727},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u109.png"}},
{
          "id":"a0bb05cc340045ce8d844875dec2346c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":727},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e80e94c7bd34258b9bdf23f96e65c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":727},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u111.png"}},
{
          "id":"900b7d126e6d43bcac74af0131b38044",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":54,
              "y":687},
            "size":{
              "width":242,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c18d6918e174e9385712abd16bcca09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":54,
                  "y":687},
                "size":{
                  "width":242,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2cab180c9e45b69e42009fb68ea3d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":730},
            "size":{
              "width":311,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ab6dc9cc0f94016a99071849c45710a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":730},
                "size":{
                  "width":311,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f82e820b45574ae4bdbc47559b9eec7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":386,
              "y":687},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52b823462edb48dc9bb75f8fe937f41a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":386,
                  "y":687},
                "size":{
                  "width":93,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61a58ca646724bfdb3e07d36419b5e8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":160,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01cd239227524df7a002eb3de17d1800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":160,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"e2ed5b30303f4483885b752c8d6eb520",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"5b1dbd0f4b494670be33dcebf5894e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43a3728f019a4171bc11a0fc24552d4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bebdacfb20d54867b7810a5c4e260320",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28270b9b59a74835ba8d5ab4b38922b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"7c408071187b48c2b475a55aca8c93e2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"27fefc9f1fba482d818140d1a971e724",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"8208199639644cf382ccf94bde6ad2d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":3},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c6dba2d5dec47bdacc0da2c4575e3c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":3},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c00844ab4cf44c7d8bced0d6993c69b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":782,
              "y":-2},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055b6e46f14842b49f65c07420df9969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":782,
                  "y":-2},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e47afe3e35cf4ab39680f2b397e26c5e",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":66},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fee0c0557b6495a8c518903d439f5a7",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44aa273624284b70990d92bbdd35eb93",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82273638d92545968fbe6b37b9bb70d1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"05963a4d179b423c92a889a44e9d27da",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3814fcd0262d4e4d8b8d8f914e32f36f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"232d28c807db43a0a1c6d6ac5677175c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a9e4cb80cf243a1b664b793c4d840fb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u131.png"}},
{
                  "id":"ccc6beccdf7943a5ba615544b88ec6e2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59301ecef3f341b98d8a7ed729d26126",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"c1979cbe496b45f6bdf32826e6bce94b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2941ceaf01f4106b016343f442e03f0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"67ff6f57663a40d99584f8075367d7d8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"927c0220ff9a404ab0acc611cd8001b1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}}]},
{
              "id":"7fbe9b5e79ed4d2e92aa0c933b230fa4",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59d2e15ec7a941f7a04d25517fcff16c",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad05e09f761b4210a01f7513d34a4782",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2728b97715424d6b8b1d0f10b696d808",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"06b4e760f8c8423bb0a8b2f3523bf8c5",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"810f1feff7674d48917fe795733947cd",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"c9c5b40262bf465184b10a8fc0f7d789",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2f56de99924045a1aeccf6d9e4429b7e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"ad7b436542f04190ae3151f9d824f68c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b307ecbbe8da4f7e989486f805b45e24",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u153.png"}},
{
                      "id":"4bb771f5feda4096b155de6bea5a9f7e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d1eafbb0f4734689b4766873c72b005c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"9408873a30774487a9e712cb4c8d8bd1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8405b02ae2e04f52a7eb1139f9b1e057",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"204edc2165ed4aab9da69287ce52fff3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"17480ae9ad3041a6b13404be80469661",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"19cdef5fa25041f0863bc3771228a66d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"407845e51e0246d5b6cacc6f4c0e187a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"f837233d22344965ba49753d9760d9a7",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e1e873bdd4f04a7db6fa097bde27569c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"c71e66786a094be4931214ebbb6a659a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"58474ce05da9411686562a0d79f66cff",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}}]}],
              "parentCellId":"05963a4d179b423c92a889a44e9d27da"}]}]}},
  "masters":{
},
  "objectPaths":{
    "586e7ead74684629b536ec7c6d0ad757":{
      "scriptId":"u0"},
    "8f5776fc8e29469db3ce7fd13a2ae5cc":{
      "scriptId":"u1"},
    "da57547b630b4adda5dbf005ab10f533":{
      "scriptId":"u2"},
    "fb9a09887601418cbeed7cf3c089ff33":{
      "scriptId":"u3"},
    "b7342b50e38440b0ba7cc562c8258b7e":{
      "scriptId":"u4"},
    "4e11f917623246f497709f985061b33b":{
      "scriptId":"u5"},
    "2337f5021c3f4a909efd466675e543d9":{
      "scriptId":"u6"},
    "43965705e7bc442c80c93476d412ab0c":{
      "scriptId":"u7"},
    "83b3788a74e34ec2a89d0db5a2064d7a":{
      "scriptId":"u8"},
    "a5d8f775488e46a78eb430d855517518":{
      "scriptId":"u9"},
    "f1b766aaac0242c29861410473dbc00f":{
      "scriptId":"u10"},
    "107bca695b0146ea80b2eb626b2d97d7":{
      "scriptId":"u11"},
    "62feae0349cb48f191cada0668659b9d":{
      "scriptId":"u12"},
    "2a7f1cab9a354ff5b319331b18f32431":{
      "scriptId":"u13"},
    "bd6defcabe894c029796aaf27b3b1168":{
      "scriptId":"u14"},
    "ef62b0b4161c492b9cecce2fae978070":{
      "scriptId":"u15"},
    "815dc632a7004813a73c4c95cf5eb958":{
      "scriptId":"u16"},
    "42d7709c261c419dab27c90373d15cc0":{
      "scriptId":"u17"},
    "a0bb05cc340045ce8d844875dec2346c":{
      "scriptId":"u18"},
    "3e80e94c7bd34258b9bdf23f96e65c63":{
      "scriptId":"u19"},
    "900b7d126e6d43bcac74af0131b38044":{
      "scriptId":"u20"},
    "8c18d6918e174e9385712abd16bcca09":{
      "scriptId":"u21"},
    "1e2cab180c9e45b69e42009fb68ea3d2":{
      "scriptId":"u22"},
    "1ab6dc9cc0f94016a99071849c45710a":{
      "scriptId":"u23"},
    "f82e820b45574ae4bdbc47559b9eec7a":{
      "scriptId":"u24"},
    "52b823462edb48dc9bb75f8fe937f41a":{
      "scriptId":"u25"},
    "61a58ca646724bfdb3e07d36419b5e8d":{
      "scriptId":"u26"},
    "01cd239227524df7a002eb3de17d1800":{
      "scriptId":"u27"},
    "e2ed5b30303f4483885b752c8d6eb520":{
      "scriptId":"u28"},
    "5b1dbd0f4b494670be33dcebf5894e84":{
      "scriptId":"u29"},
    "43a3728f019a4171bc11a0fc24552d4b":{
      "scriptId":"u30"},
    "bebdacfb20d54867b7810a5c4e260320":{
      "scriptId":"u31"},
    "28270b9b59a74835ba8d5ab4b38922b2":{
      "scriptId":"u32"},
    "7c408071187b48c2b475a55aca8c93e2":{
      "scriptId":"u33"},
    "27fefc9f1fba482d818140d1a971e724":{
      "scriptId":"u34"},
    "8208199639644cf382ccf94bde6ad2d9":{
      "scriptId":"u35"},
    "5c6dba2d5dec47bdacc0da2c4575e3c2":{
      "scriptId":"u36"},
    "c00844ab4cf44c7d8bced0d6993c69b1":{
      "scriptId":"u37"},
    "055b6e46f14842b49f65c07420df9969":{
      "scriptId":"u38"},
    "e47afe3e35cf4ab39680f2b397e26c5e":{
      "scriptId":"u39"},
    "2fee0c0557b6495a8c518903d439f5a7":{
      "scriptId":"u40"},
    "44aa273624284b70990d92bbdd35eb93":{
      "scriptId":"u41"},
    "82273638d92545968fbe6b37b9bb70d1":{
      "scriptId":"u42"},
    "05963a4d179b423c92a889a44e9d27da":{
      "scriptId":"u43"},
    "3814fcd0262d4e4d8b8d8f914e32f36f":{
      "scriptId":"u44"},
    "67ff6f57663a40d99584f8075367d7d8":{
      "scriptId":"u45"},
    "927c0220ff9a404ab0acc611cd8001b1":{
      "scriptId":"u46"},
    "c1979cbe496b45f6bdf32826e6bce94b":{
      "scriptId":"u47"},
    "b2941ceaf01f4106b016343f442e03f0":{
      "scriptId":"u48"},
    "ccc6beccdf7943a5ba615544b88ec6e2":{
      "scriptId":"u49"},
    "59301ecef3f341b98d8a7ed729d26126":{
      "scriptId":"u50"},
    "232d28c807db43a0a1c6d6ac5677175c":{
      "scriptId":"u51"},
    "9a9e4cb80cf243a1b664b793c4d840fb":{
      "scriptId":"u52"},
    "7fbe9b5e79ed4d2e92aa0c933b230fa4":{
      "scriptId":"u53"},
    "59d2e15ec7a941f7a04d25517fcff16c":{
      "scriptId":"u54"},
    "ad05e09f761b4210a01f7513d34a4782":{
      "scriptId":"u55"},
    "2728b97715424d6b8b1d0f10b696d808":{
      "scriptId":"u56"},
    "06b4e760f8c8423bb0a8b2f3523bf8c5":{
      "scriptId":"u57"},
    "810f1feff7674d48917fe795733947cd":{
      "scriptId":"u58"},
    "c9c5b40262bf465184b10a8fc0f7d789":{
      "scriptId":"u59"},
    "2f56de99924045a1aeccf6d9e4429b7e":{
      "scriptId":"u60"},
    "204edc2165ed4aab9da69287ce52fff3":{
      "scriptId":"u61"},
    "17480ae9ad3041a6b13404be80469661":{
      "scriptId":"u62"},
    "9408873a30774487a9e712cb4c8d8bd1":{
      "scriptId":"u63"},
    "8405b02ae2e04f52a7eb1139f9b1e057":{
      "scriptId":"u64"},
    "4bb771f5feda4096b155de6bea5a9f7e":{
      "scriptId":"u65"},
    "d1eafbb0f4734689b4766873c72b005c":{
      "scriptId":"u66"},
    "c71e66786a094be4931214ebbb6a659a":{
      "scriptId":"u67"},
    "58474ce05da9411686562a0d79f66cff":{
      "scriptId":"u68"},
    "f837233d22344965ba49753d9760d9a7":{
      "scriptId":"u69"},
    "e1e873bdd4f04a7db6fa097bde27569c":{
      "scriptId":"u70"},
    "19cdef5fa25041f0863bc3771228a66d":{
      "scriptId":"u71"},
    "407845e51e0246d5b6cacc6f4c0e187a":{
      "scriptId":"u72"},
    "ad7b436542f04190ae3151f9d824f68c":{
      "scriptId":"u73"},
    "b307ecbbe8da4f7e989486f805b45e24":{
      "scriptId":"u74"}}});