$axure.loadCurrentPage({
  "url":"каталог.html",
  "generationDate":new Date(1494499900499.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"c39ce0dc558d4823a4526a7310cadc34",
    "type":"Axure:Page",
    "name":"Каталог",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a4c0f94c0bd454098739c97d9578e42",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":452,
              "y":255},
            "size":{
              "width":96,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a851bfb950e04373afa5a5603249ed1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":452,
                  "y":255},
                "size":{
                  "width":96,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"186f7d1dd58a47adaa009968d0de8645",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":227,
              "y":335},
            "size":{
              "width":234,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a53dc52221314145adfb3fabfe9f47e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":227,
                  "y":335},
                "size":{
                  "width":234,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u2.png"}},
{
          "id":"efa3e924656142df860cc4c63e8458d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":343},
            "size":{
              "width":215,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abee295063be4f8d881c81b0cb1e791e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":343},
                "size":{
                  "width":215,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u4.png"}},
{
          "id":"a22ba64bc6d14f14a758734dd64d3835",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":212},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5c66e39855443ca94b9eb7e132e88a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":212},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06064336e99143b08657ec330331e8f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":213},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34b13a1479ed49f5b249ccd94b647c44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":213},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"121fc9ae126045b787c00825de5bc940",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":215},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"59521551302249a7a230ced9bbc00a85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":323,
              "y":478},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f82e116303b41288014c4764e274a12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":323,
                  "y":478},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0838b660c4224bf0a8a117b8b06cc169",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":497},
            "size":{
              "width":215,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"816ca036404742428292c4564c7731eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":497},
                "size":{
                  "width":215,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b25a84df1d647b9a06e168b6ee9b3df",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":582},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u15_image_sketch.png",
            "disabled~":"images/каталог/u15_disabled.png"}},
{
          "id":"08823e1287da4918acd21ffc101a8d49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":397,
              "y":561},
            "size":{
              "width":67,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd101fe8f20c47749444573960df45ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":397,
                  "y":561},
                "size":{
                  "width":67,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67a9d768728743119e493e03957378f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":490,
              "y":335},
            "size":{
              "width":234,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2a2b65a62a04f93b9f58081e93dcd71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":490,
                  "y":335},
                "size":{
                  "width":234,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u2.png"}},
{
          "id":"f28f8498e3fd4a74baf09475cdc882ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":343},
            "size":{
              "width":215,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc328dcda6546d5a782fda47a341daa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":343},
                "size":{
                  "width":215,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u4.png"}},
{
          "id":"db66205343d241dd914e00977b8deed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":588,
              "y":478},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9f2cc43d16545acaf63c90e1955e27b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":588,
                  "y":478},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28b0d19fe44d426aa2c0b9b7abd317a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":497},
            "size":{
              "width":215,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e534ff78b9024291a0c3d04c0bc59580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":497},
                "size":{
                  "width":215,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8eb0b471e0fe4cde99ba8354b9892ee9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":582},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u15_image_sketch.png",
            "disabled~":"images/каталог/u15_disabled.png"}},
{
          "id":"f2c7bc4c366c4369aadd86b637128a0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":660,
              "y":561},
            "size":{
              "width":67,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dc9044009054ca3b5749abf58c723f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":660,
                  "y":561},
                "size":{
                  "width":67,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"154f5b85d1f247b799295fa998e4bbd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":754,
              "y":335},
            "size":{
              "width":234,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ce90bc33ed6460bbd02fd192dead40c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":754,
                  "y":335},
                "size":{
                  "width":234,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u2.png"}},
{
          "id":"cf7d513088e04fdda5b9d92b59e2a822",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":343},
            "size":{
              "width":215,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"267405ea873a4891b1f3e4c4ef9b1633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":343},
                "size":{
                  "width":215,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u4.png"}},
{
          "id":"e4c7f455ccfd4c84ad0523b03539a2ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":851,
              "y":478},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3315d0c00b145a48ca8f95f4ea5bf44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":851,
                  "y":478},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a36ce5d5d4c4f719b59aaf543d27fe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":497},
            "size":{
              "width":215,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3933d434f4ef420f9c32101429e788a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":497},
                "size":{
                  "width":215,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c9acbe1eeba439f8a78f0a8b18579b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":902,
              "y":582},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u15_image_sketch.png",
            "disabled~":"images/каталог/u15_disabled.png"}},
{
          "id":"b47cfab235eb4ca5aeeaf2b59ed507cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":925,
              "y":561},
            "size":{
              "width":67,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b3768387fd4298b3cf63edc29c3eb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":925,
                  "y":561},
                "size":{
                  "width":67,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e993ef0b2aa1454fb0ecfa6a5bd5d162",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-2,
              "y":2438},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c024dfac2a0b45169e794a0c92da1df2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-2,
                  "y":2438},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"b914ca22198d4f318a27c3fc2f6776f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":2215},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c94896250cc49e9a99a896f88c187bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":2215},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e82f6b14708248e2ad66bcab1ff9b512",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":2199},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u80_line.png"}},
{
          "id":"4b51f0302b8642a9ad4d0e6c82cd5b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":8,
              "y":337},
            "size":{
              "width":162,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d32866fd2c545c0ab9a644017be20fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":8,
                  "y":337},
                "size":{
                  "width":162,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u45.png"}},
{
          "id":"21d3621e0a5d44eeb5edf068a7636ff4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":49,
              "y":347},
            "size":{
              "width":75,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40714658578e45f6937041f12bcf8902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":49,
                  "y":347},
                "size":{
                  "width":75,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2ab9e75281e49e89a6cefd511aafab4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":13,
              "y":385},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"357b967366594d64a2a08a684638c4ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":13,
                  "y":385},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"72c97a7d534d4feaab1052131aff41f7",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":13,
              "y":411},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0bc6f86f12e492e8a6e79f54087a5e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":13,
                  "y":411},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"548a9031a5e547c8803c37c90243e58b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":13,
              "y":437},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d299c8ba4b484620b454b62cba7f036b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":13,
                  "y":437},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"373c2ca78e7941949a57c6e880a36f08",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":13,
              "y":463},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38ea879ffd4841279905ce83d43faa3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":13,
                  "y":463},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ed8cf77b68a04b69af705b1876e84d46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":8,
              "y":507},
            "size":{
              "width":162,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81bb62fc69844d52b983c20e2eb56c6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":8,
                  "y":507},
                "size":{
                  "width":162,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u57.png"}},
{
          "id":"6db0507d775441b4819f53f9fc060573",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":54,
              "y":517},
            "size":{
              "width":75,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"244d8702b1734c9c85a58b886a03f3a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":54,
                  "y":517},
                "size":{
                  "width":75,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"464142965df1474abce1760cbbaa2230",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":13,
              "y":545},
            "size":{
              "width":129,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbbe2d0c4efa4d64908ed7fb703f99dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":13,
                  "y":545},
                "size":{
                  "width":129,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1e2941530788428d814936ce387495f0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":13,
              "y":571},
            "size":{
              "width":154,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e1c1d9126474e6ebdd5b54b92822a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":13,
                  "y":571},
                "size":{
                  "width":154,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4494e0437e9e46e9b4551b748cbc05b3",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":13,
              "y":597},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c9136bdddb347d7912d83fb147dedfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":13,
                  "y":597},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"21078cc0e41843a0a5690666c80b55c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":227,
              "y":644},
            "size":{
              "width":234,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea9a0b2adf047f9a558cb0f1380ae00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":227,
                  "y":644},
                "size":{
                  "width":234,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u2.png"}},
{
          "id":"10f7e0125c8941d4aacae311c22b5654",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":652},
            "size":{
              "width":215,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b36242ffeadd44fc8a6741411355f7a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":652},
                "size":{
                  "width":215,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u4.png"}},
{
          "id":"2aa8a2ec1b974fe0bafb6c4bbfc199fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":323,
              "y":787},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd95d8f620354a11936dbc3a02f277a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":323,
                  "y":787},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ee99654554142c2bd8ea872e063db6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":806},
            "size":{
              "width":215,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522215f4a13046da9f2e4c9352430e95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":806},
                "size":{
                  "width":215,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f276925f1fd3432bab2da55fa05e0b72",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":891},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u15_image_sketch.png",
            "disabled~":"images/каталог/u15_disabled.png"}},
{
          "id":"1084757e41f14b8ba0cce918ff9438b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":397,
              "y":870},
            "size":{
              "width":67,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b722f28980ca4382abaa7be9728de0a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":397,
                  "y":870},
                "size":{
                  "width":67,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6efff3fef3544811a5844044fe261ec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":490,
              "y":644},
            "size":{
              "width":234,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"591942a7249547b8b9a019d44be6941b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":490,
                  "y":644},
                "size":{
                  "width":234,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u2.png"}},
{
          "id":"03fab43dedf7475cbd02a62fd20e545c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":652},
            "size":{
              "width":215,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9761247688f4aa7ab0fd46390cf3e50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":652},
                "size":{
                  "width":215,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u4.png"}},
{
          "id":"6e06fee1e7874575b289e018786526dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":588,
              "y":787},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ca0a60d2164546b948531f38f960e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":588,
                  "y":787},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad51a13965024eaaa2e79adfa42bb796",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":806},
            "size":{
              "width":215,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d8f6297256748c988b4b7c1437d866b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":806},
                "size":{
                  "width":215,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16371a5ac83c42b49e06b37e3ba7bdbf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":891},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u15_image_sketch.png",
            "disabled~":"images/каталог/u15_disabled.png"}},
{
          "id":"ef7f0fe4777c4423b2bea0bbbaefc948",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":660,
              "y":870},
            "size":{
              "width":67,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f2db4c56c94e6f962bae576589e8a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":660,
                  "y":870},
                "size":{
                  "width":67,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7f0a4e0423048da814ef39547a8d784",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":754,
              "y":644},
            "size":{
              "width":234,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a2b7f076e5c48d481f53a3abaf99ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":754,
                  "y":644},
                "size":{
                  "width":234,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u2.png"}},
{
          "id":"21f10ea598fa40a8a07fab8545e08972",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":652},
            "size":{
              "width":215,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c7e89e0953d40c48d3216d81644f628",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":652},
                "size":{
                  "width":215,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/каталог/u4.png"}},
{
          "id":"fe8f437b1bf846a7b21a29217d55d244",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":851,
              "y":787},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"489af5cdb598426b88e0b376dc90a245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":851,
                  "y":787},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d375198225049d3a2f2485e354841db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":806},
            "size":{
              "width":215,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f8558fcb70441cb9e9720f7f7e71d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":806},
                "size":{
                  "width":215,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e5b31c3b00146429cc6adfe57baedaa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":902,
              "y":891},
            "size":{
              "width":78,
              "height":20}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u15_image_sketch.png",
            "disabled~":"images/каталог/u15_disabled.png"}},
{
          "id":"26f12fb2d2fc43219e33382552ee8ec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":925,
              "y":870},
            "size":{
              "width":67,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510ea94b4c8a48db91fd55333b0d4405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":925,
                  "y":870},
                "size":{
                  "width":67,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"981ecacf1c0e4d65b247171eba0da734",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":488,
              "y":999},
            "size":{
              "width":241,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dfdbd4f41a34f749ce955a21a18a645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":488,
                  "y":999},
                "size":{
                  "width":241,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2c8b43de7ce4c9898c525cfca8fbb26",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":559,
              "y":954},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u102_image_sketch.png",
            "disabled~":"images/каталог/u102_disabled.png"}},
{
          "id":"e792231043f848c69960f244570ef6cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-1,
              "y":1294},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a9858d9bb7f4e53b4784efcf79e4a4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-1,
                  "y":1294},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"09fbc809bdf84f41a4c8d003da10e66d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":1071},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ab70563ed374407845ba001ac63045b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":1071},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d663b3de8058455dbbacde6ddda1bc2c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":1055},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u80_line.png"}},
{
          "id":"a6b04a7cd03c449a8ba6ea78cbf6da40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e941272f418e4d299084d5838858f312",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"f0176a8c912643498324855bce48eaa9",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01dd595ad51049d0acc521a1c26e3f7e",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a2345d8c74b49be9f75561717d3e897",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9075fb18750a4f2f87ac038921528104",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"c5dd8487af5c42438c9ebe6185ebaea4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15bda9eb625c4aaab3ad1b21d557c363",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"cd72ddd02a3347688adbfdfba08e0406",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bad23a9c1623416d971e39b66cc20a10",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"92c81ef57aca46ca9bd5b6ade7159a1c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"118392b9a4ac4c2eb8e96dbd7e99a48e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"14f3b8c402bb46e7969dbc9d1f4f3e0f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08e819a72b7c4f96b529d3c38d74165d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"a15c5c9072004f859a428b917943062f",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41f0bbfdb21f4d6093d04cf84dbef246",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"17c0c6c498eb4d4e92b63b18fed85247",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"87ce863b270a4c2b869b769c7d9d376f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"2a4bddf332ba4364ab678a071e80f658",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a3b5792f5a504b6b81744707cd6dab4f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"3e256740b2cd4febabbce182daa15ab1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0f90e9b5ee69436ea53f4b871c90832f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"25505eb930424712a5f2faa4e3b0aadd",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"df584cff84c64675a645129ca2263630",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"2834c4bfc260458ea1137d310b43a927",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2f13c9ad52ae4619aba68807a590d68f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"c5dd8487af5c42438c9ebe6185ebaea4"}]},
{
          "id":"97198640d28840ca98442472bc98efb0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"80959e17be0a412db79b4acd94302ce7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"5bae0fc4f14645758d64d3f93f409170",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"c70d527a733d4d1bb4a8622d9ef83bfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85faf00222b74037877c86afe4a4b75d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef88635678d14bceae00f7e2c3ee08e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63546912190148b2a97d73752cbf6bdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13a8b28095404ee7b2fffdca6fd6e986",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5fdf99c221946d4a5ed81fb727734aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"2ff216b5017446c7ac3d4a840970222a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3febc8b4612041459b03a87aa75388ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"d9555ab3d53a42408f01b72a57301e58",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"69723644c5f74f368fd713680c35e9a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c76f44e3f7804b1c8f37526c52818d29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9a4c0f94c0bd454098739c97d9578e42":{
      "scriptId":"u0"},
    "a851bfb950e04373afa5a5603249ed1c":{
      "scriptId":"u1"},
    "186f7d1dd58a47adaa009968d0de8645":{
      "scriptId":"u2"},
    "a53dc52221314145adfb3fabfe9f47e3":{
      "scriptId":"u3"},
    "efa3e924656142df860cc4c63e8458d5":{
      "scriptId":"u4"},
    "abee295063be4f8d881c81b0cb1e791e":{
      "scriptId":"u5"},
    "a22ba64bc6d14f14a758734dd64d3835":{
      "scriptId":"u6"},
    "f5c66e39855443ca94b9eb7e132e88a0":{
      "scriptId":"u7"},
    "06064336e99143b08657ec330331e8f4":{
      "scriptId":"u8"},
    "34b13a1479ed49f5b249ccd94b647c44":{
      "scriptId":"u9"},
    "121fc9ae126045b787c00825de5bc940":{
      "scriptId":"u10"},
    "59521551302249a7a230ced9bbc00a85":{
      "scriptId":"u11"},
    "2f82e116303b41288014c4764e274a12":{
      "scriptId":"u12"},
    "0838b660c4224bf0a8a117b8b06cc169":{
      "scriptId":"u13"},
    "816ca036404742428292c4564c7731eb":{
      "scriptId":"u14"},
    "1b25a84df1d647b9a06e168b6ee9b3df":{
      "scriptId":"u15"},
    "08823e1287da4918acd21ffc101a8d49":{
      "scriptId":"u16"},
    "cd101fe8f20c47749444573960df45ca":{
      "scriptId":"u17"},
    "67a9d768728743119e493e03957378f1":{
      "scriptId":"u18"},
    "e2a2b65a62a04f93b9f58081e93dcd71":{
      "scriptId":"u19"},
    "f28f8498e3fd4a74baf09475cdc882ac":{
      "scriptId":"u20"},
    "4dc328dcda6546d5a782fda47a341daa":{
      "scriptId":"u21"},
    "db66205343d241dd914e00977b8deed7":{
      "scriptId":"u22"},
    "d9f2cc43d16545acaf63c90e1955e27b":{
      "scriptId":"u23"},
    "28b0d19fe44d426aa2c0b9b7abd317a7":{
      "scriptId":"u24"},
    "e534ff78b9024291a0c3d04c0bc59580":{
      "scriptId":"u25"},
    "8eb0b471e0fe4cde99ba8354b9892ee9":{
      "scriptId":"u26"},
    "f2c7bc4c366c4369aadd86b637128a0a":{
      "scriptId":"u27"},
    "6dc9044009054ca3b5749abf58c723f5":{
      "scriptId":"u28"},
    "154f5b85d1f247b799295fa998e4bbd9":{
      "scriptId":"u29"},
    "4ce90bc33ed6460bbd02fd192dead40c":{
      "scriptId":"u30"},
    "cf7d513088e04fdda5b9d92b59e2a822":{
      "scriptId":"u31"},
    "267405ea873a4891b1f3e4c4ef9b1633":{
      "scriptId":"u32"},
    "e4c7f455ccfd4c84ad0523b03539a2ba":{
      "scriptId":"u33"},
    "b3315d0c00b145a48ca8f95f4ea5bf44":{
      "scriptId":"u34"},
    "4a36ce5d5d4c4f719b59aaf543d27fe6":{
      "scriptId":"u35"},
    "3933d434f4ef420f9c32101429e788a6":{
      "scriptId":"u36"},
    "1c9acbe1eeba439f8a78f0a8b18579b1":{
      "scriptId":"u37"},
    "b47cfab235eb4ca5aeeaf2b59ed507cf":{
      "scriptId":"u38"},
    "86b3768387fd4298b3cf63edc29c3eb8":{
      "scriptId":"u39"},
    "e993ef0b2aa1454fb0ecfa6a5bd5d162":{
      "scriptId":"u40"},
    "c024dfac2a0b45169e794a0c92da1df2":{
      "scriptId":"u41"},
    "b914ca22198d4f318a27c3fc2f6776f7":{
      "scriptId":"u42"},
    "8c94896250cc49e9a99a896f88c187bf":{
      "scriptId":"u43"},
    "e82f6b14708248e2ad66bcab1ff9b512":{
      "scriptId":"u44"},
    "4b51f0302b8642a9ad4d0e6c82cd5b51":{
      "scriptId":"u45"},
    "2d32866fd2c545c0ab9a644017be20fe":{
      "scriptId":"u46"},
    "21d3621e0a5d44eeb5edf068a7636ff4":{
      "scriptId":"u47"},
    "40714658578e45f6937041f12bcf8902":{
      "scriptId":"u48"},
    "f2ab9e75281e49e89a6cefd511aafab4":{
      "scriptId":"u49"},
    "357b967366594d64a2a08a684638c4ac":{
      "scriptId":"u50"},
    "72c97a7d534d4feaab1052131aff41f7":{
      "scriptId":"u51"},
    "e0bc6f86f12e492e8a6e79f54087a5e0":{
      "scriptId":"u52"},
    "548a9031a5e547c8803c37c90243e58b":{
      "scriptId":"u53"},
    "d299c8ba4b484620b454b62cba7f036b":{
      "scriptId":"u54"},
    "373c2ca78e7941949a57c6e880a36f08":{
      "scriptId":"u55"},
    "38ea879ffd4841279905ce83d43faa3c":{
      "scriptId":"u56"},
    "ed8cf77b68a04b69af705b1876e84d46":{
      "scriptId":"u57"},
    "81bb62fc69844d52b983c20e2eb56c6e":{
      "scriptId":"u58"},
    "6db0507d775441b4819f53f9fc060573":{
      "scriptId":"u59"},
    "244d8702b1734c9c85a58b886a03f3a3":{
      "scriptId":"u60"},
    "464142965df1474abce1760cbbaa2230":{
      "scriptId":"u61"},
    "dbbe2d0c4efa4d64908ed7fb703f99dd":{
      "scriptId":"u62"},
    "1e2941530788428d814936ce387495f0":{
      "scriptId":"u63"},
    "9e1c1d9126474e6ebdd5b54b92822a45":{
      "scriptId":"u64"},
    "4494e0437e9e46e9b4551b748cbc05b3":{
      "scriptId":"u65"},
    "7c9136bdddb347d7912d83fb147dedfb":{
      "scriptId":"u66"},
    "21078cc0e41843a0a5690666c80b55c7":{
      "scriptId":"u67"},
    "cea9a0b2adf047f9a558cb0f1380ae00":{
      "scriptId":"u68"},
    "10f7e0125c8941d4aacae311c22b5654":{
      "scriptId":"u69"},
    "b36242ffeadd44fc8a6741411355f7a9":{
      "scriptId":"u70"},
    "2aa8a2ec1b974fe0bafb6c4bbfc199fb":{
      "scriptId":"u71"},
    "cd95d8f620354a11936dbc3a02f277a2":{
      "scriptId":"u72"},
    "3ee99654554142c2bd8ea872e063db6a":{
      "scriptId":"u73"},
    "522215f4a13046da9f2e4c9352430e95":{
      "scriptId":"u74"},
    "f276925f1fd3432bab2da55fa05e0b72":{
      "scriptId":"u75"},
    "1084757e41f14b8ba0cce918ff9438b1":{
      "scriptId":"u76"},
    "b722f28980ca4382abaa7be9728de0a6":{
      "scriptId":"u77"},
    "6efff3fef3544811a5844044fe261ec3":{
      "scriptId":"u78"},
    "591942a7249547b8b9a019d44be6941b":{
      "scriptId":"u79"},
    "03fab43dedf7475cbd02a62fd20e545c":{
      "scriptId":"u80"},
    "e9761247688f4aa7ab0fd46390cf3e50":{
      "scriptId":"u81"},
    "6e06fee1e7874575b289e018786526dc":{
      "scriptId":"u82"},
    "24ca0a60d2164546b948531f38f960e3":{
      "scriptId":"u83"},
    "ad51a13965024eaaa2e79adfa42bb796":{
      "scriptId":"u84"},
    "8d8f6297256748c988b4b7c1437d866b":{
      "scriptId":"u85"},
    "16371a5ac83c42b49e06b37e3ba7bdbf":{
      "scriptId":"u86"},
    "ef7f0fe4777c4423b2bea0bbbaefc948":{
      "scriptId":"u87"},
    "96f2db4c56c94e6f962bae576589e8a2":{
      "scriptId":"u88"},
    "e7f0a4e0423048da814ef39547a8d784":{
      "scriptId":"u89"},
    "1a2b7f076e5c48d481f53a3abaf99ae5":{
      "scriptId":"u90"},
    "21f10ea598fa40a8a07fab8545e08972":{
      "scriptId":"u91"},
    "1c7e89e0953d40c48d3216d81644f628":{
      "scriptId":"u92"},
    "fe8f437b1bf846a7b21a29217d55d244":{
      "scriptId":"u93"},
    "489af5cdb598426b88e0b376dc90a245":{
      "scriptId":"u94"},
    "7d375198225049d3a2f2485e354841db":{
      "scriptId":"u95"},
    "f9f8558fcb70441cb9e9720f7f7e71d1":{
      "scriptId":"u96"},
    "7e5b31c3b00146429cc6adfe57baedaa":{
      "scriptId":"u97"},
    "26f12fb2d2fc43219e33382552ee8ec8":{
      "scriptId":"u98"},
    "510ea94b4c8a48db91fd55333b0d4405":{
      "scriptId":"u99"},
    "981ecacf1c0e4d65b247171eba0da734":{
      "scriptId":"u100"},
    "2dfdbd4f41a34f749ce955a21a18a645":{
      "scriptId":"u101"},
    "c2c8b43de7ce4c9898c525cfca8fbb26":{
      "scriptId":"u102"},
    "e792231043f848c69960f244570ef6cb":{
      "scriptId":"u103"},
    "8a9858d9bb7f4e53b4784efcf79e4a4c":{
      "scriptId":"u104"},
    "09fbc809bdf84f41a4c8d003da10e66d":{
      "scriptId":"u105"},
    "5ab70563ed374407845ba001ac63045b":{
      "scriptId":"u106"},
    "d663b3de8058455dbbacde6ddda1bc2c":{
      "scriptId":"u107"},
    "a6b04a7cd03c449a8ba6ea78cbf6da40":{
      "scriptId":"u108"},
    "e941272f418e4d299084d5838858f312":{
      "scriptId":"u109"},
    "f0176a8c912643498324855bce48eaa9":{
      "scriptId":"u110"},
    "01dd595ad51049d0acc521a1c26e3f7e":{
      "scriptId":"u111"},
    "6a2345d8c74b49be9f75561717d3e897":{
      "scriptId":"u112"},
    "9075fb18750a4f2f87ac038921528104":{
      "scriptId":"u113"},
    "c5dd8487af5c42438c9ebe6185ebaea4":{
      "scriptId":"u114"},
    "15bda9eb625c4aaab3ad1b21d557c363":{
      "scriptId":"u115"},
    "92c81ef57aca46ca9bd5b6ade7159a1c":{
      "scriptId":"u116"},
    "118392b9a4ac4c2eb8e96dbd7e99a48e":{
      "scriptId":"u117"},
    "14f3b8c402bb46e7969dbc9d1f4f3e0f":{
      "scriptId":"u118"},
    "08e819a72b7c4f96b529d3c38d74165d":{
      "scriptId":"u119"},
    "cd72ddd02a3347688adbfdfba08e0406":{
      "scriptId":"u120"},
    "bad23a9c1623416d971e39b66cc20a10":{
      "scriptId":"u121"},
    "a15c5c9072004f859a428b917943062f":{
      "scriptId":"u122"},
    "41f0bbfdb21f4d6093d04cf84dbef246":{
      "scriptId":"u123"},
    "17c0c6c498eb4d4e92b63b18fed85247":{
      "scriptId":"u124"},
    "87ce863b270a4c2b869b769c7d9d376f":{
      "scriptId":"u125"},
    "3e256740b2cd4febabbce182daa15ab1":{
      "scriptId":"u126"},
    "0f90e9b5ee69436ea53f4b871c90832f":{
      "scriptId":"u127"},
    "25505eb930424712a5f2faa4e3b0aadd":{
      "scriptId":"u128"},
    "df584cff84c64675a645129ca2263630":{
      "scriptId":"u129"},
    "2a4bddf332ba4364ab678a071e80f658":{
      "scriptId":"u130"},
    "a3b5792f5a504b6b81744707cd6dab4f":{
      "scriptId":"u131"},
    "2834c4bfc260458ea1137d310b43a927":{
      "scriptId":"u132"},
    "2f13c9ad52ae4619aba68807a590d68f":{
      "scriptId":"u133"},
    "97198640d28840ca98442472bc98efb0":{
      "scriptId":"u134"},
    "80959e17be0a412db79b4acd94302ce7":{
      "scriptId":"u135"},
    "5bae0fc4f14645758d64d3f93f409170":{
      "scriptId":"u136"},
    "c70d527a733d4d1bb4a8622d9ef83bfe":{
      "scriptId":"u137"},
    "85faf00222b74037877c86afe4a4b75d":{
      "scriptId":"u138"},
    "ef88635678d14bceae00f7e2c3ee08e9":{
      "scriptId":"u139"},
    "63546912190148b2a97d73752cbf6bdd":{
      "scriptId":"u140"},
    "13a8b28095404ee7b2fffdca6fd6e986":{
      "scriptId":"u141"},
    "d5fdf99c221946d4a5ed81fb727734aa":{
      "scriptId":"u142"},
    "2ff216b5017446c7ac3d4a840970222a":{
      "scriptId":"u143"},
    "3febc8b4612041459b03a87aa75388ee":{
      "scriptId":"u144"},
    "d9555ab3d53a42408f01b72a57301e58":{
      "scriptId":"u145"},
    "69723644c5f74f368fd713680c35e9a0":{
      "scriptId":"u146"},
    "c76f44e3f7804b1c8f37526c52818d29":{
      "scriptId":"u147"}}});