$axure.loadCurrentPage({
  "url":"о_компании.html",
  "generationDate":new Date(1494499898653.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"4a01abd826d04617bbc01c8166b6cb8f",
    "type":"Axure:Page",
    "name":"О компании",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7b465c82038b4d0f8c478a36bd4f0977",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":340,
              "y":262},
            "size":{
              "width":72,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cb44a0b93784026abe77f75ea9c6ac9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":340,
                  "y":262},
                "size":{
                  "width":72,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9af50e4741e343cc84ffa360c7c37416",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":305},
            "size":{
              "width":300,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd3e16bd0b6540c6ae3193b7e6c43cc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":305},
                "size":{
                  "width":300,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_компании/u2.png"}},
{
          "id":"5ba6a950e9e24a8b9ceebcc8f3fb82d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":213},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fafa7a02ef434fd3a4a4e400e683db40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":213},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff0f9b039b8b41c9b969cba1ccca40c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":214},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14ff49181b0241b19f5632e8b5562a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":214},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef3e283f381b49b48a9e9e23a27bd9cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":216},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"96ac452c36824134b333deeb12004075",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":340,
              "y":305},
            "size":{
              "width":661,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd28253387344e9dab276801e762401f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":340,
                  "y":305},
                "size":{
                  "width":661,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e700b5f9f5c43c0adee1a1deb724508",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"26px",
            "location":{
              "x":391,
              "y":552},
            "size":{
              "width":213,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"666df55e8d4b428fb69fb1fea50ee5f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"26px",
                "location":{
                  "x":391,
                  "y":552},
                "size":{
                  "width":213,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31418f5d324a477484cc928bced26d54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":24,
              "y":598},
            "size":{
              "width":978,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f227262cdd2e4b6b95f7c5b4f6c7dbe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":24,
                  "y":598},
                "size":{
                  "width":978,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e779ad17705d463bb39448b355abea21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-3,
              "y":1135},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d68434d57e7e47968570b79940ad7624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-3,
                  "y":1135},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"154ec636c6e84efe84811d4640f97174",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":912},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81895535b26c47918778631f222d78c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":912},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"000455e5da604accafed2021214cd6a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":896},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u80_line.png"}},
{
          "id":"6fbd71b2634b4fabb1bc0de19a0d5ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9068f6e0cc3a40b698955ea469788fcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"35e2c218171047d3803e9ab83135f5c4",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a59fff15b5445cf8c24c2545b4acd47",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e10a1bc233a844eab96c8fa694859f32",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be6e59b8a2364747b26ef4ef9dc3aa31",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"5efa4dedd354466392f4950e4193e578",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"37c12bda368549d2bbb39751ea783054",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"2b5dce8cce3644c38ecfe21a62f375aa",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"762f90ff4a5a49fc87a382ee515b4434",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"0e00c0a07504467ca04ead814df9c6bf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f86dcec51b745a599686b1b5d220477",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"1222e9d3d3c3481b88d19d16790e87c2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35e21db22442443e9d270a43f7619e58",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"997c05b554d8444e8025d8b8df981151",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbe430da3a734cb08fdce8981313d24d",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06a2f2c99a2d403ab31a1da23c0a556f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ac97f66b6ef54ca3943fdc7a145b4d1c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"44f5f5dec60648008c912b5b3b9eef76",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f819553135bd4519aa10963df8f5212d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"ee3cf9cccff844c786b321360500b26a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6bb503916e2b4aa6a931937400e17f42",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"998d4daff7e245048a7efc99ea3f2aa0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2526c7570a194d06abcaeb2f3ce35474",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"afb88c9d9e884176b75b151608022e2f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ecbc81f8d7004087adf9433915f1e6e4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"5efa4dedd354466392f4950e4193e578"}]},
{
          "id":"aaa609d933ab41e4a9b09a0d0baee173",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"788bb1a39332479e9d22ecba4a74650a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"3442f29151d64d58a8ca78939dc14125",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"513babc2ec6749eeba54ea14c286f188",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad30ed733584521901e688dd015fc31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bde6866135ad4c26898851cec81674a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79f9cc6d89394e09a2dc3c352b1ec021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42ddbdcff0754943960cd2948b6dff00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3d8783d6e4416e97de0956031dddbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"d75065c1700e4d8cac16c33231f992eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe268c1fa09a41178b177cc8f483ba25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"d8bfea582d7c452488ce1ca9f2b50b45",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"4110cd5c477f4ec1b0cc6743eaac05a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3fe51bbf9da43d78e36e421aa25733a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7b465c82038b4d0f8c478a36bd4f0977":{
      "scriptId":"u0"},
    "0cb44a0b93784026abe77f75ea9c6ac9":{
      "scriptId":"u1"},
    "9af50e4741e343cc84ffa360c7c37416":{
      "scriptId":"u2"},
    "dd3e16bd0b6540c6ae3193b7e6c43cc1":{
      "scriptId":"u3"},
    "5ba6a950e9e24a8b9ceebcc8f3fb82d6":{
      "scriptId":"u4"},
    "fafa7a02ef434fd3a4a4e400e683db40":{
      "scriptId":"u5"},
    "ff0f9b039b8b41c9b969cba1ccca40c2":{
      "scriptId":"u6"},
    "14ff49181b0241b19f5632e8b5562a02":{
      "scriptId":"u7"},
    "ef3e283f381b49b48a9e9e23a27bd9cf":{
      "scriptId":"u8"},
    "96ac452c36824134b333deeb12004075":{
      "scriptId":"u9"},
    "bd28253387344e9dab276801e762401f":{
      "scriptId":"u10"},
    "8e700b5f9f5c43c0adee1a1deb724508":{
      "scriptId":"u11"},
    "666df55e8d4b428fb69fb1fea50ee5f4":{
      "scriptId":"u12"},
    "31418f5d324a477484cc928bced26d54":{
      "scriptId":"u13"},
    "f227262cdd2e4b6b95f7c5b4f6c7dbe5":{
      "scriptId":"u14"},
    "e779ad17705d463bb39448b355abea21":{
      "scriptId":"u15"},
    "d68434d57e7e47968570b79940ad7624":{
      "scriptId":"u16"},
    "154ec636c6e84efe84811d4640f97174":{
      "scriptId":"u17"},
    "81895535b26c47918778631f222d78c1":{
      "scriptId":"u18"},
    "000455e5da604accafed2021214cd6a8":{
      "scriptId":"u19"},
    "6fbd71b2634b4fabb1bc0de19a0d5ace":{
      "scriptId":"u20"},
    "9068f6e0cc3a40b698955ea469788fcf":{
      "scriptId":"u21"},
    "35e2c218171047d3803e9ab83135f5c4":{
      "scriptId":"u22"},
    "5a59fff15b5445cf8c24c2545b4acd47":{
      "scriptId":"u23"},
    "e10a1bc233a844eab96c8fa694859f32":{
      "scriptId":"u24"},
    "be6e59b8a2364747b26ef4ef9dc3aa31":{
      "scriptId":"u25"},
    "5efa4dedd354466392f4950e4193e578":{
      "scriptId":"u26"},
    "37c12bda368549d2bbb39751ea783054":{
      "scriptId":"u27"},
    "0e00c0a07504467ca04ead814df9c6bf":{
      "scriptId":"u28"},
    "9f86dcec51b745a599686b1b5d220477":{
      "scriptId":"u29"},
    "1222e9d3d3c3481b88d19d16790e87c2":{
      "scriptId":"u30"},
    "35e21db22442443e9d270a43f7619e58":{
      "scriptId":"u31"},
    "2b5dce8cce3644c38ecfe21a62f375aa":{
      "scriptId":"u32"},
    "762f90ff4a5a49fc87a382ee515b4434":{
      "scriptId":"u33"},
    "997c05b554d8444e8025d8b8df981151":{
      "scriptId":"u34"},
    "cbe430da3a734cb08fdce8981313d24d":{
      "scriptId":"u35"},
    "06a2f2c99a2d403ab31a1da23c0a556f":{
      "scriptId":"u36"},
    "ac97f66b6ef54ca3943fdc7a145b4d1c":{
      "scriptId":"u37"},
    "ee3cf9cccff844c786b321360500b26a":{
      "scriptId":"u38"},
    "6bb503916e2b4aa6a931937400e17f42":{
      "scriptId":"u39"},
    "998d4daff7e245048a7efc99ea3f2aa0":{
      "scriptId":"u40"},
    "2526c7570a194d06abcaeb2f3ce35474":{
      "scriptId":"u41"},
    "44f5f5dec60648008c912b5b3b9eef76":{
      "scriptId":"u42"},
    "f819553135bd4519aa10963df8f5212d":{
      "scriptId":"u43"},
    "afb88c9d9e884176b75b151608022e2f":{
      "scriptId":"u44"},
    "ecbc81f8d7004087adf9433915f1e6e4":{
      "scriptId":"u45"},
    "aaa609d933ab41e4a9b09a0d0baee173":{
      "scriptId":"u46"},
    "788bb1a39332479e9d22ecba4a74650a":{
      "scriptId":"u47"},
    "3442f29151d64d58a8ca78939dc14125":{
      "scriptId":"u48"},
    "513babc2ec6749eeba54ea14c286f188":{
      "scriptId":"u49"},
    "3ad30ed733584521901e688dd015fc31":{
      "scriptId":"u50"},
    "bde6866135ad4c26898851cec81674a3":{
      "scriptId":"u51"},
    "79f9cc6d89394e09a2dc3c352b1ec021":{
      "scriptId":"u52"},
    "42ddbdcff0754943960cd2948b6dff00":{
      "scriptId":"u53"},
    "7a3d8783d6e4416e97de0956031dddbd":{
      "scriptId":"u54"},
    "d75065c1700e4d8cac16c33231f992eb":{
      "scriptId":"u55"},
    "fe268c1fa09a41178b177cc8f483ba25":{
      "scriptId":"u56"},
    "d8bfea582d7c452488ce1ca9f2b50b45":{
      "scriptId":"u57"},
    "4110cd5c477f4ec1b0cc6743eaac05a2":{
      "scriptId":"u58"},
    "e3fe51bbf9da43d78e36e421aa25733a":{
      "scriptId":"u59"}}});