$axure.loadCurrentPage({
  "url":"статья.html",
  "generationDate":new Date(1493889317591.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1187342d227d4011b588a9203aa27aff",
    "type":"Axure:Page",
    "name":"Статья",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c6e0aaea528433d93ca781d8aa440c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":142},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e40cc6460ccb4dcb9868c9083ba663ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":142},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02e6a0c8ba7045c1a80c571b2e43728d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":143},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffacb999d87b4a44987df3a114e435a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":143},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7737dcec3ec4d1396f2220a83e7d117",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":145},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"0c9b103c9ef34fca98b70b58192dc2fe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":146},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"7b76a8f0a652401a9864b548b1af6bea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":156,
              "y":144},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99861576b7ca490488dc6476e7f4d2da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":156,
                  "y":144},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de29684ef76d4801ab1c0bb7a1b709fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":24,
              "y":189},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc7c9e7900524e7bbfbb2970325ff22d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":24,
                  "y":189},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb794ebfb16447d690a2444d3cbd35c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":26,
              "y":218},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a665fe57d16545e28a49b29a85c5a5f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":26,
                  "y":218},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07b7b881836c4b79bc58e965ae41263b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":257},
            "size":{
              "width":386,
              "height":262}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3dfa5ce7b314b13b75f9a6e0d782725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":257},
                "size":{
                  "width":386,
                  "height":262}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u12.png"}},
{
          "id":"27ba492ad05243a7accfaf81a9d0cd47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":277,
              "y":239},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3867821059483985280079dd3f26e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":277,
                  "y":239},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23c11ce6381d49bdbfccae3de316fddd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":239},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b541389de3e640899ccea5006f36b3b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":239},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u16.png"}},
{
          "id":"7879424d7e254ce4a1a884affe930f84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":239},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d4e85757bf04430a180e8fd66ba02c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":239},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u18.png"}},
{
          "id":"0cc0d2534e0942e2bd5bbd1a87bdb2ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":441,
              "y":257},
            "size":{
              "width":560,
              "height":472}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf0b9e367b64a89960c73febea226f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":441,
                  "y":257},
                "size":{
                  "width":560,
                  "height":472}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f45585155a7042ab9bc548f3a4da5202",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1,
              "y":756},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57743a6ddc904b59803dc37e2bd18115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1,
                  "y":756},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u33.png"}},
{
          "id":"eea76898208546a987a2f73c7566bbd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731c559430714ab2ab8005f066533cf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":0},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"ab4a9ff99d714b448b75142d2e7c7292",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"196f1e145ad549f0a61bb7a8e15216b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e48321722dd4a0782d8217fc64fe176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"061609e8ad914da58666354105cb459d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b4639fbf9d4ea080465ac3eb466475",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"c118b9d95b7b452da1730b42ee53a159",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2ac049f944ed4ca7bdb589f9d769663d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle Konsult",
                      "objectsToFades":[{
                          "objectPath":["16913a30c08f44fe8c9cc7d65e67ea33"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"4c22f5fc8ca941a3a509b39fcb3fe8f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":252,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60c9f711e1674c5e933c56c6b05c0ddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":252,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd100c282ecc4703b4576e6eba002470",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d464c5f850246b6b20555a92b1abf3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1e0da0802334a48b56fac0801568761",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":641,
              "y":34},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef5279d27c364b8e834e33c8dff5c3d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":641,
                  "y":34},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18283f4eadca4263b744550375f1d5e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":4},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47ef9c829098424d9ff9cbfd13580e97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":4},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbeadacfd369412ebb8ff5015b2f4893",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7acd3fc2c9f6425ea059a1789fd57d24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":916,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u17.png"}},
{
          "id":"96c1237976704596b46fa1665ca3af0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e2dffe70a746e89b055a5686aec0be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u19.png"}},
{
          "id":"123966b9a847446a9f96a4ce89b76eb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f46ceb42785472e9408b8b2f987cdb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u21.png"}},
{
          "id":"ef2ef3bcdd964f0d84f2cfde01f635a2",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":66},
            "size":{
              "width":500,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34e0bb02ee8c4863a97e6b0e1eec151d",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7563fdea8914a74a4d6ffb07626d7e2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0375db797c484018bbf4365646a0ca75",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"d9386abe9171428b89a11ab3a711f96e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb55088476174517a815f1cea6205653",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"3403dfb4fe514a73a75b7733b4ea7abf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4929ef5c2ade46d7914e1b64f8b71b49",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u104.png"}},
{
                  "id":"1faef50e86f646dfb958f446350dd7c8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab516695565f45e1a3886986842c118f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"6d589bfdd69148a5973a10eaa6dc2c11",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cda0b8b8ac77403cbf562e756fb33d45",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}}]},
{
              "id":"afdfdf6b54ad4a6abdf734be19990008",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cf9100528a0d455a8fcb81c072929639",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6032207b486f434ea40139d51e649787",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2504ea7ddac446a8a309e149f706e85f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"a73365bbbcd640aaab82913065eac328",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6cc831bdfe444e4899efd54948876e2c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"f1904571aae24931aee0c2efd3624290",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1b8562c2631846e1b7943f53b0400cc1",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"b454e5c3f9474c5baf77b6141135778c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c5af07935cd54d1c8d45b0d6b3fb58bd",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u126.png"}},
{
                      "id":"1e470dfbb5564cd2945745985087c5dd",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c8f640e7e8bc409fa55e33e16bdb26ce",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"8a47c54013af444d993b621629bb5499",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"66e057450a9c49b2afc2aab4bc481b60",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"483f5bf1f28b45e39fff112584a889ec",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"70cce4cd515749a4ba745399484937b6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"c38e73de700d415f863cac239b190dd8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"74b40d87d0ee42bd880a684bcac01f77",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"0f7c3df5b1e54b2eb1af1e3051aa34ec",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d4f2c0dd0cd94cd68941f6fdb503d286",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"e1e6411cc67842dc80381e0ae6abd929",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5990a63ebc5f4b23aecfb746f3b53bed",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}}]}],
              "parentCellId":"d9386abe9171428b89a11ab3a711f96e"}]},
{
          "id":"16913a30c08f44fe8c9cc7d65e67ea33",
          "label":"Konsult",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":235,
              "y":122},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5398d15d5703475495268c9188b47bea",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c9ad2accd4c54bb8be401aeaa4a8b9f1",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":358}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0278304842784886a34dafa25520c8eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":100,
                          "y":50},
                        "size":{
                          "width":300,
                          "height":358}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u129.png"}},
{
                  "id":"094fa4684e41420a845efbca2193c4f9",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":88},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"d271390254fb49829239d7ba06e8ad97",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":72},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5aa532f23c3345919a3fd041536e5577",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":72},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f2b8300fcf9148909b1d45b72d2b30fa",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":138},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"e748d9d868b641b5828ef592da8a5399",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":122},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d13c231be94246f9ab6697a5516af692",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":122},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"961f3a7b71624c53aaf13a99cb87ccb7",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":188},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"4672eeae803b4404a26703ff2c6c1639",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":172},
                    "size":{
                      "width":49,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"759915f50baf4d5dbbf18f1f0556c7b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":172},
                        "size":{
                          "width":49,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"78908cfd5767490ea59105be2ded5d89",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":238},
                    "size":{
                      "width":260,
                      "height":91}},
                  "adaptiveStyles":{
}},
{
                  "id":"65575f7b0bf74cfb804ba29e736a3ecb",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":222},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d4ed0e367164c13a0f7e59ec46ddfd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":222},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"328b1cc77d474a83a0155fe775381208",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":348},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show banner",
                              "objectsToFades":[{
                                  "objectPath":["7e453c603fd04788a978d04659c5c2f8"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"47b28eecfda8487d80d08a7127c4dcb1",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":288,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f1734d896e54a20adaca21123829105",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":106,
                          "y":0},
                        "size":{
                          "width":288,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e453c603fd04788a978d04659c5c2f8",
                  "label":"banner",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"9c9ad7d35d4c4a89b4d313d8a0c9c63e",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"9e3745326eec41768dabec90c9ab022e",
                          "label":"",
                          "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "size":{
                              "width":530,
                              "height":130}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"016cabbd6855450cb74b4ab93be7f628",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "size":{
                                  "width":530,
                                  "height":130}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/главная/u147.png"}},
{
                          "id":"20ab64f7600c4791add157862b87d259",
                          "label":"",
                          "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":500,
                              "y":10},
                            "size":{
                              "width":20,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ad6511adf2584a5585eb3679f47423cf",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":500,
                                  "y":10},
                                "size":{
                                  "width":20,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Hide banner",
                                      "objectsToFades":[{
                                          "objectPath":["7e453c603fd04788a978d04659c5c2f8"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/главная/u149.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"770e9dab8a194ac383fe8c7e4ad7e1a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":642,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20867db3e3db4fd2a2c8cf27dd4e8f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":642,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4c6e0aaea528433d93ca781d8aa440c6":{
      "scriptId":"u0"},
    "e40cc6460ccb4dcb9868c9083ba663ac":{
      "scriptId":"u1"},
    "02e6a0c8ba7045c1a80c571b2e43728d":{
      "scriptId":"u2"},
    "ffacb999d87b4a44987df3a114e435a9":{
      "scriptId":"u3"},
    "a7737dcec3ec4d1396f2220a83e7d117":{
      "scriptId":"u4"},
    "0c9b103c9ef34fca98b70b58192dc2fe":{
      "scriptId":"u5"},
    "7b76a8f0a652401a9864b548b1af6bea":{
      "scriptId":"u6"},
    "99861576b7ca490488dc6476e7f4d2da":{
      "scriptId":"u7"},
    "de29684ef76d4801ab1c0bb7a1b709fb":{
      "scriptId":"u8"},
    "dc7c9e7900524e7bbfbb2970325ff22d":{
      "scriptId":"u9"},
    "bb794ebfb16447d690a2444d3cbd35c2":{
      "scriptId":"u10"},
    "a665fe57d16545e28a49b29a85c5a5f7":{
      "scriptId":"u11"},
    "07b7b881836c4b79bc58e965ae41263b":{
      "scriptId":"u12"},
    "e3dfa5ce7b314b13b75f9a6e0d782725":{
      "scriptId":"u13"},
    "27ba492ad05243a7accfaf81a9d0cd47":{
      "scriptId":"u14"},
    "ed3867821059483985280079dd3f26e5":{
      "scriptId":"u15"},
    "23c11ce6381d49bdbfccae3de316fddd":{
      "scriptId":"u16"},
    "b541389de3e640899ccea5006f36b3b7":{
      "scriptId":"u17"},
    "7879424d7e254ce4a1a884affe930f84":{
      "scriptId":"u18"},
    "9d4e85757bf04430a180e8fd66ba02c3":{
      "scriptId":"u19"},
    "0cc0d2534e0942e2bd5bbd1a87bdb2ae":{
      "scriptId":"u20"},
    "adf0b9e367b64a89960c73febea226f1":{
      "scriptId":"u21"},
    "f45585155a7042ab9bc548f3a4da5202":{
      "scriptId":"u22"},
    "57743a6ddc904b59803dc37e2bd18115":{
      "scriptId":"u23"},
    "eea76898208546a987a2f73c7566bbd8":{
      "scriptId":"u24"},
    "731c559430714ab2ab8005f066533cf7":{
      "scriptId":"u25"},
    "ab4a9ff99d714b448b75142d2e7c7292":{
      "scriptId":"u26"},
    "196f1e145ad549f0a61bb7a8e15216b0":{
      "scriptId":"u27"},
    "3e48321722dd4a0782d8217fc64fe176":{
      "scriptId":"u28"},
    "061609e8ad914da58666354105cb459d":{
      "scriptId":"u29"},
    "a2b4639fbf9d4ea080465ac3eb466475":{
      "scriptId":"u30"},
    "c118b9d95b7b452da1730b42ee53a159":{
      "scriptId":"u31"},
    "2ac049f944ed4ca7bdb589f9d769663d":{
      "scriptId":"u32"},
    "4c22f5fc8ca941a3a509b39fcb3fe8f6":{
      "scriptId":"u33"},
    "60c9f711e1674c5e933c56c6b05c0ddb":{
      "scriptId":"u34"},
    "dd100c282ecc4703b4576e6eba002470":{
      "scriptId":"u35"},
    "8d464c5f850246b6b20555a92b1abf3b":{
      "scriptId":"u36"},
    "e1e0da0802334a48b56fac0801568761":{
      "scriptId":"u37"},
    "ef5279d27c364b8e834e33c8dff5c3d8":{
      "scriptId":"u38"},
    "18283f4eadca4263b744550375f1d5e9":{
      "scriptId":"u39"},
    "47ef9c829098424d9ff9cbfd13580e97":{
      "scriptId":"u40"},
    "cbeadacfd369412ebb8ff5015b2f4893":{
      "scriptId":"u41"},
    "7acd3fc2c9f6425ea059a1789fd57d24":{
      "scriptId":"u42"},
    "96c1237976704596b46fa1665ca3af0e":{
      "scriptId":"u43"},
    "d5e2dffe70a746e89b055a5686aec0be":{
      "scriptId":"u44"},
    "123966b9a847446a9f96a4ce89b76eb4":{
      "scriptId":"u45"},
    "3f46ceb42785472e9408b8b2f987cdb9":{
      "scriptId":"u46"},
    "ef2ef3bcdd964f0d84f2cfde01f635a2":{
      "scriptId":"u47"},
    "34e0bb02ee8c4863a97e6b0e1eec151d":{
      "scriptId":"u48"},
    "c7563fdea8914a74a4d6ffb07626d7e2":{
      "scriptId":"u49"},
    "0375db797c484018bbf4365646a0ca75":{
      "scriptId":"u50"},
    "d9386abe9171428b89a11ab3a711f96e":{
      "scriptId":"u51"},
    "eb55088476174517a815f1cea6205653":{
      "scriptId":"u52"},
    "6d589bfdd69148a5973a10eaa6dc2c11":{
      "scriptId":"u53"},
    "cda0b8b8ac77403cbf562e756fb33d45":{
      "scriptId":"u54"},
    "1faef50e86f646dfb958f446350dd7c8":{
      "scriptId":"u55"},
    "ab516695565f45e1a3886986842c118f":{
      "scriptId":"u56"},
    "3403dfb4fe514a73a75b7733b4ea7abf":{
      "scriptId":"u57"},
    "4929ef5c2ade46d7914e1b64f8b71b49":{
      "scriptId":"u58"},
    "afdfdf6b54ad4a6abdf734be19990008":{
      "scriptId":"u59"},
    "cf9100528a0d455a8fcb81c072929639":{
      "scriptId":"u60"},
    "6032207b486f434ea40139d51e649787":{
      "scriptId":"u61"},
    "2504ea7ddac446a8a309e149f706e85f":{
      "scriptId":"u62"},
    "a73365bbbcd640aaab82913065eac328":{
      "scriptId":"u63"},
    "6cc831bdfe444e4899efd54948876e2c":{
      "scriptId":"u64"},
    "f1904571aae24931aee0c2efd3624290":{
      "scriptId":"u65"},
    "1b8562c2631846e1b7943f53b0400cc1":{
      "scriptId":"u66"},
    "483f5bf1f28b45e39fff112584a889ec":{
      "scriptId":"u67"},
    "70cce4cd515749a4ba745399484937b6":{
      "scriptId":"u68"},
    "8a47c54013af444d993b621629bb5499":{
      "scriptId":"u69"},
    "66e057450a9c49b2afc2aab4bc481b60":{
      "scriptId":"u70"},
    "1e470dfbb5564cd2945745985087c5dd":{
      "scriptId":"u71"},
    "c8f640e7e8bc409fa55e33e16bdb26ce":{
      "scriptId":"u72"},
    "e1e6411cc67842dc80381e0ae6abd929":{
      "scriptId":"u73"},
    "5990a63ebc5f4b23aecfb746f3b53bed":{
      "scriptId":"u74"},
    "0f7c3df5b1e54b2eb1af1e3051aa34ec":{
      "scriptId":"u75"},
    "d4f2c0dd0cd94cd68941f6fdb503d286":{
      "scriptId":"u76"},
    "c38e73de700d415f863cac239b190dd8":{
      "scriptId":"u77"},
    "74b40d87d0ee42bd880a684bcac01f77":{
      "scriptId":"u78"},
    "b454e5c3f9474c5baf77b6141135778c":{
      "scriptId":"u79"},
    "c5af07935cd54d1c8d45b0d6b3fb58bd":{
      "scriptId":"u80"},
    "16913a30c08f44fe8c9cc7d65e67ea33":{
      "scriptId":"u81"},
    "c9ad2accd4c54bb8be401aeaa4a8b9f1":{
      "scriptId":"u82"},
    "0278304842784886a34dafa25520c8eb":{
      "scriptId":"u83"},
    "094fa4684e41420a845efbca2193c4f9":{
      "scriptId":"u84"},
    "d271390254fb49829239d7ba06e8ad97":{
      "scriptId":"u85"},
    "5aa532f23c3345919a3fd041536e5577":{
      "scriptId":"u86"},
    "f2b8300fcf9148909b1d45b72d2b30fa":{
      "scriptId":"u87"},
    "e748d9d868b641b5828ef592da8a5399":{
      "scriptId":"u88"},
    "d13c231be94246f9ab6697a5516af692":{
      "scriptId":"u89"},
    "961f3a7b71624c53aaf13a99cb87ccb7":{
      "scriptId":"u90"},
    "4672eeae803b4404a26703ff2c6c1639":{
      "scriptId":"u91"},
    "759915f50baf4d5dbbf18f1f0556c7b5":{
      "scriptId":"u92"},
    "78908cfd5767490ea59105be2ded5d89":{
      "scriptId":"u93"},
    "65575f7b0bf74cfb804ba29e736a3ecb":{
      "scriptId":"u94"},
    "8d4ed0e367164c13a0f7e59ec46ddfd3":{
      "scriptId":"u95"},
    "328b1cc77d474a83a0155fe775381208":{
      "scriptId":"u96"},
    "47b28eecfda8487d80d08a7127c4dcb1":{
      "scriptId":"u97"},
    "2f1734d896e54a20adaca21123829105":{
      "scriptId":"u98"},
    "7e453c603fd04788a978d04659c5c2f8":{
      "scriptId":"u99"},
    "9e3745326eec41768dabec90c9ab022e":{
      "scriptId":"u100"},
    "016cabbd6855450cb74b4ab93be7f628":{
      "scriptId":"u101"},
    "20ab64f7600c4791add157862b87d259":{
      "scriptId":"u102"},
    "ad6511adf2584a5585eb3679f47423cf":{
      "scriptId":"u103"},
    "770e9dab8a194ac383fe8c7e4ad7e1a6":{
      "scriptId":"u104"},
    "20867db3e3db4fd2a2c8cf27dd4e8f64":{
      "scriptId":"u105"}}});