$axure.loadCurrentPage({
  "url":"полезная_информация.html",
  "generationDate":new Date(1494499907432.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"0918a9ce67914b71a9f3ca6b23c954ec",
    "type":"Axure:Page",
    "name":"Полезная информация",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"30f61676e463443dbc07a5467c426f58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef75c04331346d68cc8d1b4354618dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"06b0c5d4667e43a9ad90d7ea446d8f4f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"e31ab5f083a54043a2036ebe7ece5d0d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"e97ac3577b7441c08eedee2141437d41",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"3bf8dba2131b4d9db7ed4dfb6c4e25b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08f8fe64be184cddb287ad809d80b876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf67e6b7236643a49e86d2ac1921f5f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3cee51080546c58ef486ec1740ccc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf6774577e604ece877ce95d2f039afd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764d8ef1059949a49caf88f75e80fbe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"646d997057554a2b9b778ee4ab38fb92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"891993fb979b4c699aac99deecc2fe34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"3d7bca93c3c6448498c8e6a4c06b973d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"3008ccd25b9240178c3db57c364b5f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec86e166f02c4ad5ab86d200781d6fc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59945bbcbf2149309e8d26d5d4a6a0ec",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c005bac587145bab5ba0f511d31c0e0",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d6194913981411a99fefddf823aedbc",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a18f6b931e654648a2ca8260d3e6fbb3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"ca97400a6330405c93bec0b2b62400bb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"327088aaf5ec4e9c8742f1ea5393eb6f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"f0007798f6844416a9bd4193b299f5da",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9757529e8dae4f53be0eb50af272d404",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"8b9d9fa8a1f84067acf1c4fa3f95f1ae",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1fc03a45a554671889e5a8d43a6f9a9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"4f3d808f57cb44daacf0a428f6644ad1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b082eeb8dcea44498a61262b6f3a9a5a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"7986a5bde9844598acd63f5d9b03f5bc",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a3d69cc27994c1c8828b5565665f843",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71ad2191b72e469b8aca5ebd00b73fa5",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"48c25f6394a545feabdf463e8be88b75",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"8e63084acf8f4776a17c7db8a4ec924f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3fdfdca7ec04416ea38c94154029153b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"95837a3acfad4399a29121b8ef0035f3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9c2dd32e63d344b1bf51738932f53b81",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"cc3c43fe23554b5f9a80e92b0cfaa4e0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"204e6cccc1f84b9cb2ec25287772061e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"54bf1a7f64804202975c506a18ddf125",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d5bdd23c7f1643f49a998ab1023d6c3e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"ca97400a6330405c93bec0b2b62400bb"}]},
{
          "id":"0937fb330f234f1c872e04e17c4ddd84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":19,
              "y":267},
            "size":{
              "width":281,
              "height":60},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3775af37a89a48d58ce703e058f12250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":19,
                  "y":267},
                "size":{
                  "width":281,
                  "height":60},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/полезная_информация/u40.png"}},
{
          "id":"0e4a636ec7f44454a589217befe7a359",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "underline":true,
            "location":{
              "x":46,
              "y":348},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3bd898114a41ebaf3a41b71750cf91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "underline":true,
                "location":{
                  "x":46,
                  "y":348},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"224032566ea34c80af362cda76c8c67b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "underline":true,
            "location":{
              "x":46,
              "y":385},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c271870ff9a4657a136e4e26e21e105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "underline":true,
                "location":{
                  "x":46,
                  "y":385},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a4d8ba812d84f538abc82b9f2226407",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "underline":true,
            "location":{
              "x":46,
              "y":423},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ea5785f0844d60a1abe645c9370ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "underline":true,
                "location":{
                  "x":46,
                  "y":423},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5985b412a3414c83b081131b79423d39",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "underline":true,
            "location":{
              "x":46,
              "y":460},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c33d64024fb04c23885bca6ad98c0343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "underline":true,
                "location":{
                  "x":46,
                  "y":460},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b1f756a9de54eb4b7c1fab13376303c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":358,
              "y":267},
            "size":{
              "width":281,
              "height":60},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"514a57ebcb714445aab648bb6f88dd47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":358,
                  "y":267},
                "size":{
                  "width":281,
                  "height":60},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/полезная_информация/u40.png"}},
{
          "id":"65075c3b925946e88cf7306353323b72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":358,
              "y":327},
            "size":{
              "width":281,
              "height":323}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"698601b8f9b74015a0b8a2fa69732aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":358,
                  "y":327},
                "size":{
                  "width":281,
                  "height":323}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/полезная_информация/u52.png"}},
{
          "id":"a627e2611b2245338c2c05a3bf4b6eb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":337},
            "size":{
              "width":260,
              "height":233}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12060b1211634e1da35c4dbe18a4dbfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":337},
                "size":{
                  "width":260,
                  "height":233}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9bfa33f7f804dcba0e3e58f3625b7b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":670,
              "y":267},
            "size":{
              "width":308,
              "height":383},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67a98c3ac83443ff95d66ebb0ce10a19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":670,
                  "y":267},
                "size":{
                  "width":308,
                  "height":383},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/полезная_информация/u56.png"}},
{
          "id":"bb336568d1a2496695babf221d35cab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-5,
              "y":726},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015a78d8991d4403b86a16173ed074fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-5,
                  "y":726},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "30f61676e463443dbc07a5467c426f58":{
      "scriptId":"u0"},
    "2ef75c04331346d68cc8d1b4354618dd":{
      "scriptId":"u1"},
    "06b0c5d4667e43a9ad90d7ea446d8f4f":{
      "scriptId":"u2"},
    "e31ab5f083a54043a2036ebe7ece5d0d":{
      "scriptId":"u3"},
    "e97ac3577b7441c08eedee2141437d41":{
      "scriptId":"u4"},
    "3bf8dba2131b4d9db7ed4dfb6c4e25b6":{
      "scriptId":"u5"},
    "08f8fe64be184cddb287ad809d80b876":{
      "scriptId":"u6"},
    "cf67e6b7236643a49e86d2ac1921f5f7":{
      "scriptId":"u7"},
    "7c3cee51080546c58ef486ec1740ccc8":{
      "scriptId":"u8"},
    "bf6774577e604ece877ce95d2f039afd":{
      "scriptId":"u9"},
    "764d8ef1059949a49caf88f75e80fbe9":{
      "scriptId":"u10"},
    "646d997057554a2b9b778ee4ab38fb92":{
      "scriptId":"u11"},
    "891993fb979b4c699aac99deecc2fe34":{
      "scriptId":"u12"},
    "3d7bca93c3c6448498c8e6a4c06b973d":{
      "scriptId":"u13"},
    "3008ccd25b9240178c3db57c364b5f00":{
      "scriptId":"u14"},
    "ec86e166f02c4ad5ab86d200781d6fc9":{
      "scriptId":"u15"},
    "59945bbcbf2149309e8d26d5d4a6a0ec":{
      "scriptId":"u16"},
    "0c005bac587145bab5ba0f511d31c0e0":{
      "scriptId":"u17"},
    "6d6194913981411a99fefddf823aedbc":{
      "scriptId":"u18"},
    "a18f6b931e654648a2ca8260d3e6fbb3":{
      "scriptId":"u19"},
    "ca97400a6330405c93bec0b2b62400bb":{
      "scriptId":"u20"},
    "327088aaf5ec4e9c8742f1ea5393eb6f":{
      "scriptId":"u21"},
    "8b9d9fa8a1f84067acf1c4fa3f95f1ae":{
      "scriptId":"u22"},
    "d1fc03a45a554671889e5a8d43a6f9a9":{
      "scriptId":"u23"},
    "4f3d808f57cb44daacf0a428f6644ad1":{
      "scriptId":"u24"},
    "b082eeb8dcea44498a61262b6f3a9a5a":{
      "scriptId":"u25"},
    "f0007798f6844416a9bd4193b299f5da":{
      "scriptId":"u26"},
    "9757529e8dae4f53be0eb50af272d404":{
      "scriptId":"u27"},
    "7986a5bde9844598acd63f5d9b03f5bc":{
      "scriptId":"u28"},
    "4a3d69cc27994c1c8828b5565665f843":{
      "scriptId":"u29"},
    "71ad2191b72e469b8aca5ebd00b73fa5":{
      "scriptId":"u30"},
    "48c25f6394a545feabdf463e8be88b75":{
      "scriptId":"u31"},
    "95837a3acfad4399a29121b8ef0035f3":{
      "scriptId":"u32"},
    "9c2dd32e63d344b1bf51738932f53b81":{
      "scriptId":"u33"},
    "cc3c43fe23554b5f9a80e92b0cfaa4e0":{
      "scriptId":"u34"},
    "204e6cccc1f84b9cb2ec25287772061e":{
      "scriptId":"u35"},
    "8e63084acf8f4776a17c7db8a4ec924f":{
      "scriptId":"u36"},
    "3fdfdca7ec04416ea38c94154029153b":{
      "scriptId":"u37"},
    "54bf1a7f64804202975c506a18ddf125":{
      "scriptId":"u38"},
    "d5bdd23c7f1643f49a998ab1023d6c3e":{
      "scriptId":"u39"},
    "0937fb330f234f1c872e04e17c4ddd84":{
      "scriptId":"u40"},
    "3775af37a89a48d58ce703e058f12250":{
      "scriptId":"u41"},
    "0e4a636ec7f44454a589217befe7a359":{
      "scriptId":"u42"},
    "1d3bd898114a41ebaf3a41b71750cf91":{
      "scriptId":"u43"},
    "224032566ea34c80af362cda76c8c67b":{
      "scriptId":"u44"},
    "4c271870ff9a4657a136e4e26e21e105":{
      "scriptId":"u45"},
    "6a4d8ba812d84f538abc82b9f2226407":{
      "scriptId":"u46"},
    "81ea5785f0844d60a1abe645c9370ac3":{
      "scriptId":"u47"},
    "5985b412a3414c83b081131b79423d39":{
      "scriptId":"u48"},
    "c33d64024fb04c23885bca6ad98c0343":{
      "scriptId":"u49"},
    "2b1f756a9de54eb4b7c1fab13376303c":{
      "scriptId":"u50"},
    "514a57ebcb714445aab648bb6f88dd47":{
      "scriptId":"u51"},
    "65075c3b925946e88cf7306353323b72":{
      "scriptId":"u52"},
    "698601b8f9b74015a0b8a2fa69732aa7":{
      "scriptId":"u53"},
    "a627e2611b2245338c2c05a3bf4b6eb0":{
      "scriptId":"u54"},
    "12060b1211634e1da35c4dbe18a4dbfb":{
      "scriptId":"u55"},
    "d9bfa33f7f804dcba0e3e58f3625b7b5":{
      "scriptId":"u56"},
    "67a98c3ac83443ff95d66ebb0ce10a19":{
      "scriptId":"u57"},
    "bb336568d1a2496695babf221d35cab8":{
      "scriptId":"u58"},
    "015a78d8991d4403b86a16173ed074fc":{
      "scriptId":"u59"}}});