$axure.loadCurrentPage({
  "url":"статья.html",
  "generationDate":new Date(1494499899824.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"3e61f85d30d74ca0849af26979d31ef4",
    "type":"Axure:Page",
    "name":"Статья",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"72eb24a5360545c290045e39ec7fc3d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":213},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bfba70856f849bf94f27aacf8c4722a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":213},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5dc7ada2493b47b981b858366066adab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":214},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f81ad60f532f4068b1a04dfb1d2dcac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":214},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5d2e93ba6af49d78ecf2c40a84a6ec3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":216},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"3f70f75abc934a958a908220cbc773d2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":217},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"a6fda97c1bf8488fb701082780f18a9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":203,
              "y":215},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"079c5cba3ad6473481a6e03bc689471d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":203,
                  "y":215},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"156e5fbff75940db8a7dd8534cc896c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":24,
              "y":292},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e16f7f7142584fabb78ded141481c194",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":24,
                  "y":292},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca52f75dd12b4da680b246bd1601c667",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":26,
              "y":321},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39e7cfaeec0549fb88f43b9740071a92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":26,
                  "y":321},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35789b152a344f4fa24e9fc5e29433d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":360},
            "size":{
              "width":386,
              "height":262}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d05b2194aabe4b45bdf189e9be1c4b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":360},
                "size":{
                  "width":386,
                  "height":262}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/статья/u12.png"}},
{
          "id":"c4bf93d028854607aaa8c24bcd11eb03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":277,
              "y":342},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece7966d768c4f37b817f0935508ad41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":277,
                  "y":342},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77fc1909ec86458ca79624255d29a16c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":342},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26965ee9c05e4c65aebcacea5b5f7e3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":342},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/статья/u16.png"}},
{
          "id":"d3fa30d1f49f428abb3285f5408acd7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":342},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efd3d51213664dc7b1a2855417e30618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":342},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/статья/u18.png"}},
{
          "id":"8d4b54e116ca4e0798de175401b86c22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":441,
              "y":360},
            "size":{
              "width":560,
              "height":472}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3324bddcca36406080868ec03415aa3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":441,
                  "y":360},
                "size":{
                  "width":560,
                  "height":472}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b185f7bd058495993b715b42edd4cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":431,
              "y":889},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4005b9c8f8f4a4a91f15af7d14f3acf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":431,
                  "y":889},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b85283b4249b490fa124fbadef1d76bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":942},
            "size":{
              "width":256,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5238f3e6f0c947eb884f7837266e9849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":942},
                "size":{
                  "width":256,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/статья/u24.png"}},
{
          "id":"37093a37b09e4eef9bb9ab1f51fc28b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":34,
              "y":1121},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12ddc7984ad5489fa259cda90873b319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":34,
                  "y":1121},
                "size":{
                  "width":64,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58f26b28527449db8b1be89051feef77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":34,
              "y":1153},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8305eac8606e4724b0b9227e4069577c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":34,
                  "y":1153},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ef8d5e0504949dab3c890c49b302cc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":942},
            "size":{
              "width":256,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e6981c24414e15b18758eb6fba66bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":942},
                "size":{
                  "width":256,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/статья/u24.png"}},
{
          "id":"ea9c98e4365441ae901a5f0fae4d6c6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":369,
              "y":1121},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"247235abd59b49eca5c92bfa1b3a330c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":369,
                  "y":1121},
                "size":{
                  "width":64,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f70e5e8fe6f4579a6875ac46c381bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":369,
              "y":1153},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d53f237a4a24e73b3a5d120472e79d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":369,
                  "y":1153},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3167ee9278a94db5b4593157a8ed8ead",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":712,
              "y":942},
            "size":{
              "width":256,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949e3a0a6ff943e6b9e8deb368f28115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":712,
                  "y":942},
                "size":{
                  "width":256,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/статья/u24.png"}},
{
          "id":"ce5ab4e6d823440bad73b311271e2f84",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":712,
              "y":1121},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37655300be1448ea00539ed1dc9a76e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":712,
                  "y":1121},
                "size":{
                  "width":64,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45a227dc4168443fa178fbf0c8b3793e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":712,
              "y":1153},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a65fed7a733e417d9bacf3834d667d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":712,
                  "y":1153},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5fd6a1b11bb4b4b812002ff8bf6bf91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"30px",
            "fontWeight":"700",
            "location":{
              "x":5,
              "y":1004},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"329063b979ed438e97c5cda74442b340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"30px",
                "fontWeight":"700",
                "location":{
                  "x":5,
                  "y":1004},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c5130f8af244e089952188f479a310b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"30px",
            "fontWeight":"700",
            "location":{
              "x":978,
              "y":1004},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b142b3aa79f4922a3e0e80c4c0ca69b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"30px",
                "fontWeight":"700",
                "location":{
                  "x":978,
                  "y":1004},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84067cc784784e6e878bd982650be655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-1,
              "y":1434},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dbeaadad87545f1ae1b0eef13422fb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-1,
                  "y":1434},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"e9749d1cd6dd46789a7cbde059d2d881",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":1211},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4798f3245f1455691360fa1cf2958e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":1211},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d5db8f5ab95456b9ff85b73242b5ae8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":1195},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u80_line.png"}},
{
          "id":"7a771f91743848eb8785683514096dfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc7e13bb39446d896a1cca8530cb19b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"7030723a02534802b32be9eebdf61069",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fc7cb473d324da0b6d27fb186c3a850",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"edf626d8fe3046e8907dd245858e2e57",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72f526e4eacb4975b77891c940470827",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"b5b358f1e81e44089eaa9bd9ace60d09",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"266f450e551f4af79af5ca37ae258434",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"0bdfdc15284c4ab0b5b06d255d68c00e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"796e5a8a517947ee9dcdc715e3bf31d2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"c1a6d54e45a54108a4edf21ac63252ac",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"53e17072d3d54b5c9ae4c1ecbf5738b5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"a9db2fcb06ce4dc9a1b4f28862ea9587",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e80ea662e12e4b71921b25b8d8e97bcb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"da14ee6ce1954ce59819373f03022ba8",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69f1c030c5e745ec821108a8f20babbb",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28ee7dcf85f843b4a32da6f5780a9c05",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5e6f504c84f94001998d2a864fce29a2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"334d74a55fe84f249941214f785d28b8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a26f92bc69b44ab8aa67310c328dbced",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"73644a288ea145a3922803f8b9dc8019",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"20b8771250d84b70a51977a2f53c79a4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"050fb56d98e849e191deeecace07cdd0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"69754278b0934126994cc66b2d84f293",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"d94090f16caa47bd979a6f9274a63552",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c26d615bfe344b9bada9001d61906a41",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"b5b358f1e81e44089eaa9bd9ace60d09"}]},
{
          "id":"93152601a8664470bbf779f1b4680dda",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"39fabb7d3f0e4ac6863a7b2a7a9fe6e1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"0757c4a2367c4f8c9915d327cd927db4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"16a3b7a5db3a47dc9312463ad6a8ec9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487e323a42fe4436b4ee83cc6c1daadb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b18ebc03e821450aa2764040c8a5bc53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2022fc99518d4faeb8486acd6861d4a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88d1997780c44cfcae1f590d253b953b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e6d46937df4bf28c00f7528226250f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"016528c947684e35b12e90df1c1a2d28",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c06ddb770f4e26bd6f662bb7781c6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"9527028c90264fdbbefaaeb13c653640",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"8ac2b669119141b0ac260a7238a4e534",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51aa8ea8bc404bd6b0fd4ed6aead5a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "72eb24a5360545c290045e39ec7fc3d7":{
      "scriptId":"u0"},
    "4bfba70856f849bf94f27aacf8c4722a":{
      "scriptId":"u1"},
    "5dc7ada2493b47b981b858366066adab":{
      "scriptId":"u2"},
    "f81ad60f532f4068b1a04dfb1d2dcac6":{
      "scriptId":"u3"},
    "e5d2e93ba6af49d78ecf2c40a84a6ec3":{
      "scriptId":"u4"},
    "3f70f75abc934a958a908220cbc773d2":{
      "scriptId":"u5"},
    "a6fda97c1bf8488fb701082780f18a9e":{
      "scriptId":"u6"},
    "079c5cba3ad6473481a6e03bc689471d":{
      "scriptId":"u7"},
    "156e5fbff75940db8a7dd8534cc896c9":{
      "scriptId":"u8"},
    "e16f7f7142584fabb78ded141481c194":{
      "scriptId":"u9"},
    "ca52f75dd12b4da680b246bd1601c667":{
      "scriptId":"u10"},
    "39e7cfaeec0549fb88f43b9740071a92":{
      "scriptId":"u11"},
    "35789b152a344f4fa24e9fc5e29433d1":{
      "scriptId":"u12"},
    "d05b2194aabe4b45bdf189e9be1c4b73":{
      "scriptId":"u13"},
    "c4bf93d028854607aaa8c24bcd11eb03":{
      "scriptId":"u14"},
    "ece7966d768c4f37b817f0935508ad41":{
      "scriptId":"u15"},
    "77fc1909ec86458ca79624255d29a16c":{
      "scriptId":"u16"},
    "26965ee9c05e4c65aebcacea5b5f7e3d":{
      "scriptId":"u17"},
    "d3fa30d1f49f428abb3285f5408acd7a":{
      "scriptId":"u18"},
    "efd3d51213664dc7b1a2855417e30618":{
      "scriptId":"u19"},
    "8d4b54e116ca4e0798de175401b86c22":{
      "scriptId":"u20"},
    "3324bddcca36406080868ec03415aa3f":{
      "scriptId":"u21"},
    "2b185f7bd058495993b715b42edd4cc2":{
      "scriptId":"u22"},
    "e4005b9c8f8f4a4a91f15af7d14f3acf":{
      "scriptId":"u23"},
    "b85283b4249b490fa124fbadef1d76bb":{
      "scriptId":"u24"},
    "5238f3e6f0c947eb884f7837266e9849":{
      "scriptId":"u25"},
    "37093a37b09e4eef9bb9ab1f51fc28b4":{
      "scriptId":"u26"},
    "12ddc7984ad5489fa259cda90873b319":{
      "scriptId":"u27"},
    "58f26b28527449db8b1be89051feef77":{
      "scriptId":"u28"},
    "8305eac8606e4724b0b9227e4069577c":{
      "scriptId":"u29"},
    "1ef8d5e0504949dab3c890c49b302cc7":{
      "scriptId":"u30"},
    "b0e6981c24414e15b18758eb6fba66bf":{
      "scriptId":"u31"},
    "ea9c98e4365441ae901a5f0fae4d6c6f":{
      "scriptId":"u32"},
    "247235abd59b49eca5c92bfa1b3a330c":{
      "scriptId":"u33"},
    "6f70e5e8fe6f4579a6875ac46c381bb8":{
      "scriptId":"u34"},
    "3d53f237a4a24e73b3a5d120472e79d7":{
      "scriptId":"u35"},
    "3167ee9278a94db5b4593157a8ed8ead":{
      "scriptId":"u36"},
    "949e3a0a6ff943e6b9e8deb368f28115":{
      "scriptId":"u37"},
    "ce5ab4e6d823440bad73b311271e2f84":{
      "scriptId":"u38"},
    "e37655300be1448ea00539ed1dc9a76e":{
      "scriptId":"u39"},
    "45a227dc4168443fa178fbf0c8b3793e":{
      "scriptId":"u40"},
    "a65fed7a733e417d9bacf3834d667d67":{
      "scriptId":"u41"},
    "b5fd6a1b11bb4b4b812002ff8bf6bf91":{
      "scriptId":"u42"},
    "329063b979ed438e97c5cda74442b340":{
      "scriptId":"u43"},
    "0c5130f8af244e089952188f479a310b":{
      "scriptId":"u44"},
    "2b142b3aa79f4922a3e0e80c4c0ca69b":{
      "scriptId":"u45"},
    "84067cc784784e6e878bd982650be655":{
      "scriptId":"u46"},
    "5dbeaadad87545f1ae1b0eef13422fb8":{
      "scriptId":"u47"},
    "e9749d1cd6dd46789a7cbde059d2d881":{
      "scriptId":"u48"},
    "b4798f3245f1455691360fa1cf2958e3":{
      "scriptId":"u49"},
    "3d5db8f5ab95456b9ff85b73242b5ae8":{
      "scriptId":"u50"},
    "7a771f91743848eb8785683514096dfe":{
      "scriptId":"u51"},
    "7cc7e13bb39446d896a1cca8530cb19b":{
      "scriptId":"u52"},
    "7030723a02534802b32be9eebdf61069":{
      "scriptId":"u53"},
    "7fc7cb473d324da0b6d27fb186c3a850":{
      "scriptId":"u54"},
    "edf626d8fe3046e8907dd245858e2e57":{
      "scriptId":"u55"},
    "72f526e4eacb4975b77891c940470827":{
      "scriptId":"u56"},
    "b5b358f1e81e44089eaa9bd9ace60d09":{
      "scriptId":"u57"},
    "266f450e551f4af79af5ca37ae258434":{
      "scriptId":"u58"},
    "c1a6d54e45a54108a4edf21ac63252ac":{
      "scriptId":"u59"},
    "53e17072d3d54b5c9ae4c1ecbf5738b5":{
      "scriptId":"u60"},
    "a9db2fcb06ce4dc9a1b4f28862ea9587":{
      "scriptId":"u61"},
    "e80ea662e12e4b71921b25b8d8e97bcb":{
      "scriptId":"u62"},
    "0bdfdc15284c4ab0b5b06d255d68c00e":{
      "scriptId":"u63"},
    "796e5a8a517947ee9dcdc715e3bf31d2":{
      "scriptId":"u64"},
    "da14ee6ce1954ce59819373f03022ba8":{
      "scriptId":"u65"},
    "69f1c030c5e745ec821108a8f20babbb":{
      "scriptId":"u66"},
    "28ee7dcf85f843b4a32da6f5780a9c05":{
      "scriptId":"u67"},
    "5e6f504c84f94001998d2a864fce29a2":{
      "scriptId":"u68"},
    "73644a288ea145a3922803f8b9dc8019":{
      "scriptId":"u69"},
    "20b8771250d84b70a51977a2f53c79a4":{
      "scriptId":"u70"},
    "050fb56d98e849e191deeecace07cdd0":{
      "scriptId":"u71"},
    "69754278b0934126994cc66b2d84f293":{
      "scriptId":"u72"},
    "334d74a55fe84f249941214f785d28b8":{
      "scriptId":"u73"},
    "a26f92bc69b44ab8aa67310c328dbced":{
      "scriptId":"u74"},
    "d94090f16caa47bd979a6f9274a63552":{
      "scriptId":"u75"},
    "c26d615bfe344b9bada9001d61906a41":{
      "scriptId":"u76"},
    "93152601a8664470bbf779f1b4680dda":{
      "scriptId":"u77"},
    "39fabb7d3f0e4ac6863a7b2a7a9fe6e1":{
      "scriptId":"u78"},
    "0757c4a2367c4f8c9915d327cd927db4":{
      "scriptId":"u79"},
    "16a3b7a5db3a47dc9312463ad6a8ec9c":{
      "scriptId":"u80"},
    "487e323a42fe4436b4ee83cc6c1daadb":{
      "scriptId":"u81"},
    "b18ebc03e821450aa2764040c8a5bc53":{
      "scriptId":"u82"},
    "2022fc99518d4faeb8486acd6861d4a8":{
      "scriptId":"u83"},
    "88d1997780c44cfcae1f590d253b953b":{
      "scriptId":"u84"},
    "58e6d46937df4bf28c00f7528226250f":{
      "scriptId":"u85"},
    "016528c947684e35b12e90df1c1a2d28":{
      "scriptId":"u86"},
    "29c06ddb770f4e26bd6f662bb7781c6e":{
      "scriptId":"u87"},
    "9527028c90264fdbbefaaeb13c653640":{
      "scriptId":"u88"},
    "8ac2b669119141b0ac260a7238a4e534":{
      "scriptId":"u89"},
    "51aa8ea8bc404bd6b0fd4ed6aead5a3e":{
      "scriptId":"u90"}}});