$axure.loadCurrentPage({
  "url":"товар.html",
  "generationDate":new Date(1495780880383.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"862358c4e841476f96da2ab0a3b84007",
    "type":"Axure:Page",
    "name":"Товар",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f3870ece4e524457a6383cc253bda81e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":139},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58845d08d51a41128275f8cc28f787fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":139},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8598bdea022140f3b897d6768ca05683",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":140},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ade4a2875824a449fdb0c13cc64e5ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":140},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca5833ecdd384966814270671d151be5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":142},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"62fa87055cb24a0ba10d7fbe88b6a3f2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":143},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"43818a9c94d8413dbccf2f0209190b09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":157,
              "y":140},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08f25cd6fa454e7aa0bc4e41c5dabd70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":157,
                  "y":140},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6a314b299c34a3b9cd9f6e9acc69352",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":24,
              "y":239},
            "size":{
              "width":436,
              "height":389}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f63005396864d929678d0cfa67b1fc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":24,
                  "y":239},
                "size":{
                  "width":436,
                  "height":389}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/товар/u8.png"}},
{
          "id":"96e12d5f0abe4b6ea7b95fbbfd39fbcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":265},
            "size":{
              "width":380,
              "height":233},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f464d9ec9e87443ca17cfb696341a590",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":265},
                "size":{
                  "width":380,
                  "height":233},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/товар/u10.png"}},
{
          "id":"ec3352f266db4e5c9670b3e2826c070d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":529},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dabe313888b48049da3070f819991a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":529},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/товар/u12.png"}},
{
          "id":"b00032c1d68e4536b58349171aff59b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":529},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2599f1384c74b41adc438a74a23dfe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":529},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/товар/u12.png"}},
{
          "id":"5edbb93e46b54d66a3a51026851c4327",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":529},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a52ff64966748a18f2304df66a40231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":529},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/товар/u12.png"}},
{
          "id":"9d7781a21cc9408bb13b6245d6888252",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":24,
              "y":546},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1819453a7404a2ea5c62b600653dbf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":24,
                  "y":546},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7939e28092a34bbcbeb4b801afd118b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":435,
              "y":546},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068bccaeb82a4e96a5920fdad431e8f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":435,
                  "y":546},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9520ff0f43c4eb68719a901e1a5c42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":521,
              "y":190},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dadf78dab00e4c969f9b0757ef9108f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":521,
                  "y":190},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d43c82d662804c8fa21eb2f9db96806a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":278},
            "size":{
              "width":499,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9dd41d8a10f4e10ae22e19f59e5e860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":521,
                  "y":278},
                "size":{
                  "width":499,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15a3e0442a904940b5223e13827ae359",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":407},
            "size":{
              "width":482,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40c7fb99acaa4d39a58adad72cf91755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":521,
                  "y":407},
                "size":{
                  "width":482,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc6574348d1047a68a9c874b332a92e6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":238},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9d48deef40434cb9adb27a6c319f9845",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":702},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34735171d0444ae99daea397bd8ce1aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":702},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2381310859e541e494fd6853190172f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":686},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/о_нас/u17_line.png"}},
{
          "id":"a46c9370cdfa44e59942d79a6dcac61c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "underline":true,
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":931},
            "size":{
              "width":1000,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c73b5af5eed4bf6b9d246c6ca6a0392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "underline":true,
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":931},
                "size":{
                  "width":1000,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u105.png"}},
{
          "id":"3d58906794bd43a49eeb06c7d80be1bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":1002},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29beff5bc3ad441384690afd51ce18a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":1002},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u107.png"}},
{
          "id":"0c3b238620a748469d2d013200851602",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":1002},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35721d9c1fe145daa66e5055e7b14037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":1002},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u109.png"}},
{
          "id":"cdc8072c303c443b9183a81f762de9db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":1002},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21eea6f13e1d47b2a2be748248cd831e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":1002},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u111.png"}},
{
          "id":"cf75054b0793425a86b685f8b6bc36f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":53,
              "y":962},
            "size":{
              "width":242,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ce95e64fe7c466d9b4255f1f028c780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":53,
                  "y":962},
                "size":{
                  "width":242,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"359b21e6be8c4c0282f26fefb0b190b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":1005},
            "size":{
              "width":311,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8601499f19b84b27a53a30afec04dc02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":1005},
                "size":{
                  "width":311,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7639a3728bc9470f8ed3338187e2cea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":385,
              "y":962},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f5f27bd87db425bb2a76e720f572bcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":385,
                  "y":962},
                "size":{
                  "width":93,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b29e518b6fbe47f3a5d9e9f19071c323",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":160,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f580ef3129314132a8ff11a7d8f9a028",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":160,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"56c35db007b540259fd5eb92b1fb9ec1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"bf63743994634dc0b5c03cace43721ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64f5fedc655a49b5b97d54f0bd9e649d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63336f236a1943d9bf36a2a0f05028ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c5f6857d313472380eba466adb4cba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"4859afc05bc24a88aa79243fa38f6f84",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f61da041a1454db9a8786ea7f8a4b77e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"75c01f43537a445bb6f0e08686ee88cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":3},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a74b281a87a04e1f8fa2b3311b037b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":3},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82b051bdd407481a972c4dad279cc1a9",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":66},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4a3293eae194bb8b32eaeb22e024d2e",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d06d04b3ba54fc18dc31ff17272f179",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"693e4bc411444788a8b17cf56cd3e53c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"2c160047a59941b8a33a8bbc8aa17a1a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb1234de3d364d1883e995717211f9c4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"7b5f3b69c10f4cb7a88059458a004026",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59346043f9064461aaed154d0fa598ae",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u131.png"}},
{
                  "id":"9f48ca8aeb8c4ed191b1a0afab840cbf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9f2afe6c1564684b629b9998d6c1971",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"1c9c631bdeda462380b603d6fba1f869",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbcc4695578d4706b77e716a284b7190",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"6b8973ea7a144cb79f8965ed6c462971",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72a3b7da5b1b41f8b1cec9e0791886cd",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}}]},
{
              "id":"c74c7a69e0aa483ab0e970029e8382d2",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f63c6294f93494aa2aab643ca8b11db",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"121c83d8113646f78d76966d98eecde8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f2af0725ebbe44de9c31923d038036a9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"e0f4c2760c4242d28f99cc429fbf7c2b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fc2fb1e7dc4346ef9b8ada32159275f1",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"ccd02384516e4468b1ab65cfca216ec9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c628316961234ce7a9ba936b6838dc54",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"de487e2f92cb459d85c5dc6c0d52f97c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e81472ddc10a4597a508c3ab06b33cb8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u153.png"}},
{
                      "id":"403f92893b0e4d54bb065019c8872a8c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5dd25f3154844bfbb2abf92e25f4724f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"712bab4234c542309ba11054afba47bc",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3536f874712a43e3948f0fda62715d81",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"037cbe13bdbe461799d7e96b41765f26",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"96923c59a6f948d8a00ca2c90ef0d234",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"f15054542d224aabbd4c6794601459c0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"82e1e1ed09db4277898defc8a6c7bdab",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"d9055e378cac4ce8b3a32c16bb022449",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4dc904cd786a4948aa949bc868456b51",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"3cca449782e54217bff74fd78e59c788",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0cf438136a17443f83f6c67191f4372b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}}]}],
              "parentCellId":"2c160047a59941b8a33a8bbc8aa17a1a"}]},
{
          "id":"ae662fcace624ae48c6fe225684232b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":853,
              "y":-2},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52058b7f0b0148878c962deed07f6216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":853,
                  "y":-2},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f3870ece4e524457a6383cc253bda81e":{
      "scriptId":"u0"},
    "58845d08d51a41128275f8cc28f787fb":{
      "scriptId":"u1"},
    "8598bdea022140f3b897d6768ca05683":{
      "scriptId":"u2"},
    "2ade4a2875824a449fdb0c13cc64e5ae":{
      "scriptId":"u3"},
    "ca5833ecdd384966814270671d151be5":{
      "scriptId":"u4"},
    "62fa87055cb24a0ba10d7fbe88b6a3f2":{
      "scriptId":"u5"},
    "43818a9c94d8413dbccf2f0209190b09":{
      "scriptId":"u6"},
    "08f25cd6fa454e7aa0bc4e41c5dabd70":{
      "scriptId":"u7"},
    "c6a314b299c34a3b9cd9f6e9acc69352":{
      "scriptId":"u8"},
    "2f63005396864d929678d0cfa67b1fc9":{
      "scriptId":"u9"},
    "96e12d5f0abe4b6ea7b95fbbfd39fbcb":{
      "scriptId":"u10"},
    "f464d9ec9e87443ca17cfb696341a590":{
      "scriptId":"u11"},
    "ec3352f266db4e5c9670b3e2826c070d":{
      "scriptId":"u12"},
    "5dabe313888b48049da3070f819991a8":{
      "scriptId":"u13"},
    "b00032c1d68e4536b58349171aff59b5":{
      "scriptId":"u14"},
    "e2599f1384c74b41adc438a74a23dfe7":{
      "scriptId":"u15"},
    "5edbb93e46b54d66a3a51026851c4327":{
      "scriptId":"u16"},
    "0a52ff64966748a18f2304df66a40231":{
      "scriptId":"u17"},
    "9d7781a21cc9408bb13b6245d6888252":{
      "scriptId":"u18"},
    "e1819453a7404a2ea5c62b600653dbf0":{
      "scriptId":"u19"},
    "7939e28092a34bbcbeb4b801afd118b1":{
      "scriptId":"u20"},
    "068bccaeb82a4e96a5920fdad431e8f7":{
      "scriptId":"u21"},
    "f9520ff0f43c4eb68719a901e1a5c42b":{
      "scriptId":"u22"},
    "dadf78dab00e4c969f9b0757ef9108f4":{
      "scriptId":"u23"},
    "d43c82d662804c8fa21eb2f9db96806a":{
      "scriptId":"u24"},
    "c9dd41d8a10f4e10ae22e19f59e5e860":{
      "scriptId":"u25"},
    "15a3e0442a904940b5223e13827ae359":{
      "scriptId":"u26"},
    "40c7fb99acaa4d39a58adad72cf91755":{
      "scriptId":"u27"},
    "cc6574348d1047a68a9c874b332a92e6":{
      "scriptId":"u28"},
    "9d48deef40434cb9adb27a6c319f9845":{
      "scriptId":"u29"},
    "34735171d0444ae99daea397bd8ce1aa":{
      "scriptId":"u30"},
    "2381310859e541e494fd6853190172f4":{
      "scriptId":"u31"},
    "a46c9370cdfa44e59942d79a6dcac61c":{
      "scriptId":"u32"},
    "5c73b5af5eed4bf6b9d246c6ca6a0392":{
      "scriptId":"u33"},
    "3d58906794bd43a49eeb06c7d80be1bc":{
      "scriptId":"u34"},
    "29beff5bc3ad441384690afd51ce18a3":{
      "scriptId":"u35"},
    "0c3b238620a748469d2d013200851602":{
      "scriptId":"u36"},
    "35721d9c1fe145daa66e5055e7b14037":{
      "scriptId":"u37"},
    "cdc8072c303c443b9183a81f762de9db":{
      "scriptId":"u38"},
    "21eea6f13e1d47b2a2be748248cd831e":{
      "scriptId":"u39"},
    "cf75054b0793425a86b685f8b6bc36f1":{
      "scriptId":"u40"},
    "1ce95e64fe7c466d9b4255f1f028c780":{
      "scriptId":"u41"},
    "359b21e6be8c4c0282f26fefb0b190b7":{
      "scriptId":"u42"},
    "8601499f19b84b27a53a30afec04dc02":{
      "scriptId":"u43"},
    "7639a3728bc9470f8ed3338187e2cea1":{
      "scriptId":"u44"},
    "2f5f27bd87db425bb2a76e720f572bcf":{
      "scriptId":"u45"},
    "b29e518b6fbe47f3a5d9e9f19071c323":{
      "scriptId":"u46"},
    "f580ef3129314132a8ff11a7d8f9a028":{
      "scriptId":"u47"},
    "56c35db007b540259fd5eb92b1fb9ec1":{
      "scriptId":"u48"},
    "bf63743994634dc0b5c03cace43721ec":{
      "scriptId":"u49"},
    "64f5fedc655a49b5b97d54f0bd9e649d":{
      "scriptId":"u50"},
    "63336f236a1943d9bf36a2a0f05028ff":{
      "scriptId":"u51"},
    "0c5f6857d313472380eba466adb4cba0":{
      "scriptId":"u52"},
    "4859afc05bc24a88aa79243fa38f6f84":{
      "scriptId":"u53"},
    "f61da041a1454db9a8786ea7f8a4b77e":{
      "scriptId":"u54"},
    "75c01f43537a445bb6f0e08686ee88cb":{
      "scriptId":"u55"},
    "a74b281a87a04e1f8fa2b3311b037b9c":{
      "scriptId":"u56"},
    "82b051bdd407481a972c4dad279cc1a9":{
      "scriptId":"u57"},
    "c4a3293eae194bb8b32eaeb22e024d2e":{
      "scriptId":"u58"},
    "7d06d04b3ba54fc18dc31ff17272f179":{
      "scriptId":"u59"},
    "693e4bc411444788a8b17cf56cd3e53c":{
      "scriptId":"u60"},
    "2c160047a59941b8a33a8bbc8aa17a1a":{
      "scriptId":"u61"},
    "eb1234de3d364d1883e995717211f9c4":{
      "scriptId":"u62"},
    "6b8973ea7a144cb79f8965ed6c462971":{
      "scriptId":"u63"},
    "72a3b7da5b1b41f8b1cec9e0791886cd":{
      "scriptId":"u64"},
    "1c9c631bdeda462380b603d6fba1f869":{
      "scriptId":"u65"},
    "fbcc4695578d4706b77e716a284b7190":{
      "scriptId":"u66"},
    "9f48ca8aeb8c4ed191b1a0afab840cbf":{
      "scriptId":"u67"},
    "e9f2afe6c1564684b629b9998d6c1971":{
      "scriptId":"u68"},
    "7b5f3b69c10f4cb7a88059458a004026":{
      "scriptId":"u69"},
    "59346043f9064461aaed154d0fa598ae":{
      "scriptId":"u70"},
    "c74c7a69e0aa483ab0e970029e8382d2":{
      "scriptId":"u71"},
    "2f63c6294f93494aa2aab643ca8b11db":{
      "scriptId":"u72"},
    "121c83d8113646f78d76966d98eecde8":{
      "scriptId":"u73"},
    "f2af0725ebbe44de9c31923d038036a9":{
      "scriptId":"u74"},
    "e0f4c2760c4242d28f99cc429fbf7c2b":{
      "scriptId":"u75"},
    "fc2fb1e7dc4346ef9b8ada32159275f1":{
      "scriptId":"u76"},
    "ccd02384516e4468b1ab65cfca216ec9":{
      "scriptId":"u77"},
    "c628316961234ce7a9ba936b6838dc54":{
      "scriptId":"u78"},
    "037cbe13bdbe461799d7e96b41765f26":{
      "scriptId":"u79"},
    "96923c59a6f948d8a00ca2c90ef0d234":{
      "scriptId":"u80"},
    "712bab4234c542309ba11054afba47bc":{
      "scriptId":"u81"},
    "3536f874712a43e3948f0fda62715d81":{
      "scriptId":"u82"},
    "403f92893b0e4d54bb065019c8872a8c":{
      "scriptId":"u83"},
    "5dd25f3154844bfbb2abf92e25f4724f":{
      "scriptId":"u84"},
    "3cca449782e54217bff74fd78e59c788":{
      "scriptId":"u85"},
    "0cf438136a17443f83f6c67191f4372b":{
      "scriptId":"u86"},
    "d9055e378cac4ce8b3a32c16bb022449":{
      "scriptId":"u87"},
    "4dc904cd786a4948aa949bc868456b51":{
      "scriptId":"u88"},
    "f15054542d224aabbd4c6794601459c0":{
      "scriptId":"u89"},
    "82e1e1ed09db4277898defc8a6c7bdab":{
      "scriptId":"u90"},
    "de487e2f92cb459d85c5dc6c0d52f97c":{
      "scriptId":"u91"},
    "e81472ddc10a4597a508c3ab06b33cb8":{
      "scriptId":"u92"},
    "ae662fcace624ae48c6fe225684232b8":{
      "scriptId":"u93"},
    "52058b7f0b0148878c962deed07f6216":{
      "scriptId":"u94"}}});