$axure.loadCurrentPage({
  "url":"единица_товара.html",
  "generationDate":new Date(1494499901220.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"ea5d834b3d6242afa1a317c99f2a0ecb",
    "type":"Axure:Page",
    "name":"Единица товара",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onClick":{
        "description":"OnClick",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"Open Link in Current Window",
                "target":{
                  "targetType":"page",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"f78baf30ac1b4aa7a172527d44eb32b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":212},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f21c7c0834245c7abab252e023e2c18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":212},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"056c8cffb2084899a35b200eccc5babd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":213},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86c79dbb4d294bc29412169f2bb0cb46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":213},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edf64b0934dd4c8faf3842e91f0c6da5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":215},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"975e157b8b21489b9781684103e674bd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":216},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"a512df98185d49c39b1c3991c8d8631a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":157,
              "y":213},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d3eb26e3eb4ac1874028a29d65e61b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":157,
                  "y":213},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a00cb03d536d4d7db57d5e3130aa9f25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":24,
              "y":312},
            "size":{
              "width":436,
              "height":389}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd54e98cdb0140b8a40d0aaba0593364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":24,
                  "y":312},
                "size":{
                  "width":436,
                  "height":389}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u8.png"}},
{
          "id":"7aaa4284e8be46a8b547a95a7e5009d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":338},
            "size":{
              "width":380,
              "height":233},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"882d8969cd4849c5a028fcc83f43cffb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":338},
                "size":{
                  "width":380,
                  "height":233},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u10.png"}},
{
          "id":"4d686e31e27e48f8bee4b21b5cb41e68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":602},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b2015076afe4360b1abd5cebd5a5ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":602},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u12.png"}},
{
          "id":"f87093b837f441758d59a0b9d73fe0a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":602},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8396dc1a2af840d4a47512730924b3c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":602},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u12.png"}},
{
          "id":"7d7c11d027ee44b8bf54b808fa5822c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":602},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f4480b762924156a79317ea496a5031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":602},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u12.png"}},
{
          "id":"9901474af6e74974beea0daeb4c5f875",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":24,
              "y":619},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccbb1fdd902342f08982a3889f37ebcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":24,
                  "y":619},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee449852248643f7a90b9030130add34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":435,
              "y":619},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f57378906704afab9e9fd44b79170b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":435,
                  "y":619},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6df146462d0a47d48fbfa6efd225dcd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":521,
              "y":263},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28d36bf3c24f40c38278d2327dded1c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":521,
                  "y":263},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfc040714fb64cccaa8614d81236d03e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":347},
            "size":{
              "width":482,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8b6b3fd384e4cd891338f2774c2074a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":521,
                  "y":347},
                "size":{
                  "width":482,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc25f2936b704e41b1139a87a27078f1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":311},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u102_image_sketch.png",
            "disabled~":"images/каталог/u102_disabled.png"}},
{
          "id":"7ded16850ea041d093ff18d91c9caacd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":0,
              "y":1350},
            "size":{
              "width":1001,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09dcd9b1951f4aa6ab5959d8790bc839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":0,
                  "y":1350},
                "size":{
                  "width":1001,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u27.png"}},
{
          "id":"c6f68f7ee6e2434f891fb682adbf72aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":467,
              "y":1224},
            "size":{
              "width":82,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd49c0f2069c407d96b8c6ebb3434546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":467,
                  "y":1224},
                "size":{
                  "width":82,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf52fecac43244d980f558aa581bf07d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":1394},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"353a649bc650415a93a3afce6138b09c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":1394},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u31.png"}},
{
          "id":"a2ae4413856643d89762c353d03019ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":95,
              "y":1504},
            "size":{
              "width":58,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bacbd7ce77a4fd0b1d9132db9ec3ca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":95,
                  "y":1504},
                "size":{
                  "width":58,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"182cf92801284fbb8047d747d5b835f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":1394},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f5d780dd6e8471a995a0d56e5288680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":1394},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u31.png"}},
{
          "id":"32bccc0e92b14ab38c7bae47afd69d94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":338,
              "y":1504},
            "size":{
              "width":58,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6222df37dcc84f83a8f5bd91ce8e8c1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":338,
                  "y":1504},
                "size":{
                  "width":58,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88400fc54f9b40d6bb343dbdfc3be497",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":1395},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b57a22cbc314120bcc442c40b2b5369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":1395},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u31.png"}},
{
          "id":"3b8777752b8d4d97be197f4a202e92fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":583,
              "y":1505},
            "size":{
              "width":58,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a0b611e6e964875b064141719271513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":583,
                  "y":1505},
                "size":{
                  "width":58,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0e2803694334640a874cd4c6de3cc3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":757,
              "y":1394},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbe5a2f83bb44e4e93d2b52f60ef0472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":757,
                  "y":1394},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u31.png"}},
{
          "id":"83c4ca062080410ca0676ccfe8bc1263",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":828,
              "y":1504},
            "size":{
              "width":58,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28cb5201a1a9413f9883480bce936f0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":828,
                  "y":1504},
                "size":{
                  "width":58,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42b68921db40406ba1af2b38b2fe4d91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":0,
              "y":1427},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11fc1a4acaa541b395e47530e29e3af7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":0,
                  "y":1427},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efdf63a412cb489c81ff0da0102848d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":967,
              "y":1426},
            "size":{
              "width":19,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e13a3680a24812946becf5b504f5dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":967,
                  "y":1426},
                "size":{
                  "width":19,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"164f6bb5f72441c3a72ae45ef72e58ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-2,
              "y":1833},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"179112e2d6564a848bff3d5650092566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-2,
                  "y":1833},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"de0d0b9754f048818214c3afca558cea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":1610},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"694bcfd4ed224c3182468fed5c7a82bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":1610},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0d370e6822f4ec094cc4c9737ba7c45",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":1594},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u80_line.png"}},
{
          "id":"bb484753f0824066837a995b72d7ef73",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":406,
              "y":766},
            "size":{
              "width":208,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf441cc4bad4562af3a0d5f893dcc4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":406,
                  "y":766},
                "size":{
                  "width":208,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f62d28a15dde4ae4bcfffb3e2d942668",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":808},
            "size":{
              "width":965,
              "height":459}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd9b201f13124e4499ebdcb9d7392720",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":808},
                "size":{
                  "width":965,
                  "height":459}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u58.png"}},
{
          "id":"9429102f47524899a7bb3480d2325463",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":468,
              "y":1316},
            "size":{
              "width":82,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1c38cb21dd5414b87fdb656a34bf36b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":468,
                  "y":1316},
                "size":{
                  "width":82,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fe1a8e251474ab58336c444381b5c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":522,
              "y":602},
            "size":{
              "width":481,
              "height":100},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03ae16c4b10241db8c9d03092a40cc84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":522,
                  "y":602},
                "size":{
                  "width":481,
                  "height":100},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u62.png"}},
{
          "id":"8208c0e462e24269a21530dd12429cad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":720},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3358efc6ede427b98ab251acdad80a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":720},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u64.png"}},
{
          "id":"4125ba2113444b489ba37059cb832056",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":720},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16a67697094e4927b8791398e55bd28b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":720},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u64.png"}},
{
          "id":"c19db0d503284911b935f8c00b651884",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":720},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0dedbc73ecc46bd85fb20e2d63259b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":720},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u64.png"}},
{
          "id":"fc184f7b18e149219d14dcf8c83daf7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":760},
            "size":{
              "width":176,
              "height":80},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c171333c7e344a695a990071a79ce77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":760},
                "size":{
                  "width":176,
                  "height":80},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/единица_товара/u70.png"}},
{
          "id":"d8658b10067d4c6eaa1bc0d3f6f428ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b777d737bf574ba2b4f3050b3cf76226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"7d7fea999f424b42840f2a463ea1d917",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"584a83e18fdd4b428a05a6dda20dc630",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd8cb7e253b149a0aef51db76f0d0ca7",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8cc7955775164ab4b3dea5d26f74d8a1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"00ceb81db16d4b0ab7a8d66a1eb571b4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"798baf7fbbc64e84a1b7a2692eedcfe0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"7c65355993654d318fa0018e61be11d1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b349ef8f1f3440c786d50691149a6590",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"362eff85b57d482d8adcc4bec2ca69d3",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a38aff2195d467b8650f4e6211259c0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"f56cdc621d6d4e66b213c98a592d532b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99d173ac673e445db9dc93df28f34537",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"badcb0feac4d455e836c5b74ccf2b89c",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d240c22c963448c4a4e0ea807d7f1627",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e14d31e369d42d39c869d5bf6a33198",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f52e2e1644c84a0582859686cabc4023",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"e0ad6d11ed4541419239e94458ff2afa",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"98fd99d25b2343f0869f891cbdb41b64",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"be3ea2440f134dac8c676f487f06e333",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6a7a1898f67f4fc4973d5a7ab5ea4e2b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"4d6ee7cbce0c41eabcb764843ebd467a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e079a47863f4484da174bdcf12611d59",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"28f06af9beab4c9c8a86cf638463c3af",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ca83c3177fa147b2906e001ee030157b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"00ceb81db16d4b0ab7a8d66a1eb571b4"}]},
{
          "id":"5f0f885949d34e16a0e3a73645d9cf4e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"3249f9020d1a4704884a9e955232a24e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"b14858f008e14db1900f43e54f32681d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"b85d5ed500ae470d94ec86ccff6a722b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3167f3d83dd947d6b33a9f50f2f3a685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65608710607e470ab74cf610620c3153",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82460c9989364828adc07353e0f10ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aee03cb4efb740988489a5e4b6a014dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96278d6ed86842a69b37a499d56aaea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"fbe2baca64884b11853313016efd1067",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"293aaf30ea634448a2a95fec64f1b294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"d0c5158072664666b8c59f5fb4ad1b2b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"2c9fc1860fdf4ca6b251e4f5a1064b2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce31a7bbdace435893b090cb582e4de7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f78baf30ac1b4aa7a172527d44eb32b5":{
      "scriptId":"u0"},
    "5f21c7c0834245c7abab252e023e2c18":{
      "scriptId":"u1"},
    "056c8cffb2084899a35b200eccc5babd":{
      "scriptId":"u2"},
    "86c79dbb4d294bc29412169f2bb0cb46":{
      "scriptId":"u3"},
    "edf64b0934dd4c8faf3842e91f0c6da5":{
      "scriptId":"u4"},
    "975e157b8b21489b9781684103e674bd":{
      "scriptId":"u5"},
    "a512df98185d49c39b1c3991c8d8631a":{
      "scriptId":"u6"},
    "91d3eb26e3eb4ac1874028a29d65e61b":{
      "scriptId":"u7"},
    "a00cb03d536d4d7db57d5e3130aa9f25":{
      "scriptId":"u8"},
    "fd54e98cdb0140b8a40d0aaba0593364":{
      "scriptId":"u9"},
    "7aaa4284e8be46a8b547a95a7e5009d4":{
      "scriptId":"u10"},
    "882d8969cd4849c5a028fcc83f43cffb":{
      "scriptId":"u11"},
    "4d686e31e27e48f8bee4b21b5cb41e68":{
      "scriptId":"u12"},
    "1b2015076afe4360b1abd5cebd5a5ebd":{
      "scriptId":"u13"},
    "f87093b837f441758d59a0b9d73fe0a5":{
      "scriptId":"u14"},
    "8396dc1a2af840d4a47512730924b3c7":{
      "scriptId":"u15"},
    "7d7c11d027ee44b8bf54b808fa5822c4":{
      "scriptId":"u16"},
    "9f4480b762924156a79317ea496a5031":{
      "scriptId":"u17"},
    "9901474af6e74974beea0daeb4c5f875":{
      "scriptId":"u18"},
    "ccbb1fdd902342f08982a3889f37ebcf":{
      "scriptId":"u19"},
    "ee449852248643f7a90b9030130add34":{
      "scriptId":"u20"},
    "7f57378906704afab9e9fd44b79170b2":{
      "scriptId":"u21"},
    "6df146462d0a47d48fbfa6efd225dcd0":{
      "scriptId":"u22"},
    "28d36bf3c24f40c38278d2327dded1c3":{
      "scriptId":"u23"},
    "cfc040714fb64cccaa8614d81236d03e":{
      "scriptId":"u24"},
    "c8b6b3fd384e4cd891338f2774c2074a":{
      "scriptId":"u25"},
    "bc25f2936b704e41b1139a87a27078f1":{
      "scriptId":"u26"},
    "7ded16850ea041d093ff18d91c9caacd":{
      "scriptId":"u27"},
    "09dcd9b1951f4aa6ab5959d8790bc839":{
      "scriptId":"u28"},
    "c6f68f7ee6e2434f891fb682adbf72aa":{
      "scriptId":"u29"},
    "cd49c0f2069c407d96b8c6ebb3434546":{
      "scriptId":"u30"},
    "bf52fecac43244d980f558aa581bf07d":{
      "scriptId":"u31"},
    "353a649bc650415a93a3afce6138b09c":{
      "scriptId":"u32"},
    "a2ae4413856643d89762c353d03019ad":{
      "scriptId":"u33"},
    "1bacbd7ce77a4fd0b1d9132db9ec3ca2":{
      "scriptId":"u34"},
    "182cf92801284fbb8047d747d5b835f2":{
      "scriptId":"u35"},
    "0f5d780dd6e8471a995a0d56e5288680":{
      "scriptId":"u36"},
    "32bccc0e92b14ab38c7bae47afd69d94":{
      "scriptId":"u37"},
    "6222df37dcc84f83a8f5bd91ce8e8c1a":{
      "scriptId":"u38"},
    "88400fc54f9b40d6bb343dbdfc3be497":{
      "scriptId":"u39"},
    "9b57a22cbc314120bcc442c40b2b5369":{
      "scriptId":"u40"},
    "3b8777752b8d4d97be197f4a202e92fa":{
      "scriptId":"u41"},
    "0a0b611e6e964875b064141719271513":{
      "scriptId":"u42"},
    "d0e2803694334640a874cd4c6de3cc3b":{
      "scriptId":"u43"},
    "bbe5a2f83bb44e4e93d2b52f60ef0472":{
      "scriptId":"u44"},
    "83c4ca062080410ca0676ccfe8bc1263":{
      "scriptId":"u45"},
    "28cb5201a1a9413f9883480bce936f0e":{
      "scriptId":"u46"},
    "42b68921db40406ba1af2b38b2fe4d91":{
      "scriptId":"u47"},
    "11fc1a4acaa541b395e47530e29e3af7":{
      "scriptId":"u48"},
    "efdf63a412cb489c81ff0da0102848d3":{
      "scriptId":"u49"},
    "28e13a3680a24812946becf5b504f5dc":{
      "scriptId":"u50"},
    "164f6bb5f72441c3a72ae45ef72e58ed":{
      "scriptId":"u51"},
    "179112e2d6564a848bff3d5650092566":{
      "scriptId":"u52"},
    "de0d0b9754f048818214c3afca558cea":{
      "scriptId":"u53"},
    "694bcfd4ed224c3182468fed5c7a82bd":{
      "scriptId":"u54"},
    "e0d370e6822f4ec094cc4c9737ba7c45":{
      "scriptId":"u55"},
    "bb484753f0824066837a995b72d7ef73":{
      "scriptId":"u56"},
    "7cf441cc4bad4562af3a0d5f893dcc4d":{
      "scriptId":"u57"},
    "f62d28a15dde4ae4bcfffb3e2d942668":{
      "scriptId":"u58"},
    "bd9b201f13124e4499ebdcb9d7392720":{
      "scriptId":"u59"},
    "9429102f47524899a7bb3480d2325463":{
      "scriptId":"u60"},
    "f1c38cb21dd5414b87fdb656a34bf36b":{
      "scriptId":"u61"},
    "6fe1a8e251474ab58336c444381b5c92":{
      "scriptId":"u62"},
    "03ae16c4b10241db8c9d03092a40cc84":{
      "scriptId":"u63"},
    "8208c0e462e24269a21530dd12429cad":{
      "scriptId":"u64"},
    "b3358efc6ede427b98ab251acdad80a8":{
      "scriptId":"u65"},
    "4125ba2113444b489ba37059cb832056":{
      "scriptId":"u66"},
    "16a67697094e4927b8791398e55bd28b":{
      "scriptId":"u67"},
    "c19db0d503284911b935f8c00b651884":{
      "scriptId":"u68"},
    "e0dedbc73ecc46bd85fb20e2d63259b6":{
      "scriptId":"u69"},
    "fc184f7b18e149219d14dcf8c83daf7f":{
      "scriptId":"u70"},
    "0c171333c7e344a695a990071a79ce77":{
      "scriptId":"u71"},
    "d8658b10067d4c6eaa1bc0d3f6f428ae":{
      "scriptId":"u72"},
    "b777d737bf574ba2b4f3050b3cf76226":{
      "scriptId":"u73"},
    "7d7fea999f424b42840f2a463ea1d917":{
      "scriptId":"u74"},
    "584a83e18fdd4b428a05a6dda20dc630":{
      "scriptId":"u75"},
    "dd8cb7e253b149a0aef51db76f0d0ca7":{
      "scriptId":"u76"},
    "8cc7955775164ab4b3dea5d26f74d8a1":{
      "scriptId":"u77"},
    "00ceb81db16d4b0ab7a8d66a1eb571b4":{
      "scriptId":"u78"},
    "798baf7fbbc64e84a1b7a2692eedcfe0":{
      "scriptId":"u79"},
    "362eff85b57d482d8adcc4bec2ca69d3":{
      "scriptId":"u80"},
    "6a38aff2195d467b8650f4e6211259c0":{
      "scriptId":"u81"},
    "f56cdc621d6d4e66b213c98a592d532b":{
      "scriptId":"u82"},
    "99d173ac673e445db9dc93df28f34537":{
      "scriptId":"u83"},
    "7c65355993654d318fa0018e61be11d1":{
      "scriptId":"u84"},
    "b349ef8f1f3440c786d50691149a6590":{
      "scriptId":"u85"},
    "badcb0feac4d455e836c5b74ccf2b89c":{
      "scriptId":"u86"},
    "d240c22c963448c4a4e0ea807d7f1627":{
      "scriptId":"u87"},
    "2e14d31e369d42d39c869d5bf6a33198":{
      "scriptId":"u88"},
    "f52e2e1644c84a0582859686cabc4023":{
      "scriptId":"u89"},
    "be3ea2440f134dac8c676f487f06e333":{
      "scriptId":"u90"},
    "6a7a1898f67f4fc4973d5a7ab5ea4e2b":{
      "scriptId":"u91"},
    "4d6ee7cbce0c41eabcb764843ebd467a":{
      "scriptId":"u92"},
    "e079a47863f4484da174bdcf12611d59":{
      "scriptId":"u93"},
    "e0ad6d11ed4541419239e94458ff2afa":{
      "scriptId":"u94"},
    "98fd99d25b2343f0869f891cbdb41b64":{
      "scriptId":"u95"},
    "28f06af9beab4c9c8a86cf638463c3af":{
      "scriptId":"u96"},
    "ca83c3177fa147b2906e001ee030157b":{
      "scriptId":"u97"},
    "5f0f885949d34e16a0e3a73645d9cf4e":{
      "scriptId":"u98"},
    "3249f9020d1a4704884a9e955232a24e":{
      "scriptId":"u99"},
    "b14858f008e14db1900f43e54f32681d":{
      "scriptId":"u100"},
    "b85d5ed500ae470d94ec86ccff6a722b":{
      "scriptId":"u101"},
    "3167f3d83dd947d6b33a9f50f2f3a685":{
      "scriptId":"u102"},
    "65608710607e470ab74cf610620c3153":{
      "scriptId":"u103"},
    "82460c9989364828adc07353e0f10ab2":{
      "scriptId":"u104"},
    "aee03cb4efb740988489a5e4b6a014dc":{
      "scriptId":"u105"},
    "96278d6ed86842a69b37a499d56aaea3":{
      "scriptId":"u106"},
    "fbe2baca64884b11853313016efd1067":{
      "scriptId":"u107"},
    "293aaf30ea634448a2a95fec64f1b294":{
      "scriptId":"u108"},
    "d0c5158072664666b8c59f5fb4ad1b2b":{
      "scriptId":"u109"},
    "2c9fc1860fdf4ca6b251e4f5a1064b2e":{
      "scriptId":"u110"},
    "ce31a7bbdace435893b090cb582e4de7":{
      "scriptId":"u111"}}});