$axure.loadCurrentPage({
  "url":"мои_заказы.html",
  "generationDate":new Date(1493889321742.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ab9b49e70194321a77c8fc2e85e1e5a",
    "type":"Axure:Page",
    "name":"Мои заказы",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6061da75d6a74f4abb886803f1ca2db9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":155},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17fffdd7f16d4f56a1f3279746698e00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":155},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1044d57cd34428197e22f9ebc3c344a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":155},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52efdf6c02dc4e7caa4ad694ed82df54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":155},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1866d41316d74e1c8600d997b7f2d7d5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":158},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"a4de3aaca3fa47feaf7f8ec110be1b2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02c51c2d3fe344a2b657c8f46f0f3504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":0},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"f948d38c236e4ecfa0763f361e4d0e50",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"163f37ce01164be0b385a07ce4664d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c003139780443c48a3884d3e7f3c822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a17f8f150e34b65b770d975249db6ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feab8618b0ff4ed7afc019f933e545ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"be99a4a1d5e44bec8cef03dc1344d8c6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"69fd0aaaef7040ba98efdf1a88f933dd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"c684addcb2b547758907e882ccec2557",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":252,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1b3d07a2b0a4102824eb124865215c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":252,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"538c6665c57547f38ccfdc6c8bab3229",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d81b293d43074108bbfec2755dd18344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66685748111144bd9438975a0d8ff41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":641,
              "y":34},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880629bf41db49c3b59acd207ec41617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":641,
                  "y":34},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85c3f7412e7547d1bf34ccc208a4361b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":4},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351f8c95cecc413f8f7f0e286ad7aa45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":4},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc6bb2b2b65a4effbf9dfe3df4553df5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e58d3eb5f3145af9d94ad70a550ae56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":916,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u17.png"}},
{
          "id":"5ed13d4b209b459fb4b8bb4f4c86e0f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a37d43c01431446fb41f34b06657f402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u19.png"}},
{
          "id":"f0ed47a7448e43d78e7e4b72ff989abe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2bf93aed77747e7a0d7479d397505c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u21.png"}},
{
          "id":"83ea71062bff43be97d10417db7ec287",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":642,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38ff3a2d067e41d091977a001d0acc17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":642,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8d480200db6481db84f53b37c4f9784",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":66},
            "size":{
              "width":500,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5de42fc0710545919b401981f400e041",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e03afe65ecf4addba24e3d852942693",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a924e5a4740f43239123f04c7332ddf7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"935fb21b591d47ab8b2cc60a5f6d50fc",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91ebcbf3852b45df9c777b14796deb52",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"5a3e82253ce6410687e9122eb0afe71f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73c40d2885764e299250da9eaf146ee3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u104.png"}},
{
                  "id":"97efab115d8f46ba80b2f632215c9e68",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11815b38bb5c4033b485a7be8c7735e3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"dcb712e19554427197c9b999ace1e591",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b32fee6adcde46558904d0dc02baf7ae",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}}]},
{
              "id":"16cdf99459a447fc98535460169f5aad",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d350bf9822243abbb27a7979958c652",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88bbf4846ff24e62b086fc15cac31f09",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"44c062a486bc4303a75c4a85dec86213",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"8ba1af58bbce4598947a0ecffd9fd097",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"629d55d744c44a1caa312ae9db2026cc",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"37a6a78243594961a4ebac7b5fe5e374",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8bea6d0749c84c51b521d26b2f1d9db1",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"29213c826eb64e579b269f6ea54f2425",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9b47afb691644fc6b61ca89c48ac8e7b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u126.png"}},
{
                      "id":"2cff7d2b04284efc8197027611ab844d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"37e41383ea0247638aec775c96ce3137",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"e07202e356624a4da529719f98ab829b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3dd92d88167a46be9d3d9c2e42317441",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"2ebae8fe23fc4347aaba5a453b521d41",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ae07699498a346818c188726f644f7dd",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"a7cae5a65f304d3ebc6c3d5191eee535",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c8875178232a44a2892ae552d9151d2d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"6cf0177243784e32b31ab3e9796cb47c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a3732049ace84c76931daf15337eb301",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"267b644c2aa643d7aa4388ebaf26c271",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a5741c48a43a4a6cb82eea296fe14719",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}}]}],
              "parentCellId":"935fb21b591d47ab8b2cc60a5f6d50fc"}]},
{
          "id":"eb904d8f448d4690a70863009bc39a94",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":406,
              "y":220},
            "size":{
              "width":187,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02bd5d5dd52444648dec34845eda9e7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":406,
                  "y":220},
                "size":{
                  "width":187,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3eacacdcf10474c94d6ec67d4a7cd14",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":305},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"060c7bb4d569448dbfe3c01db5ed921e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":99,
              "y":289},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d1fafdd5134ba0a1473bedb436d502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":99,
                  "y":289},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a2251d2e0a94b1db4a4d7bc85c2d6e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":307},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c1866d1ae994b62a959e72fc8b24724",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":307},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/мои_заказы/u69.png"}},
{
          "id":"b41f0ee14ada4d219fdd9b28bdd53676",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":307},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1439f51ea9b3461c90626846fa41fe79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":24,
              "y":370},
            "size":{
              "width":976,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e52d5d01fbcb4d15983a7e771034dbfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":24,
                  "y":370},
                "size":{
                  "width":976,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/мои_заказы/u72.png"}},
{
          "id":"d57209b1567d43da8e7de56178dc3a85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":32,
              "y":420},
            "size":{
              "width":201,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6d679d51d974a61a282272891e3e95e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":32,
                  "y":420},
                "size":{
                  "width":201,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"290c49635dd7402fbde397953a2184fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":454},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43f3ba2b7f79476fa0d3643021302638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":454},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50f0befd52db4d8092efcb5ae99d2fce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":205,
              "y":454},
            "size":{
              "width":34,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe6a466b52be4f7e99b41458f78594f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":205,
                  "y":454},
                "size":{
                  "width":34,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80c50c16f45c43c8909d549cc8d52fa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":316,
              "y":454},
            "size":{
              "width":55,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b9ae36325e47049f52e999c24c98fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":316,
                  "y":454},
                "size":{
                  "width":55,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46cf2895c7834d6388ccd2a45852bb71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":449,
              "y":454},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d77e3546d51425e8db881425f7ecfb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":449,
                  "y":454},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9828436b9c0f40a8a2c3144e0c1f9385",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":483},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e8c3109ad0049e2b00bf2052580a88c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":483},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe222f37e7a04b3ab358df3168884a6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":205,
              "y":483},
            "size":{
              "width":34,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"120fa969a71b403e959aeb6699132158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":205,
                  "y":483},
                "size":{
                  "width":34,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adf3a57848ac4a60bb3e673e7190e07e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":316,
              "y":483},
            "size":{
              "width":55,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef0c4e4031504225a093298bab6f0155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":316,
                  "y":483},
                "size":{
                  "width":55,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"313ff694b6d04cbe8d186032795155c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":449,
              "y":483},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e70f9c45214aa2946153e32b494c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":449,
                  "y":483},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa8a47f44cf9438aa0637b2af04b092b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":512},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1240639e830e41f3bad153892b279420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":512},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e88c053b5a6648d5abebc8b873303106",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":205,
              "y":512},
            "size":{
              "width":34,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f581f96dfd4f4c4092415ebd5e778175",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":205,
                  "y":512},
                "size":{
                  "width":34,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14a09c29a5fa4960911d46e1f615d9e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":316,
              "y":512},
            "size":{
              "width":55,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ce6e10836044dfbe236f13f575fcb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":316,
                  "y":512},
                "size":{
                  "width":55,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2198099484ef458dabe2500570583920",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":449,
              "y":512},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c89693a652cf42cb8b9c19f3099494e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":449,
                  "y":512},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f20220b6d4d4bc1ac637da7c40909de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":23,
              "y":570},
            "size":{
              "width":976,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94ad0fcc30bd4332994ccdc7b39efd4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":23,
                  "y":570},
                "size":{
                  "width":976,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/мои_заказы/u72.png"}},
{
          "id":"94e2c379588842439719756a1d7366bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":31,
              "y":620},
            "size":{
              "width":201,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b4bc14fa7d41478f45680f33529085",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":31,
                  "y":620},
                "size":{
                  "width":201,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bb251ec661f487bab423e2beffe1ae6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":59,
              "y":654},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f5b486a3b5c4db9a97b469568f4083b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":59,
                  "y":654},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1853900c5e2b4089b11b525ab95b885c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":204,
              "y":654},
            "size":{
              "width":34,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd93f818637f435080d82e48c3ed23fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":204,
                  "y":654},
                "size":{
                  "width":34,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ced2358f520d4fd7a6c0c23b8bbed6b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":315,
              "y":654},
            "size":{
              "width":55,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f99bfd1f4dc440b0a068659628e4a70c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":315,
                  "y":654},
                "size":{
                  "width":55,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ccc561f4b074a5da855b589e8151744",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":448,
              "y":654},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba2a15d6bb3a446994e14a2da1ef21e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":448,
                  "y":654},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8a50034feff4a30b6695e8f254ca70a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":59,
              "y":683},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba2edfab341400d884927df098c889f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":59,
                  "y":683},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e92afcf5abec402081e458e5e288b5b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":204,
              "y":683},
            "size":{
              "width":34,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39ac15036144e47a95f273b6e4ea1f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":204,
                  "y":683},
                "size":{
                  "width":34,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07042ff0235147dca3a5e4b7772432c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":315,
              "y":683},
            "size":{
              "width":55,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5d04137d0845a783511739f499ccaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":315,
                  "y":683},
                "size":{
                  "width":55,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99731ff9ef3c45e6a8d3c2f03ce9fecf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":448,
              "y":683},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a5291b490dc418590059cea797e00dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":448,
                  "y":683},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a72202aa59224bf188211f996404c4be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":59,
              "y":712},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff398470625f48b08dcfca7d24d8a71c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":59,
                  "y":712},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9f99af3de2a49499bead060868037f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":204,
              "y":712},
            "size":{
              "width":34,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a2ebd51d6247529b758b9d26e391a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":204,
                  "y":712},
                "size":{
                  "width":34,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aea4aaf44694ad2a9cf7dda166ec10e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":315,
              "y":712},
            "size":{
              "width":55,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33e6ca284ca740b3b59a899510c1ba19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":315,
                  "y":712},
                "size":{
                  "width":55,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"912b22e138084e75bc1ed956f0296065",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":448,
              "y":712},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd63cbadc66a43aeb1e26d127fa24840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":448,
                  "y":712},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c174a2e6b0c463da9aab02b78af9779",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":-1,
              "y":772},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f084e7a3e14a619e2cd620d39a6b75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":-1,
                  "y":772},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u33.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6061da75d6a74f4abb886803f1ca2db9":{
      "scriptId":"u0"},
    "17fffdd7f16d4f56a1f3279746698e00":{
      "scriptId":"u1"},
    "e1044d57cd34428197e22f9ebc3c344a":{
      "scriptId":"u2"},
    "52efdf6c02dc4e7caa4ad694ed82df54":{
      "scriptId":"u3"},
    "1866d41316d74e1c8600d997b7f2d7d5":{
      "scriptId":"u4"},
    "a4de3aaca3fa47feaf7f8ec110be1b2f":{
      "scriptId":"u5"},
    "02c51c2d3fe344a2b657c8f46f0f3504":{
      "scriptId":"u6"},
    "f948d38c236e4ecfa0763f361e4d0e50":{
      "scriptId":"u7"},
    "163f37ce01164be0b385a07ce4664d83":{
      "scriptId":"u8"},
    "2c003139780443c48a3884d3e7f3c822":{
      "scriptId":"u9"},
    "3a17f8f150e34b65b770d975249db6ff":{
      "scriptId":"u10"},
    "feab8618b0ff4ed7afc019f933e545ac":{
      "scriptId":"u11"},
    "be99a4a1d5e44bec8cef03dc1344d8c6":{
      "scriptId":"u12"},
    "69fd0aaaef7040ba98efdf1a88f933dd":{
      "scriptId":"u13"},
    "c684addcb2b547758907e882ccec2557":{
      "scriptId":"u14"},
    "f1b3d07a2b0a4102824eb124865215c5":{
      "scriptId":"u15"},
    "538c6665c57547f38ccfdc6c8bab3229":{
      "scriptId":"u16"},
    "d81b293d43074108bbfec2755dd18344":{
      "scriptId":"u17"},
    "66685748111144bd9438975a0d8ff41d":{
      "scriptId":"u18"},
    "880629bf41db49c3b59acd207ec41617":{
      "scriptId":"u19"},
    "85c3f7412e7547d1bf34ccc208a4361b":{
      "scriptId":"u20"},
    "351f8c95cecc413f8f7f0e286ad7aa45":{
      "scriptId":"u21"},
    "bc6bb2b2b65a4effbf9dfe3df4553df5":{
      "scriptId":"u22"},
    "8e58d3eb5f3145af9d94ad70a550ae56":{
      "scriptId":"u23"},
    "5ed13d4b209b459fb4b8bb4f4c86e0f3":{
      "scriptId":"u24"},
    "a37d43c01431446fb41f34b06657f402":{
      "scriptId":"u25"},
    "f0ed47a7448e43d78e7e4b72ff989abe":{
      "scriptId":"u26"},
    "d2bf93aed77747e7a0d7479d397505c4":{
      "scriptId":"u27"},
    "83ea71062bff43be97d10417db7ec287":{
      "scriptId":"u28"},
    "38ff3a2d067e41d091977a001d0acc17":{
      "scriptId":"u29"},
    "b8d480200db6481db84f53b37c4f9784":{
      "scriptId":"u30"},
    "5de42fc0710545919b401981f400e041":{
      "scriptId":"u31"},
    "6e03afe65ecf4addba24e3d852942693":{
      "scriptId":"u32"},
    "a924e5a4740f43239123f04c7332ddf7":{
      "scriptId":"u33"},
    "935fb21b591d47ab8b2cc60a5f6d50fc":{
      "scriptId":"u34"},
    "91ebcbf3852b45df9c777b14796deb52":{
      "scriptId":"u35"},
    "dcb712e19554427197c9b999ace1e591":{
      "scriptId":"u36"},
    "b32fee6adcde46558904d0dc02baf7ae":{
      "scriptId":"u37"},
    "97efab115d8f46ba80b2f632215c9e68":{
      "scriptId":"u38"},
    "11815b38bb5c4033b485a7be8c7735e3":{
      "scriptId":"u39"},
    "5a3e82253ce6410687e9122eb0afe71f":{
      "scriptId":"u40"},
    "73c40d2885764e299250da9eaf146ee3":{
      "scriptId":"u41"},
    "16cdf99459a447fc98535460169f5aad":{
      "scriptId":"u42"},
    "6d350bf9822243abbb27a7979958c652":{
      "scriptId":"u43"},
    "88bbf4846ff24e62b086fc15cac31f09":{
      "scriptId":"u44"},
    "44c062a486bc4303a75c4a85dec86213":{
      "scriptId":"u45"},
    "8ba1af58bbce4598947a0ecffd9fd097":{
      "scriptId":"u46"},
    "629d55d744c44a1caa312ae9db2026cc":{
      "scriptId":"u47"},
    "37a6a78243594961a4ebac7b5fe5e374":{
      "scriptId":"u48"},
    "8bea6d0749c84c51b521d26b2f1d9db1":{
      "scriptId":"u49"},
    "2ebae8fe23fc4347aaba5a453b521d41":{
      "scriptId":"u50"},
    "ae07699498a346818c188726f644f7dd":{
      "scriptId":"u51"},
    "e07202e356624a4da529719f98ab829b":{
      "scriptId":"u52"},
    "3dd92d88167a46be9d3d9c2e42317441":{
      "scriptId":"u53"},
    "2cff7d2b04284efc8197027611ab844d":{
      "scriptId":"u54"},
    "37e41383ea0247638aec775c96ce3137":{
      "scriptId":"u55"},
    "267b644c2aa643d7aa4388ebaf26c271":{
      "scriptId":"u56"},
    "a5741c48a43a4a6cb82eea296fe14719":{
      "scriptId":"u57"},
    "6cf0177243784e32b31ab3e9796cb47c":{
      "scriptId":"u58"},
    "a3732049ace84c76931daf15337eb301":{
      "scriptId":"u59"},
    "a7cae5a65f304d3ebc6c3d5191eee535":{
      "scriptId":"u60"},
    "c8875178232a44a2892ae552d9151d2d":{
      "scriptId":"u61"},
    "29213c826eb64e579b269f6ea54f2425":{
      "scriptId":"u62"},
    "9b47afb691644fc6b61ca89c48ac8e7b":{
      "scriptId":"u63"},
    "eb904d8f448d4690a70863009bc39a94":{
      "scriptId":"u64"},
    "02bd5d5dd52444648dec34845eda9e7a":{
      "scriptId":"u65"},
    "d3eacacdcf10474c94d6ec67d4a7cd14":{
      "scriptId":"u66"},
    "060c7bb4d569448dbfe3c01db5ed921e":{
      "scriptId":"u67"},
    "96d1fafdd5134ba0a1473bedb436d502":{
      "scriptId":"u68"},
    "3a2251d2e0a94b1db4a4d7bc85c2d6e6":{
      "scriptId":"u69"},
    "7c1866d1ae994b62a959e72fc8b24724":{
      "scriptId":"u70"},
    "b41f0ee14ada4d219fdd9b28bdd53676":{
      "scriptId":"u71"},
    "1439f51ea9b3461c90626846fa41fe79":{
      "scriptId":"u72"},
    "e52d5d01fbcb4d15983a7e771034dbfe":{
      "scriptId":"u73"},
    "d57209b1567d43da8e7de56178dc3a85":{
      "scriptId":"u74"},
    "d6d679d51d974a61a282272891e3e95e":{
      "scriptId":"u75"},
    "290c49635dd7402fbde397953a2184fb":{
      "scriptId":"u76"},
    "43f3ba2b7f79476fa0d3643021302638":{
      "scriptId":"u77"},
    "50f0befd52db4d8092efcb5ae99d2fce":{
      "scriptId":"u78"},
    "fe6a466b52be4f7e99b41458f78594f7":{
      "scriptId":"u79"},
    "80c50c16f45c43c8909d549cc8d52fa5":{
      "scriptId":"u80"},
    "58b9ae36325e47049f52e999c24c98fc":{
      "scriptId":"u81"},
    "46cf2895c7834d6388ccd2a45852bb71":{
      "scriptId":"u82"},
    "4d77e3546d51425e8db881425f7ecfb0":{
      "scriptId":"u83"},
    "9828436b9c0f40a8a2c3144e0c1f9385":{
      "scriptId":"u84"},
    "0e8c3109ad0049e2b00bf2052580a88c":{
      "scriptId":"u85"},
    "fe222f37e7a04b3ab358df3168884a6e":{
      "scriptId":"u86"},
    "120fa969a71b403e959aeb6699132158":{
      "scriptId":"u87"},
    "adf3a57848ac4a60bb3e673e7190e07e":{
      "scriptId":"u88"},
    "ef0c4e4031504225a093298bab6f0155":{
      "scriptId":"u89"},
    "313ff694b6d04cbe8d186032795155c8":{
      "scriptId":"u90"},
    "58e70f9c45214aa2946153e32b494c0d":{
      "scriptId":"u91"},
    "fa8a47f44cf9438aa0637b2af04b092b":{
      "scriptId":"u92"},
    "1240639e830e41f3bad153892b279420":{
      "scriptId":"u93"},
    "e88c053b5a6648d5abebc8b873303106":{
      "scriptId":"u94"},
    "f581f96dfd4f4c4092415ebd5e778175":{
      "scriptId":"u95"},
    "14a09c29a5fa4960911d46e1f615d9e8":{
      "scriptId":"u96"},
    "40ce6e10836044dfbe236f13f575fcb4":{
      "scriptId":"u97"},
    "2198099484ef458dabe2500570583920":{
      "scriptId":"u98"},
    "c89693a652cf42cb8b9c19f3099494e5":{
      "scriptId":"u99"},
    "8f20220b6d4d4bc1ac637da7c40909de":{
      "scriptId":"u100"},
    "94ad0fcc30bd4332994ccdc7b39efd4d":{
      "scriptId":"u101"},
    "94e2c379588842439719756a1d7366bc":{
      "scriptId":"u102"},
    "20b4bc14fa7d41478f45680f33529085":{
      "scriptId":"u103"},
    "2bb251ec661f487bab423e2beffe1ae6":{
      "scriptId":"u104"},
    "0f5b486a3b5c4db9a97b469568f4083b":{
      "scriptId":"u105"},
    "1853900c5e2b4089b11b525ab95b885c":{
      "scriptId":"u106"},
    "cd93f818637f435080d82e48c3ed23fd":{
      "scriptId":"u107"},
    "ced2358f520d4fd7a6c0c23b8bbed6b3":{
      "scriptId":"u108"},
    "f99bfd1f4dc440b0a068659628e4a70c":{
      "scriptId":"u109"},
    "0ccc561f4b074a5da855b589e8151744":{
      "scriptId":"u110"},
    "ba2a15d6bb3a446994e14a2da1ef21e8":{
      "scriptId":"u111"},
    "e8a50034feff4a30b6695e8f254ca70a":{
      "scriptId":"u112"},
    "fba2edfab341400d884927df098c889f":{
      "scriptId":"u113"},
    "e92afcf5abec402081e458e5e288b5b0":{
      "scriptId":"u114"},
    "f39ac15036144e47a95f273b6e4ea1f3":{
      "scriptId":"u115"},
    "07042ff0235147dca3a5e4b7772432c5":{
      "scriptId":"u116"},
    "bc5d04137d0845a783511739f499ccaf":{
      "scriptId":"u117"},
    "99731ff9ef3c45e6a8d3c2f03ce9fecf":{
      "scriptId":"u118"},
    "9a5291b490dc418590059cea797e00dd":{
      "scriptId":"u119"},
    "a72202aa59224bf188211f996404c4be":{
      "scriptId":"u120"},
    "ff398470625f48b08dcfca7d24d8a71c":{
      "scriptId":"u121"},
    "c9f99af3de2a49499bead060868037f7":{
      "scriptId":"u122"},
    "f4a2ebd51d6247529b758b9d26e391a7":{
      "scriptId":"u123"},
    "6aea4aaf44694ad2a9cf7dda166ec10e":{
      "scriptId":"u124"},
    "33e6ca284ca740b3b59a899510c1ba19":{
      "scriptId":"u125"},
    "912b22e138084e75bc1ed956f0296065":{
      "scriptId":"u126"},
    "dd63cbadc66a43aeb1e26d127fa24840":{
      "scriptId":"u127"},
    "1c174a2e6b0c463da9aab02b78af9779":{
      "scriptId":"u128"},
    "22f084e7a3e14a619e2cd620d39a6b75":{
      "scriptId":"u129"}}});