$axure.loadCurrentPage({
  "url":"специалистам.html",
  "generationDate":new Date(1493281618797.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"c8209db1125a42bb8c8f884d6ca6f026",
    "type":"Axure:Page",
    "name":"Специалистам",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7e2b6d4c888f43bdb2800f8a8b40db61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":213},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00720508ad70419f9a1b4b5d3fe20249",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":213},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87e4fa696c9b4144b6d3460783f30d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":214},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d50b3da6f16842969572cb7afdcd30cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":214},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a937e9a4cd51495a901d05b487efac0c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":216},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"e0b729d457a342a986ff2a8a2fc533a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":354},
            "size":{
              "width":296,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"739e9075da254936b069fe503ba065f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":354},
                "size":{
                  "width":296,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/специалистам/u5.png"}},
{
          "id":"4f5fa549bb40455abd380c1b3c385160",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":818,
              "y":256},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f162db318804f4cb80d4caf22a00acd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":818,
                  "y":256},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/специалистам/u7.png"}},
{
          "id":"416803793b634880a0790699b7408782",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":856,
              "y":264},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3e3977c2db45e29e6a74f0b4323fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":856,
                  "y":264},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1aa3991a90b40728dbe6bb20397b7ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":363,
              "y":353},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8170d1acf8c74ec4a717b6ef0971d336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":363,
                  "y":353},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86cd936b833b45dcbae71bb896f830a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":365,
              "y":382},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d729c0402ee4178ae0ddc0dc091aee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":365,
                  "y":382},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"540dc723182d481498567fd152a67d5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":408},
            "size":{
              "width":619,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3ec3a2a165f4e1682aa06606c735c4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":408},
                "size":{
                  "width":619,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16799d563f424a3ea1de4b22d16fd1d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":910,
              "y":528},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eebab7d201a34e5590e3f5808e671a3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":910,
                  "y":528},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8349ebec9e5043f2a60e7b5af0431b90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":593},
            "size":{
              "width":296,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c52d780e0524103916ec195b4ffba12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":593},
                "size":{
                  "width":296,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/специалистам/u5.png"}},
{
          "id":"fb57d72238b3402a803087068f7f37b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":363,
              "y":592},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28c836c71ec24573941c0410d667f799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":363,
                  "y":592},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95afdb67e1cc4e9bb8f378fe4679d772",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":365,
              "y":621},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f1b526a77dc49aea1048a82718ec87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":365,
                  "y":621},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74f318316b954631a359aeda0c255ef8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":647},
            "size":{
              "width":619,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e25489ea9ea40128dd50319d12bf740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":647},
                "size":{
                  "width":619,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61a7c382a10a40c2b2af3284daa9e000",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":910,
              "y":767},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c022cb6813214a9287b8a57370796fa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":910,
                  "y":767},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eb1e79110cd4dc3a827bf768ec8386c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":833},
            "size":{
              "width":296,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf39269f566a41ce998945d30cfea056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":833},
                "size":{
                  "width":296,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/специалистам/u5.png"}},
{
          "id":"3bf3dd8c587547b58804e7e2bba8ff34",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":363,
              "y":832},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a91227f1d14531824b67743ddf4c46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":363,
                  "y":832},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cbdb4599ac44765aabf7e6ceabdf8ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":365,
              "y":861},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"651f7d0b3bb44726a9e45a0687f37de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":365,
                  "y":861},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57123f39b209473a86b6e644353c2cb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":887},
            "size":{
              "width":619,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e4cd69ce5e346ffb5375d30041ce0fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":887},
                "size":{
                  "width":619,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d5f4b9556d34fb1897f58a09926bad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":910,
              "y":1007},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b12e40d2d804145b25063da14e89128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":910,
                  "y":1007},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59898816bcd54fa9a08d8d34ade75046",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":1073},
            "size":{
              "width":296,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf659aad947f4ed498db39e1fc92f52d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":1073},
                "size":{
                  "width":296,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/специалистам/u5.png"}},
{
          "id":"03a184ae2309456c97397a75f09791a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":363,
              "y":1072},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c474024fd1d46c488fbe09b5af477a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":363,
                  "y":1072},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"874ea2f1367940ef99dc2a395114d435",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":365,
              "y":1101},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac9c06b51664172a46356745bad5e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":365,
                  "y":1101},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32f4cc5d6ff34e1d9a1b1e158acd42e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":1127},
            "size":{
              "width":619,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbb239bcd6ad41a68066df8b08d9a0e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":1127},
                "size":{
                  "width":619,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49568c1e1f8d4c07bf3794ddedad2527",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":910,
              "y":1247},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b6d9fe879541fd9ae0be9611da390d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":910,
                  "y":1247},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"015d4fbe988e4838b5c6ee87aaf1fa45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":1313},
            "size":{
              "width":296,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d9fce0efeed41cf8b81ec78fc43c049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":1313},
                "size":{
                  "width":296,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/специалистам/u5.png"}},
{
          "id":"be9400d8786f45149945e12fffd3c839",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":363,
              "y":1312},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b870262b20e46e6bb34897ffede73aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":363,
                  "y":1312},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"207f21e9f0b940868ad4dad55f1ba33b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":365,
              "y":1341},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a4511c1de96433cbf8e749681b25d5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":365,
                  "y":1341},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ae3eae5f8814a8f959f8d4ff1d19e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":1367},
            "size":{
              "width":619,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83d02ca6c3834a3d924c72f2a15101fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":1367},
                "size":{
                  "width":619,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d78f81924c674941a12d88865eb1aba4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":910,
              "y":1487},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b16582629364fb4ad99aff935091ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":910,
                  "y":1487},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39a3c96bd70e4ef3a66b26ce743398c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":380,
              "y":1552},
            "size":{
              "width":241,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5841af9c6cda4f309484972539c05825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":380,
                  "y":1552},
                "size":{
                  "width":241,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98c7e068e2cc4ad9b93b2bb39bd91c8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-4,
              "y":1861},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62ac6bf6807479197b42963437e1856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-4,
                  "y":1861},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"a35ccc64ad56405da669a1fedbb232f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1638},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96a0b8487584498798d344794dd02c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1638},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"235a89621a854c089d4245e3a198d129",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1622},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u89_line.png"}},
{
          "id":"5c9b8a43464647c09edfb9f97dfcf783",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6c564f44bb4918b6d76d8f94d033c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"4c1913f9c93d4463b818d6dd4d48628e",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":146},
            "size":{
              "width":700,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"632a751766484ab1b602e3a632343628",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":700,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92fe3b95c91c4bb383c27ea3e7b057bf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f24a60fe9c6e423ea561e4e7a39a396b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"833e1e5525894c77a7fc7001543f9216",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b9a3323e0284cebb37a8fdf4b53683f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"1e433b9db85a44ad872b14161bae9500",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":614,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae9c85130ffe49128125280c102cfb80",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":614,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u47.png"}},
{
                  "id":"6f245d36cacf48b8bbeec9a616e7ddf9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e787d4ea669b4ae8a931f30b0f14f02a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"5a4ee3d0678847948df8e6bf2251356a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":514,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1698e637a026456cad8dc1b97c0b89f5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":514,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"2b9467b94f70484ea959b6ecd6c888af",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4fa7688a518b43b98da1a76574cb0c30",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"203426c9ac174204887fcb5711482325",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b93dbefebe1e4ae3a86d5453e19fd27d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"af2c2677f3dc4bc5b225b6a77e6bd893",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"576d8ef9e40645c882f6e9bcd55b9e63",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"49ab78588c6342978296eca89f271879",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"849207ef97214b5cac233bb34808b4a7",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"b66af7183602492ab6c6d41260dd6063",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4e7dae18496d4f048cfe3d503298a5e8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"a77eddaba9954b3faf0c70476e6bbf6d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f26b2bc73ab4473dba52c5d7b2af35ed",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"07da577cf0c143cdb7bca69957fa7324",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f09a2dfcb6544e808241ac7f294eb7be",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}},
{
                      "id":"db8600306c0a4a7aa653dd661099cca2",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d3944b370aa345209c9bc392373af8ab",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u59.png"}}]}],
              "parentCellId":"833e1e5525894c77a7fc7001543f9216"}]},
{
          "id":"65fcf18f9064443db0b4199605b3c99c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":18},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u61_image_sketch.png",
            "disabled~":"images/главная/u61_disabled.png"}},
{
          "id":"0b9c723116624c088865cf7ea356c6aa",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":56},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u62_image_sketch.png",
            "disabled~":"images/главная/u62_disabled.png"}},
{
          "id":"d84615281c434c4d98bcd698ad6773ac",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":141},
            "size":{
              "width":150,
              "height":44}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u73_image_sketch.png",
            "disabled~":"images/главная/u73_disabled.png"}},
{
          "id":"828b58baf7094f478c0049d1d92f1d4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":862,
              "y":192},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77645ed32f014aa0a70b79a72d7cc332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":862,
                  "y":192},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6277201d6b074a89998fa90c6fcf5f6e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":18},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u76_image_sketch.png",
            "disabled~":"images/главная/u76_disabled.png"}},
{
          "id":"8d34fe86e37e47308023a10b3f750872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":16},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee0eaeeae4884302a85468202f60ae2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":16},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36433d66245b4df8b8be76b9f8203130",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":45},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f29228a286b4f7e900fc1b004667e32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":45},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48fd46235f80458eb6dd24f13dd3ae19",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4917f04a4c884bf6b487bda79d59d3aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u81.png"}},
{
          "id":"6d22b9c0e82440709422ce4ce8590306",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5320d896acb41ee89404e5b974e0331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u83.png"}},
{
          "id":"009195fea00340d7b9f572c5e2ef3311",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761a0cf629c4494fa17905c4faed1a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u85.png"}},
{
          "id":"e41c5e692ede4fe3b2dcb030f53eaeb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":428,
              "y":267},
            "size":{
              "width":144,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bbc3f58bb154b519246fafb20c430b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":428,
                  "y":267},
                "size":{
                  "width":144,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7e2b6d4c888f43bdb2800f8a8b40db61":{
      "scriptId":"u0"},
    "00720508ad70419f9a1b4b5d3fe20249":{
      "scriptId":"u1"},
    "87e4fa696c9b4144b6d3460783f30d8f":{
      "scriptId":"u2"},
    "d50b3da6f16842969572cb7afdcd30cb":{
      "scriptId":"u3"},
    "a937e9a4cd51495a901d05b487efac0c":{
      "scriptId":"u4"},
    "e0b729d457a342a986ff2a8a2fc533a8":{
      "scriptId":"u5"},
    "739e9075da254936b069fe503ba065f3":{
      "scriptId":"u6"},
    "4f5fa549bb40455abd380c1b3c385160":{
      "scriptId":"u7"},
    "4f162db318804f4cb80d4caf22a00acd":{
      "scriptId":"u8"},
    "416803793b634880a0790699b7408782":{
      "scriptId":"u9"},
    "7a3e3977c2db45e29e6a74f0b4323fc5":{
      "scriptId":"u10"},
    "d1aa3991a90b40728dbe6bb20397b7ed":{
      "scriptId":"u11"},
    "8170d1acf8c74ec4a717b6ef0971d336":{
      "scriptId":"u12"},
    "86cd936b833b45dcbae71bb896f830a4":{
      "scriptId":"u13"},
    "6d729c0402ee4178ae0ddc0dc091aee1":{
      "scriptId":"u14"},
    "540dc723182d481498567fd152a67d5c":{
      "scriptId":"u15"},
    "c3ec3a2a165f4e1682aa06606c735c4a":{
      "scriptId":"u16"},
    "16799d563f424a3ea1de4b22d16fd1d0":{
      "scriptId":"u17"},
    "eebab7d201a34e5590e3f5808e671a3f":{
      "scriptId":"u18"},
    "8349ebec9e5043f2a60e7b5af0431b90":{
      "scriptId":"u19"},
    "1c52d780e0524103916ec195b4ffba12":{
      "scriptId":"u20"},
    "fb57d72238b3402a803087068f7f37b2":{
      "scriptId":"u21"},
    "28c836c71ec24573941c0410d667f799":{
      "scriptId":"u22"},
    "95afdb67e1cc4e9bb8f378fe4679d772":{
      "scriptId":"u23"},
    "4f1b526a77dc49aea1048a82718ec87f":{
      "scriptId":"u24"},
    "74f318316b954631a359aeda0c255ef8":{
      "scriptId":"u25"},
    "8e25489ea9ea40128dd50319d12bf740":{
      "scriptId":"u26"},
    "61a7c382a10a40c2b2af3284daa9e000":{
      "scriptId":"u27"},
    "c022cb6813214a9287b8a57370796fa0":{
      "scriptId":"u28"},
    "1eb1e79110cd4dc3a827bf768ec8386c":{
      "scriptId":"u29"},
    "bf39269f566a41ce998945d30cfea056":{
      "scriptId":"u30"},
    "3bf3dd8c587547b58804e7e2bba8ff34":{
      "scriptId":"u31"},
    "b7a91227f1d14531824b67743ddf4c46":{
      "scriptId":"u32"},
    "1cbdb4599ac44765aabf7e6ceabdf8ff":{
      "scriptId":"u33"},
    "651f7d0b3bb44726a9e45a0687f37de2":{
      "scriptId":"u34"},
    "57123f39b209473a86b6e644353c2cb4":{
      "scriptId":"u35"},
    "6e4cd69ce5e346ffb5375d30041ce0fd":{
      "scriptId":"u36"},
    "2d5f4b9556d34fb1897f58a09926bad0":{
      "scriptId":"u37"},
    "6b12e40d2d804145b25063da14e89128":{
      "scriptId":"u38"},
    "59898816bcd54fa9a08d8d34ade75046":{
      "scriptId":"u39"},
    "cf659aad947f4ed498db39e1fc92f52d":{
      "scriptId":"u40"},
    "03a184ae2309456c97397a75f09791a0":{
      "scriptId":"u41"},
    "4c474024fd1d46c488fbe09b5af477a7":{
      "scriptId":"u42"},
    "874ea2f1367940ef99dc2a395114d435":{
      "scriptId":"u43"},
    "eac9c06b51664172a46356745bad5e02":{
      "scriptId":"u44"},
    "32f4cc5d6ff34e1d9a1b1e158acd42e5":{
      "scriptId":"u45"},
    "fbb239bcd6ad41a68066df8b08d9a0e4":{
      "scriptId":"u46"},
    "49568c1e1f8d4c07bf3794ddedad2527":{
      "scriptId":"u47"},
    "f5b6d9fe879541fd9ae0be9611da390d":{
      "scriptId":"u48"},
    "015d4fbe988e4838b5c6ee87aaf1fa45":{
      "scriptId":"u49"},
    "6d9fce0efeed41cf8b81ec78fc43c049":{
      "scriptId":"u50"},
    "be9400d8786f45149945e12fffd3c839":{
      "scriptId":"u51"},
    "3b870262b20e46e6bb34897ffede73aa":{
      "scriptId":"u52"},
    "207f21e9f0b940868ad4dad55f1ba33b":{
      "scriptId":"u53"},
    "5a4511c1de96433cbf8e749681b25d5a":{
      "scriptId":"u54"},
    "0ae3eae5f8814a8f959f8d4ff1d19e94":{
      "scriptId":"u55"},
    "83d02ca6c3834a3d924c72f2a15101fd":{
      "scriptId":"u56"},
    "d78f81924c674941a12d88865eb1aba4":{
      "scriptId":"u57"},
    "8b16582629364fb4ad99aff935091ef5":{
      "scriptId":"u58"},
    "39a3c96bd70e4ef3a66b26ce743398c6":{
      "scriptId":"u59"},
    "5841af9c6cda4f309484972539c05825":{
      "scriptId":"u60"},
    "98c7e068e2cc4ad9b93b2bb39bd91c8b":{
      "scriptId":"u61"},
    "d62ac6bf6807479197b42963437e1856":{
      "scriptId":"u62"},
    "a35ccc64ad56405da669a1fedbb232f2":{
      "scriptId":"u63"},
    "96a0b8487584498798d344794dd02c63":{
      "scriptId":"u64"},
    "235a89621a854c089d4245e3a198d129":{
      "scriptId":"u65"},
    "5c9b8a43464647c09edfb9f97dfcf783":{
      "scriptId":"u66"},
    "ee6c564f44bb4918b6d76d8f94d033c8":{
      "scriptId":"u67"},
    "4c1913f9c93d4463b818d6dd4d48628e":{
      "scriptId":"u68"},
    "632a751766484ab1b602e3a632343628":{
      "scriptId":"u69"},
    "92fe3b95c91c4bb383c27ea3e7b057bf":{
      "scriptId":"u70"},
    "f24a60fe9c6e423ea561e4e7a39a396b":{
      "scriptId":"u71"},
    "2b9467b94f70484ea959b6ecd6c888af":{
      "scriptId":"u72"},
    "4fa7688a518b43b98da1a76574cb0c30":{
      "scriptId":"u73"},
    "833e1e5525894c77a7fc7001543f9216":{
      "scriptId":"u74"},
    "4b9a3323e0284cebb37a8fdf4b53683f":{
      "scriptId":"u75"},
    "203426c9ac174204887fcb5711482325":{
      "scriptId":"u76"},
    "b93dbefebe1e4ae3a86d5453e19fd27d":{
      "scriptId":"u77"},
    "6f245d36cacf48b8bbeec9a616e7ddf9":{
      "scriptId":"u78"},
    "e787d4ea669b4ae8a931f30b0f14f02a":{
      "scriptId":"u79"},
    "5a4ee3d0678847948df8e6bf2251356a":{
      "scriptId":"u80"},
    "1698e637a026456cad8dc1b97c0b89f5":{
      "scriptId":"u81"},
    "1e433b9db85a44ad872b14161bae9500":{
      "scriptId":"u82"},
    "ae9c85130ffe49128125280c102cfb80":{
      "scriptId":"u83"},
    "af2c2677f3dc4bc5b225b6a77e6bd893":{
      "scriptId":"u84"},
    "576d8ef9e40645c882f6e9bcd55b9e63":{
      "scriptId":"u85"},
    "49ab78588c6342978296eca89f271879":{
      "scriptId":"u86"},
    "849207ef97214b5cac233bb34808b4a7":{
      "scriptId":"u87"},
    "a77eddaba9954b3faf0c70476e6bbf6d":{
      "scriptId":"u88"},
    "f26b2bc73ab4473dba52c5d7b2af35ed":{
      "scriptId":"u89"},
    "07da577cf0c143cdb7bca69957fa7324":{
      "scriptId":"u90"},
    "f09a2dfcb6544e808241ac7f294eb7be":{
      "scriptId":"u91"},
    "b66af7183602492ab6c6d41260dd6063":{
      "scriptId":"u92"},
    "4e7dae18496d4f048cfe3d503298a5e8":{
      "scriptId":"u93"},
    "db8600306c0a4a7aa653dd661099cca2":{
      "scriptId":"u94"},
    "d3944b370aa345209c9bc392373af8ab":{
      "scriptId":"u95"},
    "65fcf18f9064443db0b4199605b3c99c":{
      "scriptId":"u96"},
    "0b9c723116624c088865cf7ea356c6aa":{
      "scriptId":"u97"},
    "d84615281c434c4d98bcd698ad6773ac":{
      "scriptId":"u98"},
    "828b58baf7094f478c0049d1d92f1d4b":{
      "scriptId":"u99"},
    "77645ed32f014aa0a70b79a72d7cc332":{
      "scriptId":"u100"},
    "6277201d6b074a89998fa90c6fcf5f6e":{
      "scriptId":"u101"},
    "8d34fe86e37e47308023a10b3f750872":{
      "scriptId":"u102"},
    "ee0eaeeae4884302a85468202f60ae2c":{
      "scriptId":"u103"},
    "36433d66245b4df8b8be76b9f8203130":{
      "scriptId":"u104"},
    "3f29228a286b4f7e900fc1b004667e32":{
      "scriptId":"u105"},
    "48fd46235f80458eb6dd24f13dd3ae19":{
      "scriptId":"u106"},
    "4917f04a4c884bf6b487bda79d59d3aa":{
      "scriptId":"u107"},
    "6d22b9c0e82440709422ce4ce8590306":{
      "scriptId":"u108"},
    "b5320d896acb41ee89404e5b974e0331":{
      "scriptId":"u109"},
    "009195fea00340d7b9f572c5e2ef3311":{
      "scriptId":"u110"},
    "761a0cf629c4494fa17905c4faed1a29":{
      "scriptId":"u111"},
    "e41c5e692ede4fe3b2dcb030f53eaeb7":{
      "scriptId":"u112"},
    "8bbc3f58bb154b519246fafb20c430b9":{
      "scriptId":"u113"}}});