$axure.loadCurrentPage({
  "url":"регистрация.html",
  "generationDate":new Date(1494499903445.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"4daca0696785413a8d70fefff894096f",
    "type":"Axure:Page",
    "name":"Регистрация",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2caa83540ca2498aab6d71c0ff5e3d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":217},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2350743c545847c4a599c6efa989838f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":217},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40ee47b9ed4a4a6595cf8e2e87ab3072",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":217},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ce1d8fd42c458fa4cc25dafdeb047d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":217},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecc3492087b140aa93f9f9408a2f9054",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":220},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"7140e1c352574759b2c4b2934b3a42ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":383,
              "y":235},
            "size":{
              "width":234,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"062051044e4d4cf2a9ea677c84d641aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":383,
                  "y":235},
                "size":{
                  "width":234,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4184d434aa5249ee8ffa8ae9ae9a48de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEDEDED},
            "location":{
              "x":385,
              "y":284},
            "size":{
              "width":230,
              "height":420},
            "borderFill":{
              "fillType":"solid",
              "color":0xFEFEFE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"052f7b3836fb4917801c2c0fad6aa27b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEDEDED},
                "location":{
                  "x":385,
                  "y":284},
                "size":{
                  "width":230,
                  "height":420},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFEFEFE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/регистрация/u7.png"}},
{
          "id":"a136d5473d8e463998d71cb54fb3079e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":437,
              "y":296},
            "size":{
              "width":124,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb0b1fa751c40da88de2b599a5604bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":437,
                  "y":296},
                "size":{
                  "width":124,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21f9566a12824e8d9fa04e988f42722f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":329},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"cc246b99e08541f49a9f7d74cbe6d0e9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":365},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"864b2c796cae465eb384cbf07f996aa9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":401},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"5f0f6cbd2c82493389f9546668eca7dd",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":524},
            "size":{
              "width":200,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u13_image_sketch.png",
            "disabled~":"images/контакты/u13_disabled.png"}},
{
          "id":"ed6766e69fb34d8385c2496748306b30",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":401,
              "y":643},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u14_image_sketch.png",
            "disabled~":"images/контакты/u14_disabled.png"}},
{
          "id":"5568032569e94a729c90d985ed6fa1ea",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":474},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u10_image_sketch.png",
            "disabled~":"images/контакты/u10_disabled.png"}},
{
          "id":"dee3b72c4b164052b865c4800ceb353d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":436},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/регистрация/u17_image_sketch.png",
            "disabled~":"images/регистрация/u17_disabled.png"}},
{
          "id":"79d0512011ec4116bd986de1c75584cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aad340bbfa9e4b8baed7f05304da300a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"7cdc4f63598d400eaeea76fea78144c2",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e26fe52dd034abfa55a5c07df7f8818",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9732c2d1f6f24ddab2815b9f6e05f57b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e360a35e3e7241c48555e76ec1be1f7d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"4dd9289197c245cf989252a04f5a1980",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18964f896c964419909efef5add4edf3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"7f0555ca2baf48819b0dade57fc4b5a1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44b4286d64544ba6b6d3f9674406b046",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"861c59081fe442e0ad5ac5413c5dd11c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9e34b7d11ca437b8fb06b082f9bc165",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"665ff02c693b4eaf89540e8d0f35dc94",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ad79f27d1fa4246930166256dfdb67c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"94bc5b5fb62645089dd41842d5d4fbb6",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"424f2699324a42f2b311c30a2fde3952",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb5b9e4c982146c881a0ddc345c011ff",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a47faaff967347f4835a134c2ba029b9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"4fe2241444e14bc2bc665cc2954b88da",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f2737cf5c62b42b0a7fb64ca4c4bffc5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"f77fbb174c9344c2b3ed0e82e0f40070",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d5d62b5d785b4a9ba51e07748f074911",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"7621a8a4ac7b41568fc80a7376993e36",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6a8b67aaf8b44100a1a482bc4947844b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"29629ee24f784f4985b4b5c085c214fd",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6388c956522f428da22da59d1d29bfa1",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"4dd9289197c245cf989252a04f5a1980"}]},
{
          "id":"e38b4eaf882a4aba8d667524cdc1a0ff",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"3514f0c6a8854064afb374b551acc780",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"bbaf98ba09c9470b9ac5950646092080",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"3ef3f84e043a4f6ca7d61279f6d575b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"355454e6c51f47a4a5f3ba0b20384027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c20fd2af3aaa4d389ab763e8d2aaa223",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4faefd7df96b4f118da08183b1819fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b6d4b826d4f4c298b67b9d42f459098",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03c008daa885490eadae6870e9f9dfee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"4f58ad9074fb46d999e349d6346d9688",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e483b50184124851948a381eab6f4e8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"8cc6483fe07b4c8d845a938923f6174b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"3c3c853dd6254820a5ab03650bb79f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b5d95cf7134e4c95e5f4ef68575d7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7eb62f616aa4689be4db92dc9ee59df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-3,
              "y":736},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64ecc8704397455185057510f3c45806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-3,
                  "y":736},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2caa83540ca2498aab6d71c0ff5e3d0b":{
      "scriptId":"u0"},
    "2350743c545847c4a599c6efa989838f":{
      "scriptId":"u1"},
    "40ee47b9ed4a4a6595cf8e2e87ab3072":{
      "scriptId":"u2"},
    "56ce1d8fd42c458fa4cc25dafdeb047d":{
      "scriptId":"u3"},
    "ecc3492087b140aa93f9f9408a2f9054":{
      "scriptId":"u4"},
    "7140e1c352574759b2c4b2934b3a42ef":{
      "scriptId":"u5"},
    "062051044e4d4cf2a9ea677c84d641aa":{
      "scriptId":"u6"},
    "4184d434aa5249ee8ffa8ae9ae9a48de":{
      "scriptId":"u7"},
    "052f7b3836fb4917801c2c0fad6aa27b":{
      "scriptId":"u8"},
    "a136d5473d8e463998d71cb54fb3079e":{
      "scriptId":"u9"},
    "beb0b1fa751c40da88de2b599a5604bd":{
      "scriptId":"u10"},
    "21f9566a12824e8d9fa04e988f42722f":{
      "scriptId":"u11"},
    "cc246b99e08541f49a9f7d74cbe6d0e9":{
      "scriptId":"u12"},
    "864b2c796cae465eb384cbf07f996aa9":{
      "scriptId":"u13"},
    "5f0f6cbd2c82493389f9546668eca7dd":{
      "scriptId":"u14"},
    "ed6766e69fb34d8385c2496748306b30":{
      "scriptId":"u15"},
    "5568032569e94a729c90d985ed6fa1ea":{
      "scriptId":"u16"},
    "dee3b72c4b164052b865c4800ceb353d":{
      "scriptId":"u17"},
    "79d0512011ec4116bd986de1c75584cc":{
      "scriptId":"u18"},
    "aad340bbfa9e4b8baed7f05304da300a":{
      "scriptId":"u19"},
    "7cdc4f63598d400eaeea76fea78144c2":{
      "scriptId":"u20"},
    "3e26fe52dd034abfa55a5c07df7f8818":{
      "scriptId":"u21"},
    "9732c2d1f6f24ddab2815b9f6e05f57b":{
      "scriptId":"u22"},
    "e360a35e3e7241c48555e76ec1be1f7d":{
      "scriptId":"u23"},
    "4dd9289197c245cf989252a04f5a1980":{
      "scriptId":"u24"},
    "18964f896c964419909efef5add4edf3":{
      "scriptId":"u25"},
    "861c59081fe442e0ad5ac5413c5dd11c":{
      "scriptId":"u26"},
    "e9e34b7d11ca437b8fb06b082f9bc165":{
      "scriptId":"u27"},
    "665ff02c693b4eaf89540e8d0f35dc94":{
      "scriptId":"u28"},
    "5ad79f27d1fa4246930166256dfdb67c":{
      "scriptId":"u29"},
    "7f0555ca2baf48819b0dade57fc4b5a1":{
      "scriptId":"u30"},
    "44b4286d64544ba6b6d3f9674406b046":{
      "scriptId":"u31"},
    "94bc5b5fb62645089dd41842d5d4fbb6":{
      "scriptId":"u32"},
    "424f2699324a42f2b311c30a2fde3952":{
      "scriptId":"u33"},
    "bb5b9e4c982146c881a0ddc345c011ff":{
      "scriptId":"u34"},
    "a47faaff967347f4835a134c2ba029b9":{
      "scriptId":"u35"},
    "f77fbb174c9344c2b3ed0e82e0f40070":{
      "scriptId":"u36"},
    "d5d62b5d785b4a9ba51e07748f074911":{
      "scriptId":"u37"},
    "7621a8a4ac7b41568fc80a7376993e36":{
      "scriptId":"u38"},
    "6a8b67aaf8b44100a1a482bc4947844b":{
      "scriptId":"u39"},
    "4fe2241444e14bc2bc665cc2954b88da":{
      "scriptId":"u40"},
    "f2737cf5c62b42b0a7fb64ca4c4bffc5":{
      "scriptId":"u41"},
    "29629ee24f784f4985b4b5c085c214fd":{
      "scriptId":"u42"},
    "6388c956522f428da22da59d1d29bfa1":{
      "scriptId":"u43"},
    "e38b4eaf882a4aba8d667524cdc1a0ff":{
      "scriptId":"u44"},
    "3514f0c6a8854064afb374b551acc780":{
      "scriptId":"u45"},
    "bbaf98ba09c9470b9ac5950646092080":{
      "scriptId":"u46"},
    "3ef3f84e043a4f6ca7d61279f6d575b1":{
      "scriptId":"u47"},
    "355454e6c51f47a4a5f3ba0b20384027":{
      "scriptId":"u48"},
    "c20fd2af3aaa4d389ab763e8d2aaa223":{
      "scriptId":"u49"},
    "4faefd7df96b4f118da08183b1819fbc":{
      "scriptId":"u50"},
    "6b6d4b826d4f4c298b67b9d42f459098":{
      "scriptId":"u51"},
    "03c008daa885490eadae6870e9f9dfee":{
      "scriptId":"u52"},
    "4f58ad9074fb46d999e349d6346d9688":{
      "scriptId":"u53"},
    "e483b50184124851948a381eab6f4e8f":{
      "scriptId":"u54"},
    "8cc6483fe07b4c8d845a938923f6174b":{
      "scriptId":"u55"},
    "3c3c853dd6254820a5ab03650bb79f69":{
      "scriptId":"u56"},
    "45b5d95cf7134e4c95e5f4ef68575d7d":{
      "scriptId":"u57"},
    "c7eb62f616aa4689be4db92dc9ee59df":{
      "scriptId":"u58"},
    "64ecc8704397455185057510f3c45806":{
      "scriptId":"u59"}}});