$axure.loadCurrentPage({
  "url":"отзывы.html",
  "generationDate":new Date(1493281621316.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"15023fdf63974b9eafcd21511ae05f85",
    "type":"Axure:Page",
    "name":"Отзывы",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dceca9ffd0ad4abd8eeee3bfe1578292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":3,
              "y":233},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2deabb9bebdd4c23b7a9d00d2ea83035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":3,
                  "y":233},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44249af757fe4d66a5f261718aa56b68",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":236},
            "size":{
              "width":17,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/отзывы/u2_end.png",
            "line~":"images/отзывы/u2_line.png"}},
{
          "id":"3be5765aef5741978f58016d26e5d183",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":76,
              "y":233},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a62de04011048fe916dd2d92727d3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":76,
                  "y":233},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d9e74d921c54fa4bcea770d3f9a4a2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":78,
              "y":339},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9afdeac4d6634efc9d74ae3ea0df01d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":78,
                  "y":339},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e89c0c583e34b69a5a89ed9c4f628af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":80,
              "y":376},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87431022a8194eac9a77be772b8aa74c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":80,
                  "y":376},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0c0ae2ddf6141e7bf76811f376c2701",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":368},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2e479192c44285b9a386cedbe0569f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":368},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"de69721367a647178f0d04e78cf491c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":413},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0d722491e6460ebee8fa567c4067be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":413},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65431a13d2294461888961b5b9c2ac2a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":471},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"3c320eb58123452cbe19847a27fa414f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":256},
            "size":{
              "width":99,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe0332dfc0645308fc0c6f68616786d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":256},
                "size":{
                  "width":99,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a3e325c01f74064b5a299a4abbc7fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "location":{
              "x":413,
              "y":1125},
            "size":{
              "width":177,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c0c2922479c44a0a745a1d88f5f882e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "location":{
                  "x":413,
                  "y":1125},
                "size":{
                  "width":177,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f555cd977acc4a568c47b4f5139cb07b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":1078},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/каталог/u102_image_sketch.png",
            "disabled~":"images/каталог/u102_disabled.png"}},
{
          "id":"883525f5fc664058be440497816e051e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":1181},
            "size":{
              "width":980,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"671e589bf7c44c558d9fc81e26fa0627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":1181},
                "size":{
                  "width":980,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49197f474bb14a26946d4a5ee29b4ddc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8869b0c656d54632929a6eea27a857c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"59f6edb37ed5419ea3bbf6b979ad37ff",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":146},
            "size":{
              "width":700,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72a75c2dbfb845209a8dc3db7e92095b",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":700,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"598b0cfb9c9e457783114e162ee9f19e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"530d3f10a7754d108718541b83c99e99",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"6ac811baa52f484890c9aef8f1e46213",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"610d1dfd46c84f58a054f8c385e067b2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"af81906b2c024314b58af1b832f35e99",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":614,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd8cc2842ec74704888c9ad564d62f75",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":614,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u47.png"}},
{
                  "id":"feaf35da4ad640d5b90c01c6ab8c1285",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c772f73d7af444da4421ea3b4204913",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"cbb1041f6d6c4383b0f11cc7c22128fd",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":514,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a4d422b9a304e699dd0dceefa9c3ed2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":514,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"e687fc7f6fbf4ff587533c3646422f42",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c6fd0f46e8a4cc28e702b1ba82ca6f0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"de3518e5a57040ab9f3770b20e2aa326",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b22db217e0f44d40b5d4b96ac6f724a8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"ac1f06d16b58465199639c64853f2dc4",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33143b6e74c641bea92a40ef7cfeffa4",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"47f0c5ef38164aad8b4703128e7f8893",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fe77d5a3f6db45a1bc0304dc89959de8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"fc3d62560b2e487aacbb458fb53fd249",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"22f56a4b21c44f3f92c3ab38df99bf42",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"11f3877773bf414b9e238a80b0bf39e3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6281e5089f844bccaa501c3b03c8d665",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"aa24a571aba3425a85635f1cc638c6df",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b032d09f876e4133b81fe45abb7ba85f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}},
{
                      "id":"0c9b38c787ca4e0c80224381212daa5d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"dd473587a7f24330b2b92e77cf635039",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u59.png"}}]}],
              "parentCellId":"6ac811baa52f484890c9aef8f1e46213"}]},
{
          "id":"13867780af7f4a4fb54c57291f98b765",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":18},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u61_image_sketch.png",
            "disabled~":"images/главная/u61_disabled.png"}},
{
          "id":"cbca5a5845934a2c80f185515aec923f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":56},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u62_image_sketch.png",
            "disabled~":"images/главная/u62_disabled.png"}},
{
          "id":"1ffc973a42e54fcf90bc41f01939c900",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":141},
            "size":{
              "width":150,
              "height":44}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u73_image_sketch.png",
            "disabled~":"images/главная/u73_disabled.png"}},
{
          "id":"6fcec273390941a486039a84e025b619",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":862,
              "y":192},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1adcd2460c0e4fd5b6ec49935ef7bb9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":862,
                  "y":192},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb30810cf70544b7b385e29899feef53",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":18},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u76_image_sketch.png",
            "disabled~":"images/главная/u76_disabled.png"}},
{
          "id":"5d62f2a31a7f4c44a7f9d5684337b8e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":16},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d27976ab0df4fd4bf6334a6abebd567",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":16},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4a5deebf1e64d769b01ab78436fbdbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":45},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40618a261d9f4edc8dd6c44cf7894230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":45},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6721be7b05534aeb867d9df4eddc472b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d51022b0064485af2af9ddde610943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u81.png"}},
{
          "id":"0166242d01b94f8e87e8ee3c424df461",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19433198347646d9ab458750a6516ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u83.png"}},
{
          "id":"7e6db312ceff452a80b49ac138636ffb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b22b07fe92da420a81611ca93ee4e33d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u85.png"}},
{
          "id":"db7d8c3ad18e4f1190d12bcef199244e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":80,
              "y":526},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e3787c19e8d473ca16037c3428d0b2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":80,
                  "y":526},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ce84369cc294b6c867ea4bcf1784a1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":82,
              "y":563},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c167271ee83454fa83fc590d7ea5428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":82,
                  "y":563},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f4102c4569f499b8700ebbdb72e23e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":555},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f29143f3b5b4483ea199ae12e13b1a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":555},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"e80e72f4919e41f0a6a81b62ed468a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":600},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7ba6e5fff0429191f3de71889726ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":600},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f904ce4dccc4774b236715d9c057a10",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":658},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"6a981290230b48e29409c558d6c6177c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":900},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb1a0c1efffd4d8c963a14223ce959b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":900},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5fc0a4908924dd1a137d7e76ec3a3e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":84,
              "y":937},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01e98b8e9eb45f0addd937ca39d7ed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":84,
                  "y":937},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f8522a20a464571ab72be4459445d93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":929},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52db0bb322b64601be66b743acb7b098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":929},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"353e09b7fdce4ccdb736b4f7adbf1069",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":974},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2516b02a1991439db010280184e5ff40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":974},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5db0805aa3bb40ce8775f322c9452bea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":1032},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"e4a5bf47e5dd4c7b819711476ffe04c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":90,
              "y":713},
            "size":{
              "width":240,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c53b993d2a8d4d2e9465229f86ce4aa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":90,
                  "y":713},
                "size":{
                  "width":240,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa2ac76f54ea4facbbccda0cdb8f576a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":92,
              "y":750},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e4a568bdf6747a6b3b8016609ea3574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":92,
                  "y":750},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce0b2e69634d4f1c94acf6243d8d2789",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":742},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6609200958b04af19a3d21470128f150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":742},
                "size":{
                  "width":110,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/отзывы/u9.png"}},
{
          "id":"cd8a8216d63f4d1291ebdcd9e7be0d5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":787},
            "size":{
              "width":921,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a7193faf5e4156b216b396f6904fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":787},
                "size":{
                  "width":921,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db72f9033856439b84f94d4135ee6e48",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":845},
            "size":{
              "width":921,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/отзывы/u13_line.png"}},
{
          "id":"72486addddc34b65befb7ce6d69bf126",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-4,
              "y":1450},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"904cb5ac5ef44df2bf6cbf95c17c0271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-4,
                  "y":1450},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "dceca9ffd0ad4abd8eeee3bfe1578292":{
      "scriptId":"u0"},
    "2deabb9bebdd4c23b7a9d00d2ea83035":{
      "scriptId":"u1"},
    "44249af757fe4d66a5f261718aa56b68":{
      "scriptId":"u2"},
    "3be5765aef5741978f58016d26e5d183":{
      "scriptId":"u3"},
    "9a62de04011048fe916dd2d92727d3d5":{
      "scriptId":"u4"},
    "0d9e74d921c54fa4bcea770d3f9a4a2b":{
      "scriptId":"u5"},
    "9afdeac4d6634efc9d74ae3ea0df01d8":{
      "scriptId":"u6"},
    "0e89c0c583e34b69a5a89ed9c4f628af":{
      "scriptId":"u7"},
    "87431022a8194eac9a77be772b8aa74c":{
      "scriptId":"u8"},
    "b0c0ae2ddf6141e7bf76811f376c2701":{
      "scriptId":"u9"},
    "4e2e479192c44285b9a386cedbe0569f":{
      "scriptId":"u10"},
    "de69721367a647178f0d04e78cf491c7":{
      "scriptId":"u11"},
    "ff0d722491e6460ebee8fa567c4067be":{
      "scriptId":"u12"},
    "65431a13d2294461888961b5b9c2ac2a":{
      "scriptId":"u13"},
    "3c320eb58123452cbe19847a27fa414f":{
      "scriptId":"u14"},
    "6fe0332dfc0645308fc0c6f68616786d":{
      "scriptId":"u15"},
    "1a3e325c01f74064b5a299a4abbc7fb5":{
      "scriptId":"u16"},
    "9c0c2922479c44a0a745a1d88f5f882e":{
      "scriptId":"u17"},
    "f555cd977acc4a568c47b4f5139cb07b":{
      "scriptId":"u18"},
    "883525f5fc664058be440497816e051e":{
      "scriptId":"u19"},
    "671e589bf7c44c558d9fc81e26fa0627":{
      "scriptId":"u20"},
    "49197f474bb14a26946d4a5ee29b4ddc":{
      "scriptId":"u21"},
    "8869b0c656d54632929a6eea27a857c6":{
      "scriptId":"u22"},
    "59f6edb37ed5419ea3bbf6b979ad37ff":{
      "scriptId":"u23"},
    "72a75c2dbfb845209a8dc3db7e92095b":{
      "scriptId":"u24"},
    "598b0cfb9c9e457783114e162ee9f19e":{
      "scriptId":"u25"},
    "530d3f10a7754d108718541b83c99e99":{
      "scriptId":"u26"},
    "e687fc7f6fbf4ff587533c3646422f42":{
      "scriptId":"u27"},
    "8c6fd0f46e8a4cc28e702b1ba82ca6f0":{
      "scriptId":"u28"},
    "6ac811baa52f484890c9aef8f1e46213":{
      "scriptId":"u29"},
    "610d1dfd46c84f58a054f8c385e067b2":{
      "scriptId":"u30"},
    "de3518e5a57040ab9f3770b20e2aa326":{
      "scriptId":"u31"},
    "b22db217e0f44d40b5d4b96ac6f724a8":{
      "scriptId":"u32"},
    "feaf35da4ad640d5b90c01c6ab8c1285":{
      "scriptId":"u33"},
    "4c772f73d7af444da4421ea3b4204913":{
      "scriptId":"u34"},
    "cbb1041f6d6c4383b0f11cc7c22128fd":{
      "scriptId":"u35"},
    "6a4d422b9a304e699dd0dceefa9c3ed2":{
      "scriptId":"u36"},
    "af81906b2c024314b58af1b832f35e99":{
      "scriptId":"u37"},
    "cd8cc2842ec74704888c9ad564d62f75":{
      "scriptId":"u38"},
    "ac1f06d16b58465199639c64853f2dc4":{
      "scriptId":"u39"},
    "33143b6e74c641bea92a40ef7cfeffa4":{
      "scriptId":"u40"},
    "47f0c5ef38164aad8b4703128e7f8893":{
      "scriptId":"u41"},
    "fe77d5a3f6db45a1bc0304dc89959de8":{
      "scriptId":"u42"},
    "11f3877773bf414b9e238a80b0bf39e3":{
      "scriptId":"u43"},
    "6281e5089f844bccaa501c3b03c8d665":{
      "scriptId":"u44"},
    "aa24a571aba3425a85635f1cc638c6df":{
      "scriptId":"u45"},
    "b032d09f876e4133b81fe45abb7ba85f":{
      "scriptId":"u46"},
    "fc3d62560b2e487aacbb458fb53fd249":{
      "scriptId":"u47"},
    "22f56a4b21c44f3f92c3ab38df99bf42":{
      "scriptId":"u48"},
    "0c9b38c787ca4e0c80224381212daa5d":{
      "scriptId":"u49"},
    "dd473587a7f24330b2b92e77cf635039":{
      "scriptId":"u50"},
    "13867780af7f4a4fb54c57291f98b765":{
      "scriptId":"u51"},
    "cbca5a5845934a2c80f185515aec923f":{
      "scriptId":"u52"},
    "1ffc973a42e54fcf90bc41f01939c900":{
      "scriptId":"u53"},
    "6fcec273390941a486039a84e025b619":{
      "scriptId":"u54"},
    "1adcd2460c0e4fd5b6ec49935ef7bb9e":{
      "scriptId":"u55"},
    "fb30810cf70544b7b385e29899feef53":{
      "scriptId":"u56"},
    "5d62f2a31a7f4c44a7f9d5684337b8e9":{
      "scriptId":"u57"},
    "1d27976ab0df4fd4bf6334a6abebd567":{
      "scriptId":"u58"},
    "b4a5deebf1e64d769b01ab78436fbdbd":{
      "scriptId":"u59"},
    "40618a261d9f4edc8dd6c44cf7894230":{
      "scriptId":"u60"},
    "6721be7b05534aeb867d9df4eddc472b":{
      "scriptId":"u61"},
    "a0d51022b0064485af2af9ddde610943":{
      "scriptId":"u62"},
    "0166242d01b94f8e87e8ee3c424df461":{
      "scriptId":"u63"},
    "19433198347646d9ab458750a6516ff4":{
      "scriptId":"u64"},
    "7e6db312ceff452a80b49ac138636ffb":{
      "scriptId":"u65"},
    "b22b07fe92da420a81611ca93ee4e33d":{
      "scriptId":"u66"},
    "db7d8c3ad18e4f1190d12bcef199244e":{
      "scriptId":"u67"},
    "4e3787c19e8d473ca16037c3428d0b2f":{
      "scriptId":"u68"},
    "3ce84369cc294b6c867ea4bcf1784a1f":{
      "scriptId":"u69"},
    "7c167271ee83454fa83fc590d7ea5428":{
      "scriptId":"u70"},
    "1f4102c4569f499b8700ebbdb72e23e6":{
      "scriptId":"u71"},
    "f29143f3b5b4483ea199ae12e13b1a41":{
      "scriptId":"u72"},
    "e80e72f4919e41f0a6a81b62ed468a46":{
      "scriptId":"u73"},
    "de7ba6e5fff0429191f3de71889726ea":{
      "scriptId":"u74"},
    "4f904ce4dccc4774b236715d9c057a10":{
      "scriptId":"u75"},
    "6a981290230b48e29409c558d6c6177c":{
      "scriptId":"u76"},
    "eb1a0c1efffd4d8c963a14223ce959b0":{
      "scriptId":"u77"},
    "c5fc0a4908924dd1a137d7e76ec3a3e2":{
      "scriptId":"u78"},
    "c01e98b8e9eb45f0addd937ca39d7ed8":{
      "scriptId":"u79"},
    "5f8522a20a464571ab72be4459445d93":{
      "scriptId":"u80"},
    "52db0bb322b64601be66b743acb7b098":{
      "scriptId":"u81"},
    "353e09b7fdce4ccdb736b4f7adbf1069":{
      "scriptId":"u82"},
    "2516b02a1991439db010280184e5ff40":{
      "scriptId":"u83"},
    "5db0805aa3bb40ce8775f322c9452bea":{
      "scriptId":"u84"},
    "e4a5bf47e5dd4c7b819711476ffe04c7":{
      "scriptId":"u85"},
    "c53b993d2a8d4d2e9465229f86ce4aa2":{
      "scriptId":"u86"},
    "aa2ac76f54ea4facbbccda0cdb8f576a":{
      "scriptId":"u87"},
    "6e4a568bdf6747a6b3b8016609ea3574":{
      "scriptId":"u88"},
    "ce0b2e69634d4f1c94acf6243d8d2789":{
      "scriptId":"u89"},
    "6609200958b04af19a3d21470128f150":{
      "scriptId":"u90"},
    "cd8a8216d63f4d1291ebdcd9e7be0d5e":{
      "scriptId":"u91"},
    "38a7193faf5e4156b216b396f6904fbe":{
      "scriptId":"u92"},
    "db72f9033856439b84f94d4135ee6e48":{
      "scriptId":"u93"},
    "72486addddc34b65befb7ce6d69bf126":{
      "scriptId":"u94"},
    "904cb5ac5ef44df2bf6cbf95c17c0271":{
      "scriptId":"u95"}}});