$axure.loadCurrentPage({
  "url":"рабочий_кабинет.html",
  "generationDate":new Date(1493889318908.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"227b5b96ac8f415ebbbf1713e4262f66",
    "type":"Axure:Page",
    "name":"Рабочий кабинет",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eca539e70fc74fa3a48a040eccb948a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c93f5d8e2c245cc9411b33b8018ce1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":0},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"93e460b5d22a4f328104a95c76f020d9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"943b2db26dbd46fb8775bbca07fde49f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4031ace3c248f59ca2fc489380cbad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a38693af89a43db82160fcfaa494f33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"165dd4728ad24069b07d8074ab9eda46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"c427754086cf40519b2b6ac83dd9495a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fe37685eb60e4b5c96e97d880d61a8ac",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"a4a1943bcf9d4eff916c8f22c3673ff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":252,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3df1632983e2408b90ea8ba601b2f70d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":252,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f43932ddd48c4cdab049e22f61012458",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b873ca60ee743608a4337d026d9a627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d47111d3da814098a183e29e7931d29d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":641,
              "y":34},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8628f1c3d0e544daac7a15a3e0c68bfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":641,
                  "y":34},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0947ea9e41a945e6a5df0b8f3ceae464",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":4},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c401ecb07af74348adbc18685d67ee1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":4},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5270d053233640f5adab92f4578da334",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6653e853b0e448db6a06bea12d2eb9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":916,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u17.png"}},
{
          "id":"5af5e05ce2b4443bbdb05df1f4830e86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b89bb42bd26444f9584e07bc8adba0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u19.png"}},
{
          "id":"a8794c548e574ff88da86ff2af67d257",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28daa704e7ff449faf405ff8d5fa2b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u21.png"}},
{
          "id":"9068ca9cc1bc4a83a1289abd749e15eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":642,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c5b9fa0b044b5a844e31c56f1b7fe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":642,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35afe4bfcd1c425a8129e09184bc26ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":155},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a9cd3a19a04a5d9ad99f868b2e9dc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":155},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a69430644564f45ac86726ecff237e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":155},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c0ce8f47cfc4f5281de2f8967945778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":155},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50e59e088733465fb678d6dcb6faadb7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":158},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"473519a87cde4dfe8337a89cc01a8617",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":218},
            "size":{
              "width":397,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fadc26f969ce49ebb97fd8f140aa55e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":218},
                "size":{
                  "width":397,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7422302cbf341b8ad21d6a20e639df8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":278},
            "size":{
              "width":950,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/рабочий_кабинет/u32_line.png"}},
{
          "id":"db94596bb26346c68c25bc95b818bf70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":316},
            "size":{
              "width":92,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85551c8afa00444d98b1acb8504b6836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":316},
                "size":{
                  "width":92,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/рабочий_кабинет/u33.png"}},
{
          "id":"0401e578d24642b196efdfe29a797c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":136,
              "y":347},
            "size":{
              "width":680,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"338c660aa5df42898bec9a8683ac70a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":136,
                  "y":347},
                "size":{
                  "width":680,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdd875bd0024436f848b65f9edc2f071",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":136,
              "y":314},
            "size":{
              "width":170,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"574524fbc982472ab44971706aad0a1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":136,
                  "y":314},
                "size":{
                  "width":170,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68588d7257224ab1941cf8fc08756748",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":413},
            "size":{
              "width":92,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0535ff353222481dbd7bdf86eba984c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":413},
                "size":{
                  "width":92,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/рабочий_кабинет/u33.png"}},
{
          "id":"e03772fc5d9d40edbf760766147904b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":135,
              "y":444},
            "size":{
              "width":680,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eec1947ed1dc4e6dae3183ac97a598c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":135,
                  "y":444},
                "size":{
                  "width":680,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c340b5b031344d1886f09567a25325ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":135,
              "y":411},
            "size":{
              "width":142,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4425f9150b148f499f8807ff29191ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":135,
                  "y":411},
                "size":{
                  "width":142,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a81e840d67b4c298b7a665920fa76dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":316},
            "size":{
              "width":92,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6834105f130a44dfb8547d970a3b9274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":316},
                "size":{
                  "width":92,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/рабочий_кабинет/u33.png"}},
{
          "id":"310e63783ee94571813fd172001c1b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":610,
              "y":347},
            "size":{
              "width":680,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"544f4195d5c74193a27a19c564a8b30c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":610,
                  "y":347},
                "size":{
                  "width":680,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e72e5461e254463809e03d4bbd4c1d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":610,
              "y":314},
            "size":{
              "width":93,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b702e641372a4f4fb0d9ddfe13b89772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":610,
                  "y":314},
                "size":{
                  "width":93,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"067b62e6e040497aac5641d008ed534e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":-3,
              "y":582},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7ed92a2eac4d23923c439093f44080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":-3,
                  "y":582},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u33.png"}},
{
          "id":"2ac6d4b929e4493c8f3a9a83cee4bdf1",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":66},
            "size":{
              "width":500,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0fa3275405d474183afb2db2ae3a6e8",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45ea634cfa704266b4ce73cd4758c1a9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0de3fd1532974f3cb6a5502a7d8c1541",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"02b7016e58a543a8a2008144527f6b34",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"47324d5266a546dba1841db1a340e407",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"be3fdab50262448c89d8dae5275ad7a6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d34a51cac21247a2b35858189f1f0b76",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u104.png"}},
{
                  "id":"9862f7f81d464d659628987b3ae630ef",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b89eb136ac349b1bdb418ef659bcb3f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}},
{
                  "id":"8300025658e746658ededa7ab7cbe7f1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8a03f659c834443bb059ca39db8f2ae2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u96.png"}}]},
{
              "id":"c2fca4b6a91f474e834dbd8268e87198",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e030d36fa284706a71fee9fa078ae04",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e871ed18f4814970aae4658db91f0927",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f668b97b0802481d86cf20ccafd1da02",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"d370e244ad4849f9a2076ba41aa8635a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"795cfd61a68b4cb1b366a89cb46529c1",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"b9c33db48f664fc894f735be6d43ac9c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b063def3587b45eb94f5962a164eb781",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"12b5e4963e844d9481bd0879ca17fda3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9aecdf8659d04995bef21695d2dc2ccd",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u126.png"}},
{
                      "id":"c9d505ce03444e82a187911804e277fb",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"297c09e05c934abd81d06b6bb081eae4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"0f5ef89998dd4b5cb4ad38de4b7b3d01",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bb1e9d8622b049cc88ae558e068bcb52",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u116.png"}},
{
                      "id":"c4b8a70623d34332ba519077b663da9e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"36423a5178444d1db74b37abc4e9689b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"b03b52a59f564fa594e5d462474575c4",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bbef88ff4fc84e4aa5753381410c03ee",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u108.png"}},
{
                      "id":"91cae2dd3cde48ad870725298ebdfa7e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"09e1f21f5fdd44dcabf5956c72dec761",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}},
{
                      "id":"33f28d06605540158719f428c618fa6a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"90a01144cb7a420a8c09c8d2bb4dda0a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u110.png"}}]}],
              "parentCellId":"02b7016e58a543a8a2008144527f6b34"}]}]}},
  "masters":{
},
  "objectPaths":{
    "eca539e70fc74fa3a48a040eccb948a6":{
      "scriptId":"u0"},
    "5c93f5d8e2c245cc9411b33b8018ce1f":{
      "scriptId":"u1"},
    "93e460b5d22a4f328104a95c76f020d9":{
      "scriptId":"u2"},
    "943b2db26dbd46fb8775bbca07fde49f":{
      "scriptId":"u3"},
    "1a4031ace3c248f59ca2fc489380cbad":{
      "scriptId":"u4"},
    "1a38693af89a43db82160fcfaa494f33":{
      "scriptId":"u5"},
    "165dd4728ad24069b07d8074ab9eda46":{
      "scriptId":"u6"},
    "c427754086cf40519b2b6ac83dd9495a":{
      "scriptId":"u7"},
    "fe37685eb60e4b5c96e97d880d61a8ac":{
      "scriptId":"u8"},
    "a4a1943bcf9d4eff916c8f22c3673ff6":{
      "scriptId":"u9"},
    "3df1632983e2408b90ea8ba601b2f70d":{
      "scriptId":"u10"},
    "f43932ddd48c4cdab049e22f61012458":{
      "scriptId":"u11"},
    "8b873ca60ee743608a4337d026d9a627":{
      "scriptId":"u12"},
    "d47111d3da814098a183e29e7931d29d":{
      "scriptId":"u13"},
    "8628f1c3d0e544daac7a15a3e0c68bfb":{
      "scriptId":"u14"},
    "0947ea9e41a945e6a5df0b8f3ceae464":{
      "scriptId":"u15"},
    "c401ecb07af74348adbc18685d67ee1a":{
      "scriptId":"u16"},
    "5270d053233640f5adab92f4578da334":{
      "scriptId":"u17"},
    "e6653e853b0e448db6a06bea12d2eb9f":{
      "scriptId":"u18"},
    "5af5e05ce2b4443bbdb05df1f4830e86":{
      "scriptId":"u19"},
    "3b89bb42bd26444f9584e07bc8adba0c":{
      "scriptId":"u20"},
    "a8794c548e574ff88da86ff2af67d257":{
      "scriptId":"u21"},
    "28daa704e7ff449faf405ff8d5fa2b5c":{
      "scriptId":"u22"},
    "9068ca9cc1bc4a83a1289abd749e15eb":{
      "scriptId":"u23"},
    "87c5b9fa0b044b5a844e31c56f1b7fe3":{
      "scriptId":"u24"},
    "35afe4bfcd1c425a8129e09184bc26ee":{
      "scriptId":"u25"},
    "c9a9cd3a19a04a5d9ad99f868b2e9dc8":{
      "scriptId":"u26"},
    "2a69430644564f45ac86726ecff237e4":{
      "scriptId":"u27"},
    "9c0ce8f47cfc4f5281de2f8967945778":{
      "scriptId":"u28"},
    "50e59e088733465fb678d6dcb6faadb7":{
      "scriptId":"u29"},
    "473519a87cde4dfe8337a89cc01a8617":{
      "scriptId":"u30"},
    "fadc26f969ce49ebb97fd8f140aa55e2":{
      "scriptId":"u31"},
    "d7422302cbf341b8ad21d6a20e639df8":{
      "scriptId":"u32"},
    "db94596bb26346c68c25bc95b818bf70":{
      "scriptId":"u33"},
    "85551c8afa00444d98b1acb8504b6836":{
      "scriptId":"u34"},
    "0401e578d24642b196efdfe29a797c17":{
      "scriptId":"u35"},
    "338c660aa5df42898bec9a8683ac70a4":{
      "scriptId":"u36"},
    "bdd875bd0024436f848b65f9edc2f071":{
      "scriptId":"u37"},
    "574524fbc982472ab44971706aad0a1a":{
      "scriptId":"u38"},
    "68588d7257224ab1941cf8fc08756748":{
      "scriptId":"u39"},
    "0535ff353222481dbd7bdf86eba984c6":{
      "scriptId":"u40"},
    "e03772fc5d9d40edbf760766147904b8":{
      "scriptId":"u41"},
    "eec1947ed1dc4e6dae3183ac97a598c1":{
      "scriptId":"u42"},
    "c340b5b031344d1886f09567a25325ad":{
      "scriptId":"u43"},
    "e4425f9150b148f499f8807ff29191ef":{
      "scriptId":"u44"},
    "7a81e840d67b4c298b7a665920fa76dd":{
      "scriptId":"u45"},
    "6834105f130a44dfb8547d970a3b9274":{
      "scriptId":"u46"},
    "310e63783ee94571813fd172001c1b8f":{
      "scriptId":"u47"},
    "544f4195d5c74193a27a19c564a8b30c":{
      "scriptId":"u48"},
    "8e72e5461e254463809e03d4bbd4c1d9":{
      "scriptId":"u49"},
    "b702e641372a4f4fb0d9ddfe13b89772":{
      "scriptId":"u50"},
    "067b62e6e040497aac5641d008ed534e":{
      "scriptId":"u51"},
    "7b7ed92a2eac4d23923c439093f44080":{
      "scriptId":"u52"},
    "2ac6d4b929e4493c8f3a9a83cee4bdf1":{
      "scriptId":"u53"},
    "b0fa3275405d474183afb2db2ae3a6e8":{
      "scriptId":"u54"},
    "45ea634cfa704266b4ce73cd4758c1a9":{
      "scriptId":"u55"},
    "0de3fd1532974f3cb6a5502a7d8c1541":{
      "scriptId":"u56"},
    "02b7016e58a543a8a2008144527f6b34":{
      "scriptId":"u57"},
    "47324d5266a546dba1841db1a340e407":{
      "scriptId":"u58"},
    "8300025658e746658ededa7ab7cbe7f1":{
      "scriptId":"u59"},
    "8a03f659c834443bb059ca39db8f2ae2":{
      "scriptId":"u60"},
    "9862f7f81d464d659628987b3ae630ef":{
      "scriptId":"u61"},
    "3b89eb136ac349b1bdb418ef659bcb3f":{
      "scriptId":"u62"},
    "be3fdab50262448c89d8dae5275ad7a6":{
      "scriptId":"u63"},
    "d34a51cac21247a2b35858189f1f0b76":{
      "scriptId":"u64"},
    "c2fca4b6a91f474e834dbd8268e87198":{
      "scriptId":"u65"},
    "8e030d36fa284706a71fee9fa078ae04":{
      "scriptId":"u66"},
    "e871ed18f4814970aae4658db91f0927":{
      "scriptId":"u67"},
    "f668b97b0802481d86cf20ccafd1da02":{
      "scriptId":"u68"},
    "d370e244ad4849f9a2076ba41aa8635a":{
      "scriptId":"u69"},
    "795cfd61a68b4cb1b366a89cb46529c1":{
      "scriptId":"u70"},
    "b9c33db48f664fc894f735be6d43ac9c":{
      "scriptId":"u71"},
    "b063def3587b45eb94f5962a164eb781":{
      "scriptId":"u72"},
    "c4b8a70623d34332ba519077b663da9e":{
      "scriptId":"u73"},
    "36423a5178444d1db74b37abc4e9689b":{
      "scriptId":"u74"},
    "0f5ef89998dd4b5cb4ad38de4b7b3d01":{
      "scriptId":"u75"},
    "bb1e9d8622b049cc88ae558e068bcb52":{
      "scriptId":"u76"},
    "c9d505ce03444e82a187911804e277fb":{
      "scriptId":"u77"},
    "297c09e05c934abd81d06b6bb081eae4":{
      "scriptId":"u78"},
    "33f28d06605540158719f428c618fa6a":{
      "scriptId":"u79"},
    "90a01144cb7a420a8c09c8d2bb4dda0a":{
      "scriptId":"u80"},
    "91cae2dd3cde48ad870725298ebdfa7e":{
      "scriptId":"u81"},
    "09e1f21f5fdd44dcabf5956c72dec761":{
      "scriptId":"u82"},
    "b03b52a59f564fa594e5d462474575c4":{
      "scriptId":"u83"},
    "bbef88ff4fc84e4aa5753381410c03ee":{
      "scriptId":"u84"},
    "12b5e4963e844d9481bd0879ca17fda3":{
      "scriptId":"u85"},
    "9aecdf8659d04995bef21695d2dc2ccd":{
      "scriptId":"u86"}}});