$axure.loadCurrentPage({
  "url":"контакты.html",
  "generationDate":new Date(1495780882827.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bbddb3f07dbb4ddb9d87da75266c1f9e",
    "type":"Axure:Page",
    "name":"Контакты",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91fd0536228e413688a866d170ef89e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":256},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50b84a298d6040f9af396594bcf8b5e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":256},
                "size":{
                  "width":300,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8738d7c634ff431f90aff775938b2196",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":262},
            "size":{
              "width":470,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df91ca1c921c4ba8b5a4d445c5a90880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":262},
                "size":{
                  "width":470,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u2.png"}},
{
          "id":"eadb8f47785646d384c8bad0496304cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":362},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35b073a5a5554d4eb91be4eb6193053e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":362},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u4.png"}},
{
          "id":"da6a754d7ada403d874eb8433876e1c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":760,
              "y":262},
            "size":{
              "width":230,
              "height":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3a5060f920144fba36907e46e3b4a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":760,
                  "y":262},
                "size":{
                  "width":230,
                  "height":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u6.png"}},
{
          "id":"b962b1da49304f9cbe89b77410271014",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":776,
              "y":274},
            "size":{
              "width":177,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c40505d84bf949f28e61db6358add47b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":776,
                  "y":274},
                "size":{
                  "width":177,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c5f91ea8eb4040945abed8d5d15471",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":307},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4c814b3dad63424d949c9398fb89935b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":342},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ce97af5985a84357bc4db64e110c34d7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":377},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ff0e6af3fb3442318ef5ac8a71b9f34f",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":412},
            "size":{
              "width":200,
              "height":94}},
          "adaptiveStyles":{
}},
{
          "id":"68e373bff2a64da8915ac8974bc8828b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":776,
              "y":531},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"89b101792c51416ebb29422a28f7c010",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":201},
            "size":{
              "width":114,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9d2fc8cda8445abb61ff3e0323010e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":444,
                  "y":201},
                "size":{
                  "width":114,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d9ae33cbef544aebd678d39c9197997",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":147},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5355a9e9553d4d96af472c7a545762cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":147},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3b468a9ab8040678842f396a7a635f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":148},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65766b09047845b9bc38c83d8e976efe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":148},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a94fe32727434c768d81c047878e752f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":150},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"2a47ac1c02a143c6bfea350631304a54",
          "label":"Konsult",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":235,
              "y":122},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"16798e2bf85f4674bee1488a50ed0e81",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aeb560596ff542e99bbcafa3c7f0da1f",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":358}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34c2f7ca572a4f2e8df7a489455e8991",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":100,
                          "y":50},
                        "size":{
                          "width":300,
                          "height":358}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u81.png"}},
{
                  "id":"5957f203b2374380a27b3760d533f84e",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":88},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"f38a4d32a83d43b588abf3dd87364653",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":72},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18841c74b7ac4363a2cb6831cfcf6600",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":72},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"71c8ac427db347ad92e8ea52ab8239ad",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":138},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"dca5d27e22b24881bcc5656df4470b7b",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":122},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d55e3cc044754f1baaa45d7f31e205bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":122},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c75e7b09279e40edae3c36eb9a5b5f03",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":188},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"e77c0316ca1b4ec4b85c9e69d0016c38",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":172},
                    "size":{
                      "width":49,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"128a865fa2f5430881d159cb7e7e982f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":172},
                        "size":{
                          "width":49,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ef46dd87a2124910be517c73b94bcfb7",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":238},
                    "size":{
                      "width":260,
                      "height":91}},
                  "adaptiveStyles":{
}},
{
                  "id":"d06e2a15929a46948e6bb56ac47b0f40",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":222},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbd39b921b9a42d4a7d2797448945b47",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":222},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e8dc2301a0e14cdc9104e0afa14fb080",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":348},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show banner",
                              "objectsToFades":[{
                                  "objectPath":["7e2b1f06740b4feb95c59644358f2aaf"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"8ceb13bbb9a84816a8a774bc67f7d5c5",
                  "label":"",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":288,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4553dca83f7c46b2ad8240175b5d82eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":106,
                          "y":0},
                        "size":{
                          "width":288,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e2b1f06740b4feb95c59644358f2aaf",
                  "label":"banner",
                  "parentDynamicPanel":"2a47ac1c02a143c6bfea350631304a54",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a3914de4e07944a58ef5eb68c44c84db",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"d529038ca33642b895137d066ac1ab59",
                          "label":"",
                          "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "size":{
                              "width":530,
                              "height":130}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"77d2ec8187a443dc9dd8ccb262446aae",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "size":{
                                  "width":530,
                                  "height":130}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/главная/u99.png"}},
{
                          "id":"3ce00153cdf94f9ca4e93a98e865b2ec",
                          "label":"",
                          "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":500,
                              "y":10},
                            "size":{
                              "width":20,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f462f65fce0e4522946285e5432a1817",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e2b1f06740b4feb95c59644358f2aaf",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":500,
                                  "y":10},
                                "size":{
                                  "width":20,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Hide banner",
                                      "objectsToFades":[{
                                          "objectPath":["7e2b1f06740b4feb95c59644358f2aaf"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/главная/u101.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f589e1f72ab84d59b2eaaea6d0f22d9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "underline":true,
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":611},
            "size":{
              "width":1000,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f6288bc8c640e5ac871fab307d3b54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "underline":true,
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":611},
                "size":{
                  "width":1000,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u105.png"}},
{
          "id":"d1416eeb74464f33aa294f4ee500898b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":682},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f91ba226d44cfb8342a76e6018ae28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":682},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u107.png"}},
{
          "id":"d7d4561fd74448799f10198722c2ee76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":682},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aa016dbff00491fa9c828749405d556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":682},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u109.png"}},
{
          "id":"b38432cf75fa4e219373ff8994f3f81d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":682},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab0d8c302c1546c3a048304d8371d24c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":682},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u111.png"}},
{
          "id":"abb8cfe3f3404e1194b8f3b7007585ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":53,
              "y":642},
            "size":{
              "width":242,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23b3f89cb8f481397a53676ef471698",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":53,
                  "y":642},
                "size":{
                  "width":242,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"011ce7857d1e49b9b1801bf49062ca58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":685},
            "size":{
              "width":311,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85d175fffec64791acec8b42f5520b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":685},
                "size":{
                  "width":311,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d19c03eebd4143fbae6e107439e917cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":385,
              "y":642},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"750317bc0f624dc49df86113c62347b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":385,
                  "y":642},
                "size":{
                  "width":93,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f4046d8956e4f1b9acd03519a5c4120",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":160,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b7e67c188f94cac991e53399b769f5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":160,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"475d19a063a3434a9c3e5bf12682119d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"3800ab1a3ff7462e82861ba4f89a642a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b44aa93e84454b16bfddf85b61783d34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4727459329774a70b1e5cad2d45a39d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fffb46ad8bb7478e993269c4daf80630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"4687ed997bb54ddb8642a9951c88cce7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"05886fda489847618c2894a3dde86a1b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"4ccac057d3f847b6bb41b9df6602d62d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":3},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b2a1f0da9704f03a4fa4623848bcb98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":3},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0d74a25154048b984f57e8107218274",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":66},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c99180428c2946108c943d02e1c1c2e5",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70770939600144a98ab191e9139a21ae",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04edbb0d044e4333b960a5d712e01d67",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"b6f6ae064c534c99b898dfc3c616939f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1de3a3ae52647d7b21cde0d5ec83b67",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"86dcecd6b89f4ffdaaf52127bbce451c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3bdbc5d938d942c18277f705a542943e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u131.png"}},
{
                  "id":"0a85ee69685c49bba34fbead2e1343ec",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6614baa7530432abc18b9aebfe1dc79",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"aaa8ab59a19a4a5ab56e64da41b2def5",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"256f53253cc642cdb740d09e109feb45",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"6720c215d4524ea0bd748ed50e0c0266",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ba3c455f9fa4394b8ec127f8ae6d1e5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}}]},
{
              "id":"d7be63cdff2a4cf585ef8b872299e7a6",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0795096589f348b385a56108ad52d2e6",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b4cc1fa4fd54438b159e3d3b8e2ede6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"07bf997d159d4a6fa739ffdcc5a0b4bb",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"01358a8230254c409d5e5e8a854a0544",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d8304a4992e7421f86e2c402e31099d6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"3c078988f49345448508f1d7077d4bbd",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e086e51edb92421ab37eed4ebe9c228a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"b134a66dec3a47549be0e8541d601e6a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f2afd447f81b451897fe74e57b55bb6b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u153.png"}},
{
                      "id":"e836ed1a948b42cca0491394f8136a92",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4784817d056d4ecab1117285f1914eac",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"a9b3dee9c6ef44beb3fb0a28864b3e68",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"993581929bb0428aa9aa92655a5f2dbb",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"9f18dd05cfa8434c9e13de06a52aa9b6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"93fc90b6087647a9a26521046718cb62",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"e556600737a54043a8c71060f56b36b1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"787b67885a334c199ffecd140b505fd2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"3b3e1e52eb44479c9dee91c159d233ff",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5590536350404100a05ae7f5fc9e752d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"b611682af9784b09a288e6578dfbe2f5",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ddf3698a716f4de491d8e8c282b12b79",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}}]}],
              "parentCellId":"b6f6ae064c534c99b898dfc3c616939f"}]},
{
          "id":"e910f4604bed4ffca97b43d220fd793f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":853,
              "y":-2},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98f121b1219d41b39629cce58990f357",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":853,
                  "y":-2},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "91fd0536228e413688a866d170ef89e7":{
      "scriptId":"u0"},
    "50b84a298d6040f9af396594bcf8b5e1":{
      "scriptId":"u1"},
    "8738d7c634ff431f90aff775938b2196":{
      "scriptId":"u2"},
    "df91ca1c921c4ba8b5a4d445c5a90880":{
      "scriptId":"u3"},
    "eadb8f47785646d384c8bad0496304cd":{
      "scriptId":"u4"},
    "35b073a5a5554d4eb91be4eb6193053e":{
      "scriptId":"u5"},
    "da6a754d7ada403d874eb8433876e1c5":{
      "scriptId":"u6"},
    "b3a5060f920144fba36907e46e3b4a6e":{
      "scriptId":"u7"},
    "b962b1da49304f9cbe89b77410271014":{
      "scriptId":"u8"},
    "c40505d84bf949f28e61db6358add47b":{
      "scriptId":"u9"},
    "08c5f91ea8eb4040945abed8d5d15471":{
      "scriptId":"u10"},
    "4c814b3dad63424d949c9398fb89935b":{
      "scriptId":"u11"},
    "ce97af5985a84357bc4db64e110c34d7":{
      "scriptId":"u12"},
    "ff0e6af3fb3442318ef5ac8a71b9f34f":{
      "scriptId":"u13"},
    "68e373bff2a64da8915ac8974bc8828b":{
      "scriptId":"u14"},
    "89b101792c51416ebb29422a28f7c010":{
      "scriptId":"u15"},
    "e9d2fc8cda8445abb61ff3e0323010e8":{
      "scriptId":"u16"},
    "1d9ae33cbef544aebd678d39c9197997":{
      "scriptId":"u17"},
    "5355a9e9553d4d96af472c7a545762cd":{
      "scriptId":"u18"},
    "b3b468a9ab8040678842f396a7a635f7":{
      "scriptId":"u19"},
    "65766b09047845b9bc38c83d8e976efe":{
      "scriptId":"u20"},
    "a94fe32727434c768d81c047878e752f":{
      "scriptId":"u21"},
    "2a47ac1c02a143c6bfea350631304a54":{
      "scriptId":"u22"},
    "aeb560596ff542e99bbcafa3c7f0da1f":{
      "scriptId":"u23"},
    "34c2f7ca572a4f2e8df7a489455e8991":{
      "scriptId":"u24"},
    "5957f203b2374380a27b3760d533f84e":{
      "scriptId":"u25"},
    "f38a4d32a83d43b588abf3dd87364653":{
      "scriptId":"u26"},
    "18841c74b7ac4363a2cb6831cfcf6600":{
      "scriptId":"u27"},
    "71c8ac427db347ad92e8ea52ab8239ad":{
      "scriptId":"u28"},
    "dca5d27e22b24881bcc5656df4470b7b":{
      "scriptId":"u29"},
    "d55e3cc044754f1baaa45d7f31e205bb":{
      "scriptId":"u30"},
    "c75e7b09279e40edae3c36eb9a5b5f03":{
      "scriptId":"u31"},
    "e77c0316ca1b4ec4b85c9e69d0016c38":{
      "scriptId":"u32"},
    "128a865fa2f5430881d159cb7e7e982f":{
      "scriptId":"u33"},
    "ef46dd87a2124910be517c73b94bcfb7":{
      "scriptId":"u34"},
    "d06e2a15929a46948e6bb56ac47b0f40":{
      "scriptId":"u35"},
    "dbd39b921b9a42d4a7d2797448945b47":{
      "scriptId":"u36"},
    "e8dc2301a0e14cdc9104e0afa14fb080":{
      "scriptId":"u37"},
    "8ceb13bbb9a84816a8a774bc67f7d5c5":{
      "scriptId":"u38"},
    "4553dca83f7c46b2ad8240175b5d82eb":{
      "scriptId":"u39"},
    "7e2b1f06740b4feb95c59644358f2aaf":{
      "scriptId":"u40"},
    "d529038ca33642b895137d066ac1ab59":{
      "scriptId":"u41"},
    "77d2ec8187a443dc9dd8ccb262446aae":{
      "scriptId":"u42"},
    "3ce00153cdf94f9ca4e93a98e865b2ec":{
      "scriptId":"u43"},
    "f462f65fce0e4522946285e5432a1817":{
      "scriptId":"u44"},
    "f589e1f72ab84d59b2eaaea6d0f22d9b":{
      "scriptId":"u45"},
    "b6f6288bc8c640e5ac871fab307d3b54":{
      "scriptId":"u46"},
    "d1416eeb74464f33aa294f4ee500898b":{
      "scriptId":"u47"},
    "44f91ba226d44cfb8342a76e6018ae28":{
      "scriptId":"u48"},
    "d7d4561fd74448799f10198722c2ee76":{
      "scriptId":"u49"},
    "8aa016dbff00491fa9c828749405d556":{
      "scriptId":"u50"},
    "b38432cf75fa4e219373ff8994f3f81d":{
      "scriptId":"u51"},
    "ab0d8c302c1546c3a048304d8371d24c":{
      "scriptId":"u52"},
    "abb8cfe3f3404e1194b8f3b7007585ab":{
      "scriptId":"u53"},
    "e23b3f89cb8f481397a53676ef471698":{
      "scriptId":"u54"},
    "011ce7857d1e49b9b1801bf49062ca58":{
      "scriptId":"u55"},
    "85d175fffec64791acec8b42f5520b94":{
      "scriptId":"u56"},
    "d19c03eebd4143fbae6e107439e917cf":{
      "scriptId":"u57"},
    "750317bc0f624dc49df86113c62347b8":{
      "scriptId":"u58"},
    "8f4046d8956e4f1b9acd03519a5c4120":{
      "scriptId":"u59"},
    "1b7e67c188f94cac991e53399b769f5f":{
      "scriptId":"u60"},
    "475d19a063a3434a9c3e5bf12682119d":{
      "scriptId":"u61"},
    "3800ab1a3ff7462e82861ba4f89a642a":{
      "scriptId":"u62"},
    "b44aa93e84454b16bfddf85b61783d34":{
      "scriptId":"u63"},
    "4727459329774a70b1e5cad2d45a39d8":{
      "scriptId":"u64"},
    "fffb46ad8bb7478e993269c4daf80630":{
      "scriptId":"u65"},
    "4687ed997bb54ddb8642a9951c88cce7":{
      "scriptId":"u66"},
    "05886fda489847618c2894a3dde86a1b":{
      "scriptId":"u67"},
    "4ccac057d3f847b6bb41b9df6602d62d":{
      "scriptId":"u68"},
    "8b2a1f0da9704f03a4fa4623848bcb98":{
      "scriptId":"u69"},
    "b0d74a25154048b984f57e8107218274":{
      "scriptId":"u70"},
    "c99180428c2946108c943d02e1c1c2e5":{
      "scriptId":"u71"},
    "70770939600144a98ab191e9139a21ae":{
      "scriptId":"u72"},
    "04edbb0d044e4333b960a5d712e01d67":{
      "scriptId":"u73"},
    "b6f6ae064c534c99b898dfc3c616939f":{
      "scriptId":"u74"},
    "d1de3a3ae52647d7b21cde0d5ec83b67":{
      "scriptId":"u75"},
    "6720c215d4524ea0bd748ed50e0c0266":{
      "scriptId":"u76"},
    "3ba3c455f9fa4394b8ec127f8ae6d1e5":{
      "scriptId":"u77"},
    "aaa8ab59a19a4a5ab56e64da41b2def5":{
      "scriptId":"u78"},
    "256f53253cc642cdb740d09e109feb45":{
      "scriptId":"u79"},
    "0a85ee69685c49bba34fbead2e1343ec":{
      "scriptId":"u80"},
    "a6614baa7530432abc18b9aebfe1dc79":{
      "scriptId":"u81"},
    "86dcecd6b89f4ffdaaf52127bbce451c":{
      "scriptId":"u82"},
    "3bdbc5d938d942c18277f705a542943e":{
      "scriptId":"u83"},
    "d7be63cdff2a4cf585ef8b872299e7a6":{
      "scriptId":"u84"},
    "0795096589f348b385a56108ad52d2e6":{
      "scriptId":"u85"},
    "5b4cc1fa4fd54438b159e3d3b8e2ede6":{
      "scriptId":"u86"},
    "07bf997d159d4a6fa739ffdcc5a0b4bb":{
      "scriptId":"u87"},
    "01358a8230254c409d5e5e8a854a0544":{
      "scriptId":"u88"},
    "d8304a4992e7421f86e2c402e31099d6":{
      "scriptId":"u89"},
    "3c078988f49345448508f1d7077d4bbd":{
      "scriptId":"u90"},
    "e086e51edb92421ab37eed4ebe9c228a":{
      "scriptId":"u91"},
    "9f18dd05cfa8434c9e13de06a52aa9b6":{
      "scriptId":"u92"},
    "93fc90b6087647a9a26521046718cb62":{
      "scriptId":"u93"},
    "a9b3dee9c6ef44beb3fb0a28864b3e68":{
      "scriptId":"u94"},
    "993581929bb0428aa9aa92655a5f2dbb":{
      "scriptId":"u95"},
    "e836ed1a948b42cca0491394f8136a92":{
      "scriptId":"u96"},
    "4784817d056d4ecab1117285f1914eac":{
      "scriptId":"u97"},
    "b611682af9784b09a288e6578dfbe2f5":{
      "scriptId":"u98"},
    "ddf3698a716f4de491d8e8c282b12b79":{
      "scriptId":"u99"},
    "3b3e1e52eb44479c9dee91c159d233ff":{
      "scriptId":"u100"},
    "5590536350404100a05ae7f5fc9e752d":{
      "scriptId":"u101"},
    "e556600737a54043a8c71060f56b36b1":{
      "scriptId":"u102"},
    "787b67885a334c199ffecd140b505fd2":{
      "scriptId":"u103"},
    "b134a66dec3a47549be0e8541d601e6a":{
      "scriptId":"u104"},
    "f2afd447f81b451897fe74e57b55bb6b":{
      "scriptId":"u105"},
    "e910f4604bed4ffca97b43d220fd793f":{
      "scriptId":"u106"},
    "98f121b1219d41b39629cce58990f357":{
      "scriptId":"u107"}}});