$axure.loadCurrentPage({
  "url":"новость.html",
  "generationDate":new Date(1493365932484.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3fcf91df7b2746bcbb7abcbcf104fa1a",
    "type":"Axure:Page",
    "name":"Новость",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03be04e4d9ec46e09f6faf0930e72b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":147},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a0e0e7e718e410899cc566307402e6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":147},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45ab25c68803417f8793ec8daf32cfb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":148},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0717e6d0ea4e3f8ba47540ff5fbb5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":148},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0af0720520cc410e8b21ead86a6d1093",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":150},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"ccf245d0d125411eb4597f8d57e5fff5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":151},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"c24e50e8916b434fbd4b3a8688698c5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":163,
              "y":149},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f9c9bb06654bf095321ebbe11e023d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":163,
                  "y":149},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83af2d8bba1d4cc6b2c25ee74ea2e33f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":24,
              "y":192},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa95f5e707a140c5896e083cff3506c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":24,
                  "y":192},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70130f091b2943f0ab4695523d94de9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":26,
              "y":221},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ca687ca63be4dd3aa297562fac99eed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":26,
                  "y":221},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d75a867e461f4479b725bcff56728443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":260},
            "size":{
              "width":386,
              "height":262}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c0ceb5d9bbc4c238053eb75bbc2a922",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":260},
                "size":{
                  "width":386,
                  "height":262}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u12.png"}},
{
          "id":"a85978e8c29b407b833d96aff2fa6b33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":277,
              "y":242},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75015907e796498681eac23efe6acc39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":277,
                  "y":242},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d07c1c22f4442e0a716315e2cc279f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":242},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c89c545732f646fc9183725a49cb9268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":242},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u16.png"}},
{
          "id":"3dc738e55a4b48c2aaae2acddd0f280a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":242},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eea4fc0e464a411186d8606860f5cf64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":242},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u18.png"}},
{
          "id":"a44a04f2cc844df280293b9722e04887",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":441,
              "y":260},
            "size":{
              "width":560,
              "height":472}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"768d23be14ef44a6a0ba5e662379f187",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":441,
                  "y":260},
                "size":{
                  "width":560,
                  "height":472}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f63216c85fab412ba905a07e153d75c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1,
              "y":756},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1f7c44273e4f5e87098a63962605c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1,
                  "y":756},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/о_нас/u33.png"}},
{
          "id":"76cabf06a0a44b9db8eb766ad399d05a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15483562ab5943f3a32771064a5d4325",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":0},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"7f6c8faf7f674e3da86bd6ecc352f4b7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"09d77011141b49ecbb5dafd25eff71cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a2252fdc0e47d6b9c066a5e47516a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c2a1409553b4ec8a99a3d0e99c01eef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1285e2779fe94e3d9d6f1d6b519e4115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"e409f4a4845b47cea703000c37810d24",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"47ccc0fbd9214287be7ca57180576325",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle Konsult",
                      "objectsToFades":[{
                          "objectPath":["0948d535055a41168d96e3795d7baf69"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"99dfb7f33da648a98623c5e6d27868de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":252,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c780de7dd0f4011a8877470be10ba23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":252,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be3c3132846d436c9811b31cf3762b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":33},
            "size":{
              "width":130,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568f5b1b3b0846ee879a0c4ef8e472fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":33},
                "size":{
                  "width":130,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48ce011ae67e424c9ae325f827011976",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":641,
              "y":34},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4cc04c2a9fd4eb590344b957cdd58e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":641,
                  "y":34},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eba0e6930f4d41019d80fc0d6038dcf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":4},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1877d2b9045d421285fdf01fabd24f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":4},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e42c60c7b3294b8aafa30c11cf963f9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":916,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12e87a986f504fc99479ed3c6e3b34c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":916,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"94e7295579284787aa250c576b90dbd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"620ebd60ed0a4689ab0fc5c1e709f36f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"6dddd30ac1e94ae8bac96cf91be2b9d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":971,
              "y":7},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76fdc3b7dda45bb9d265433f82317cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":971,
                  "y":7},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u21.png"}},
{
          "id":"1031531b529e4b1ab5e1de4ddb6bad94",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":66},
            "size":{
              "width":500,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d65f4a6e900c49d684f4fdff10064d2f",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2c0a1316f214c078f705e43c972f3b2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"688d80d38f7c4ac088a553f32cfac55c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}},
{
                  "id":"b031d08de8cb41c8bcc64f752e892ae0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"771e77a5aa154bddb9516f32b8553ddd",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}},
{
                  "id":"a12d8eab88384010a7610c984751f9a3",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"baf48ee893a14a4a9d6ca175225e8f36",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u104.png"}},
{
                  "id":"a938fd1920724ff1a314820019d4f0ad",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0703e397a1e14d02a8a7a14cb596909e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}},
{
                  "id":"fd61743492034f549fda55e7357d4a8b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b27b494780e5465e9c56643390b6293b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u96.png"}}]},
{
              "id":"79714c98d4ff4468911ef8471f13982d",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83780fb1a706400b87d50627acfc9f12",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80168a2eafbd4b2aa678d7ca1c26e7f9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"cecebdb5bfdd473cb32d262116ce2c52",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"e1ffe0dd0fb04b5882250e6867cc67b9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b6b64c03904a40eca242e288d7f148b4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u110.png"}},
{
                      "id":"59cc8e5f37994d35b160490b148e0913",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"70d53824c87c4a3f9b9137b5336012f4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"e2091b8c08b543d7bb18e3b55027640b",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"548aef2e8e0f4156aa43b6f2fe470f6f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u126.png"}},
{
                      "id":"7eb40d5d2d394394a34bc8f74888db87",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0ea0aea873894d0faca643797505ecde",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u116.png"}},
{
                      "id":"f7c3179c0760421e880c0b844200ee96",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b849c9a021ea42468ea9ed6ff68eed17",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u116.png"}},
{
                      "id":"05b551cad79f46bfa66c47be3548d3b0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7779db95d635487eb2e88df436835c7a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"abd98eed008f4cdc9b9ab64cecd3b592",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a0714b6e116b447589f7b00b3ddbb359",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u108.png"}},
{
                      "id":"c7a1a4f3e0634720ba319fb7fe77ee4c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a54b414293b14aa4a3949c7148a387ed",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u110.png"}},
{
                      "id":"9e4b54ce317148d1893dd44ae1c137c4",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"05a251a0d6ed4523b71f4b0b92e2d115",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/home/u110.png"}}]}],
              "parentCellId":"b031d08de8cb41c8bcc64f752e892ae0"}]},
{
          "id":"0948d535055a41168d96e3795d7baf69",
          "label":"Konsult",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":235,
              "y":122},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a420dbc9199d4526af012b55d15f5064",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"906b94364f754ad6bc489806ade80f83",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":358}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5488ec2cd8ba4f5988532233f79c0abf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":100,
                          "y":50},
                        "size":{
                          "width":300,
                          "height":358}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u129.png"}},
{
                  "id":"47fae7d02d844fe2928bf9ba23ad1ede",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":88},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"8dd72227d8a04990998421fc1d492aa7",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":72},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05d893968b7d4ba5b8fe28facab14355",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":72},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4131dcf78f894441975ab858cf2c76c2",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":138},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"3555c0462bbf4b24be8aaefee8ed1c61",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":122},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f3539f3653c40d68591b9d0c9fa5ee8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":122},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b09d3607a02b484f966dfc5900f59418",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":188},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"45ee02af0b3f4ce499ba4ae25b952d32",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":172},
                    "size":{
                      "width":49,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"beea126d717d4fbdae274b8f885bf1e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":172},
                        "size":{
                          "width":49,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"67a3562df156469e98e1a0eae518b525",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":238},
                    "size":{
                      "width":260,
                      "height":91}},
                  "adaptiveStyles":{
}},
{
                  "id":"c2d360deab5d452bb39d4a072d83e228",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":222},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dec973be0c7e40a3bff376021fb0cf4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":222},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c8223d33009848a88b85bf5cd9b3d5ed",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":348},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show banner",
                              "objectsToFades":[{
                                  "objectPath":["018aa0335a7448dea3c345b8fa6e6c80"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"36df0839ea68437296961c94685eb4c9",
                  "label":"",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":288,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2cfe899265c4446e9d2225e86f3967be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":106,
                          "y":0},
                        "size":{
                          "width":288,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"018aa0335a7448dea3c345b8fa6e6c80",
                  "label":"banner",
                  "parentDynamicPanel":"0948d535055a41168d96e3795d7baf69",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"f70ffbcd492241eb924c0c4b7d9c7099",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"0db044ba133347a5a1f19d23c2720725",
                          "label":"",
                          "parentDynamicPanel":"018aa0335a7448dea3c345b8fa6e6c80",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "size":{
                              "width":530,
                              "height":130}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5284c80f58cc48d28ccb808ff980e0bd",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"018aa0335a7448dea3c345b8fa6e6c80",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "size":{
                                  "width":530,
                                  "height":130}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/u147.png"}},
{
                          "id":"8c46becd074441d4bd1c790d286caf7a",
                          "label":"",
                          "parentDynamicPanel":"018aa0335a7448dea3c345b8fa6e6c80",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":500,
                              "y":10},
                            "size":{
                              "width":20,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9ebb78ae77ce42beb44d7f6aa08b9236",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"018aa0335a7448dea3c345b8fa6e6c80",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":500,
                                  "y":10},
                                "size":{
                                  "width":20,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Hide banner",
                                      "objectsToFades":[{
                                          "objectPath":["018aa0335a7448dea3c345b8fa6e6c80"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/home/u149.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "03be04e4d9ec46e09f6faf0930e72b7f":{
      "scriptId":"u0"},
    "0a0e0e7e718e410899cc566307402e6c":{
      "scriptId":"u1"},
    "45ab25c68803417f8793ec8daf32cfb4":{
      "scriptId":"u2"},
    "9f0717e6d0ea4e3f8ba47540ff5fbb5e":{
      "scriptId":"u3"},
    "0af0720520cc410e8b21ead86a6d1093":{
      "scriptId":"u4"},
    "ccf245d0d125411eb4597f8d57e5fff5":{
      "scriptId":"u5"},
    "c24e50e8916b434fbd4b3a8688698c5d":{
      "scriptId":"u6"},
    "e4f9c9bb06654bf095321ebbe11e023d":{
      "scriptId":"u7"},
    "83af2d8bba1d4cc6b2c25ee74ea2e33f":{
      "scriptId":"u8"},
    "fa95f5e707a140c5896e083cff3506c3":{
      "scriptId":"u9"},
    "70130f091b2943f0ab4695523d94de9a":{
      "scriptId":"u10"},
    "6ca687ca63be4dd3aa297562fac99eed":{
      "scriptId":"u11"},
    "d75a867e461f4479b725bcff56728443":{
      "scriptId":"u12"},
    "4c0ceb5d9bbc4c238053eb75bbc2a922":{
      "scriptId":"u13"},
    "a85978e8c29b407b833d96aff2fa6b33":{
      "scriptId":"u14"},
    "75015907e796498681eac23efe6acc39":{
      "scriptId":"u15"},
    "2d07c1c22f4442e0a716315e2cc279f3":{
      "scriptId":"u16"},
    "c89c545732f646fc9183725a49cb9268":{
      "scriptId":"u17"},
    "3dc738e55a4b48c2aaae2acddd0f280a":{
      "scriptId":"u18"},
    "eea4fc0e464a411186d8606860f5cf64":{
      "scriptId":"u19"},
    "a44a04f2cc844df280293b9722e04887":{
      "scriptId":"u20"},
    "768d23be14ef44a6a0ba5e662379f187":{
      "scriptId":"u21"},
    "f63216c85fab412ba905a07e153d75c5":{
      "scriptId":"u22"},
    "8b1f7c44273e4f5e87098a63962605c8":{
      "scriptId":"u23"},
    "76cabf06a0a44b9db8eb766ad399d05a":{
      "scriptId":"u24"},
    "15483562ab5943f3a32771064a5d4325":{
      "scriptId":"u25"},
    "7f6c8faf7f674e3da86bd6ecc352f4b7":{
      "scriptId":"u26"},
    "09d77011141b49ecbb5dafd25eff71cf":{
      "scriptId":"u27"},
    "07a2252fdc0e47d6b9c066a5e47516a2":{
      "scriptId":"u28"},
    "1c2a1409553b4ec8a99a3d0e99c01eef":{
      "scriptId":"u29"},
    "1285e2779fe94e3d9d6f1d6b519e4115":{
      "scriptId":"u30"},
    "e409f4a4845b47cea703000c37810d24":{
      "scriptId":"u31"},
    "47ccc0fbd9214287be7ca57180576325":{
      "scriptId":"u32"},
    "99dfb7f33da648a98623c5e6d27868de":{
      "scriptId":"u33"},
    "0c780de7dd0f4011a8877470be10ba23":{
      "scriptId":"u34"},
    "be3c3132846d436c9811b31cf3762b83":{
      "scriptId":"u35"},
    "568f5b1b3b0846ee879a0c4ef8e472fa":{
      "scriptId":"u36"},
    "48ce011ae67e424c9ae325f827011976":{
      "scriptId":"u37"},
    "b4cc04c2a9fd4eb590344b957cdd58e0":{
      "scriptId":"u38"},
    "eba0e6930f4d41019d80fc0d6038dcf3":{
      "scriptId":"u39"},
    "1877d2b9045d421285fdf01fabd24f21":{
      "scriptId":"u40"},
    "e42c60c7b3294b8aafa30c11cf963f9c":{
      "scriptId":"u41"},
    "12e87a986f504fc99479ed3c6e3b34c5":{
      "scriptId":"u42"},
    "94e7295579284787aa250c576b90dbd5":{
      "scriptId":"u43"},
    "620ebd60ed0a4689ab0fc5c1e709f36f":{
      "scriptId":"u44"},
    "6dddd30ac1e94ae8bac96cf91be2b9d1":{
      "scriptId":"u45"},
    "f76fdc3b7dda45bb9d265433f82317cb":{
      "scriptId":"u46"},
    "1031531b529e4b1ab5e1de4ddb6bad94":{
      "scriptId":"u47"},
    "d65f4a6e900c49d684f4fdff10064d2f":{
      "scriptId":"u48"},
    "f2c0a1316f214c078f705e43c972f3b2":{
      "scriptId":"u49"},
    "688d80d38f7c4ac088a553f32cfac55c":{
      "scriptId":"u50"},
    "b031d08de8cb41c8bcc64f752e892ae0":{
      "scriptId":"u51"},
    "771e77a5aa154bddb9516f32b8553ddd":{
      "scriptId":"u52"},
    "fd61743492034f549fda55e7357d4a8b":{
      "scriptId":"u53"},
    "b27b494780e5465e9c56643390b6293b":{
      "scriptId":"u54"},
    "a938fd1920724ff1a314820019d4f0ad":{
      "scriptId":"u55"},
    "0703e397a1e14d02a8a7a14cb596909e":{
      "scriptId":"u56"},
    "a12d8eab88384010a7610c984751f9a3":{
      "scriptId":"u57"},
    "baf48ee893a14a4a9d6ca175225e8f36":{
      "scriptId":"u58"},
    "79714c98d4ff4468911ef8471f13982d":{
      "scriptId":"u59"},
    "83780fb1a706400b87d50627acfc9f12":{
      "scriptId":"u60"},
    "80168a2eafbd4b2aa678d7ca1c26e7f9":{
      "scriptId":"u61"},
    "cecebdb5bfdd473cb32d262116ce2c52":{
      "scriptId":"u62"},
    "e1ffe0dd0fb04b5882250e6867cc67b9":{
      "scriptId":"u63"},
    "b6b64c03904a40eca242e288d7f148b4":{
      "scriptId":"u64"},
    "59cc8e5f37994d35b160490b148e0913":{
      "scriptId":"u65"},
    "70d53824c87c4a3f9b9137b5336012f4":{
      "scriptId":"u66"},
    "05b551cad79f46bfa66c47be3548d3b0":{
      "scriptId":"u67"},
    "7779db95d635487eb2e88df436835c7a":{
      "scriptId":"u68"},
    "f7c3179c0760421e880c0b844200ee96":{
      "scriptId":"u69"},
    "b849c9a021ea42468ea9ed6ff68eed17":{
      "scriptId":"u70"},
    "7eb40d5d2d394394a34bc8f74888db87":{
      "scriptId":"u71"},
    "0ea0aea873894d0faca643797505ecde":{
      "scriptId":"u72"},
    "9e4b54ce317148d1893dd44ae1c137c4":{
      "scriptId":"u73"},
    "05a251a0d6ed4523b71f4b0b92e2d115":{
      "scriptId":"u74"},
    "c7a1a4f3e0634720ba319fb7fe77ee4c":{
      "scriptId":"u75"},
    "a54b414293b14aa4a3949c7148a387ed":{
      "scriptId":"u76"},
    "abd98eed008f4cdc9b9ab64cecd3b592":{
      "scriptId":"u77"},
    "a0714b6e116b447589f7b00b3ddbb359":{
      "scriptId":"u78"},
    "e2091b8c08b543d7bb18e3b55027640b":{
      "scriptId":"u79"},
    "548aef2e8e0f4156aa43b6f2fe470f6f":{
      "scriptId":"u80"},
    "0948d535055a41168d96e3795d7baf69":{
      "scriptId":"u81"},
    "906b94364f754ad6bc489806ade80f83":{
      "scriptId":"u82"},
    "5488ec2cd8ba4f5988532233f79c0abf":{
      "scriptId":"u83"},
    "47fae7d02d844fe2928bf9ba23ad1ede":{
      "scriptId":"u84"},
    "8dd72227d8a04990998421fc1d492aa7":{
      "scriptId":"u85"},
    "05d893968b7d4ba5b8fe28facab14355":{
      "scriptId":"u86"},
    "4131dcf78f894441975ab858cf2c76c2":{
      "scriptId":"u87"},
    "3555c0462bbf4b24be8aaefee8ed1c61":{
      "scriptId":"u88"},
    "0f3539f3653c40d68591b9d0c9fa5ee8":{
      "scriptId":"u89"},
    "b09d3607a02b484f966dfc5900f59418":{
      "scriptId":"u90"},
    "45ee02af0b3f4ce499ba4ae25b952d32":{
      "scriptId":"u91"},
    "beea126d717d4fbdae274b8f885bf1e8":{
      "scriptId":"u92"},
    "67a3562df156469e98e1a0eae518b525":{
      "scriptId":"u93"},
    "c2d360deab5d452bb39d4a072d83e228":{
      "scriptId":"u94"},
    "dec973be0c7e40a3bff376021fb0cf4e":{
      "scriptId":"u95"},
    "c8223d33009848a88b85bf5cd9b3d5ed":{
      "scriptId":"u96"},
    "36df0839ea68437296961c94685eb4c9":{
      "scriptId":"u97"},
    "2cfe899265c4446e9d2225e86f3967be":{
      "scriptId":"u98"},
    "018aa0335a7448dea3c345b8fa6e6c80":{
      "scriptId":"u99"},
    "0db044ba133347a5a1f19d23c2720725":{
      "scriptId":"u100"},
    "5284c80f58cc48d28ccb808ff980e0bd":{
      "scriptId":"u101"},
    "8c46becd074441d4bd1c790d286caf7a":{
      "scriptId":"u102"},
    "9ebb78ae77ce42beb44d7f6aa08b9236":{
      "scriptId":"u103"}}});