$axure.loadCurrentPage({
  "url":"донорам_крови.html",
  "generationDate":new Date(1494499903052.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"fa19c3bda4994a09970b91eefc457f6c",
    "type":"Axure:Page",
    "name":"Донорам крови",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4070f4c21bc7437187b83d55e2e21d5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":1090},
            "size":{
              "width":220,
              "height":220},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"562e29abedfc4f4cbd5ce95797a6bfd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":1090},
                "size":{
                  "width":220,
                  "height":220},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/донорам_крови/u0.png"}},
{
          "id":"7e32e54590284e1898a7da1bb1d0d5df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":0,
              "y":392},
            "size":{
              "width":1001,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4899978158f49f7ab0ef584e628e197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":0,
                  "y":392},
                "size":{
                  "width":1001,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/донорам_крови/u2.png"}},
{
          "id":"eb5841bb4cee445bad569ce4b996110e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b40b439ce62144edb3ddb6747b37acc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"4e4d80aca1264e40843a4e4cd844f44b",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":158},
            "size":{
              "width":500,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b41c77a0de244ef9850b1075aed9012c",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":500,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54ed582cdf194f94b1e550bf16dacb97",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87f14f06669d41ccb6cb529ffabb2c0f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"997fb7af9179432d92583cefb8ae995b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f588a50000ba431d85612bb259930704",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"064954679063463b8acf9fbf1f5c3674",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":414,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e91c97ce3df54e0e99d0720011964c31",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":414,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"2dcccd420fd44e5ea2d2beeaf2b39223",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9705888045bf4167a55c0a0d8c8ad61b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u39.png"}},
{
                  "id":"5d072a7f99924510abae6c9f436f4798",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b62e041cdb14c1a9150303bed52ce77",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":314,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"d2ef9c0dfac24aa1a8a745f299718fac",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55fd22edbf0c48fcb3b33eb177f15f30",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09d14d9747fa40949c4cbacc0283428e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8e6b059b3b0f42389b28c58cd68081d9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u47.png"}},
{
                      "id":"b5d815bccf184025ab36adcc330e9ed5",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9fbd912d173244cfa5407f9ed3504950",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"12328db4d798434aae0e775da7fbb2da",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7a901c4d39224dda8d930b07f9025963",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u49.png"}},
{
                      "id":"309cc31f194b4d348aa813b11e32cb3d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"228c4092d171403b9342379e233188b3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"93e4c9d071fb4273b1a1e28f92571dd8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fc4b29195ed8465bb6bab007db45343f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}}]}],
              "parentCellId":"997fb7af9179432d92583cefb8ae995b"}]},
{
          "id":"7f618262f8db40c0846a06762b83239b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":30},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u57_image_sketch.png",
            "disabled~":"images/главная/u57_disabled.png"}},
{
          "id":"b08721a911f142d6bec673e958f25a89",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":68},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u58_image_sketch.png",
            "disabled~":"images/главная/u58_disabled.png"}},
{
          "id":"0fdbd4e9733f4294bc7c343895a41332",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":128},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"a696696dddcb4e7297d218afc103a835",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":28},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a128c1e877456b857eeb8ed9a9e579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":28},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5f7b2281c9849e48bc0dbe6152a1ae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":57},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3391b5a56e48429b8114175fc9b3643d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":57},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62346e2aec9c4818876b0890afa4e034",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93a4e5a3a4e8420180d7106bab52c5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u74.png"}},
{
          "id":"2cc8026d6bf1461fbacb61e8791fd074",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":29},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81a7956a346847b8be7d9de01ecc06ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":29},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u76.png"}},
{
          "id":"6209b76f8b634593aa5272284df33f62",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":167},
            "size":{
              "width":150,
              "height":29}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u69_image_sketch.png",
            "disabled~":"images/главная/u69_disabled.png"}},
{
          "id":"64e17cb2d4d44e45868afd16b1e16150",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":792,
              "y":5},
            "size":{
              "width":207,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e557fb0f07634725b075c681f78f11f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":792,
                  "y":5},
                "size":{
                  "width":207,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54f3601dee9b41d49dec44a36ad00fdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":220},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dc9578776cd4849b80b903a42eca452",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":220},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a686826771c94ea5b63db93b9c08a0a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":221},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bb93fabb3964d6d8b353a6365818c31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":221},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd49e4e80e484be194372af27395d812",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":223},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"714977d8a7df4179a7edf64ad19026dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":419,
              "y":287},
            "size":{
              "width":165,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c424ed8ec15147f184959f89c7899561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":419,
                  "y":287},
                "size":{
                  "width":165,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22a77fa9e9514ad381c8a95ba1810d3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":419,
              "y":352},
            "size":{
              "width":162,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0099e53cb9f4363a881d10488fde351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":419,
                  "y":352},
                "size":{
                  "width":162,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"695975572dce42c29cad188c76c6b7a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":402},
            "size":{
              "width":980,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"221473aa5791409ca7dbe49b8a3cc0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":402},
                "size":{
                  "width":980,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81ab1b6522a74ade97fd6b9a8f3bc3c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":10,
              "y":723},
            "size":{
              "width":278,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee74034740064aa88803709b743edf4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":10,
                  "y":723},
                "size":{
                  "width":278,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e0166d52d4543a0926a544b66e9dddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":364,
              "y":723},
            "size":{
              "width":269,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347d941516f147b29d1d3756c39b5aea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":364,
                  "y":723},
                "size":{
                  "width":269,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6c76e2f22f64f3f86c5201933fe2051",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":763,
              "y":723},
            "size":{
              "width":173,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4566e3cbd3cb4bc293d9422b74a44649",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":763,
                  "y":723},
                "size":{
                  "width":173,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38a276a10b9d4695ae7180d1118f4116",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":10,
              "y":760},
            "size":{
              "width":278,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccac834ffd3f409f8e1870ce7ad57e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":10,
                  "y":760},
                "size":{
                  "width":278,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/донорам_крови/u61.png"}},
{
          "id":"144c4e9c1c424fefbe77957be70cbfcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":361,
              "y":760},
            "size":{
              "width":278,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6e846ba93564b24a15aa4251d2fe859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":361,
                  "y":760},
                "size":{
                  "width":278,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/донорам_крови/u61.png"}},
{
          "id":"c2c764c70acb443fbc9480aa3ecc31f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":712,
              "y":760},
            "size":{
              "width":278,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1f2fadc8e84ee3866163b68f622264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":712,
                  "y":760},
                "size":{
                  "width":278,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/донорам_крови/u61.png"}},
{
          "id":"332b1fc68deb450ea0bb52c61a6c96a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":780},
            "size":{
              "width":256,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41760cb8621b44568e6f16fec0c488f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":780},
                "size":{
                  "width":256,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"688cdfa8c2144509808ef8a6b50203a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":780},
            "size":{
              "width":256,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bf857c7a0414e91af5e813228d037aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":780},
                "size":{
                  "width":256,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfab5f324210430a81dd62331be3055e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":723,
              "y":781},
            "size":{
              "width":256,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4824f042a46540eb8373c826549744ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":723,
                  "y":781},
                "size":{
                  "width":256,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19c53e6004df468890275dd14c66ce19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":1090},
            "size":{
              "width":220,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0336b01438e47ac820437e4def294c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":1090},
                "size":{
                  "width":220,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c93b82089df4cd4a682283e273c2e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":361,
              "y":1090},
            "size":{
              "width":629,
              "height":220},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce8c32eaa7864def998086a5e03f31b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":361,
                  "y":1090},
                "size":{
                  "width":629,
                  "height":220},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/донорам_крови/u75.png"}},
{
          "id":"76af5ac95161432b9cd76a6e2cd2898b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-4,
              "y":1373},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ae870c5cb74b2f9a2be8662d91c14b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-4,
                  "y":1373},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4070f4c21bc7437187b83d55e2e21d5b":{
      "scriptId":"u0"},
    "562e29abedfc4f4cbd5ce95797a6bfd7":{
      "scriptId":"u1"},
    "7e32e54590284e1898a7da1bb1d0d5df":{
      "scriptId":"u2"},
    "f4899978158f49f7ab0ef584e628e197":{
      "scriptId":"u3"},
    "eb5841bb4cee445bad569ce4b996110e":{
      "scriptId":"u4"},
    "b40b439ce62144edb3ddb6747b37acc6":{
      "scriptId":"u5"},
    "4e4d80aca1264e40843a4e4cd844f44b":{
      "scriptId":"u6"},
    "b41c77a0de244ef9850b1075aed9012c":{
      "scriptId":"u7"},
    "54ed582cdf194f94b1e550bf16dacb97":{
      "scriptId":"u8"},
    "87f14f06669d41ccb6cb529ffabb2c0f":{
      "scriptId":"u9"},
    "997fb7af9179432d92583cefb8ae995b":{
      "scriptId":"u10"},
    "f588a50000ba431d85612bb259930704":{
      "scriptId":"u11"},
    "2dcccd420fd44e5ea2d2beeaf2b39223":{
      "scriptId":"u12"},
    "9705888045bf4167a55c0a0d8c8ad61b":{
      "scriptId":"u13"},
    "5d072a7f99924510abae6c9f436f4798":{
      "scriptId":"u14"},
    "2b62e041cdb14c1a9150303bed52ce77":{
      "scriptId":"u15"},
    "064954679063463b8acf9fbf1f5c3674":{
      "scriptId":"u16"},
    "e91c97ce3df54e0e99d0720011964c31":{
      "scriptId":"u17"},
    "d2ef9c0dfac24aa1a8a745f299718fac":{
      "scriptId":"u18"},
    "55fd22edbf0c48fcb3b33eb177f15f30":{
      "scriptId":"u19"},
    "09d14d9747fa40949c4cbacc0283428e":{
      "scriptId":"u20"},
    "8e6b059b3b0f42389b28c58cd68081d9":{
      "scriptId":"u21"},
    "12328db4d798434aae0e775da7fbb2da":{
      "scriptId":"u22"},
    "7a901c4d39224dda8d930b07f9025963":{
      "scriptId":"u23"},
    "309cc31f194b4d348aa813b11e32cb3d":{
      "scriptId":"u24"},
    "228c4092d171403b9342379e233188b3":{
      "scriptId":"u25"},
    "b5d815bccf184025ab36adcc330e9ed5":{
      "scriptId":"u26"},
    "9fbd912d173244cfa5407f9ed3504950":{
      "scriptId":"u27"},
    "93e4c9d071fb4273b1a1e28f92571dd8":{
      "scriptId":"u28"},
    "fc4b29195ed8465bb6bab007db45343f":{
      "scriptId":"u29"},
    "7f618262f8db40c0846a06762b83239b":{
      "scriptId":"u30"},
    "b08721a911f142d6bec673e958f25a89":{
      "scriptId":"u31"},
    "0fdbd4e9733f4294bc7c343895a41332":{
      "scriptId":"u32"},
    "a696696dddcb4e7297d218afc103a835":{
      "scriptId":"u33"},
    "d5a128c1e877456b857eeb8ed9a9e579":{
      "scriptId":"u34"},
    "b5f7b2281c9849e48bc0dbe6152a1ae3":{
      "scriptId":"u35"},
    "3391b5a56e48429b8114175fc9b3643d":{
      "scriptId":"u36"},
    "62346e2aec9c4818876b0890afa4e034":{
      "scriptId":"u37"},
    "93a4e5a3a4e8420180d7106bab52c5c6":{
      "scriptId":"u38"},
    "2cc8026d6bf1461fbacb61e8791fd074":{
      "scriptId":"u39"},
    "81a7956a346847b8be7d9de01ecc06ca":{
      "scriptId":"u40"},
    "6209b76f8b634593aa5272284df33f62":{
      "scriptId":"u41"},
    "64e17cb2d4d44e45868afd16b1e16150":{
      "scriptId":"u42"},
    "e557fb0f07634725b075c681f78f11f5":{
      "scriptId":"u43"},
    "54f3601dee9b41d49dec44a36ad00fdc":{
      "scriptId":"u44"},
    "3dc9578776cd4849b80b903a42eca452":{
      "scriptId":"u45"},
    "a686826771c94ea5b63db93b9c08a0a6":{
      "scriptId":"u46"},
    "9bb93fabb3964d6d8b353a6365818c31":{
      "scriptId":"u47"},
    "fd49e4e80e484be194372af27395d812":{
      "scriptId":"u48"},
    "714977d8a7df4179a7edf64ad19026dd":{
      "scriptId":"u49"},
    "c424ed8ec15147f184959f89c7899561":{
      "scriptId":"u50"},
    "22a77fa9e9514ad381c8a95ba1810d3a":{
      "scriptId":"u51"},
    "b0099e53cb9f4363a881d10488fde351":{
      "scriptId":"u52"},
    "695975572dce42c29cad188c76c6b7a5":{
      "scriptId":"u53"},
    "221473aa5791409ca7dbe49b8a3cc0ec":{
      "scriptId":"u54"},
    "81ab1b6522a74ade97fd6b9a8f3bc3c0":{
      "scriptId":"u55"},
    "ee74034740064aa88803709b743edf4f":{
      "scriptId":"u56"},
    "2e0166d52d4543a0926a544b66e9dddf":{
      "scriptId":"u57"},
    "347d941516f147b29d1d3756c39b5aea":{
      "scriptId":"u58"},
    "a6c76e2f22f64f3f86c5201933fe2051":{
      "scriptId":"u59"},
    "4566e3cbd3cb4bc293d9422b74a44649":{
      "scriptId":"u60"},
    "38a276a10b9d4695ae7180d1118f4116":{
      "scriptId":"u61"},
    "ccac834ffd3f409f8e1870ce7ad57e31":{
      "scriptId":"u62"},
    "144c4e9c1c424fefbe77957be70cbfcc":{
      "scriptId":"u63"},
    "b6e846ba93564b24a15aa4251d2fe859":{
      "scriptId":"u64"},
    "c2c764c70acb443fbc9480aa3ecc31f4":{
      "scriptId":"u65"},
    "2d1f2fadc8e84ee3866163b68f622264":{
      "scriptId":"u66"},
    "332b1fc68deb450ea0bb52c61a6c96a3":{
      "scriptId":"u67"},
    "41760cb8621b44568e6f16fec0c488f6":{
      "scriptId":"u68"},
    "688cdfa8c2144509808ef8a6b50203a8":{
      "scriptId":"u69"},
    "8bf857c7a0414e91af5e813228d037aa":{
      "scriptId":"u70"},
    "dfab5f324210430a81dd62331be3055e":{
      "scriptId":"u71"},
    "4824f042a46540eb8373c826549744ed":{
      "scriptId":"u72"},
    "19c53e6004df468890275dd14c66ce19":{
      "scriptId":"u73"},
    "b0336b01438e47ac820437e4def294c0":{
      "scriptId":"u74"},
    "5c93b82089df4cd4a682283e273c2e1b":{
      "scriptId":"u75"},
    "ce8c32eaa7864def998086a5e03f31b6":{
      "scriptId":"u76"},
    "76af5ac95161432b9cd76a6e2cd2898b":{
      "scriptId":"u77"},
    "a9ae870c5cb74b2f9a2be8662d91c14b":{
      "scriptId":"u78"}}});