$axure.loadCurrentPage({
  "url":"статья.html",
  "generationDate":new Date(1495780882446.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1187342d227d4011b588a9203aa27aff",
    "type":"Axure:Page",
    "name":"Статья",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c6e0aaea528433d93ca781d8aa440c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":142},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e40cc6460ccb4dcb9868c9083ba663ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":142},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02e6a0c8ba7045c1a80c571b2e43728d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":143},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffacb999d87b4a44987df3a114e435a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":143},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7737dcec3ec4d1396f2220a83e7d117",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":145},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"0c9b103c9ef34fca98b70b58192dc2fe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":146},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"7b76a8f0a652401a9864b548b1af6bea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":156,
              "y":144},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99861576b7ca490488dc6476e7f4d2da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":156,
                  "y":144},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de29684ef76d4801ab1c0bb7a1b709fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":24,
              "y":189},
            "size":{
              "width":384,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc7c9e7900524e7bbfbb2970325ff22d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":24,
                  "y":189},
                "size":{
                  "width":384,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb794ebfb16447d690a2444d3cbd35c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":26,
              "y":218},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a665fe57d16545e28a49b29a85c5a5f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":26,
                  "y":218},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07b7b881836c4b79bc58e965ae41263b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":257},
            "size":{
              "width":386,
              "height":262}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3dfa5ce7b314b13b75f9a6e0d782725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":257},
                "size":{
                  "width":386,
                  "height":262}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u12.png"}},
{
          "id":"27ba492ad05243a7accfaf81a9d0cd47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":277,
              "y":239},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3867821059483985280079dd3f26e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":277,
                  "y":239},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23c11ce6381d49bdbfccae3de316fddd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":239},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b541389de3e640899ccea5006f36b3b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":239},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u16.png"}},
{
          "id":"7879424d7e254ce4a1a884affe930f84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":239},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d4e85757bf04430a180e8fd66ba02c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":239},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/новость/u18.png"}},
{
          "id":"0cc0d2534e0942e2bd5bbd1a87bdb2ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":441,
              "y":257},
            "size":{
              "width":560,
              "height":472}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf0b9e367b64a89960c73febea226f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":441,
                  "y":257},
                "size":{
                  "width":560,
                  "height":472}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16913a30c08f44fe8c9cc7d65e67ea33",
          "label":"Konsult",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":235,
              "y":122},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5398d15d5703475495268c9188b47bea",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c9ad2accd4c54bb8be401aeaa4a8b9f1",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":358}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0278304842784886a34dafa25520c8eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":100,
                          "y":50},
                        "size":{
                          "width":300,
                          "height":358}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u81.png"}},
{
                  "id":"094fa4684e41420a845efbca2193c4f9",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":88},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"d271390254fb49829239d7ba06e8ad97",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":72},
                    "size":{
                      "width":33,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5aa532f23c3345919a3fd041536e5577",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":72},
                        "size":{
                          "width":33,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f2b8300fcf9148909b1d45b72d2b30fa",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":138},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"e748d9d868b641b5828ef592da8a5399",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":122},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d13c231be94246f9ab6697a5516af692",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":122},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"961f3a7b71624c53aaf13a99cb87ccb7",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":188},
                    "size":{
                      "width":260,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"4672eeae803b4404a26703ff2c6c1639",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":172},
                    "size":{
                      "width":49,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"759915f50baf4d5dbbf18f1f0556c7b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":172},
                        "size":{
                          "width":49,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"78908cfd5767490ea59105be2ded5d89",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":238},
                    "size":{
                      "width":260,
                      "height":91}},
                  "adaptiveStyles":{
}},
{
                  "id":"65575f7b0bf74cfb804ba29e736a3ecb",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":120,
                      "y":222},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d4ed0e367164c13a0f7e59ec46ddfd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":120,
                          "y":222},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"328b1cc77d474a83a0155fe775381208",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":348},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show banner",
                              "objectsToFades":[{
                                  "objectPath":["7e453c603fd04788a978d04659c5c2f8"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"47b28eecfda8487d80d08a7127c4dcb1",
                  "label":"",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":288,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f1734d896e54a20adaca21123829105",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":106,
                          "y":0},
                        "size":{
                          "width":288,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e453c603fd04788a978d04659c5c2f8",
                  "label":"banner",
                  "parentDynamicPanel":"16913a30c08f44fe8c9cc7d65e67ea33",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"9c9ad7d35d4c4a89b4d313d8a0c9c63e",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"9e3745326eec41768dabec90c9ab022e",
                          "label":"",
                          "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "size":{
                              "width":530,
                              "height":130}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"016cabbd6855450cb74b4ab93be7f628",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "size":{
                                  "width":530,
                                  "height":130}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/главная/u99.png"}},
{
                          "id":"20ab64f7600c4791add157862b87d259",
                          "label":"",
                          "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":500,
                              "y":10},
                            "size":{
                              "width":20,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ad6511adf2584a5585eb3679f47423cf",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"7e453c603fd04788a978d04659c5c2f8",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":500,
                                  "y":10},
                                "size":{
                                  "width":20,
                                  "height":20}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"Hide banner",
                                      "objectsToFades":[{
                                          "objectPath":["7e453c603fd04788a978d04659c5c2f8"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/главная/u101.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"eafdbd970e704d9cac5589b9181a7475",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "underline":true,
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":6,
              "y":754},
            "size":{
              "width":1000,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de17c9eca7cb404fb268155f79122aa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "underline":true,
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":6,
                  "y":754},
                "size":{
                  "width":1000,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u105.png"}},
{
          "id":"8fc3757781dc4c059bb0df3565705720",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":825},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0d125fb1c594a218f41ddfd8a7afff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":825},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u107.png"}},
{
          "id":"8aadfbab81ac4d398541e89bd8ea5543",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":825},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe381dbf0a7d429c9477b4ddaab964a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":825},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u109.png"}},
{
          "id":"abd2c61357f449e1b1750b84f967f3e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":825},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"093037c9e1f54de2b0e5e058628fe68c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":825},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u111.png"}},
{
          "id":"6805bf73d28b4e29bced89d1dc45f540",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":59,
              "y":785},
            "size":{
              "width":242,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcc902151eeb49c2a31764d6432896f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":59,
                  "y":785},
                "size":{
                  "width":242,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c8c33c2380a46baabf848a607ee5eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":828},
            "size":{
              "width":311,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf0834c754894572928e829238429d9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":828},
                "size":{
                  "width":311,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39d6be4837b8429c8ebef66fc417b0bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":391,
              "y":785},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b19891ae91ad4f668b010380e043cd16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":391,
                  "y":785},
                "size":{
                  "width":93,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5a78ccbc0cc4f93b598280ebd79cc39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":160,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47c5dad3179141f28e4a1cbd8fdd669c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":160,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"bbabfb5b0d5c43b5a9c4cfae8bea891a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"16afbf0a0cbe428389310f085ac79e65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05dd9b357abf4fc6b65790fa41249c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98490edf951f44deaf38495ed1adc917",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea0efd9485a84c5aaf1c884e36711a55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"a245275e7bee4be7bc898ac4b3bd0cd6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5ed4ab5372db4005be6acbaaab4bb917",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"8f5e068bd0424185a18e438afea310c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":3},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58f2bf710abb4644b2bc89e7cc8d7102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":3},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05de0bc7c87e4e41a6ee2bea99865e98",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":66},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b7c8f05b5cc4d1e8d5777852a31fa44",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f69340b4bd074782badfe37580dd6119",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d30b45d460a842c69f73b5747a60b670",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"cfa623465b164e4a8afa200cabf20097",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87be3d7943af4253be69252839531c9e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"e70a3f792de84163a0a42772d95bf80a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b85e5d9bf5124fdeab37bbbbaa131a3c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u131.png"}},
{
                  "id":"c6ea7e209ddb4aadb0edee867afc032f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2feb1940ddf43caab99f81351636e89",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"e96d28fc08e348f09065e8ab5b183152",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b70ebbd80f804d3a90042b97ed724ec5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"1559f8bc70094a038a40ad76e63b6bc2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3daa68e61e4b4a109e339421dde366d2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}}]},
{
              "id":"e1f85aaedf4e45fa811889a3ee09fe0b",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"af1316f18ae747e3a7c2467762ade151",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbed6fffdec443c68705d9db8fa0d351",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b91b01e15c134bd48e62f41124ddae5d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"afe57d5d88e84a43a4ed36f705c65c00",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"27368ac34d564c5786fdd9fbbbe50ccd",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"a675daa3454a4274ad956605943d6fa2",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d35745f7cbb640adbaa7aa1ef4399408",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"16941ee24ffb477494611a9190a4dba8",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d2324a497a5b4be898f265ef6843372f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u153.png"}},
{
                      "id":"da021a29c4744552a36f58d484f44e51",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a83c55a6dba841ef9b9ead809d5a68e5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"7580b7edfe274929aee2ca7a467aeb26",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ed9b2c391dd0461db81fbf0fb94ef1f4",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"7d600df8b9f54984998eb4378873ffdc",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3be1cd6ff8a44165ae3d973df74d4ba8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"5605d6aa4a0746d6aa756c75db1c5699",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"aced0c4974614daf8d67abe635f722e8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"30d01834fe1144e48d8838e3cc36e4ac",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"418696f6e7c54028b46b0061a5702643",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"844cfa09b3af4950bbd09e0d09700d07",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"75df1dc937744e34946fcdc3b0b25c76",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}}]}],
              "parentCellId":"cfa623465b164e4a8afa200cabf20097"}]},
{
          "id":"94d8b5c3477c4a528c5b0ed809138762",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":853,
              "y":-2},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"455b460d5eca4ec5a71764b9cbf03d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":853,
                  "y":-2},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4c6e0aaea528433d93ca781d8aa440c6":{
      "scriptId":"u0"},
    "e40cc6460ccb4dcb9868c9083ba663ac":{
      "scriptId":"u1"},
    "02e6a0c8ba7045c1a80c571b2e43728d":{
      "scriptId":"u2"},
    "ffacb999d87b4a44987df3a114e435a9":{
      "scriptId":"u3"},
    "a7737dcec3ec4d1396f2220a83e7d117":{
      "scriptId":"u4"},
    "0c9b103c9ef34fca98b70b58192dc2fe":{
      "scriptId":"u5"},
    "7b76a8f0a652401a9864b548b1af6bea":{
      "scriptId":"u6"},
    "99861576b7ca490488dc6476e7f4d2da":{
      "scriptId":"u7"},
    "de29684ef76d4801ab1c0bb7a1b709fb":{
      "scriptId":"u8"},
    "dc7c9e7900524e7bbfbb2970325ff22d":{
      "scriptId":"u9"},
    "bb794ebfb16447d690a2444d3cbd35c2":{
      "scriptId":"u10"},
    "a665fe57d16545e28a49b29a85c5a5f7":{
      "scriptId":"u11"},
    "07b7b881836c4b79bc58e965ae41263b":{
      "scriptId":"u12"},
    "e3dfa5ce7b314b13b75f9a6e0d782725":{
      "scriptId":"u13"},
    "27ba492ad05243a7accfaf81a9d0cd47":{
      "scriptId":"u14"},
    "ed3867821059483985280079dd3f26e5":{
      "scriptId":"u15"},
    "23c11ce6381d49bdbfccae3de316fddd":{
      "scriptId":"u16"},
    "b541389de3e640899ccea5006f36b3b7":{
      "scriptId":"u17"},
    "7879424d7e254ce4a1a884affe930f84":{
      "scriptId":"u18"},
    "9d4e85757bf04430a180e8fd66ba02c3":{
      "scriptId":"u19"},
    "0cc0d2534e0942e2bd5bbd1a87bdb2ae":{
      "scriptId":"u20"},
    "adf0b9e367b64a89960c73febea226f1":{
      "scriptId":"u21"},
    "16913a30c08f44fe8c9cc7d65e67ea33":{
      "scriptId":"u22"},
    "c9ad2accd4c54bb8be401aeaa4a8b9f1":{
      "scriptId":"u23"},
    "0278304842784886a34dafa25520c8eb":{
      "scriptId":"u24"},
    "094fa4684e41420a845efbca2193c4f9":{
      "scriptId":"u25"},
    "d271390254fb49829239d7ba06e8ad97":{
      "scriptId":"u26"},
    "5aa532f23c3345919a3fd041536e5577":{
      "scriptId":"u27"},
    "f2b8300fcf9148909b1d45b72d2b30fa":{
      "scriptId":"u28"},
    "e748d9d868b641b5828ef592da8a5399":{
      "scriptId":"u29"},
    "d13c231be94246f9ab6697a5516af692":{
      "scriptId":"u30"},
    "961f3a7b71624c53aaf13a99cb87ccb7":{
      "scriptId":"u31"},
    "4672eeae803b4404a26703ff2c6c1639":{
      "scriptId":"u32"},
    "759915f50baf4d5dbbf18f1f0556c7b5":{
      "scriptId":"u33"},
    "78908cfd5767490ea59105be2ded5d89":{
      "scriptId":"u34"},
    "65575f7b0bf74cfb804ba29e736a3ecb":{
      "scriptId":"u35"},
    "8d4ed0e367164c13a0f7e59ec46ddfd3":{
      "scriptId":"u36"},
    "328b1cc77d474a83a0155fe775381208":{
      "scriptId":"u37"},
    "47b28eecfda8487d80d08a7127c4dcb1":{
      "scriptId":"u38"},
    "2f1734d896e54a20adaca21123829105":{
      "scriptId":"u39"},
    "7e453c603fd04788a978d04659c5c2f8":{
      "scriptId":"u40"},
    "9e3745326eec41768dabec90c9ab022e":{
      "scriptId":"u41"},
    "016cabbd6855450cb74b4ab93be7f628":{
      "scriptId":"u42"},
    "20ab64f7600c4791add157862b87d259":{
      "scriptId":"u43"},
    "ad6511adf2584a5585eb3679f47423cf":{
      "scriptId":"u44"},
    "eafdbd970e704d9cac5589b9181a7475":{
      "scriptId":"u45"},
    "de17c9eca7cb404fb268155f79122aa3":{
      "scriptId":"u46"},
    "8fc3757781dc4c059bb0df3565705720":{
      "scriptId":"u47"},
    "f0d125fb1c594a218f41ddfd8a7afff3":{
      "scriptId":"u48"},
    "8aadfbab81ac4d398541e89bd8ea5543":{
      "scriptId":"u49"},
    "fe381dbf0a7d429c9477b4ddaab964a8":{
      "scriptId":"u50"},
    "abd2c61357f449e1b1750b84f967f3e6":{
      "scriptId":"u51"},
    "093037c9e1f54de2b0e5e058628fe68c":{
      "scriptId":"u52"},
    "6805bf73d28b4e29bced89d1dc45f540":{
      "scriptId":"u53"},
    "dcc902151eeb49c2a31764d6432896f2":{
      "scriptId":"u54"},
    "9c8c33c2380a46baabf848a607ee5eb1":{
      "scriptId":"u55"},
    "cf0834c754894572928e829238429d9b":{
      "scriptId":"u56"},
    "39d6be4837b8429c8ebef66fc417b0bf":{
      "scriptId":"u57"},
    "b19891ae91ad4f668b010380e043cd16":{
      "scriptId":"u58"},
    "b5a78ccbc0cc4f93b598280ebd79cc39":{
      "scriptId":"u59"},
    "47c5dad3179141f28e4a1cbd8fdd669c":{
      "scriptId":"u60"},
    "bbabfb5b0d5c43b5a9c4cfae8bea891a":{
      "scriptId":"u61"},
    "16afbf0a0cbe428389310f085ac79e65":{
      "scriptId":"u62"},
    "05dd9b357abf4fc6b65790fa41249c7a":{
      "scriptId":"u63"},
    "98490edf951f44deaf38495ed1adc917":{
      "scriptId":"u64"},
    "ea0efd9485a84c5aaf1c884e36711a55":{
      "scriptId":"u65"},
    "a245275e7bee4be7bc898ac4b3bd0cd6":{
      "scriptId":"u66"},
    "5ed4ab5372db4005be6acbaaab4bb917":{
      "scriptId":"u67"},
    "8f5e068bd0424185a18e438afea310c4":{
      "scriptId":"u68"},
    "58f2bf710abb4644b2bc89e7cc8d7102":{
      "scriptId":"u69"},
    "05de0bc7c87e4e41a6ee2bea99865e98":{
      "scriptId":"u70"},
    "1b7c8f05b5cc4d1e8d5777852a31fa44":{
      "scriptId":"u71"},
    "f69340b4bd074782badfe37580dd6119":{
      "scriptId":"u72"},
    "d30b45d460a842c69f73b5747a60b670":{
      "scriptId":"u73"},
    "cfa623465b164e4a8afa200cabf20097":{
      "scriptId":"u74"},
    "87be3d7943af4253be69252839531c9e":{
      "scriptId":"u75"},
    "1559f8bc70094a038a40ad76e63b6bc2":{
      "scriptId":"u76"},
    "3daa68e61e4b4a109e339421dde366d2":{
      "scriptId":"u77"},
    "e96d28fc08e348f09065e8ab5b183152":{
      "scriptId":"u78"},
    "b70ebbd80f804d3a90042b97ed724ec5":{
      "scriptId":"u79"},
    "c6ea7e209ddb4aadb0edee867afc032f":{
      "scriptId":"u80"},
    "f2feb1940ddf43caab99f81351636e89":{
      "scriptId":"u81"},
    "e70a3f792de84163a0a42772d95bf80a":{
      "scriptId":"u82"},
    "b85e5d9bf5124fdeab37bbbbaa131a3c":{
      "scriptId":"u83"},
    "e1f85aaedf4e45fa811889a3ee09fe0b":{
      "scriptId":"u84"},
    "af1316f18ae747e3a7c2467762ade151":{
      "scriptId":"u85"},
    "dbed6fffdec443c68705d9db8fa0d351":{
      "scriptId":"u86"},
    "b91b01e15c134bd48e62f41124ddae5d":{
      "scriptId":"u87"},
    "afe57d5d88e84a43a4ed36f705c65c00":{
      "scriptId":"u88"},
    "27368ac34d564c5786fdd9fbbbe50ccd":{
      "scriptId":"u89"},
    "a675daa3454a4274ad956605943d6fa2":{
      "scriptId":"u90"},
    "d35745f7cbb640adbaa7aa1ef4399408":{
      "scriptId":"u91"},
    "7d600df8b9f54984998eb4378873ffdc":{
      "scriptId":"u92"},
    "3be1cd6ff8a44165ae3d973df74d4ba8":{
      "scriptId":"u93"},
    "7580b7edfe274929aee2ca7a467aeb26":{
      "scriptId":"u94"},
    "ed9b2c391dd0461db81fbf0fb94ef1f4":{
      "scriptId":"u95"},
    "da021a29c4744552a36f58d484f44e51":{
      "scriptId":"u96"},
    "a83c55a6dba841ef9b9ead809d5a68e5":{
      "scriptId":"u97"},
    "844cfa09b3af4950bbd09e0d09700d07":{
      "scriptId":"u98"},
    "75df1dc937744e34946fcdc3b0b25c76":{
      "scriptId":"u99"},
    "30d01834fe1144e48d8838e3cc36e4ac":{
      "scriptId":"u100"},
    "418696f6e7c54028b46b0061a5702643":{
      "scriptId":"u101"},
    "5605d6aa4a0746d6aa756c75db1c5699":{
      "scriptId":"u102"},
    "aced0c4974614daf8d67abe635f722e8":{
      "scriptId":"u103"},
    "16941ee24ffb477494611a9190a4dba8":{
      "scriptId":"u104"},
    "d2324a497a5b4be898f265ef6843372f":{
      "scriptId":"u105"},
    "94d8b5c3477c4a528c5b0ed809138762":{
      "scriptId":"u106"},
    "455b460d5eca4ec5a71764b9cbf03d3b":{
      "scriptId":"u107"}}});