$axure.loadCurrentPage({
  "url":"регистрация.html",
  "generationDate":new Date(1495780883113.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c39741dfa7ed41ec9d052f622aa2cbbf",
    "type":"Axure:Page",
    "name":"Регистрация",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b52b8608e28d45c2ba51b8db8f031243",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":155},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9710533c25cf4c44913bba8039aad764",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":155},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cdab3ef9c8f4e5e86a4bb211ad24909",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":155},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6772c9376e5a4ec88ed1739e6ec0b887",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":155},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b21e5160d834b609d1d60ba2a9ec267",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":158},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_нас/u8_end.png",
            "line~":"images/о_нас/u8_line.png"}},
{
          "id":"5b297a2fb81a466aa734897792075d62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":383,
              "y":235},
            "size":{
              "width":234,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"362618f205af45998c6c136a76ddfc09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":383,
                  "y":235},
                "size":{
                  "width":234,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d95678d31a7c4487b1288ba2b19704e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":385,
              "y":284},
            "size":{
              "width":230,
              "height":420},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0efbd60c0c614c13b07993c37149326e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":385,
                  "y":284},
                "size":{
                  "width":230,
                  "height":420},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/регистрация/u7.png"}},
{
          "id":"6888786d042049eab90848bda85457bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":437,
              "y":296},
            "size":{
              "width":124,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54819f3daf7943949c7bc6e90bf437f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":437,
                  "y":296},
                "size":{
                  "width":124,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e57e3453353e4942bc1b0a6a678ab3ed",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":329},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"28856a44787248e6814bc72c2b00e87f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":365},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0a0bf04b29c94f739c7b3d4741018d78",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":401},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dcb909d51c58499294af2468bf7b90dd",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":524},
            "size":{
              "width":200,
              "height":66}},
          "adaptiveStyles":{
}},
{
          "id":"391d4e856b0a49ffa70270c144aa69b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":401,
              "y":643},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e004fb025bdb4fda8298daffda0fa52d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":474},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3226ba89099144df999f060f2bfa5de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "underline":true,
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1,
              "y":750},
            "size":{
              "width":1000,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff745f82c569423694c11fd945f7dbe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "underline":true,
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1,
                  "y":750},
                "size":{
                  "width":1000,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u105.png"}},
{
          "id":"d1a261c65526416396a6167dd6b2a351",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":821},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6cbb454a90444fbbe4c3153ab5f4ace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":821},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u107.png"}},
{
          "id":"521579c05b24458e9450982459b65bce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":821},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c80bb3a3c1d447ff9b31f4706d78ce3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":97,
                  "y":821},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u109.png"}},
{
          "id":"d7e370b3cb154ac58303c11c1d680466",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":821},
            "size":{
              "width":29,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcbdba12007144248a4279df9ea629c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":821},
                "size":{
                  "width":29,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u111.png"}},
{
          "id":"38a15fe7398141c1a7cf3dd437ec4abf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":54,
              "y":781},
            "size":{
              "width":242,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb899e6b612346c3b711c41375f4dc2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":54,
                  "y":781},
                "size":{
                  "width":242,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0737db804d344b3ebbe764dbe3219d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":824},
            "size":{
              "width":311,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c0d3aaff1bb40e79ad34a37e00d619b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":824},
                "size":{
                  "width":311,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89d6811631b14549a1ae349bc894f4d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":386,
              "y":781},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6281c362297547a0bda063b0def06793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":386,
                  "y":781},
                "size":{
                  "width":93,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20a4d501c538499e9cb1753784d0932d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":436},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"250140eb9d0f4dd5bd28f0c9aa4cec8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":160,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9735056b5f0a424eb46e722c9f526ae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":160,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u0.png"}},
{
          "id":"b617ad2f103b4e98b3373a010ed2563e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":791,
              "y":37},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
}},
{
          "id":"c379318f74154feab678477c74f57036",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":791,
              "y":21},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0b71751de364c5daec58803af179e85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":791,
                  "y":21},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"679458df1f294a8fabe923de2ffc8cff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":968,
              "y":39},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0abe4720a785434f95866a669b2d59ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":968,
                  "y":39},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u5.png"}},
{
          "id":"a4e7574f59664102b6fbf8acf2a5a36d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":939,
              "y":74},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ca56bf3d123f405c9742118ccf6390b8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":71},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"fa7a91848a694aa6bb7276268f1eb974",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":3},
            "size":{
              "width":328,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f4a49b214445b59fb23a8bb03e8e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":3},
                "size":{
                  "width":328,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b6f4c1186a449e58785c49e607cdd96",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":66},
            "size":{
              "width":600,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c66ccf37e8047fb8f6d6d77dd42e428",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee50f3775b694d9b82dcbbfa0cc1a28c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1afa7710f64d44eeb7371973fb20212b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"480b41bc25c349f2a6ce1be967156d7b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"969d7b1aa4cf4fc2b6811a4b73583756",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"02e73bd9ae1e409db93c964b464730ac",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"716f8bf772924e9babd06e30bca8d995",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u131.png"}},
{
                  "id":"fe50f547f4654c758f92b0f71ced8bc0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"171d8dd26e194122ae0947abd8fb7ded",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"3191fd29dc2442ed99bdd2c97c8ae70a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42ab82968f694394866b0509e080f0d8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}},
{
                  "id":"7618fc1c34a8402bae04f67c1b041523",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"885293deb01c4e14bf3ea418dbd0510c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u121.png"}}]},
{
              "id":"e6aace7979d04c56ba1cefb6b042ecca",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":294,
                  "height":472},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2dddadd0871345f89ec4ba219bbeea9a",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":294,
                      "height":472}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a85c01828a72448fbb550f585379e4ee",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7afdbe26e592450ea23a3513fb8f1b17",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"31629982a8464e6e9b333b09c5154193",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5cc6fea340e7432bbf61c1e889a17823",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"761a538035a540ee9b756a023a4fb4fe",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c00f0ec0fdce494bb14f2d50d43b1bee",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"b1875e36ceec485681333bf7e9e2ebc6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":436},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e08d49e3501a48518752be7a04e4cfd5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":436},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u153.png"}},
{
                      "id":"30141b513c99419ba28162bd775d46bf",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f5708fdb2b964d04a22df41273b65675",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":228},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"1155c44c49d64a94bc50678b355a4d4e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":294,
                          "height":68},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"97208121c4dc4bc299dc889e4d77b5e5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":160},
                            "size":{
                              "width":294,
                              "height":68},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u143.png"}},
{
                      "id":"30c53bf7503843c29a835f87c9c884a0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":124},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4eba012ce3b34a05ae66f674dbf2324c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":124},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"324ed85df47a4ae7881dd5042df307e6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":294,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b228de0232ab45389a72221822b9b549",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":294,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u135.png"}},
{
                      "id":"5c77225ba92e4d788d1706c010a4fa5c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":348},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5289c752700e4c2c9b12faeef4228d30",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":348},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}},
{
                      "id":"165fc2168d9a4bdb97bdaa0ece003d4a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":296},
                        "size":{
                          "width":294,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7b94fecaa14c4bbda6d8f7395f9fe8d6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":296},
                            "size":{
                              "width":294,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u137.png"}}]}],
              "parentCellId":"480b41bc25c349f2a6ce1be967156d7b"}]},
{
          "id":"f25388f6bdf241f08bdc217263a82655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":471,
              "y":601},
            "size":{
              "width":130,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e9920b4de0c41c8a316eee44fed8713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":471,
                  "y":601},
                "size":{
                  "width":130,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2885a8b7bd52473c8ce628a1c1e7fa6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":852,
              "y":8},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a52962f7610e4c06b56b90f3f56a71b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":852,
                  "y":8},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b52b8608e28d45c2ba51b8db8f031243":{
      "scriptId":"u0"},
    "9710533c25cf4c44913bba8039aad764":{
      "scriptId":"u1"},
    "7cdab3ef9c8f4e5e86a4bb211ad24909":{
      "scriptId":"u2"},
    "6772c9376e5a4ec88ed1739e6ec0b887":{
      "scriptId":"u3"},
    "7b21e5160d834b609d1d60ba2a9ec267":{
      "scriptId":"u4"},
    "5b297a2fb81a466aa734897792075d62":{
      "scriptId":"u5"},
    "362618f205af45998c6c136a76ddfc09":{
      "scriptId":"u6"},
    "d95678d31a7c4487b1288ba2b19704e0":{
      "scriptId":"u7"},
    "0efbd60c0c614c13b07993c37149326e":{
      "scriptId":"u8"},
    "6888786d042049eab90848bda85457bb":{
      "scriptId":"u9"},
    "54819f3daf7943949c7bc6e90bf437f1":{
      "scriptId":"u10"},
    "e57e3453353e4942bc1b0a6a678ab3ed":{
      "scriptId":"u11"},
    "28856a44787248e6814bc72c2b00e87f":{
      "scriptId":"u12"},
    "0a0bf04b29c94f739c7b3d4741018d78":{
      "scriptId":"u13"},
    "dcb909d51c58499294af2468bf7b90dd":{
      "scriptId":"u14"},
    "391d4e856b0a49ffa70270c144aa69b1":{
      "scriptId":"u15"},
    "e004fb025bdb4fda8298daffda0fa52d":{
      "scriptId":"u16"},
    "3226ba89099144df999f060f2bfa5de6":{
      "scriptId":"u17"},
    "ff745f82c569423694c11fd945f7dbe7":{
      "scriptId":"u18"},
    "d1a261c65526416396a6167dd6b2a351":{
      "scriptId":"u19"},
    "c6cbb454a90444fbbe4c3153ab5f4ace":{
      "scriptId":"u20"},
    "521579c05b24458e9450982459b65bce":{
      "scriptId":"u21"},
    "c80bb3a3c1d447ff9b31f4706d78ce3d":{
      "scriptId":"u22"},
    "d7e370b3cb154ac58303c11c1d680466":{
      "scriptId":"u23"},
    "fcbdba12007144248a4279df9ea629c8":{
      "scriptId":"u24"},
    "38a15fe7398141c1a7cf3dd437ec4abf":{
      "scriptId":"u25"},
    "cb899e6b612346c3b711c41375f4dc2b":{
      "scriptId":"u26"},
    "0737db804d344b3ebbe764dbe3219d30":{
      "scriptId":"u27"},
    "7c0d3aaff1bb40e79ad34a37e00d619b":{
      "scriptId":"u28"},
    "89d6811631b14549a1ae349bc894f4d4":{
      "scriptId":"u29"},
    "6281c362297547a0bda063b0def06793":{
      "scriptId":"u30"},
    "20a4d501c538499e9cb1753784d0932d":{
      "scriptId":"u31"},
    "250140eb9d0f4dd5bd28f0c9aa4cec8d":{
      "scriptId":"u32"},
    "9735056b5f0a424eb46e722c9f526ae2":{
      "scriptId":"u33"},
    "b617ad2f103b4e98b3373a010ed2563e":{
      "scriptId":"u34"},
    "c379318f74154feab678477c74f57036":{
      "scriptId":"u35"},
    "e0b71751de364c5daec58803af179e85":{
      "scriptId":"u36"},
    "679458df1f294a8fabe923de2ffc8cff":{
      "scriptId":"u37"},
    "0abe4720a785434f95866a669b2d59ab":{
      "scriptId":"u38"},
    "a4e7574f59664102b6fbf8acf2a5a36d":{
      "scriptId":"u39"},
    "ca56bf3d123f405c9742118ccf6390b8":{
      "scriptId":"u40"},
    "fa7a91848a694aa6bb7276268f1eb974":{
      "scriptId":"u41"},
    "b0f4a49b214445b59fb23a8bb03e8e67":{
      "scriptId":"u42"},
    "8b6f4c1186a449e58785c49e607cdd96":{
      "scriptId":"u43"},
    "4c66ccf37e8047fb8f6d6d77dd42e428":{
      "scriptId":"u44"},
    "ee50f3775b694d9b82dcbbfa0cc1a28c":{
      "scriptId":"u45"},
    "1afa7710f64d44eeb7371973fb20212b":{
      "scriptId":"u46"},
    "480b41bc25c349f2a6ce1be967156d7b":{
      "scriptId":"u47"},
    "969d7b1aa4cf4fc2b6811a4b73583756":{
      "scriptId":"u48"},
    "7618fc1c34a8402bae04f67c1b041523":{
      "scriptId":"u49"},
    "885293deb01c4e14bf3ea418dbd0510c":{
      "scriptId":"u50"},
    "3191fd29dc2442ed99bdd2c97c8ae70a":{
      "scriptId":"u51"},
    "42ab82968f694394866b0509e080f0d8":{
      "scriptId":"u52"},
    "fe50f547f4654c758f92b0f71ced8bc0":{
      "scriptId":"u53"},
    "171d8dd26e194122ae0947abd8fb7ded":{
      "scriptId":"u54"},
    "02e73bd9ae1e409db93c964b464730ac":{
      "scriptId":"u55"},
    "716f8bf772924e9babd06e30bca8d995":{
      "scriptId":"u56"},
    "e6aace7979d04c56ba1cefb6b042ecca":{
      "scriptId":"u57"},
    "2dddadd0871345f89ec4ba219bbeea9a":{
      "scriptId":"u58"},
    "a85c01828a72448fbb550f585379e4ee":{
      "scriptId":"u59"},
    "7afdbe26e592450ea23a3513fb8f1b17":{
      "scriptId":"u60"},
    "31629982a8464e6e9b333b09c5154193":{
      "scriptId":"u61"},
    "5cc6fea340e7432bbf61c1e889a17823":{
      "scriptId":"u62"},
    "761a538035a540ee9b756a023a4fb4fe":{
      "scriptId":"u63"},
    "c00f0ec0fdce494bb14f2d50d43b1bee":{
      "scriptId":"u64"},
    "30c53bf7503843c29a835f87c9c884a0":{
      "scriptId":"u65"},
    "4eba012ce3b34a05ae66f674dbf2324c":{
      "scriptId":"u66"},
    "1155c44c49d64a94bc50678b355a4d4e":{
      "scriptId":"u67"},
    "97208121c4dc4bc299dc889e4d77b5e5":{
      "scriptId":"u68"},
    "30141b513c99419ba28162bd775d46bf":{
      "scriptId":"u69"},
    "f5708fdb2b964d04a22df41273b65675":{
      "scriptId":"u70"},
    "165fc2168d9a4bdb97bdaa0ece003d4a":{
      "scriptId":"u71"},
    "7b94fecaa14c4bbda6d8f7395f9fe8d6":{
      "scriptId":"u72"},
    "5c77225ba92e4d788d1706c010a4fa5c":{
      "scriptId":"u73"},
    "5289c752700e4c2c9b12faeef4228d30":{
      "scriptId":"u74"},
    "324ed85df47a4ae7881dd5042df307e6":{
      "scriptId":"u75"},
    "b228de0232ab45389a72221822b9b549":{
      "scriptId":"u76"},
    "b1875e36ceec485681333bf7e9e2ebc6":{
      "scriptId":"u77"},
    "e08d49e3501a48518752be7a04e4cfd5":{
      "scriptId":"u78"},
    "f25388f6bdf241f08bdc217263a82655":{
      "scriptId":"u79"},
    "9e9920b4de0c41c8a316eee44fed8713":{
      "scriptId":"u80"},
    "2885a8b7bd52473c8ce628a1c1e7fa6b":{
      "scriptId":"u81"},
    "a52962f7610e4c06b56b90f3f56a71b3":{
      "scriptId":"u82"}}});