$axure.loadCurrentPage({
  "url":"сотрудничество.html",
  "generationDate":new Date(1493281621042.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"dbbae6f39e894f8ebb0c78616eebff69",
    "type":"Axure:Page",
    "name":"Сотрудничество",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eeea8b21842d412e901f86eb1cf26a4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":213},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaf4232411414e949c2bf7b1091f4833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":213},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d68cba0a7334bba94ec24b994077697",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":214},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f837164b63d48acabdd0cd14fdf289d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":214},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a723714aa6354a27bcf4ffa3a1a5bb48",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":216},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}},
{
          "id":"306bed2d05a649c2967263aa4357a749",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":329,
              "y":258},
            "size":{
              "width":342,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f46015b79f430fafb598f61cd393f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":329,
                  "y":258},
                "size":{
                  "width":342,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2edb853af8d64765b50eb5314b13e907",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":400,
              "y":322},
            "size":{
              "width":601,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a4a8447c3f46a69c36210fb5a10c4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":400,
                  "y":322},
                "size":{
                  "width":601,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"195658e46d384c2fb0a7ab4c4c4068b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":322},
            "size":{
              "width":306,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cc868a6532946b5a4b5a26eac6083c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":322},
                "size":{
                  "width":306,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/сотрудничество/u9.png"}},
{
          "id":"11e6004c859342af8e4ac1b6e8d87b0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":346,
              "y":582},
            "size":{
              "width":307,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51772ce8e63349f28750c808f50f066a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":346,
                  "y":582},
                "size":{
                  "width":307,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"475be5e666bf44bb8f26fdceb350a70e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":0,
              "y":628},
            "size":{
              "width":1001,
              "height":314}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e3cd3d7ca8433b9c9839cb7c3df63e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":0,
                  "y":628},
                "size":{
                  "width":1001,
                  "height":314}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/сотрудничество/u13.png"}},
{
          "id":"70fa9c461c124aa1b058f0204f87167d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":31,
              "y":658},
            "size":{
              "width":940,
              "height":254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c65b974749d488599ebea7d95b8e48a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":31,
                  "y":658},
                "size":{
                  "width":940,
                  "height":254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f6c0a10707c4da793b3c0fb6b6b7a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-2,
              "y":1229},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0239b8792194ec3a86ef36a750c184b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-2,
                  "y":1229},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"8c02e10409f048e1b7adf2ada4fe1f63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":1006},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd3505f398d47ebbd676089284e6ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":1006},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0abe647e4c1544b686d1a2f06277729d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":990},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u89_line.png"}},
{
          "id":"c7ab77f277ca403284741fda3e503596",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d6c6535fd4456086c1adfd55635ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"3771f798621e4faaaac82fd3aff8068f",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":146},
            "size":{
              "width":700,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb4ac1fc9d594a73a916d47a6dec15af",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":700,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8c3672384b84a538df25ae3710d3e9f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b110a67509f04914ade51f8c05ace7ac",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"78706f4b37344b3fa2d9eb428002459a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b95307e2fbb34a3caa2c1fa21f2233bb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"2a8fb199e62f4fb1ada8a51aab243d56",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":614,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ec9f42785834b24907248efe1731c45",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":614,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u47.png"}},
{
                  "id":"fbfc5ccd65364186b41f34ee21b0df9a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67442b73c7ac4aba8eda399121a0c7f0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"d1a79d54a5d9418c895053647e4794b3",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":514,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4af9602d4c88469e85eac80c459ffee0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":514,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"fbce0a5cddac4ee0913860fff4d8b32c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5256d7ca0740491abbfb4e5c875a4b6c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"0a4d0da15166410aa1f7509b8a722b27",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ed10f6eaed2480e984f663015b3cc2c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"921ad54afddc4241ae1aa841f179a038",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"26db55e847884252a3fa96fb84292280",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69f1fd57423d4a9aac60f4405ca712dd",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"38e3c10060e7456dbd85d0d6fc4c18cf",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"1f68ede660c0402f82e24952ee02ee25",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d0a1f276b8a14705966b897cbd0a9550",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"cc3236ca9543486d8c10138db6684ee9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"01d826b0121e4588aef22d3d3ff133d7",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"30d34a09b5df4f3295eba41fe6ab80e6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f93663b97a324158b17a00af28f1ab56",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}},
{
                      "id":"9792847aee774174a8e22a7bdd32ec4f",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"15575dd9d90d47dc8012e73bc62c5380",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u59.png"}}]}],
              "parentCellId":"78706f4b37344b3fa2d9eb428002459a"}]},
{
          "id":"d59e8a1ed76f44a5bb51ae6e2d1fa2aa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":18},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u61_image_sketch.png",
            "disabled~":"images/главная/u61_disabled.png"}},
{
          "id":"727a582fcbcb41c894c59974be1a243e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":56},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u62_image_sketch.png",
            "disabled~":"images/главная/u62_disabled.png"}},
{
          "id":"104a5563bd384a6390f203807d87370a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":141},
            "size":{
              "width":150,
              "height":44}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u73_image_sketch.png",
            "disabled~":"images/главная/u73_disabled.png"}},
{
          "id":"b346bf44e17648e3aad71a91ee0dfb09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":862,
              "y":192},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf7597ae2002490e98c1eafb6acd6ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":862,
                  "y":192},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2408324d6784c409ab61bdac7fd0e01",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":18},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u76_image_sketch.png",
            "disabled~":"images/главная/u76_disabled.png"}},
{
          "id":"6e7deea574c84e3b90d511920292b00e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":16},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8517a90168934eb79453e0d6abc4753c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":16},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f955320b0bf4076a12ff1ab61b9ea67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":45},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e566b782794c5db36b679570622dea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":45},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09bb92920e9d4edb86cee219b13f7548",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07397455f5424607a7df12a22bee8f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u81.png"}},
{
          "id":"0e7c9072272b443191b6ed1fe8a1d55d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5ad0d2d71364e949db335de407ff7bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u83.png"}},
{
          "id":"4b24b7687ee1494d91ef33f7e1c9f7d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf5b1c4d37a64f34a43940dff5b1d2bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u85.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "eeea8b21842d412e901f86eb1cf26a4b":{
      "scriptId":"u0"},
    "aaf4232411414e949c2bf7b1091f4833":{
      "scriptId":"u1"},
    "5d68cba0a7334bba94ec24b994077697":{
      "scriptId":"u2"},
    "3f837164b63d48acabdd0cd14fdf289d":{
      "scriptId":"u3"},
    "a723714aa6354a27bcf4ffa3a1a5bb48":{
      "scriptId":"u4"},
    "306bed2d05a649c2967263aa4357a749":{
      "scriptId":"u5"},
    "f5f46015b79f430fafb598f61cd393f7":{
      "scriptId":"u6"},
    "2edb853af8d64765b50eb5314b13e907":{
      "scriptId":"u7"},
    "a9a4a8447c3f46a69c36210fb5a10c4b":{
      "scriptId":"u8"},
    "195658e46d384c2fb0a7ab4c4c4068b8":{
      "scriptId":"u9"},
    "6cc868a6532946b5a4b5a26eac6083c0":{
      "scriptId":"u10"},
    "11e6004c859342af8e4ac1b6e8d87b0f":{
      "scriptId":"u11"},
    "51772ce8e63349f28750c808f50f066a":{
      "scriptId":"u12"},
    "475be5e666bf44bb8f26fdceb350a70e":{
      "scriptId":"u13"},
    "d3e3cd3d7ca8433b9c9839cb7c3df63e":{
      "scriptId":"u14"},
    "70fa9c461c124aa1b058f0204f87167d":{
      "scriptId":"u15"},
    "7c65b974749d488599ebea7d95b8e48a":{
      "scriptId":"u16"},
    "4f6c0a10707c4da793b3c0fb6b6b7a31":{
      "scriptId":"u17"},
    "f0239b8792194ec3a86ef36a750c184b":{
      "scriptId":"u18"},
    "8c02e10409f048e1b7adf2ada4fe1f63":{
      "scriptId":"u19"},
    "ecd3505f398d47ebbd676089284e6ee0":{
      "scriptId":"u20"},
    "0abe647e4c1544b686d1a2f06277729d":{
      "scriptId":"u21"},
    "c7ab77f277ca403284741fda3e503596":{
      "scriptId":"u22"},
    "91d6c6535fd4456086c1adfd55635ce3":{
      "scriptId":"u23"},
    "3771f798621e4faaaac82fd3aff8068f":{
      "scriptId":"u24"},
    "cb4ac1fc9d594a73a916d47a6dec15af":{
      "scriptId":"u25"},
    "b8c3672384b84a538df25ae3710d3e9f":{
      "scriptId":"u26"},
    "b110a67509f04914ade51f8c05ace7ac":{
      "scriptId":"u27"},
    "fbce0a5cddac4ee0913860fff4d8b32c":{
      "scriptId":"u28"},
    "5256d7ca0740491abbfb4e5c875a4b6c":{
      "scriptId":"u29"},
    "78706f4b37344b3fa2d9eb428002459a":{
      "scriptId":"u30"},
    "b95307e2fbb34a3caa2c1fa21f2233bb":{
      "scriptId":"u31"},
    "0a4d0da15166410aa1f7509b8a722b27":{
      "scriptId":"u32"},
    "2ed10f6eaed2480e984f663015b3cc2c":{
      "scriptId":"u33"},
    "fbfc5ccd65364186b41f34ee21b0df9a":{
      "scriptId":"u34"},
    "67442b73c7ac4aba8eda399121a0c7f0":{
      "scriptId":"u35"},
    "d1a79d54a5d9418c895053647e4794b3":{
      "scriptId":"u36"},
    "4af9602d4c88469e85eac80c459ffee0":{
      "scriptId":"u37"},
    "2a8fb199e62f4fb1ada8a51aab243d56":{
      "scriptId":"u38"},
    "2ec9f42785834b24907248efe1731c45":{
      "scriptId":"u39"},
    "921ad54afddc4241ae1aa841f179a038":{
      "scriptId":"u40"},
    "26db55e847884252a3fa96fb84292280":{
      "scriptId":"u41"},
    "69f1fd57423d4a9aac60f4405ca712dd":{
      "scriptId":"u42"},
    "38e3c10060e7456dbd85d0d6fc4c18cf":{
      "scriptId":"u43"},
    "cc3236ca9543486d8c10138db6684ee9":{
      "scriptId":"u44"},
    "01d826b0121e4588aef22d3d3ff133d7":{
      "scriptId":"u45"},
    "30d34a09b5df4f3295eba41fe6ab80e6":{
      "scriptId":"u46"},
    "f93663b97a324158b17a00af28f1ab56":{
      "scriptId":"u47"},
    "1f68ede660c0402f82e24952ee02ee25":{
      "scriptId":"u48"},
    "d0a1f276b8a14705966b897cbd0a9550":{
      "scriptId":"u49"},
    "9792847aee774174a8e22a7bdd32ec4f":{
      "scriptId":"u50"},
    "15575dd9d90d47dc8012e73bc62c5380":{
      "scriptId":"u51"},
    "d59e8a1ed76f44a5bb51ae6e2d1fa2aa":{
      "scriptId":"u52"},
    "727a582fcbcb41c894c59974be1a243e":{
      "scriptId":"u53"},
    "104a5563bd384a6390f203807d87370a":{
      "scriptId":"u54"},
    "b346bf44e17648e3aad71a91ee0dfb09":{
      "scriptId":"u55"},
    "bf7597ae2002490e98c1eafb6acd6ee3":{
      "scriptId":"u56"},
    "a2408324d6784c409ab61bdac7fd0e01":{
      "scriptId":"u57"},
    "6e7deea574c84e3b90d511920292b00e":{
      "scriptId":"u58"},
    "8517a90168934eb79453e0d6abc4753c":{
      "scriptId":"u59"},
    "0f955320b0bf4076a12ff1ab61b9ea67":{
      "scriptId":"u60"},
    "13e566b782794c5db36b679570622dea":{
      "scriptId":"u61"},
    "09bb92920e9d4edb86cee219b13f7548":{
      "scriptId":"u62"},
    "07397455f5424607a7df12a22bee8f74":{
      "scriptId":"u63"},
    "0e7c9072272b443191b6ed1fe8a1d55d":{
      "scriptId":"u64"},
    "e5ad0d2d71364e949db335de407ff7bb":{
      "scriptId":"u65"},
    "4b24b7687ee1494d91ef33f7e1c9f7d5":{
      "scriptId":"u66"},
    "cf5b1c4d37a64f34a43940dff5b1d2bf":{
      "scriptId":"u67"}}});