$axure.loadCurrentPage({
  "url":"главная.html",
  "generationDate":new Date(1493281617312.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"c004a6523510475cb28617b9ac4486ff",
    "type":"Axure:Page",
    "name":"Главная",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34be81924c31486e8000660f2a9319ba",
          "label":"Слайдер",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":227},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Слайдер to Next fade in 500ms wrap repeat every 4000 ms",
                      "panelsToStates":[{
                          "panelPath":["34be81924c31486e8000660f2a9319ba"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":4000,
                            "options":{
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"00507a1a76664084808839f7d93d5319",
              "label":"Слайд 1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c6e74d415a5d49a3a1347650a252b13f",
                  "label":"",
                  "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1001,
                      "height":310}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52e91c03f1ee4d85b8430119e50f24de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1001,
                          "height":310}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFEFEFE},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f53eaad37767424193812eb49c6f839d",
              "label":"Слайд 2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"73726a2f33914e39810951d7fc4d4cc3",
                  "label":"",
                  "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1001,
                      "height":310}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9011702308814afc82f2b96fe60f85d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1001,
                          "height":310}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFEFEFE},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"484a1b52bf27461eaabb2ca61dab87ab",
              "label":"Слайд 3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6f3b9cb56ed44c0980c6165f5027897b",
                  "label":"",
                  "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1001,
                      "height":310}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfab3fc24c80429fb11efad41a45bb6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1001,
                          "height":310}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFEFEFE},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"bb840e29836f4a2ca913dccdbf9a7deb",
              "label":"Слайд 4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7646abc068024c93b4c69e0500429112",
                  "label":"",
                  "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1001,
                      "height":310}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d15c46bd9f14b639cf937ba345521c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34be81924c31486e8000660f2a9319ba",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1001,
                          "height":310}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFEFEFE},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"4140dc0815de46c7be72c378c1680100",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":179,
              "y":582},
            "size":{
              "width":640,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca26a0cbd3647738c252fa868798a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":179,
                  "y":582},
                "size":{
                  "width":640,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"710c37ac14214bc28ae4145c0ff05a44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":10,
              "y":629},
            "size":{
              "width":980,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35032e04fd894061a8a8139ee80f5e88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":10,
                  "y":629},
                "size":{
                  "width":980,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u11.png"}},
{
          "id":"284f36606751484fa814ed0acedbf4b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":639},
            "size":{
              "width":471,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be1e7eca84844f0182835ec0073e4131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":639},
                "size":{
                  "width":471,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7272a48c49a4f3f84765aa9828d9c2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":640},
            "size":{
              "width":471,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36afcac6640a42aea3935c58e361373c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":640},
                "size":{
                  "width":471,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ccb604744fb4180b4a0d0bb508fc615",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":10,
              "y":984},
            "size":{
              "width":991,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9644007e55584cb5b5ea344df06f78da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":10,
                  "y":984},
                "size":{
                  "width":991,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u17.png"}},
{
          "id":"a14f0c24f3bf42188ca662f5eed5e0d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":341,
              "y":941},
            "size":{
              "width":321,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f1266106cca44a09b3e205d7e5f50c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":341,
                  "y":941},
                "size":{
                  "width":321,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c3ce4ed10054f40afe6276422d5b443",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":1328},
            "size":{
              "width":640,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6531d5db076a43569217f67ff8dada6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":1328},
                "size":{
                  "width":640,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"549d1d35ebb3401f91518577580c7437",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":10,
              "y":1375},
            "size":{
              "width":980,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be5729091ec4fb68dfcd98fa7240731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":10,
                  "y":1375},
                "size":{
                  "width":980,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u11.png"}},
{
          "id":"327b11b241154922a1a2cf9516b43566",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1385},
            "size":{
              "width":471,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdbc0c201c2e4ef581252efcf2197ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":1385},
                "size":{
                  "width":471,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"572e6111e7b14d63a8875d5279fd3eb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1386},
            "size":{
              "width":471,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e731521b9d429a80c3fb5c33952d85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":1386},
                "size":{
                  "width":471,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c70cb07888e84134bedd016ae4bc0d68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-4,
              "y":1904},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"170c3db0b0d24b8ea2577283bf510462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-4,
                  "y":1904},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"e44736aec90e4e78aeb7cf1c445fce01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00f48aad120f4511a6d5a8047f50c3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"22a4b529de3a43d899107851a6dc562f",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":146},
            "size":{
              "width":700,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"652da090bbee4d7b8f304f9755a3c9ae",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":700,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"275b93e2aebb4647870d434d5c29448f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4fcf85b14f284d1d81bb85398558f6b7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"b17cf38fa89f4f469dcc0d67f9f10b01",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3eae04ea3a1c48c0bd60010c4932904b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"2cc2334a198d4c9fb5ec5751a4c18107",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":614,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"534da915f40245a0b0a880aab8da7bcf",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":614,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u47.png"}},
{
                  "id":"25613747d42845fcb61d103e10b7ff41",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae43be97b7384eb3a601a2e7eace5042",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"dba861fa60444429906e78eb88de7139",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":514,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e7643d82c7e41e7bff44f744e57c9e8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":514,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"bf97ed9f986a4ee7b0ea147cd9670494",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b19a06f229d7463e8ae91c5759dac6b0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"6c99d36614e044b4a788e45247fd7bcb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d65b4b63111f4b16a007b9a212625320",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"1d43a7977ef5458ba9957bba8dddd141",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa2fee977c3346a391ce9bf0e92cea7f",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1e73dbdc57f74e09b3c086697ae43af9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"66aec0f939df4d78b25970ad1fa26373",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"81c46afedbf64f208508249e3a9251ae",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"88a055660b6046b2a7a0210dc99c6b5a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"3f37c2e3499f4e89945bd0ad14df0bf3",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4bade564f4a149a9aedb05d878a8bbc7",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"6c58aaee7d304086a81bab47592d24b0",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"42fb8fd8bad7407cbd9472f82d9cfe10",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}},
{
                      "id":"258cc96203474fd390a1b4ffa6548f9a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"00f786579aca4ab4b37435603bb44929",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u59.png"}}]}],
              "parentCellId":"b17cf38fa89f4f469dcc0d67f9f10b01"}]},
{
          "id":"6603fab47a7b4ed8b2d85fb504de7aa2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":18},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u61_image_sketch.png",
            "disabled~":"images/главная/u61_disabled.png"}},
{
          "id":"a8084fe5d0cc4af5a4eb3c2885916d19",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":56},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u62_image_sketch.png",
            "disabled~":"images/главная/u62_disabled.png"}},
{
          "id":"ae18a9d387714659b2670d0c3ed5d5f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1681},
            "size":{
              "width":980,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f54ac73898342dca1d745184111974f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1681},
                "size":{
                  "width":980,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33e65c1c50e4442bb84ee26df13e7182",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":21,
              "y":1040},
            "size":{
              "width":185,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c4e23280ae4306b1ff09f18a42d778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":21,
                  "y":1040},
                "size":{
                  "width":185,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u65.png"}},
{
          "id":"89405b5e0489441fbc0ad32550d4deaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":215,
              "y":1040},
            "size":{
              "width":185,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b63e77bacf84183a9b2836cb2bd70f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":215,
                  "y":1040},
                "size":{
                  "width":185,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u67.png"}},
{
          "id":"8b9f5dc2503c4bfd90d5f6c576a0214d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":410,
              "y":1040},
            "size":{
              "width":185,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45226a4b4d6d4450b45396efb891648e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":410,
                  "y":1040},
                "size":{
                  "width":185,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u65.png"}},
{
          "id":"0a9ce1a0959c40d6b0223f9743806b1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":604,
              "y":1040},
            "size":{
              "width":185,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"090330b6ee1f4aff8bc176684780949c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":604,
                  "y":1040},
                "size":{
                  "width":185,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u65.png"}},
{
          "id":"09abcc40ad3b4e5ea272e9ec6716a1e0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":141},
            "size":{
              "width":150,
              "height":44}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u73_image_sketch.png",
            "disabled~":"images/главная/u73_disabled.png"}},
{
          "id":"ffc052b365b64ce69aedd2f4f7a827a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":862,
              "y":192},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52b7c99e1bb44d9a871677c569b79d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":862,
                  "y":192},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"875aed5e806b4e40b52a7d7ba4bf1be7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":18},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u76_image_sketch.png",
            "disabled~":"images/главная/u76_disabled.png"}},
{
          "id":"0b8f3275186747e2a6a54b9c17305789",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":16},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a98a28df1f7e426280a0a53bf3989060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":16},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f04fc4f56784b5e80c230563034eef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":45},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7882025e7a2e4f1a8f94c2ef543ba021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":45},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f0a317338b248cdacb3b2f676f37b49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2285afadfeb8470da6b13f9c48d4273d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u81.png"}},
{
          "id":"c04aa27f395c4d009e3f436dac0f35fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac087be04dd94cef82e3192296ca09be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u83.png"}},
{
          "id":"27603536929d4be7aa8f6c22fd02a9e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a07ec62e4c43208385eac00244c1fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u85.png"}},
{
          "id":"006c5aa4383a4e98abfbccaa445f03e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":798,
              "y":1040},
            "size":{
              "width":185,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cbbaba02a8f430f9643459efd74c8ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":798,
                  "y":1040},
                "size":{
                  "width":185,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u87.png"}},
{
          "id":"7584c640ca6f4e89bf56b47ce49b9b66",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1665},
            "size":{
              "width":1001,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/главная/u89_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "34be81924c31486e8000660f2a9319ba":{
      "scriptId":"u0"},
    "c6e74d415a5d49a3a1347650a252b13f":{
      "scriptId":"u1"},
    "52e91c03f1ee4d85b8430119e50f24de":{
      "scriptId":"u2"},
    "73726a2f33914e39810951d7fc4d4cc3":{
      "scriptId":"u3"},
    "9011702308814afc82f2b96fe60f85d2":{
      "scriptId":"u4"},
    "6f3b9cb56ed44c0980c6165f5027897b":{
      "scriptId":"u5"},
    "bfab3fc24c80429fb11efad41a45bb6c":{
      "scriptId":"u6"},
    "7646abc068024c93b4c69e0500429112":{
      "scriptId":"u7"},
    "5d15c46bd9f14b639cf937ba345521c6":{
      "scriptId":"u8"},
    "4140dc0815de46c7be72c378c1680100":{
      "scriptId":"u9"},
    "dca26a0cbd3647738c252fa868798a89":{
      "scriptId":"u10"},
    "710c37ac14214bc28ae4145c0ff05a44":{
      "scriptId":"u11"},
    "35032e04fd894061a8a8139ee80f5e88":{
      "scriptId":"u12"},
    "284f36606751484fa814ed0acedbf4b3":{
      "scriptId":"u13"},
    "be1e7eca84844f0182835ec0073e4131":{
      "scriptId":"u14"},
    "a7272a48c49a4f3f84765aa9828d9c2d":{
      "scriptId":"u15"},
    "36afcac6640a42aea3935c58e361373c":{
      "scriptId":"u16"},
    "6ccb604744fb4180b4a0d0bb508fc615":{
      "scriptId":"u17"},
    "9644007e55584cb5b5ea344df06f78da":{
      "scriptId":"u18"},
    "a14f0c24f3bf42188ca662f5eed5e0d5":{
      "scriptId":"u19"},
    "7f1266106cca44a09b3e205d7e5f50c8":{
      "scriptId":"u20"},
    "6c3ce4ed10054f40afe6276422d5b443":{
      "scriptId":"u21"},
    "6531d5db076a43569217f67ff8dada6e":{
      "scriptId":"u22"},
    "549d1d35ebb3401f91518577580c7437":{
      "scriptId":"u23"},
    "0be5729091ec4fb68dfcd98fa7240731":{
      "scriptId":"u24"},
    "327b11b241154922a1a2cf9516b43566":{
      "scriptId":"u25"},
    "fdbc0c201c2e4ef581252efcf2197ae9":{
      "scriptId":"u26"},
    "572e6111e7b14d63a8875d5279fd3eb4":{
      "scriptId":"u27"},
    "92e731521b9d429a80c3fb5c33952d85":{
      "scriptId":"u28"},
    "c70cb07888e84134bedd016ae4bc0d68":{
      "scriptId":"u29"},
    "170c3db0b0d24b8ea2577283bf510462":{
      "scriptId":"u30"},
    "e44736aec90e4e78aeb7cf1c445fce01":{
      "scriptId":"u31"},
    "00f48aad120f4511a6d5a8047f50c3ad":{
      "scriptId":"u32"},
    "22a4b529de3a43d899107851a6dc562f":{
      "scriptId":"u33"},
    "652da090bbee4d7b8f304f9755a3c9ae":{
      "scriptId":"u34"},
    "275b93e2aebb4647870d434d5c29448f":{
      "scriptId":"u35"},
    "4fcf85b14f284d1d81bb85398558f6b7":{
      "scriptId":"u36"},
    "bf97ed9f986a4ee7b0ea147cd9670494":{
      "scriptId":"u37"},
    "b19a06f229d7463e8ae91c5759dac6b0":{
      "scriptId":"u38"},
    "b17cf38fa89f4f469dcc0d67f9f10b01":{
      "scriptId":"u39"},
    "3eae04ea3a1c48c0bd60010c4932904b":{
      "scriptId":"u40"},
    "6c99d36614e044b4a788e45247fd7bcb":{
      "scriptId":"u41"},
    "d65b4b63111f4b16a007b9a212625320":{
      "scriptId":"u42"},
    "25613747d42845fcb61d103e10b7ff41":{
      "scriptId":"u43"},
    "ae43be97b7384eb3a601a2e7eace5042":{
      "scriptId":"u44"},
    "dba861fa60444429906e78eb88de7139":{
      "scriptId":"u45"},
    "8e7643d82c7e41e7bff44f744e57c9e8":{
      "scriptId":"u46"},
    "2cc2334a198d4c9fb5ec5751a4c18107":{
      "scriptId":"u47"},
    "534da915f40245a0b0a880aab8da7bcf":{
      "scriptId":"u48"},
    "1d43a7977ef5458ba9957bba8dddd141":{
      "scriptId":"u49"},
    "fa2fee977c3346a391ce9bf0e92cea7f":{
      "scriptId":"u50"},
    "1e73dbdc57f74e09b3c086697ae43af9":{
      "scriptId":"u51"},
    "66aec0f939df4d78b25970ad1fa26373":{
      "scriptId":"u52"},
    "3f37c2e3499f4e89945bd0ad14df0bf3":{
      "scriptId":"u53"},
    "4bade564f4a149a9aedb05d878a8bbc7":{
      "scriptId":"u54"},
    "6c58aaee7d304086a81bab47592d24b0":{
      "scriptId":"u55"},
    "42fb8fd8bad7407cbd9472f82d9cfe10":{
      "scriptId":"u56"},
    "81c46afedbf64f208508249e3a9251ae":{
      "scriptId":"u57"},
    "88a055660b6046b2a7a0210dc99c6b5a":{
      "scriptId":"u58"},
    "258cc96203474fd390a1b4ffa6548f9a":{
      "scriptId":"u59"},
    "00f786579aca4ab4b37435603bb44929":{
      "scriptId":"u60"},
    "6603fab47a7b4ed8b2d85fb504de7aa2":{
      "scriptId":"u61"},
    "a8084fe5d0cc4af5a4eb3c2885916d19":{
      "scriptId":"u62"},
    "ae18a9d387714659b2670d0c3ed5d5f6":{
      "scriptId":"u63"},
    "8f54ac73898342dca1d745184111974f":{
      "scriptId":"u64"},
    "33e65c1c50e4442bb84ee26df13e7182":{
      "scriptId":"u65"},
    "46c4e23280ae4306b1ff09f18a42d778":{
      "scriptId":"u66"},
    "89405b5e0489441fbc0ad32550d4deaf":{
      "scriptId":"u67"},
    "6b63e77bacf84183a9b2836cb2bd70f1":{
      "scriptId":"u68"},
    "8b9f5dc2503c4bfd90d5f6c576a0214d":{
      "scriptId":"u69"},
    "45226a4b4d6d4450b45396efb891648e":{
      "scriptId":"u70"},
    "0a9ce1a0959c40d6b0223f9743806b1d":{
      "scriptId":"u71"},
    "090330b6ee1f4aff8bc176684780949c":{
      "scriptId":"u72"},
    "09abcc40ad3b4e5ea272e9ec6716a1e0":{
      "scriptId":"u73"},
    "ffc052b365b64ce69aedd2f4f7a827a5":{
      "scriptId":"u74"},
    "52b7c99e1bb44d9a871677c569b79d98":{
      "scriptId":"u75"},
    "875aed5e806b4e40b52a7d7ba4bf1be7":{
      "scriptId":"u76"},
    "0b8f3275186747e2a6a54b9c17305789":{
      "scriptId":"u77"},
    "a98a28df1f7e426280a0a53bf3989060":{
      "scriptId":"u78"},
    "7f04fc4f56784b5e80c230563034eef7":{
      "scriptId":"u79"},
    "7882025e7a2e4f1a8f94c2ef543ba021":{
      "scriptId":"u80"},
    "6f0a317338b248cdacb3b2f676f37b49":{
      "scriptId":"u81"},
    "2285afadfeb8470da6b13f9c48d4273d":{
      "scriptId":"u82"},
    "c04aa27f395c4d009e3f436dac0f35fc":{
      "scriptId":"u83"},
    "ac087be04dd94cef82e3192296ca09be":{
      "scriptId":"u84"},
    "27603536929d4be7aa8f6c22fd02a9e3":{
      "scriptId":"u85"},
    "21a07ec62e4c43208385eac00244c1fd":{
      "scriptId":"u86"},
    "006c5aa4383a4e98abfbccaa445f03e2":{
      "scriptId":"u87"},
    "6cbbaba02a8f430f9643459efd74c8ee":{
      "scriptId":"u88"},
    "7584c640ca6f4e89bf56b47ce49b9b66":{
      "scriptId":"u89"}}});