$axure.loadCurrentPage({
  "url":"контакты.html",
  "generationDate":new Date(1493281621685.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"4ef15b743c06484784fd5e0075c7c9cf",
    "type":"Axure:Page",
    "name":"Контакты",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFEFEFE},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"grayscale",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7121b9d046364f8591f81de1721e41f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a944a7f5a204d45865d683cfda20f98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u31.png"}},
{
          "id":"440f562dd6324ce382212c0aa1117e58",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":146},
            "size":{
              "width":700,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"706453881a7241379ae200e7efd815b8",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":700,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0edd2c8dd5d480ab772a0dd3b5ab989",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c6abf6704e9746efaafab4a104024a52",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"a80554a4cfbc422ca5750646ed497e3a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"561d5c4cafd64112b912c6015fb15c2c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"56e0114053eb49d79c6cc6a12d7c5580",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":614,
                      "y":0},
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"466f968d05414956972b468248e05174",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":614,
                          "y":0},
                        "size":{
                          "width":86,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u47.png"}},
{
                  "id":"57a1b3ec58924a3eafce28eeec97ca62",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c6055a027a546359e61473e4e1f8d18",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":114,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u43.png"}},
{
                  "id":"8cc95fa043b24be39ebcdfa074855d00",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":514,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"774fe884a46f41ab9a8a62723d87e818",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":514,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"b6fc8990eb3840c79512eb80ad0c284e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d311daa41b049daaabfa68a20f3a422",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}},
{
                  "id":"23c170965fc74236803b86ddbf4fb6eb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFEFEFE},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5de1e9f4246c48b0a784a55a6bc409f6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/главная/u35.png"}}]},
{
              "id":"9c44b41f7c7e481fb724ce267335efaa",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":187,
                  "height":180},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"384bda653fee4fa08c373aae963965d2",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":187,
                      "height":180}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b92f0e553bcd4441a291a7b91c97f0e7",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "size":{
                          "width":187,
                          "height":52},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"de22ae67e8d9496580d43ac1a910c412",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "size":{
                              "width":187,
                              "height":52},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u51.png"}},
{
                      "id":"b70695e85196468da589208c8ee8ae17",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":108},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fbf495979b704340800d99be47e2e493",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":108},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"1584fcb28c2f4b128ceb1ac8823b06b1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":52},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8cf567b1da6447bf83eb9d0c0fdb386d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":52},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u53.png"}},
{
                      "id":"071ef1c7ac644db38ab617b4836eb50e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":187,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fd1dc0fc3ccb4b0f97170ceec1c87a74",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":88},
                            "size":{
                              "width":187,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u55.png"}},
{
                      "id":"247475975a4d4f3688bcb5eadd82185d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFEFEFE},
                        "location":{
                          "x":0,
                          "y":144},
                        "size":{
                          "width":187,
                          "height":36},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1429dfa680f64b468f7dbee843eb786e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFEFEFE},
                            "location":{
                              "x":0,
                              "y":144},
                            "size":{
                              "width":187,
                              "height":36},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/главная/u59.png"}}]}],
              "parentCellId":"a80554a4cfbc422ca5750646ed497e3a"}]},
{
          "id":"ad055c10450f455f8e638f01b0d4125b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":18},
            "size":{
              "width":191,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u61_image_sketch.png",
            "disabled~":"images/главная/u61_disabled.png"}},
{
          "id":"ff0fba723d6e4cddbdfd6d4d1d3e455b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":941,
              "y":56},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u62_image_sketch.png",
            "disabled~":"images/главная/u62_disabled.png"}},
{
          "id":"b4790b24800442adbedcc2efc1ca3fa8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":141},
            "size":{
              "width":150,
              "height":44}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u73_image_sketch.png",
            "disabled~":"images/главная/u73_disabled.png"}},
{
          "id":"7ef90de08f9b435b861888297fd34ac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":862,
              "y":192},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecedc4a7d1f748889a5ec2b137aca676",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":862,
                  "y":192},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a4e71a165db4198a407a2ba33653c1a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":18},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/главная/u76_image_sketch.png",
            "disabled~":"images/главная/u76_disabled.png"}},
{
          "id":"c485f4ae2b3a4b7d8436a70535a7617c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":518,
              "y":16},
            "size":{
              "width":272,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2abbaab4b94d4d73a7a6725719a23740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":518,
                  "y":16},
                "size":{
                  "width":272,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d993ebc346a2407d984a82e7ae047179",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":45},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9a16ab75cc64899894611b87cf374c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":45},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4560267e93084c72afa5fb0f26db82b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf732cc463ec41529ece3da762e85518",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u81.png"}},
{
          "id":"6030a8c9b6784bd2a4513f9e521ae60e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1a8aa0664014e30bc0cb39741e13419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u83.png"}},
{
          "id":"95e696b5c5eb461f8f6c03fca82a5e5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":58},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27a89107167b4a4fbfc482cc73479062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":58},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u85.png"}},
{
          "id":"a1417c625dcd4a97aad9dfe851d15c5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":322},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ecad52d4b74e89b6b4442043b8b9c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":322},
                "size":{
                  "width":300,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc4fc11bb9f142b6a1ab20f52f905677",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":328},
            "size":{
              "width":470,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e4f4e899b54ec499e523de85702bf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":328},
                "size":{
                  "width":470,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u48.png"}},
{
          "id":"ab89171e91144707914ab923b926dc86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":428},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6700017f0b6846e09203be1dac534ed7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":428},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u50.png"}},
{
          "id":"1051a92c59ff41d4a9fa4a5573cf76ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEDEDED},
            "location":{
              "x":760,
              "y":328},
            "size":{
              "width":230,
              "height":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFEFEFE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa27633b88ce4b1599da2cac3e8f6da2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEDEDED},
                "location":{
                  "x":760,
                  "y":328},
                "size":{
                  "width":230,
                  "height":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFEFEFE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/контакты/u52.png"}},
{
          "id":"a50d80ee16d74d088be31ec0aef1c3f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":776,
              "y":340},
            "size":{
              "width":177,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb52c7af54248b3a70387fa9d2ec683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":776,
                  "y":340},
                "size":{
                  "width":177,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86d389ee129045789e4f7ea7be8f4c3d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":373},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u56_image_sketch.png",
            "disabled~":"images/контакты/u56_disabled.png"}},
{
          "id":"f4a76a693ed448bd811ef81a2acdb4af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":408},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u56_image_sketch.png",
            "disabled~":"images/контакты/u56_disabled.png"}},
{
          "id":"2d9aff9396f747f88948ea77b65e4f10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":443},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u56_image_sketch.png",
            "disabled~":"images/контакты/u56_disabled.png"}},
{
          "id":"889c166b6d484ff7af740ed00039e2f2",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":478},
            "size":{
              "width":200,
              "height":94}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u59_image_sketch.png",
            "disabled~":"images/контакты/u59_disabled.png"}},
{
          "id":"39629aae70de47629661bab63d09a22d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":776,
              "y":597},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/контакты/u60_image_sketch.png",
            "disabled~":"images/контакты/u60_disabled.png"}},
{
          "id":"dd9ae83be44c41d0bd4149b3733b84c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":267},
            "size":{
              "width":114,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"767ce9066af04d1d896969733e7dd750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":444,
                  "y":267},
                "size":{
                  "width":114,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30cb5f2731e54378bdf8cffd8045c841",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCBCBCB},
            "location":{
              "x":-3,
              "y":688},
            "size":{
              "width":1005,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50babb2b763e4acdaea8d977d98d913b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCBCBCB},
                "location":{
                  "x":-3,
                  "y":688},
                "size":{
                  "width":1005,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/главная/u29.png"}},
{
          "id":"52acf44c6f2447599a00528cfd653ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":213},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aafc4c84ac01438dbb6b8b7cd800db81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":213},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48dcd52ce0d34138972e3c24291fac2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":92,
              "y":214},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a6025d4e7a34aeabaca99b95d91ff1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":92,
                  "y":214},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e16094a41dfc4ce28ed2be00fcaa8698",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":216},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/о_компании/u8_end.png",
            "line~":"images/о_компании/u8_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7121b9d046364f8591f81de1721e41f3":{
      "scriptId":"u0"},
    "4a944a7f5a204d45865d683cfda20f98":{
      "scriptId":"u1"},
    "440f562dd6324ce382212c0aa1117e58":{
      "scriptId":"u2"},
    "706453881a7241379ae200e7efd815b8":{
      "scriptId":"u3"},
    "e0edd2c8dd5d480ab772a0dd3b5ab989":{
      "scriptId":"u4"},
    "c6abf6704e9746efaafab4a104024a52":{
      "scriptId":"u5"},
    "b6fc8990eb3840c79512eb80ad0c284e":{
      "scriptId":"u6"},
    "9d311daa41b049daaabfa68a20f3a422":{
      "scriptId":"u7"},
    "a80554a4cfbc422ca5750646ed497e3a":{
      "scriptId":"u8"},
    "561d5c4cafd64112b912c6015fb15c2c":{
      "scriptId":"u9"},
    "23c170965fc74236803b86ddbf4fb6eb":{
      "scriptId":"u10"},
    "5de1e9f4246c48b0a784a55a6bc409f6":{
      "scriptId":"u11"},
    "57a1b3ec58924a3eafce28eeec97ca62":{
      "scriptId":"u12"},
    "1c6055a027a546359e61473e4e1f8d18":{
      "scriptId":"u13"},
    "8cc95fa043b24be39ebcdfa074855d00":{
      "scriptId":"u14"},
    "774fe884a46f41ab9a8a62723d87e818":{
      "scriptId":"u15"},
    "56e0114053eb49d79c6cc6a12d7c5580":{
      "scriptId":"u16"},
    "466f968d05414956972b468248e05174":{
      "scriptId":"u17"},
    "9c44b41f7c7e481fb724ce267335efaa":{
      "scriptId":"u18"},
    "384bda653fee4fa08c373aae963965d2":{
      "scriptId":"u19"},
    "b92f0e553bcd4441a291a7b91c97f0e7":{
      "scriptId":"u20"},
    "de22ae67e8d9496580d43ac1a910c412":{
      "scriptId":"u21"},
    "1584fcb28c2f4b128ceb1ac8823b06b1":{
      "scriptId":"u22"},
    "8cf567b1da6447bf83eb9d0c0fdb386d":{
      "scriptId":"u23"},
    "071ef1c7ac644db38ab617b4836eb50e":{
      "scriptId":"u24"},
    "fd1dc0fc3ccb4b0f97170ceec1c87a74":{
      "scriptId":"u25"},
    "b70695e85196468da589208c8ee8ae17":{
      "scriptId":"u26"},
    "fbf495979b704340800d99be47e2e493":{
      "scriptId":"u27"},
    "247475975a4d4f3688bcb5eadd82185d":{
      "scriptId":"u28"},
    "1429dfa680f64b468f7dbee843eb786e":{
      "scriptId":"u29"},
    "ad055c10450f455f8e638f01b0d4125b":{
      "scriptId":"u30"},
    "ff0fba723d6e4cddbdfd6d4d1d3e455b":{
      "scriptId":"u31"},
    "b4790b24800442adbedcc2efc1ca3fa8":{
      "scriptId":"u32"},
    "7ef90de08f9b435b861888297fd34ac9":{
      "scriptId":"u33"},
    "ecedc4a7d1f748889a5ec2b137aca676":{
      "scriptId":"u34"},
    "7a4e71a165db4198a407a2ba33653c1a":{
      "scriptId":"u35"},
    "c485f4ae2b3a4b7d8436a70535a7617c":{
      "scriptId":"u36"},
    "2abbaab4b94d4d73a7a6725719a23740":{
      "scriptId":"u37"},
    "d993ebc346a2407d984a82e7ae047179":{
      "scriptId":"u38"},
    "d9a16ab75cc64899894611b87cf374c5":{
      "scriptId":"u39"},
    "4560267e93084c72afa5fb0f26db82b3":{
      "scriptId":"u40"},
    "cf732cc463ec41529ece3da762e85518":{
      "scriptId":"u41"},
    "6030a8c9b6784bd2a4513f9e521ae60e":{
      "scriptId":"u42"},
    "f1a8aa0664014e30bc0cb39741e13419":{
      "scriptId":"u43"},
    "95e696b5c5eb461f8f6c03fca82a5e5d":{
      "scriptId":"u44"},
    "27a89107167b4a4fbfc482cc73479062":{
      "scriptId":"u45"},
    "a1417c625dcd4a97aad9dfe851d15c5a":{
      "scriptId":"u46"},
    "23ecad52d4b74e89b6b4442043b8b9c1":{
      "scriptId":"u47"},
    "fc4fc11bb9f142b6a1ab20f52f905677":{
      "scriptId":"u48"},
    "c7e4f4e899b54ec499e523de85702bf0":{
      "scriptId":"u49"},
    "ab89171e91144707914ab923b926dc86":{
      "scriptId":"u50"},
    "6700017f0b6846e09203be1dac534ed7":{
      "scriptId":"u51"},
    "1051a92c59ff41d4a9fa4a5573cf76ce":{
      "scriptId":"u52"},
    "aa27633b88ce4b1599da2cac3e8f6da2":{
      "scriptId":"u53"},
    "a50d80ee16d74d088be31ec0aef1c3f6":{
      "scriptId":"u54"},
    "bdb52c7af54248b3a70387fa9d2ec683":{
      "scriptId":"u55"},
    "86d389ee129045789e4f7ea7be8f4c3d":{
      "scriptId":"u56"},
    "f4a76a693ed448bd811ef81a2acdb4af":{
      "scriptId":"u57"},
    "2d9aff9396f747f88948ea77b65e4f10":{
      "scriptId":"u58"},
    "889c166b6d484ff7af740ed00039e2f2":{
      "scriptId":"u59"},
    "39629aae70de47629661bab63d09a22d":{
      "scriptId":"u60"},
    "dd9ae83be44c41d0bd4149b3733b84c7":{
      "scriptId":"u61"},
    "767ce9066af04d1d896969733e7dd750":{
      "scriptId":"u62"},
    "30cb5f2731e54378bdf8cffd8045c841":{
      "scriptId":"u63"},
    "50babb2b763e4acdaea8d977d98d913b":{
      "scriptId":"u64"},
    "52acf44c6f2447599a00528cfd653ae9":{
      "scriptId":"u65"},
    "aafc4c84ac01438dbb6b8b7cd800db81":{
      "scriptId":"u66"},
    "48dcd52ce0d34138972e3c24291fac2a":{
      "scriptId":"u67"},
    "7a6025d4e7a34aeabaca99b95d91ff1f":{
      "scriptId":"u68"},
    "e16094a41dfc4ce28ed2be00fcaa8698":{
      "scriptId":"u69"}}});